### ISSUE TITLE
Define and Create AQA BoM for inclusion with release artifacts

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#1169]
Create a Bill of Materials (BoM) to include with the release that contains:

- SHAs of test repos used

- Summary of test targets ran & results

- Listing of disabled tests

**Comment by smlambert** [comment]
We are now generating all 3 items listed (separately).  We will now need to amalgamate and put all 3 items in a single file (shas, results summary and excludes) and gets pushed to releases repo with the binary.

**Comment by smlambert** [comment]
If you look at the description, there are 3 pieces of information we thought we'd need back when we first created this issue.  The first of the 3 is the testenv.properties file (SHAs of the test repos).  

The next 2 things are essentially the TAP files and the TAP summary that gets produced at the end of a test run.  

This issue is still valid and it involves us both ensure that all of these files get archived with the test job but also pushing these things to a releases repo...  (a related work is in https://github.com/adoptium/aqa-tests/pull/2859).

**Comment by psaunderualberta** [comment]
I can take this then. I'll talk to Sophia to learn more about what specifically needs to be done.

**Comment by smlambert** [comment]
Closing this since we now create testenv.properties file and an AQAcert.log file that encompasses what we need for now.
