### ISSUE TITLE
Intermittent failing test: sun/net/www/http/ChunkedOutputStream/checkError.java

### ISSUE THREAD

**Issue by adam-thorpe** [adoptium/aqa-tests#1506]
Version: jdk8
Platform: linux-all
JVM Impl: Both
Fail rate: 2%

Test sets up a server on a second thread and sends a bunch of data to it. When the server receives the data, it will close the connection, which should cause an IOException on the client side. However if the server start-up thread is slow, the client sometimes finishes sending all of the data before the connection closes (which causes the test to fail). 

Documented here: https://bugs.openjdk.java.net/browse/JDK-8041924
Looks like a test fix for this went into jdk9 but not 8.

**Comment by adam-thorpe** [comment]
Test was already excluded on windows, so I'll just update it to this issue as it explains the need for this to be raised at openjdk

**Comment by karianna** [comment]
> Test was already excluded on windows, so I'll just update it to this issue as it explains the need for this to be raised at openjdk

@adam-thorpe do you have the ability to raise issues in OpenJDK?  If not ask the jbs channel in Slack

**Comment by adam-thorpe** [comment]
No I don't, so I'll raise this in slack

**Comment by smlambert** [comment]
Based on the jbs channel discussion, this relates to the upstream defect JDK-8041924, that needed to be back ported to jdk8.  We should find the related JBS issue and reference the upstream issue in the [exclude file for hs](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk8.txt#L172) and [exclude file for j9](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk/ProblemList_openjdk8-openj9.txt#L158) (and close this issue).

**Comment by adam-thorpe** [comment]
I don't think another issue has been raised yet
