### ISSUE TITLE
Mac: jdk_jdi: com/sun/jdi/DoubleAgentTest.java.DoubleAgentTest failed with java.lang.Exception: Agent 0 timed out with a timeout of 480 seconds; check console log for any additional details

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#155]
19:23:06 ACTION: main -- Error. Agent error: java.lang.Exception: Agent 0 timed out with a timeout of 480 seconds; check console log for any additional details
19:23:06 REASON: User specified action: run main DoubleAgentTest 
19:23:06 TIME:   480.794 seconds
19:23:06 messages:
19:23:06 command: main DoubleAgentTest
19:23:06 reason: User specified action: run main DoubleAgentTest 
19:23:06 Mode: agentvm
19:23:06 Agent id: 0
19:23:06 Timeout signalled after 480 seconds
19:23:06 Timeout information:
19:23:06 Running jstack on process 32481
19:23:06 2017-10-12 10:22:53
19:23:06 Full thread dump OpenJDK 64-Bit Server VM (25.71-b00 mixed mode):
19:23:06 
19:23:06 "Attach Listener" #14 daemon prio=9 os_prio=31 tid=0x00007f9df9d80000 nid=0x460f waiting on condition [0x0000000000000000]
19:23:06    java.lang.Thread.State: RUNNABLE
19:23:06 
19:23:06 "SameVMThread" #10 prio=5 os_prio=31 tid=0x00007f9df9d77800 nid=0x2f0b in Object.wait() [0x0000000177a08000]
19:23:06    java.lang.Thread.State: WAITING (on object monitor)
19:23:06 	at java.lang.Object.wait(Native Method)
19:23:06 	- waiting on <0x000000012a18c958> (a java.lang.Object)
19:23:06 	at java.lang.Object.wait(Object.java:502)
19:23:06 	at DoubleAgentTest.main(DoubleAgentTest.java:128)
19:23:06 	- locked <0x000000012a18c958> (a java.lang.Object)
19:23:06 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:23:06 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
19:23:06 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:23:06 	at java.lang.reflect.Method.invoke(Method.java:498)
19:23:06 	at com.sun.javatest.regtest.agent.MainActionHelper$SameVMRunnable.run(MainActionHelper.java:230)
19:23:06 	at java.lang.Thread.run(Thread.java:748)
19:23:06 
19:23:06 "pool-1-thread-1" #8 daemon prio=5 os_prio=31 tid=0x00007f9df9099000 nid=0x4b07 waiting on condition [0x00000001798b1000]
19:23:06    java.lang.Thread.State: TIMED_WAITING (parking)
19:23:06 	at sun.misc.Unsafe.park(Native Method)
19:23:06 	- parking to wait for  <0x0000000114f4e778> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
19:23:06 	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
19:23:06 	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
19:23:06 	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
19:23:06 	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
19:23:06 	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
19:23:06 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
19:23:06 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
19:23:06 	at java.lang.Thread.run(Thread.java:748)
19:23:06 
19:23:06 "Service Thread" #7 daemon prio=9 os_prio=31 tid=0x00007f9df982b800 nid=0x4103 runnable [0x0000000000000000]
19:23:06    java.lang.Thread.State: RUNNABLE
19:23:06 
19:23:06 "C1 CompilerThread1" #6 daemon prio=9 os_prio=31 tid=0x00007f9df9055000 nid=0x3f03 waiting on condition [0x0000000000000000]
19:23:06    java.lang.Thread.State: RUNNABLE

**Comment by akolarkunnu** [comment]
I rerun this on mac and I didn't see the issue mentioned in this bug, but I am seeing different issue:
Starting: /Users/jenkins/workspace/test_personal/openjdkbinary/j2sdk-image/jre/bin/java -classpath /Users/jenkins/workspace/test_personal/jvmtest/openjdk_regression/SE80/work/classes/0/com/sun/jdi  -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=61512 -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=61512 Exit0
ERROR: Cannot load this JVM TI agent twice, check your java command line for duplicate jdwp options.
Error occurred during initialization of VM
agent library failed to init: jdwp

**Comment by akolarkunnu** [comment]
I checked linux result on CI: https://ci.adoptopenjdk.net/view/OpenJDK%20tests/job/openjdk8_hs_openjdktest_x86-64_linux/3/testReport/com_sun_jdi_DoubleAgentTest/java/DoubleAgentTest/ 

There also same issue is happening.

**Comment by akolarkunnu** [comment]
And this is the expected behavior of this test case. 
Summary of the test case: 
"@summary Check that a double agent request fails" 

So this bug also a candidate to close .

**Comment by akolarkunnu** [comment]
Created a PR https://github.com/AdoptOpenJDK/openjdk-tests/pull/216

**Comment by akolarkunnu** [comment]
It resolved by PR #216
