### ISSUE TITLE
Staged JCK material update logic needs improving

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/aqa-tests#1606]
**Describe the bug**
When jck material is already staged on disk, we run a git clean and a git pull to ensure it's up to date. We have some builds failing at this point because there are changes on disk that are blocking these operations. Not sure how we've got to this point.
https://github.com/AdoptOpenJDK/openjdk-tests/blob/278401c2e312e52bff8b6c3be7afd2bf7c041881/jck/build.xml#L71
```
23:02:37  stage_jck_material:
23:02:37       [echo] Running git clean at C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.jck_x86-64_windows_Nightly\openjdk-tests\jck/../../../../jck_root/JCK11-unzipped...
23:02:37       [echo] Updating C:\Users\jenkins\workspace\Test_openjdk11_j9_sanity.jck_x86-64_windows_Nightly\openjdk-tests\jck/../../../../jck_root/JCK11-unzipped with latest...
23:02:47       [exec] From github.ibm.com:runtimes/JCK11-unzipped
23:02:47       [exec]    caaefa62629..19e8da15434  master     -> origin/master
23:02:51       [exec] Updating 67028e821ba..19e8da15434
23:02:51       [exec] error: Your local changes to the following files would be overwritten by merge:
23:02:51       [exec] 	config/default/jcktest.properties
23:02:51       [exec] 	excludes/jck11.jtx
23:02:51       [exec] Please commit your changes or stash them before you merge.
23:02:51       [exec] Aborting
```
Only have seen this error on Winx64 JDK11 so far. Not sure why.
cc @Mesbah-Alam 

**Expected behavior**
The clean and pull should be robust enough to handle the repo contents on disk being in any state.

**Comment by Mesbah-Alam** [comment]
Any file changed on disc is supposed to be cleaned up by the `git clean` command. Not sure why that's not happening.

**Comment by Mesbah-Alam** [comment]
And not sure why we have those two files changed on disc either. The build is not supposed to change them - 
```
23:02:51       [exec] config/default/jcktest.properties
23:02:51       [exec] excludes/jck11.jtx
```

**Comment by Mesbah-Alam** [comment]
@AdamBrousseau - Just wondering: did we find out why we had `jck11.jtx` and `jcktest.properties` changed on disc locally? Was it a manual update? If not, have we seen this again anywhere else?

**Comment by AdamBrousseau** [comment]
>did we find out why

I don't believe so.

>have we seen this again

I haven't personally, but I probably haven't been looking. I noticed recently when I ran `git clean -ffxd` on my laptop it didn't revert "changes not staged for commit". I think we just need to figure out the option we need to add to the clean to handle those changes. But it may not even be worth doing if we've never seen this again.

**Comment by Mesbah-Alam** [comment]
Perhaps related: we have a newer issue for improving the performance of git clone / update JCK materials on z/OS on where the current implementation has proven to be extremely slow. https://github.ibm.com/runtimes/backlog/issues/405: https://github.ibm.com/runtimes/backlog/issues/405

**Comment by smlambert** [comment]
Believe this is now resolved via https://github.com/adoptium/aqa-tests/pull/2689
