### ISSUE TITLE
get.bat - wget command fails with unable to establish SSL Connection

### ISSUE THREAD

**Issue by chandrams** [adoptium/aqa-tests#167]
wget https://downloads.sourceforge.net/project/junit/junit/4.10/junit-4.10.jar
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = c:\systemtest_prereqs\wget-1.11.4-1-bin/etc/wgetrc
--2017-11-02 14:16:37--  https://downloads.sourceforge.net/project/junit/junit/4
.10/junit-4.10.jar
Resolving downloads.sourceforge.net... 216.34.181.59
Connecting to downloads.sourceforge.net|216.34.181.59|:443... connected.
ERROR: cannot verify downloads.sourceforge.net's certificate, issued by `/C=US/O=GeoTrust Inc./CN=GeoTrust SSL CA - G3':
  Unable to locally verify the issuer's authority.
To connect to downloads.sourceforge.net insecurely, use `--no-check-certificate'
.
Unable to establish SSL connection.

wget https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz 
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = c:\systemtest_prereqs\wget-1.11.4-1-bin/etc/wgetrc
--2017-10-31 14:42:46--  https://ci.adoptopenjdk.net/job/jtreg/lastSuccessfulBuild/artifact/jtreg-4.2.0-tip.tar.gz
Resolving ci.adoptopenjdk.net... 78.47.239.97
Connecting to ci.adoptopenjdk.net|78.47.239.97|:443... connected.
ERROR: cannot verify ci.adoptopenjdk.net's certificate, issued by `/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3':
  Unable to locally verify the issuer's authority.
To connect to ci.adoptopenjdk.net insecurely, use `--no-check-certificate'.
Unable to establish SSL connection.

c:\git\openjdk-tests\TestConfig\lib>tar xf jtreg-4.2.0-tip.tar.gz 
'tar' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chandrams** [comment]
Adding --no-check-certificate to the the wget command resolves this.  I 'm unable to assign this issue. I see a "In Progress" is someone working on this?

**Comment by smlambert** [comment]
@sophia-guo has addressed a similar issue, (https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh#L88), though I do not believe all cases where wget is used incorporates the --no-check-certificate option (https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/get.sh#L85, etc).

**Comment by sophia-guo** [comment]
yes, I only use  --no-check-certificate option  if I got  that certificate failure as it is a insecure mode.
If we are convinced of those sites' authenticity probably better idea is using this option for all wget commands.

**Comment by karianna** [comment]
@chandrams No one was workkng on it, I put it in progress by mistake sorry!

**Comment by chandrams** [comment]
@karianna - No problem, thanks.

Thanks @smlambert

**Comment by chandrams** [comment]
Strange, wget --no-check-certificate https://downloads.sourceforge.net/project/junit/junit/4.10/junit-4.10.jar seems to work for me from my home network but fails at office network

**Comment by Lewiscowles1986** [comment]
I'm getting this same issue on windows. Its also affecting openssl in windows, so even git commit. Assuming the issue is there, but re-install is having no positive effect. No problems using wget on ubuntu 16.04 or 18.04 at home & work.

**Comment by smlambert** [comment]
Note: we are switching the prereqs/expected windows configuration to cygwin environment, and from wget to curl.  (related: #506)  You may wish to try with the new approach.
