### ISSUE TITLE
Jenkins script cleanup

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#1728]
- [x] there is no need to [iterationCount](https://github.com/AdoptOpenJDK/openjdk-tests/blob/481fb72c1030a2693af9d7b078c252f3d457a450/buildenv/jenkins/JenkinsfileBase#L393), we can just use variable `i`

- [x] we do not have `native-test-lib` anymore, following code can be removed
https://github.com/AdoptOpenJDK/openjdk-tests/blob/481fb72c1030a2693af9d7b078c252f3d457a450/get.sh#L349

- [ ] due to [Merge compressedrefs and non-compressedrefs tests builds into one](https://github.com/eclipse/openj9/issues/9231) work, `*_xl` should be removed (pending on https://github.com/eclipse/openj9/issues/9257). For example, 
https://github.com/AdoptOpenJDK/openjdk-tests/blob/481fb72c1030a2693af9d7b078c252f3d457a450/buildenv/jenkins/openjdk_tests#L12

**Comment by llxia** [comment]
FYI @nikolamilijevic1

**Comment by smlambert** [comment]
Seems like we will soon be able to close on this... mixed builds arriving soon.

**Comment by llxia** [comment]
Mixedref SDK is enabled on all platforms (except zos). We can remove _xl and _mixed in openjdk_tests for all other platforms.

**Comment by Darshnadas** [comment]
Hi, I am an outreachy applicant, Iis this issue still open to working? I would like to take on this issue then

**Comment by karianna** [comment]
@llxia can probably comment on that.

**Comment by Darshnadas** [comment]
@llxia Hi, can I take on this issue?

**Comment by smlambert** [comment]
hi @Darshnadas ! (answering for @llxia as she is on vacation this week)... 

you can definitely take this issue, the last checkbox still needs doing, which is to update the [PLATFORM_MAP in the openjdk_tests file](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/openjdk_tests#L3) to remove entries that end in _xl and _mixed, with the exception of zos and riscv platforms.

**Comment by Darshnadas** [comment]
Hi @smlambert Thank you so much

**Comment by jeffalder** [comment]
@llxia @smlambert - I created a draft PR for this; I'll move it into "ready for review" if it's OK that I grab this issue, since it appears abandoned.

I _think_ the ECA is good now; someone needs to approve running GH workflows as a first-time contributor.

**Comment by smlambert** [comment]
fricken' awesome @jeffalder !  ECA is good and GH workflow approved 👍
