### ISSUE TITLE
Investigate adding 'count tests' & 'live monitor' features to AQA

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#1744]
On discussion with @macarte and getting a view of the python scripts he has written for being able to report on the number of openjdk tests in a particular directory and addressing the user story of a developer that is running tests locally and wishes to see current/live status, we want to look at whether we can/should incorporate them into the AdoptOpenJDK Quality Assurance set of tests, which include the openjdk suite.

His 2 scripts are here:
count: https://gist.github.com/macarte/76b555b4dd73584c51e9420f00fd84be
live monitor: https://gist.github.com/macarte/14884e22371e3edf8642996146122a43

User story includes:
Developer wishes to know how many tests in total there are in a particular directory (more granular than test targets defined in playlists)
Developer wishes to have current test status during a live run of tests on their laptop (more granular that TAP results)

Other considerations/questions:

- Is it possible to apply this same features (count and live monitor) to all types of testing we have (or just relevant to openjdk)?  For the count feature, some types tests are not annotated with `@Test` but they potentially could be.  
- Is there a different way of accomplishing these 2 distinct tasks in jtreg already?  In other underlying test frameworks already?
- Is it possible to apply live monitor to the ITERATIONS=xxx scenario, where we grind a particular test target?
- If we want to integrate this functionality into TKG, there would be several ways to do it.  We should detail those out and consider how these look for various types of testing (even if its only applied to openjdk tests to start with).

Things to try:
- For live monitor, try piping a TKG run of sanity.openjdk to the live monitor script to see if it just 'works'

**Comment by brngylni** [comment]
Hey, I think I can do that investigation. (hopefully)

**Comment by brngylni** [comment]
Hey, I can work on that.

**Comment by ellschi** [comment]
I want to work on this issue. Thank you in advance for assigning me. :)

**Comment by brngylni** [comment]
Here is the report that contains the answers of "other considerations/questions" : 

[report1.pdf](https://github.com/AdoptOpenJDK/openjdk-tests/files/6297543/report1.pdf)

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/TKG/pull/177
