### ISSUE TITLE
Enhancement: Transition JCK logic in testJobTemplate into jck.mk

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#1754]
Currently, there's some jck code in testJobTemplate.

```
if (GROUP == "jck" && JDK_IMPL == "openj9") {
	EXTRA_OPTIONS = "-Xfuture"
	if (JDK_VERSION != "8") {
		EXTRA_OPTIONS += " --enable-preview"
	}
	if (ARCH_OS == "s390x_zos") {
		// zOS has Attach API disabled by default
		EXTRA_OPTIONS += " -Dcom.ibm.tools.attach.enable=yes"
	}
}
```

This issue covers moving that into jck.mk, and any related changes.

As mentioned in https://github.com/AdoptOpenJDK/openjdk-tests/pull/1753 

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the [openjdk-test](https://github.com/AdoptOpenJDK/openjdk-tests) in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Using any kind of git client (command line, Git plugin on Eclipse IDE, etc) create a feature branch off of your fork for the issue. We do not have any naming definition for branches.
- [ ] At this point, you'd have a local clone of openjdk-test](https://github.com/AdoptOpenJDK/openjdk-tests). Update the jck.mk file with your change in the local clone. 
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewers find some missing peaces or a problem, s/he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by smlambert** [comment]
The requirement here is to move logic from a Jenkins groovy script, [testJobTemplateL154-165](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L154-L165) into the [jck/jck.mk](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/jck/jck.mk) file.

This comment may be helpful, as it describes how the openjdk/openjdk.mk file was updated for something similar:
https://github.com/AdoptOpenJDK/openjdk-tests/pull/1753#issuecomment-619077491

**Comment by ellschi** [comment]
Hi @vanichitkara! Are you still interested in working on this issue? If not I'd take it. :)

**Comment by vanichitkara** [comment]
Hi @ellschi! You can take up this issue since I have 2 more issues to work on at the moment

**Comment by ellschi** [comment]
Great @vanichitkara, thank you for letting me know! @adamfarley, @smlambert Please assign me :)

**Comment by ellschi** [comment]
Ready for review!

**Comment by adamfarley** [comment]
@ellschi - Heya. Are you asking someone to review a Pull Request?

If so, please add them as reviewers in the Pull Request and paste a PR link in this issue.

**Comment by smlambert** [comment]
@adamfarley - not sure that new contributors have the ability to add reviewers and brand new contributors would not know who to add as reviewers.  Rest assured as the core-team in Ottawa start their day, they know to assist in reviewing the PR backlog of this repo.

**Comment by smlambert** [comment]
@ellschi - I do not see a PR from you, if you have changes in a branch, please create a PR so we can review, thanks!

**Comment by ellschi** [comment]
@smlambert: Thank you for the feedback! I created this [PR](https://github.com/AdoptOpenJDK/openjdk-tests/pull/2474) and now am unsure if this was the right way to do it...

**Comment by keerthi-kamath** [comment]
I would love to give it a try!

**Comment by llxia** [comment]
Thanks @keerthi-kamath !

**Comment by keerthi-kamath** [comment]
@llxia Going through the steps and comments, I just have one confusion. Do I paste the logic before the endif statement in 
ifneq ($(filter openj9 ibm, $(JDK_IMPL)),)
 OTHER_OPTS=-Xtrace:maximal=all{level2}
endif

**Comment by llxia** [comment]
Yes, we need something like following in in https://github.com/adoptium/aqa-tests/blob/master/jck/jck.mk
```
OTHER_OPTS=
# if JDK_IMPL is openj9 or ibm
ifneq ($(filter openj9 ibm, $(JDK_IMPL)),)
 OTHER_OPTS=" -Xtrace:maximal=all{level2} -Xfuture "
 ifeq ($(OS),OS/390)
     OTHER_OPTS +=" -Dcom.ibm.tools.attach.enable=yes"
  endif
  ifneq (8, $(JDK_VERSION))
    OTHER_OPTS += " --enable-preview"
  else
endif
```

**Comment by YeeSkywalker** [comment]
Hi there, could I try on this one?
