### ISSUE TITLE
Add a test that checks how stale is the latest nightly from API

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#1802]
jdk14 is currently serving up [builds from May 8th ](https://github.com/AdoptOpenJDK/openjdk-build/issues/1794)(from 20 days ago).  We can add a test that runs that will fail if the nightlies from the API are over a certain number of days old.  As we do not turn off builds (only testing) during release period, this should always be a short period of time that we miss producing a nightly build for any given version.

**Comment by smlambert** [comment]
We could add a test case in functional/api that checks that API serves up the 'correct' release and a non-stale nightly (allow for up to 5 ? days of no published nightly before failing as too stale)

**Comment by aahlenst** [comment]
I consider the API serving the wrong builds, outdated builds, not having nightly builds etc. an operational issue. I'd therefore add a check to our monitoring so that the right people get alerted. @Willsparker is currently working on various checks. Performing these checks with jq should be doable.

**Comment by smlambert** [comment]
FYI @sxa

**Comment by smlambert** [comment]
@Willsparker - do you have an issue in another repo that describes the work you are doing?  If so, I will close this one.  :)

**Comment by aahlenst** [comment]
Please keep it. https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1229 is already overloaded.

**Comment by smlambert** [comment]
At least the initial part (of raising awareness) is being addressed via https://github.com/adoptium/ci-jenkins-pipelines/pull/204 - thanks @jerboaa !  Closing this as further enhancements can be raised in the relevant repository.
