### ISSUE TITLE
Assess test target execution time & define test schedule

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2037]
We have nightly and weekly targets defined in the build pipelines.  We eventually want to enable the entire 'grid' of test levels x groups at the project for all platforms that we release.  We will embrace some notion of [graduated testing](https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Graduated-Testing-&-Test-Numbers) to conserve machines, as we can not run all testing every night.

<img width="161" alt="grid" src="https://user-images.githubusercontent.com/2836948/98045766-000e5900-1df7-11eb-84cd-abcbb9024396.png">

This issue will gather test duration times for all top-level test targets on all platforms for all versions to attempt to develop a schedule that works with the current machine capacity (and/or advice where we are needing to augment capacity), ideally creating a script where this can be rerun/revisited on a quarterly cadence.

**Average Duration for [Nightly test targets](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/build_base_file.groovy#L64-L71):**
|version|target| xlinux avgDuration (mins) | mac avgDuration (mins) | aix avgDuration (mins) | aarch64 | win64 | s390x |
|---|---|---|---|---|---|---|---|
|jdk8|sanity.openjdk| [22.78](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=openjdk&platform=x86-64_linux) | [41.04](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=openjdk&platform=x86-64_mac) | 101 | 21 | 85 | 120 |
||sanity.system| [135.49](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=system&platform=x86-64_linux) | [158.79](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=system&platform=x86-64_mac)|   135| 76| 66 | 210 |
||extended.system| [91.29](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=extended&jdkVersion=8&group=system&platform=x86-64_linux) |[128.88](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=extended&jdkVersion=8&group=system&platform=x86-64_mac) |75 | 14 | 95 | 150 |
||sanity.perf| [47.02](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=perf&platform=x86-64_linux) | [33.08](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=perf&platform=x86-64_mac)|8 | 14| 55 | 127 |
| |sanity.functional| [81.5](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&jdkImpl=hotspot&group=functional&platform=x86-64_linux) | [83](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&jdkImpl=hotspot&group=functional&platform=x86-64_mac) |120 | 223 | 83 | 128 |
| |extended.functional| [221](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=extended&jdkVersion=8&jdkImpl=hotspot&group=functional&platform=x86-64_linux) | [112](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=extended&jdkVersion=8&jdkImpl=hotspot&group=functional&platform=x86-64_mac) | 270 | 120| 141 | 174 |
| | |~599 min (~10hrs)| ~557 min (~9.2hrs)| ~694 (~11.5hrs) | ~468 (~7.8hrs) | ~525 (~8.75hrs) | ~909 (~15hrs)|

**Average Duration for [Weekly test targets](https://github.com/AdoptOpenJDK/openjdk-build/blob/master/pipelines/build/common/build_base_file.groovy#L64-L71):** (TBD)
|version|target| xlinux avgDuration (TRSS query)|
|---|---|---|
|jdk8|extended.openjdk|  TBD [query](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=extended&jdkVersion=8&group=openjdk&platform=x86-64_linux) |
||special.functional| TBD [query](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=special&jdkVersion=8&group=functional&platform=x86-64_linux) |
||extended.perf| TBD [query](https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=extended&jdkVersion=8&group=perf&platform=x86-64_linux) |
| |sanity.external| ||

**Comment by andrew-m-leonard** [comment]
fyi: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2050

**Comment by andrew-m-leonard** [comment]
https://github.com/AdoptOpenJDK/openjdk-tests/issues/2051

**Comment by smlambert** [comment]
Updated average nightly test execution times for xlinux and mac.  Currently if all top-level targets were run serially on a machine... should complete at around 10hrs for jdk8.  Note: the execution time varies across platforms (for example, based on information shared earlier in this issue, on mac shows a 9.2hr average execution time).  This exercise needs to eventually take that into account, but for a spitball initial estimate, we will assume ~10hr execution time .

We do not run test targets serially, but rather try to divide and queue the top-level targets up across the machines we have.   (and multiplied by 4 impls, hotspot, dragonwell, openj9, openj9XL and for jdk11 x 5 impls with addition of corretto on xlinux).  40/50/30 hrs of test execution time nightly per each version respectively.  

Now to look at machine resources, execution time has to be shared across 19 [xlinux machines](https://ci.adoptopenjdk.net/label/ci.role.test&&sw.os.linux&&hw.arch.x86/) and across 7 [mac machines](https://ci.adoptopenjdk.net/label/ci.role.test&&sw.os.osx&&hw.arch.x86/).  **If** all test targets were granularly divided in 1hr segments, and if no other jobs utilize test machines and all machines are online, the shortest completion time for a nightly build is execution time % number of machines.  In reality, the queuing/scheduling across Jenkins resources is never entirely optimal, nonetheless, if the execution time % num of machines is too large we will need to consider a different schedule or more machines or not using the default set of tests on that platform, but rather a reduced set of tests.

| Version | Platform/Spec | Nightly Execution Time (hrs) | Num of Test Machines | Execution Time / Machines (shortest completion time possible) |
| --- | --- | --- | --- | --- |
| jdk8 | xlinux | 40 |  |  |
| jdk11 | xlinux | 50 |  | |
| jdk15 | xlinux | 30 | | |
| all | xlinux| 120 hrs | 19 | 6.31 hrs |
| jdk8 | mac | 30 |  |  |
| jdk11 | mac | 30 |  | |
| jdk15 | mac | 30 | | |
| all | mac| 90 hrs | 7 | 12.86 hrs |

**Comment by smlambert** [comment]
In the middle of this assessment, I have also managed to locate a similar assessment done in April 2019, adding it for completeness.

<img width="1266" alt="Screen Shot 2020-11-25 at 10 52 12 PM" src="https://user-images.githubusercontent.com/2836948/100306256-f64cc100-2f70-11eb-93db-d810da4a070a.png">
<img width="1255" alt="Screen Shot 2020-11-25 at 10 52 27 PM" src="https://user-images.githubusercontent.com/2836948/100306262-fc42a200-2f70-11eb-9407-4fa1da26dc61.png">

**Comment by smlambert** [comment]
Closing this as stale and no longer relevant.

The queries linked in the table above (which call an API in TRSS) are still valid and could be used to tabulate data in the future should it be needed, example:

https://trss.adoptopenjdk.net/api/getTestAvgDuration?level=sanity&jdkVersion=8&group=openjdk&platform=x86-64_linux
