### ISSUE TITLE
jdk8 Hotspot zLinux tests take too long to run...

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#2050]
Analysis of jdk8 Hotspot zLinux:
```
- sanity.perf 9Hrs
- sanity.system 4Hrs
- extended.openjdk 10Hrs
- sanity.external 10Hrs **(Bogus, is caused by sub-parallel job Queue times)**
- extended.perf 10Hrs
- sanity.openjdk 2hrs40mins
```

**Comment by andrew-m-leonard** [comment]
sanity.perf:
```
dacapo-eclipse_0 : 7mins
test dacapo-h2_0 : 6mins (OutOfMemory!)
dacapo-lusearch-fix_0 : <1min
renaissance-fj-kmeans_0 : **4hrs20mins**
renaissance-future-genetic_0 : **2hrs30mins**
renaissance-scala-kmeans_0 : **2hrs4mins**
IdleMicrobenchmark_HS_0 : <1min
```

**Comment by andrew-m-leonard** [comment]
sanity.system:

MathLoadTest_autosimd_0 : 2mins
MathLoadTest_bigdecimal_0 : 35mins
MauveSingleThreadLoadTest_HotSpot_0 : 30mins
MauveSingleInvocationLoadTest_HotSpot_0 : <1min
MauveMultiThreadLoadTest_0 : 33mins
ClassLoadingTest_0 : 45mins
NioLoadTest_0 : 3mins
LambdaLoadTest_Hotspot_0 : <1min
TestJlmLocal_0 : 1min
TestJlmRemoteClassAuth_0 : 11mins
TestJlmRemoteClassNoAuth_0 : 11mins
TestJlmRemoteMemoryAuth_0 : 12mins
TestJlmRemoteMemoryNoAuth_0 : 11mins
TestJlmRemoteNotifierProxyAuth_0 : 3mins
TestJlmRemoteThreadAuth_0 : 31mins
TestJlmRemoteThreadNoAuth_0 : 21mins

**Comment by andrew-m-leonard** [comment]
### extended.openjdk:

jdk_custom_0 : 15mins
hotspot_all_0 : <1min
hotspot_jre_0 : **8hrs**
jdk_awt_0 : 1hr40mins
rest...Aborted 10hr Timeout...

**Comment by andrew-m-leonard** [comment]
### sanity.external:

All sub-parallel test run quickly, apparent long run of this test suite is due to Queue times of parallel jobs.

**Comment by andrew-m-leonard** [comment]
### extended.perf:

dacapo-avrora_0 : 2mins
dacapo-fop_0 : <1min
dacapo-jython_0 : 5mins
dacapo-luindex_0 : <1min
dacapo-pmd_0 : <1min
dacapo-sunflow_0 : 2mins
dacapo-xalan_0 : <1min
renaissance-als_0 : <1min (Failed: Not enough memory)
renaissance-chi-square_0 : <1min (Failed: Not enough memory)
renaissance-db-shootout_0 : 16mins (Failed: libleveldbjni load error)
renaissance-dec-tree_0 : <1min (Failed: Not enough memory)
renaissance-finagle-http_0 : **2hrs37mins**
renaissance-gauss-mix_0 : <1min (Failed: Not enough memory)
renaissance-log-regression_0 : <1min (Failed: Not enough memory)
renaissance-mnemonics_0 : **3hrs40mins**
renaissance-movie-lens_0 : <1min (Failed: Not enough memory)
renaissance-par-mnemonics_0 : **>2hrs40mins** (Aborted...Timeout)

**Comment by andrew-m-leonard** [comment]
### sanity.openjdk:

jdk_lang_0: 41mins
jdk_math_0 : 15mins
jdk_util_0 : **1hr40mins**
jdk_jdi_0 : 9mins

**Comment by smlambert** [comment]
Closing this as we no longer build/release/test the jdk8 s390x hotspot build (as it has no JIT and is too slow to offer to anyone).
