### ISSUE TITLE
Consider running macos testing on aarch64

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#2171]
With the aarch64 macos systems able to run x64 code under their Rosetta emulation layer, we could run out macos testing across this machines as well as the x64 ones.

In order to determine if this is feasible I have [kicked off a run](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_sanity.openjdk_x86-64_mac/409/console) of the latest JDK8/HotSpot/macos on [one of our macos/aarch64 systems](https://ci.adoptopenjdk.net/computer/test-macstadium-macos11-arm64-2).

Note that at the moment, the OpenJ9 builds for macos/x64 crash when run on the aarch64 systems, so if we added this functionaliy in we'd have to exclude openj9 (although we now have precedent for splitting them now that https://github.com/AdoptOpenJDK/openjdk-build/pull/2372 has been implemented

**Comment by aahlenst** [comment]
There are a bunch of crashes and unexpected behaviours when running x64 builds on Apple Silicon: 

https://github.com/AdoptOpenJDK/openjdk-support/issues/231
https://github.com/AdoptOpenJDK/openjdk-support/issues/211

**Comment by sxa** [comment]
Yeah my test run wasn't clean either (although I haven't looked into the failures) so this definitely sounds like it'll need the native port to be useful

**Comment by smlambert** [comment]
Will close this as stale (but it may be relevant to recent discussion on where Rebuild_Same_JDK_Reproducibility_Test_Mac needs to be run, related: https://github.com/adoptium/temurin-build/pull/3844).
