### ISSUE TITLE
JDK 16 and 17 on Alpine (musl) need testing

### ISSUE THREAD

**Issue by aahlenst** [adoptium/aqa-tests#2223]
In roughly a month, we're going to release AdoptOpenJDK 16. For the first time, support for musl instead of glibc is included. While we build nightlies, we don't test them:

https://github.com/AdoptOpenJDK/openjdk-build/blob/3a26592a68ac5d58ae55bbe385a620f29d2ce695/pipelines/jobs/configurations/jdk16_pipeline_config.groovy#L55-L65

I think we should do something about that.

**Comment by smlambert** [comment]
@gdams @sxa - Do we have designated test machines?

**Comment by aahlenst** [comment]
We have machines now: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1929#issuecomment-783465921.

**Comment by smlambert** [comment]
Very first Grinder attempt: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7211/ 
seems to be taking a long time on this step, will check tomorrow on whether its totally hung and times out
`22:14:08       [echo] git clone --depth 1 -q -b dev https://github.com/AdoptOpenJDK/openjdk-jdk16.git`

Notes: 
- request a naming convention for builds that is predictable (I think it will be helpful for redistributors also, as it will be easier to predict what to query through the API)
- Grinder is pulling from upstream, need to check what is the correct API query to make to pull it from there (for SDK_RESOURCE=nightly|releases

**Comment by smlambert** [comment]
Yay! Grinder/7211 (which was a quick test BUILD_LIST=openjdk, TARGET=jdk_math) passed!

Next up:
- sanity.openjdk in [Grinder/7212](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7212)
- special.functional in [Grinder/7213](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7213)
- sanity.system in [Grinder/7214](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/7214) - expect this to not work... updates expected to be required in STF

**Comment by smlambert** [comment]
JDK16 test jobs generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/252/
JDK17 test jobs generated via https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/253/

**Comment by smlambert** [comment]
sanity.system did fail as expected (in compiling native tests since currently native makefiles require platform additions), will prep an STF PR to make appropriate updates

**Comment by smlambert** [comment]
re: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2223#issuecomment-784734949 - will wait on https://github.com/AdoptOpenJDK/openjdk-systemtest/issues/413 (and related: https://github.com/AdoptOpenJDK/openjdk-systemtest/pull/415) before making changes to support system tests for new platforms.

**Comment by smlambert** [comment]
Reopen to verify we can compile and run system test material.

**Comment by aahlenst** [comment]
@smlambert Can you paste the error here so that I can have a look without having to dig up the Grinder?

**Comment by sxa** [comment]
I've just triggered https://ci.adoptopenjdk.net/job/Grinder/7839/console based on the "Rerun in Grinder" link on https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_sanity.system_x86-64_alpine-linux/4/

**Comment by Mesbah-Alam** [comment]
Looking at the latest run of https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_sanity.system_x86-64_alpine-linux/8/tapResults/, the system tests are now failing with the following common error: 

```
64_alpine-linux/openjdk-tests/TKG/../../jvmtest/system/otherLoadTest/..//stf/stf.core/scripts/stf.pl at /usr/share/perl5/core_perl/diagnostics.pm line 259, <POD_DIAG> line 711.
```

The `<POD_DIAG> line 711` part is very similar to the error we had seen [before](https://github.com/adoptium/aqa-systemtest/issues/416#issuecomment-797598014 ) for Perl diagnostics module being missing on Linux Alpine.

**Comment by aahlenst** [comment]
Necessary dependencies are in. Once @sxa or somebody else has updated the existing containers, we can schedule some grinders.

**Comment by smlambert** [comment]
Closing as complete (tests enabled in build pipelines).

**Comment by smlambert** [comment]
Re-opening given: https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_sanity.system_x86-64_alpine-linux/24/ all fail on [test-docker-alpine311-x64-1](https://ci.adoptopenjdk.net/computer/test-docker-alpine311-x64-1/) to compile due to:

```
couldn't find diagnostic data in /usr/share/perl5/core_perl/pods/perldiag.pod /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_x86-64_alpine-linux/jvmtest/system/stf/stf.core/scripts/.. /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_x86-64_alpine-linux/jvmtest/system/stf/stf.core/scripts /usr/local/lib/perl5/site_perl /usr/local/share/perl5/site_perl /usr/lib/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl /home/jenkins/workspace/Test_openjdk16_hs_sanity.system_x86-64_alpine-linux/openjdk-tests/TKG/../../jvmtest/system/otherLoadTest/..//stf/stf.core/scripts/stf.pl at /usr/share/perl5/core_perl/diagnostics.pm line 259, <POD_DIAG> line 711.
```

**Comment by lumpfish** [comment]
I cannot find anywhere that the `use diagnostics` package is actually used.
I'll run some tests with the statement excluded.

**Comment by lumpfish** [comment]
sanity.system ran OK: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Old/8177/ (1 failure also seen on other platforms)
extended .system ran OK: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Old/8178/ (all passed)

Created PR https://github.com/adoptium/STF/pull/116 to remove the `use diagnostics` statement.

**Comment by smlambert** [comment]
Thanks @lumpfish - closing this issue as completed.
