### ISSUE TITLE
Grinder PLATFORMS=all generates incorrect jobs and misses others

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2227]
If 'all' is specified for PLATFORM:

1. Jobs are generated for platform ppc64-aix_xl, which does not exist
2. Jobs are not generated for x86-32_windows for anything other than jdk8, though it exists for jdk11 and later on hotspot
3. Jobs are not generated for aarch64-linux_xl which exists for jdk11 and later on openj9

Jobs are not generated for other platforms (e.g. RISC-V, Solaris), but I think this is the desired behaviour since they are excluded from the 'normal' test runs).

Also once the jobs are generated the are submitted in the order they were added to the platforms list (in https://github.com/AdoptOpenJDK/openjdk-tests/blob/314dc7c35260354d60bf0455c54f9728be7aef12/buildenv/jenkins/openjdk_tests).  It would be nice if the list were sorted once complete so that which jobs are which once they are submitted would be more predictable.

**Comment by smlambert** [comment]
Yes.  'all' does not mean literally all.   While we will not rename it to 'most' or 'primary' platforms, that was the intent.  By design, it's 'all primary platforms of interest'.

We will address this by a combination of updating the comment under the Jenkins parameter and removing any _XL jobs that may get triggered.  

It is uncertain whether we can easily enforce ordering.  That may need more investigation and may not be feasible (TBD).

**Comment by smlambert** [comment]
Hi @Codesuha, there are a couple of parts to this issue, the first part is:

- updating the [testJobTemplate](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate) to add some extra information for the user
  - changing https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L280 from `all platforms: all (actual platforms will change based on JDK_VERSION/JDK_IMPL)` to `all platforms: all (this set actually excludes some secondary platforms and changes based on JDK_VERSION/JDK_IMPL selected)`

The 2nd part requires verifying if its still an issue (to check if any _xl platforms get launched, of so, we will want to find the place in the code where the change is required.  Do not worry about this 2nd part for now.

**Comment by gervaisj** [comment]
@smlambert I'll take the issue.

Regarding this:
> The 2nd part requires verifying if its still an issue (to check if any _xl platforms get launched, of so, we will want to find the place in the code where the change is required. Do not worry about this 2nd part for now.

No `_XL` platforms seem to get triggered (see `all` grinder runs below). Looking at the code confirms this.

![image](https://user-images.githubusercontent.com/50028573/150658561-036a3986-37fc-45c4-911c-fd6c1cc118ad.png)

**Comment by smlambert** [comment]
Ok great, re: _XL builds, they should no longer be included (ensure to double-check using SDK_RESOURCE=releases and JDK_IMPL=openj9).

**Comment by gervaisj** [comment]
> Ok great, re: _XL builds, they should no longer be included (ensure to double-check using SDK_RESOURCE=releases and JDK_IMPL=openj9).

I'll check!
