### ISSUE TITLE
Comment triggered PR builds enhancements

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2296]
Recently, we enabled comment-triggered PR builds https://github.com/AdoptOpenJDK/openjdk-tests/issues/2199 (Thanks @Icohedron). There are a couple of enhancements that we would like to add:

- `--sdk_resource` can be a URL. It is the same as `CUSTOMIZED_SDK_URL ` in Grinder that users can provide a URL for downloading SDK. We should use this SDK for testing. We can ignore credentials for now.
```
--sdk_resource=customized --customized_sdk_url=https://xxx
```
- build SDK using github action at https://github.com/AdoptOpenJDK/build-jdk or https://github.com/eclipse/build-openj9. Users should provide jdk/openj9 repo and branch for now.
```
--sdk_resource=build
```

**Comment by Icohedron** [comment]
The `AdoptOpenJDK/install-jdk` action requires an additional parameter `archiveExtension` when fetching a customized SDK from a URL. Should the workflow try to predict the archive extension from the URL or should the archive extension be provided as an additional argument?

**Comment by Icohedron** [comment]
> Users should provide jdk/openj9 repo and branch for now.

How should the repo and branch to be provided for building the SDK?

**Comment by sophia-guo** [comment]
Both build-jdk and build-openj9 currently auto supports PRs in related repos, i.e. AdoptOpenjdk/openjdk-builds, Eclipse/openj9, Eclispe/openj9-omr, ibmruntimes/openj9-openjdk-jdk${version}. Need to update if we'd like to support explicitly passing in repo/branch info.

**Comment by sophia-guo** [comment]
> The AdoptOpenJDK/install-jdk action requires an additional parameter archiveExtension when fetching a customized SDK from a URL. Should the workflow try to predict the archive extension from the URL or should the archive extension be provided as an additional argument?

I think if we could predict the archive extension the prediction logic should be in AdoptOpenJDK/install-jdk action. That is the action could be enhanced to enable it.

**Comment by Icohedron** [comment]
> Both build-jdk and build-openj9 currently auto supports PRs in related repos, i.e. AdoptOpenjdk/openjdk-builds, Eclipse/openj9, Eclispe/openj9-omr, ibmruntimes/openj9-openjdk-jdk${version}. Need to update if we'd like to support explicitly passing in repo/branch info.

So if I'm understanding this correctly, then `--sdk_resource=build` should only work for PRs in those repos?

**Comment by sophia-guo** [comment]
If using ` --sdk_resource=upstream` default build-jdk | build-openj9 action can be used for now no need for user to provide repo and branch.

There are two other scenarios :
1. In openjdk-tests, tkg ( non build-jdk | build-openj9 related repos) user comment in PRs to trigger tests based on JDK built by user defined build-jdk | build-openj9 repo and branch.
2. In build-jdk | build-openj9 related repos, user comment in PRs to trigger tests based on JDK built by the repo's PRs ( no need for user to define build repo and branch), tests are fectched from run-aqa.

For case 1 is common build-jdk | build-openj9 will need to be updated.

**Comment by llxia** [comment]
Changes are delivered. I think we can close this issue.
