### ISSUE TITLE
Update external tests to allow for autogen of Docker images for jdk16+

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2317]
**👾 Description of the issue**

jdk 16 sanity.external jobs are being launched but the build fails with this error:

11:26:31  build_image:
11:26:31       [echo] Executing external.sh --build --dir camel --tag nightly --version 16 --impl openj9 
11:26:31       [exec] ERROR: Invalid Version: 16
11:26:31       [exec] Usage: /home/jenkins/workspace/Test_openjdk16_j9_sanity.external_ppc64le_linux/openjdk-tests/TKG/../../jvmtest/external/external.sh [8 9 10 11 12 13 14 15]

As a quick fix, this will require an update to [common_functions.sh:L17](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/common_functions.sh#L17) to add 16 and 17 to the list.  

As a future fix, perhaps we can come up with a mechanism to check for the existence of jdk git repos to verify which versions are released (and then add one to include the main/tip of development).  This future fix does not have to happen as part of this issue.  It is fine to focus on the quick fix defined above.

In order to test the fix locally, you can [download a jdk16 binary](https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot) from the API or website then follow these instructions for running a test locally: https://github.com/AdoptOpenJDK/openjdk-tests/tree/master/external#running-external-tests-locally 

If the fix was good, then you will not hit `ERROR: Invalid Version: 16` in the output during compilation.

**📋 Step by Step**

To solve this issue and contribute a fix you should check the following step-by-step list. A more detailed documentation of the workflow can be found [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

- [ ] Claim this issue: Comment below.
- [ ]  Fork the repository in github by simply clicking the 'fork' button.
- [ ]  Check out the forked repository
- [ ]  Create a feature branch for the issue. We do not have any naming definition for branches.
- [ ]  Commit your changes.
- [ ]  Start a Pull Request.
- [ ]  Done 👍 Ask in comments for a review :)
- [ ]  If the reviewer find some missing peaces or a problem he will start a discussion with you and describe the next steps how the problem can be solved.
- [ ]  You did it 🎉 We will merge the fix in the master branch.
- [ ]  Thanks, thanks, thanks for being part of this project as an open source contributor ❤️

**🤔❓ Questions**

If you have any questions just ask us directly in this issue by adding a comment. You can join our community chat at [Slack](https://adoptopenjdk.net/slack.html). Next to this you can find a general manual about open source contributions [here](https://github.com/firstcontributions/first-contributions/blob/master/README.md).

**Comment by brngylni** [comment]
Hi, can I try to solve it?

**Comment by smlambert** [comment]
Most certainly @brngylni !

**Comment by brngylni** [comment]
`sudo make compile` 
gives
 `please provide TEST_JDK_HOME` 
although I provided it with 
`export TEST_JDK_HOME=/path/to/openjdk`

@smlambert

**Comment by smlambert** [comment]
Closed via 2456
