### ISSUE TITLE
Investigate mark Jenkins node offline due to machine issue

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2370]
As we run more and more test builds nightly and weekly with different jvm and versions and parallelization, the machine issue (i.e., space issue, git issue, network issue, etc) on one machine could tank the whole nightly run on that platform. I would like to investigate to see if we can mark Jenkins node offline automatically due to machine issues.

example of a bad run:
![image](https://user-images.githubusercontent.com/19273206/110704206-a5c93e80-81c2-11eb-9f8b-794207a33dbf.png)

It looks like there is a Jenkins plugin for it https://plugins.jenkins.io/offlineonfailure-plugin/

**Comment by sxa** [comment]
You have to be very careful with anything like that - you run the risk of one type of test (e.g. all system tests) taking all the test boxes off line if there is a specific system test thing that's making the jobs fail catastrophically.

**Comment by llxia** [comment]
Yes, we will be very careful/strict about the rules. The plan is not to take nodes offline when there is a failure. I would like to like to find a way to take nodes offline for the specific reasons that we are certain is the machine issue, such as no disk space, cannot run git, etc.

**Comment by llxia** [comment]
The above plugin is quite old. We can just use Jenkins API to achieve setting node temporarily offline due to specific errors.
