### ISSUE TITLE
Add test support for risc-v platform

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2391]
This issue is to list the set of PRs already completed to support the riscv platform and to close on any final items required for lifting up fully automated AQA testing at the project (using default list as defined in build pipelines).

- [x] https://github.com/AdoptOpenJDK/openjdk-tests/pull/1832
- [x] https://github.com/adoptium/TKG/pull/42
- [x] https://github.com/adoptium/TKG/pull/83

- [x] https://github.com/adoptium/aqa-systemtest/pull/349
- [x] https://github.com/adoptium/STF/pull/78

**Comment by sxa** [comment]
Current status: RISC-V needs two things at present:
- an increased timeout on the Xvfb startup (I've increased it from 10 to 100 for the purposes of testing but it likely doens't need to be that high (https://github.com/sxa/openjdk-tests/commit/d54025efc93eb6aaa7ff219ac302c81ce845da47)
- Changes to enable it in `ottawa.csv` (https://github.com/sxa/TKG/commit/3349be17c2b3ca53388161b2f2c4ef0e5eba148b) otherwise all tests will be skipped

Latest grinder_tkg output with both changes as follows:
- [[OpenJ9](https://ci.adoptopenjdk.net/job/Grinder_TKG/198/parameters/)]
- [[Bisheng (with JVM_IMPL=hotspot)](https://ci.adoptopenjdk.net/job/Grinder_TKG/201/console/)] - Lots of `NullPointerException`s

**Comment by glemon-123** [comment]
Hi sxa, we have done some tests on the board with BishengJDK-RISCV, and the result seems ok. Would you please run the following command: `cat /proc/self/mountinfo` and see if `sys/fs/cgroup/memory` exists like this:
```
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
``` 

Thanks!

**Comment by sxa** [comment]
The machine is currently offline as per https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/2066 so I can't get that from you at the moment although it's a fairly default Debian installation on a HiFive Unleashed board.

**Comment by feilongjiang** [comment]
Hi @sxa, are there any updates on Bisheng risc-v grinder_tkg tests? Hope I didn't miss anything... :eyes:

**Comment by sxa** [comment]
@lumpfish has been looking at it - the physical RISC-V machines we have have been offline for a few weeks unfortunately (I'm hoping to get another two delivered to me soon - is Huawei able to provide any accessible RISC-V systems?) so we've been testing on a virtual system, and I believe he has two issues which he is about to raise.

**Comment by yadongw** [comment]
> @lumpfish has been looking at it - the physical RISC-V machines we have have been offline for a few weeks unfortunately (I'm hoping to get another two delivered to me soon - is Huawei able to provide any accessible RISC-V systems?) so we've been testing on a virtual system, and I believe he has two issues which he is about to raise.

Unfortunately, it's also difficult for us to access the risc-v boards. As far as I know, the HiFive Unleashed is discontinued and the stock is extremely low, and the Hifive Unmatched is delayed due to component shortages.

**Comment by yadongw** [comment]
@sxa The testing progress of bishengjdk riscv have been pended for months due to lack of hardware. Recently, we've got several unmatched broads  exclusively used to do the test.  Shall we restart this work?

**Comment by sxa** [comment]
Yes please :-) I've put in a [PR to enable testing on JDK11](https://github.com/adoptium/ci-jenkins-pipelines/pull/193). I'm currently [running tests](https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk17_hs_sanity.openjdk_riscv64_linux/) on an Unleashed and a a Beagleboard Starlight prototype board so we have some capacity but more is always welcome!

**Comment by smlambert** [comment]
Closing this as complete (and also noting the risc-v builds are not currently running, once they are back up, we can always create a new issue if there are any issues with running tests).

**Comment by sxa** [comment]
There are definitely issues with running them, but at least for now the ones I've sen are not related to the automation around it - the jobs run as well as can be expected so thanks for closing this one.
