### ISSUE TITLE
Port comment triggered PR builds into Openj9 and TKG repo

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2399]
Comment-triggered PR builds are enabled at Adopt test repo with nightly/releases. And we are working on [PR builds enhancement](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2296). In order for more people to benefit from the current comment triggered PR builds feature, I think we should port it into openj9 and TKG repo. The enhancement can be ported at a later stage.

For [openj9 repo](https://github.com/eclipse/openj9):
PR builds workflow should take openj9 repo and branch from the openj9 PR. The rest repo and branch should use the default values.

For [TKG repo](https://github.com/adoptium/TKG):
PR builds workflow should take TKG repo and branch from the TKG PR. The rest repo and branch should use the default values.

**Comment by llxia** [comment]
FYI @Icohedron

**Comment by Icohedron** [comment]
> The rest repo and branch should use the default values.

Could you clarify what you mean by this?

> For openj9 repo:
PR builds workflow should take openj9 repo and branch from the openj9 PR.

The defaults for the openj9 repo are to build the SDK from the head repo/ref of an openj9 PR, correct?

> For TKG repo:
PR builds workflow should take TKG repo and branch from the TKG PR.

I'm not sure how this would work. Could you give an example of the default parameters you'd expect for the TKG repo?

**Comment by Icohedron** [comment]
> > For TKG repo:
> > PR builds workflow should take TKG repo and branch from the TKG PR.
> 
> I'm not sure how this would work. Could you give an example of the default parameters you'd expect for the TKG repo?

Nevermind, I figure that the PR Comment Triggered Build action needs a way for the user to specify the TKG repository to use when running AdoptOpenJDK/run-aqa

**Comment by llxia** [comment]
The workflow needs to be added into openj9 and TKG repo respectively. Similar to port auto test exclusion in openj9: https://github.com/eclipse/openj9/tree/master/.github/workflows

Use Case for openj9 repo:
- users open a PR in openj9 repo (not Adopt test repo)
- users add a comment to trigger PR builds. The user does NOT need to specify openj9 repo and branch in the comment. The workflow should be able to grep the information.
- PR builds are launched using openj9 user's repo and branch from the original PR (openj9 user's repo and branch should be used when running run-aqa). 

The use case for TKG repo is very similar. PR builds are launched using TKG user's repo and branch from the original PR.

**Comment by smlambert** [comment]
Believe this has now been accomplished, further enhancement (like making more things reusable) can be addressed in a separate enhancement issue.
