### ISSUE TITLE
get.sh: line 300: validate: bad array subscript

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#2539]
Commit: https://github.com/AdoptOpenJDK/openjdk-tests/commit/a8e7c9bbde47b41e02142bdbc14e0f88cd372589
introduced the usage of bash negative array index, but this only works on some bash versions >=4.2
```
14:22:36  ./openjdk-tests/get.sh: line 300: validate: bad array subscript
```
Some AdoptOpenJDK nodes don't support it, eg:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/377/console

**Comment by andrew-m-leonard** [comment]
@xichen1 fyi

**Comment by llxia** [comment]
`test-macincloud-macos1010-x64-2` is used in the above Grinder. This machine does not seem to setup properly. Even if there is no bash issue, it has the problem to find `antlib`. 

```00:03:02.120  Buildfile: /Users/jenkins/workspace/Grinder/openjdk-tests/TKG/scripts/build_test.xml
00:03:04.084    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
00:03:05.060    [taskdef] Could not load definitions from resource net/sf/antcontrib/antlib.xml. It could not be found.
00:03:05.060  
00:03:05.060  BUILD FAILED
```

**Comment by smlambert** [comment]
@sxa - tagging you re: https://github.com/AdoptOpenJDK/openjdk-tests/issues/2539#issuecomment-827027158 - is test-macincloud-macos1010-x64-2 a new machine that is missing dependencies?

**Comment by sophia-guo** [comment]
test-macincloud-macos1010-x64-2 is tagged as ci.role.testDISABLED https://ci.adoptopenjdk.net/computer/test-macincloud-macos1010-x64-2/. So regular test jobs won't be assigned to the machine unless using the label to specify to that machine. like https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/390/

**Comment by sxa** [comment]
> @sxa - tagging you re: [#2539 (comment)](https://github.com/AdoptOpenJDK/openjdk-tests/issues/2539#issuecomment-827027158) - is test-macincloud-macos1010-x64-2 a new machine that is missing dependencies?

Issue: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/1922
As far as I'm aware @gdams was dealing with it: Slack thread [1](https://adoptium.slack.com/archives/C5219G28G/p1613376089087200?thread_ts=1613375658.086000&cid=C5219G28G) [2](https://adoptium.slack.com/archives/C53GHCXL4/p1613137179232200?thread_ts=1613130185.225300&cid=C53GHCXL4)

**Comment by andrew-m-leonard** [comment]
Yes as Stewart said, issue AdoptOpenJDK/openjdk-infrastructure#1922
I was just using Grinder on that node to test issue 1922... and happen to find this issue as well...

**Comment by smlambert** [comment]
Closing this as not valid / won't fix (given machine was not tagged for use by test).
