### ISSUE TITLE
Improvements to parameter comments in testJobTemplate

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2546]
There are several improvements that can be made to the testJobTemplate to further assist a user in understanding the values and format expected for various parameters in a Jenkins test job.

Here is a list of several places in testJobTemplate that could be improved (and assume it would be preferable to include some line breaks to improve readability for longer comments):
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L267 - changed to "Is docker required? True, if BUILD_LIST contains external."
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L268 - set a default value to be 'nightly'
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L269 - set a default value to be '-v ${TEST_JDK_HOME}:/opt/java/openjdk'
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L306 should be changed to "Specific test directories to compile.  This can be a comma-separated list of directories.  Advisable to specify to a granularity that suits the targets you want to run.  Example: if only running dacapo targets, BUILD_LIST=perf/dacapo."
- https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L243 can be updated to say 'Additional test repositories that can be overlaid onto existing AQA test material for extra testing.  If multiple repositories are being provided, the values are to be comma-separated and in the same order in each related parameter of this set.'

There are likely other improvements but let's start with these.  https://github.com/AdoptOpenJDK/openjdk-tests/pull/2488 gives an example of updating the file in question.

**Comment by Martins-O-U** [comment]
Hello @smlambert this looks interesting. I'd like to work on it please assign me.

**Comment by smlambert** [comment]
Removing 
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L268 - set a default value to be 'nightly'
https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/buildenv/jenkins/testJobTemplate#L269 - set a default value to be '-v ${TEST_JDK_HOME}:/opt/java/openjdk'

from the set of items to do in this issue, as it appears those are already done.
