### ISSUE TITLE
Update github URL in test repos to refer to eclipse-openj9

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2551]
The openj9 repos have been moved from https://github.com/eclipse to https://github.com/eclipse-openj9, we should update any github URLs to refer to eclipse-openj9.

https://github.com/eclipse-openj9/openj9
https://github.com/eclipse-openj9/openj9-systemtest

PR for updating openj9 repo: eclipse-openj9/openj9#12592

**Comment by SAY-droid427** [comment]
Hey @llxia May I work on this issue?

**Comment by SAY-droid427** [comment]
@llxia @smlambert I have made a PR for the issue. Please review it. Thank you!

**Comment by SAY-droid427** [comment]
@lxia Any copyright updates I need to make for the [https://github.com/adoptium/aqa-tests](https://github.com/adoptium/aqa-tests)

**Comment by LongyuZhang** [comment]
Repo https://github.com/adoptium/aqa-test-tools is also affected by this move, e.g.  `PossibleIssues.jsx` has [`eclipse/openj9`](https://github.com/adoptium/aqa-test-tools/blob/ae7328238aa86da6aa2a80cc99ab34718839e702/test-result-summary-client/src/Build/PossibleIssues.jsx#L55).

**Comment by smlambert** [comment]
Lan is correct, any of the test repositories under the adoptium github organization do not require the same handling of copyright as those under the eclipse-openj9 organization.

and regarding https://github.com/adoptium/aqa-tests/issues/2551#issuecomment-830983221, we should create issues in each of the test repos for checking and updating references to AdoptOpenJDK now that we have moved all the test repositories out of that github organization.  And those changes will likely have to be coordinated, as example, this PR in the run-aqa will fail: https://github.com/adoptium/run-aqa/pull/82 unless we also update the get.sh script in this aqa-tests repository.

**Comment by SAY-droid427** [comment]
@LongyuZhang Should I make a PR for making the changes in the [https://github.com/adoptium/aqa-test-tools](https://github.com/adoptium/aqa-test-tools) repo ?

**Comment by LongyuZhang** [comment]
> @LongyuZhang Should I make a PR for making the changes in the https://github.com/adoptium/aqa-test-tools repo ?

Hi @SAY-droid427 I have created issue for it in aqa-test-tools repo, feel free to wok on it if you are interested. Thanks.
