### ISSUE TITLE
Update references to AdoptOpenJDK to Adoptium

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2558]
There are some references to Github organizations and repos that need updating in this repository.  Now that all test materials are moved to Adoptium, we should search for and replace the references to any that are no longer valid (even though Github forwarding will mostly handle it, we should update nonetheless).  Org names and repo names need to be searched for and updated.

Test repos moved/renamed:
adoptopenjdk/openjdk-tests -> adoptium/aqa-tests
adoptopenjdk/openjdk-systemtest -> adoptium/aqa-systemtest
adoptopenjdk/openjdk-test-tools -> adoptium/aqa-test-tools
adoptopenjdk/STF -> adoptium/STF
adoptopenjdk/TKG -> adoptium/TKG
adoptopenjdk/bumblebench -> adoptium/bumblebench
adoptopenjdk/run-aqa -> adoptium/run-aqa

Other potentially referenced repos moved/renamed:
adoptopenjdk/build-jdk -> adoptium/build-jdk

**Comment by 2001asjad** [comment]
@ShelleyLambert we need to find wherever these names occur in this repo and change them isn't it?

**Comment by llxia** [comment]
Related: https://github.com/adoptium/aqa-systemtest/issues/424

**Comment by smlambert** [comment]
Yes @2001asjad - Searching for words like AdoptOpenJDK and openjdk-tests and openjdk-systemtest and openjdk-test-tools and _when appropriate_, updating them with their new names.  There may be a few cases where something would not get changed, but it will be easier to see them if you create a PR, and then make minor updates to a PR.

**Comment by smlambert** [comment]
Addressed via:

https://github.com/adoptium/aqa-tests/pull/2638
https://github.com/adoptium/aqa-tests/pull/2630
https://github.com/adoptium/aqa-tests/pull/2612
