### ISSUE TITLE
New Grinder Jenkins job missing systemtest repo parameters

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2585]
The old Grinder job (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Old/build?delay=0sec) had parameters to override the systemtest and STF repositories.
```
ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH
OPENJ9_SYSTEMTEST_OWNER_BRANCH
STF_OWNER_BRANCH
```
Those parameters are missing from the new Grinder job (https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/build?delay=0sec), but are required when testing changes to those repository in a fork / branch.

**Comment by smlambert** [comment]
Strange, I thought @Mesbah-Alam manually added them and then they were also added to the testJobTemplate via https://github.com/adoptium/aqa-tests/pull/2521.

I have added them to the Grinder job now.
