### ISSUE TITLE
Request to regenerate the Bisheng smoke tests

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#2597]
The Bisheng smoke tests need to be regenerated to include [a fix](https://github.com/adoptium/aqa-tests/pull/2589) that enables them to work by changing a default parameter value (JDK_IMPL from bisheng to hotspot).

However, I'm not seeing an obvious way to do it via [Test_Job_Auto_Gen](https://ci.adoptopenjdk.net/job/Test_Job_Auto_Gen/).

Here are the four jobs that need to be regenerated. Help/Advice requested.

- [jdk8u-linux-x64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-bisheng_SmokeTests/)
- [jdk8u-linux-aarch64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-aarch64-bisheng_SmokeTests/)
- [jdk11u-linux-x64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-x64-bisheng_SmokeTests/)
- [jdk11u-linux-aarch64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-aarch64-bisheng_SmokeTests/)

Plan B: If it's not currently possible to regenerate the smoke tests, I propose manually modifying the smoke tests listed above. Smoke tests created in the future should have the correct JDK_IMPL value as per the aforementioned [PR](https://github.com/adoptium/aqa-tests/pull/2589).

**Comment by smlambert** [comment]
Delete the smoke test jobs and on the next run they will get regenerated.

**Comment by adamfarley** [comment]
Good idea Shelley. :)

I don't have the permissions to do this, unfortunately, so I'll ask if one of the Jenkins admins is around on the infra slack channel.

**Comment by smlambert** [comment]
I've deleted the 4 jobs, so they will be regenerated next time build pipelines run.  (Note: we specifically choose not to regen each time jobs are run, as its somewhat expensive and most often unecessary to do so.

**Comment by adamfarley** [comment]
Thanks Shelley. :)
