### ISSUE TITLE
Test jobs being scheduled on wrong platform

### ISSUE THREAD

**Issue by lumpfish** [adoptium/aqa-tests#2608]
Some test jobs are being run on the wrong platforms: - e.g.  for https://ci.adoptopenjdk.net/job/Test_openjdk8_j9_extended.openjdk_ppc64le_linux/27/console (ppcle test) an AIX test machine was selected.

I'm assuming it's caused by the recent parallel testing enablement:   https://github.com/adoptium/ci-jenkins-pipelines/commit/4609ca71c10a4dac06b6529cfc6628c64eacb364?

**Comment by sophia-guo** [comment]
This is expected. We can use any available node for copying TAP files in parallel test builds, https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L894. More details see https://github.com/adoptium/aqa-tests/issues/2262.
