### ISSUE TITLE
Request to regenerate the bisheng non-smoke tests

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#2609]
**Summary:**

Please regenerate all of the bisheng non-smoke tests in order to include a fix that allows them to run.

Note: We must verify that the resultant jobs have the default JDK_IMPL value set to "hotspot", even though the JDK_IMPL value in TEST_JOB_AUTO_GEN is set to "bisheng" (which I believe to be necessary so we  regenerate the right jobs).

**Test Sets:**

LEVELS: sanity,extended
GROUPS: openjdk,perf,system
JDK_VERSIONS: 8,11
JDK_IMPL: bisheng
ARCH_OS_LIST: aarch64_linux,x86-64_linux

and

LEVELS: sanity,extended,special
GROUPS: functional
JDK_VERSIONS: 8,11
JDK_IMPL: bisheng
ARCH_OS_LIST: aarch64_linux,x86-64_linux

**Details:**

In [this issue](https://github.com/adoptium/aqa-tests/issues/2597), we discussed how setting the JDK_IMPL value to "bisheng" causes the smoke tests to fail before they can run, and how this value should instead be "hotspot".

This change was effected by creating a PR that sets the JDK_IMPL value correctly during test job generation, followed by a deletion and re-creation of the aforementioned smoke tests.

However, this was all done without considering the non-smoke tests, which are now failing.

@smlambert - Asking for your thoughts on this, please.

**Comment by smlambert** [comment]
Jobs listed above regenerated via:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/264/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/265/ - openjdk regenerated separately to keep report dir equals true as default (when tests pass), unlike other test groups
https://ci.adoptopenjdk.net/view/Test_grinder/job/Test_Job_Auto_Gen/266/

**Comment by adamfarley** [comment]
Thanks Shelley. :)
