### ISSUE TITLE
Tweetest: Refactor external test directories

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2614]

**Comment by emmasaroyan** [comment]
@smlambert is this issue still open? Could you please provide its description?

**Comment by smlambert** [comment]
hi @emmasaroyan - This issue is an "epic", which is really just a holder for a set of related issues.  As I look at the 8 sub-issues, they are now all completed/closed, so we can close this Epic.  Please take a look at some other issues or let me know if you want help selecting something.  Cheers!

**Comment by emmasaroyan** [comment]
@smlambert hi! I am working on a task as part of OSD Mentor application and looking for a good issue to solve. 
I'd appreciate your help with that. Thank you!

**Comment by smlambert** [comment]
hi @emmasaroyan - for a good first warm-up issue, you could take on xxx. For something more complex, https://github.com/adoptium/aqa-tests/issues/2368 or https://github.com/adoptium/aqa-tests/issues/1966 may be of interest.
