### ISSUE TITLE
Update parentsJobPipeline to reference jenkins-helper

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2626]
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/parentsJobPipeline.groovy#L52 should be updated to reference the renamed jenkins-helper at https://github.com/adoptium/jenkins-helper

otherwise hitting this issue:
```
ERROR: No library named openjdk-jenkins-helper found
Finished: FAILURE
```

**Comment by sophia-guo** [comment]
We should do the renaming. However renaming may not solve the issue. Is the issue hit in other jenkins server?

**Comment by smlambert** [comment]
Yes, and I have added that jenkins-helper global shared library to the private temurin-compliance server now.

**Comment by llxia** [comment]
Openj9 Jenkins seems fine, and it is using the updated git URL. I am not sure about the settings in Adopt Jenkins.
![image](https://user-images.githubusercontent.com/19273206/120508533-cfdf6680-c395-11eb-810a-5b34cd9cf514.png)
https://openj9-jenkins.osuosl.org/view/Test_Functional_Nightly/job/Test_openjdk11_j9_extended.functional_ppc64_aix_Nightly/13/console

**Comment by sophia-guo** [comment]
Adopt Jenkins is fine with old name, which is same as in Openj9. It could do the re-reference automatically. Though we'd better to reference the new name

<img width="726" alt="Screen Shot 2021-06-02 at 12 04 00 PM" src="https://user-images.githubusercontent.com/18030625/120513869-ad9c1780-c39a-11eb-8618-1bc75df2d45f.png">

https://ci.adoptopenjdk.net/view/Test_grinder/job/External_Kicker/4/console

**Comment by smlambert** [comment]
I see that I can now use the current version of the groovy file (old name, without this PR).  I must not have waited long enough for Jenkins config changes via the EF bugzilla report.  

So I am not blocked, but agree that eventually we should update to use all the correct/current names of things.

**Comment by smlambert** [comment]
re:  https://github.com/adoptium/aqa-tests/issues/2626#issuecomment-859074720 infrastructure repo

Though interestingly enough, the config in Jenkins system has the URL of the repo updated, but not the name of the helper... not sure what side-effects will occur if I rename it... would like @sxa's input

<img width="885" alt="Screen Shot 2021-06-10 at 5 29 53 PM" src="https://user-images.githubusercontent.com/2836948/121599910-b8495300-ca11-11eb-94cc-515bf3a119dd.png">

**Comment by sophia-guo** [comment]
I guess if it is renamed all repos' jenkinsfile using the library has to be updated to the new name.

**Comment by smlambert** [comment]
Which means I guess before changing we should check in ci-jenkins-pipeline repo if there are any references to the old name.

**Comment by sophia-guo** [comment]
Yes, and aqa-tests repo also need to update the references. And then openj9 jenkins @AdamBrousseau will also need to update.
