### ISSUE TITLE
MBCS_Tests_i18n_zh_CN testcases were failed by 17 EA

### ISSUE THREAD

**Issue by takiguc** [adoptium/aqa-tests#2633]
**Describe the bug**
According to following link, "MBCS_Tests_i18n_zh_CN_linux_0" testcase was failed
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/276/tapResults/
1 files 404 tests, 91 ok, 1 not ok, 312 skipped, 0 ToDo, 0 Bail Out!
Following testcase was failed
* MBCS_Tests_i18n_zh_CN_linux_0

Java version information:
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment AdoptOpenJDK-17+18-202105062345 (build 17+18-202105062345)
Eclipse OpenJ9 VM AdoptOpenJDK-17+18-202105062345 (build master-295e06e0d, JRE 17 Linux amd64-64-Bit Compressed References 20210506_285 (JIT enabled, AOT enabled)
OpenJ9   - 295e06e0d
OMR      - d96f2b34f
JCL      - 780fa63b0b based on jdk-17+18)

**To Reproduce**
Grinder_Simple parameters link is as follows:
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/276/parameters/
PLATFORM: x86-64_linux
BUILD_LIST: functional/MBCS_Tests
TARGET: special
SDK_RESOURCE: nightly
JDK_VERSION: 17
JDK_IMPL: openj9
LABEL: test-ibmcloud-rhel7-x64-1
(Note: some x86-64_linux test machines don't have MBCS locales, at least above machine has MBCS locales)

**Expected behavior**
MBCS_Tests_i18n_zh_CN_linux_0 should not be failed
This issue happened because of following CLDR locale changes.
JDK-8258794 Support for CLDR version 39 https://bugs.openjdk.java.net/browse/JDK-8258794

**Comment by smlambert** [comment]
> (Note: some x86-64_linux test machines don't have MBCS locales, at least above machine has MBCS locales)

Is there an infrastructure issue to update other x86-64_linux so that we do not land on machines that do not have the full configuration?

FYI @sxa
