### ISSUE TITLE
Add ability to change docker registry for external tests

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2645]
Related to the now stale pull request for https://github.com/adoptium/aqa-tests/pull/1833, this enhancement issue is to add support for using Docker images from other registries (besides where we currently pull from... the AdoptOpenJDK Docker repo).

This is not urgent, but wanted to create it so we do not lose the request, as we will close the stale PR that has no associated issue.

**Comment by norbline** [comment]
@smlambert please can i take this

**Comment by jnjerin** [comment]
Please assign me to this. I would like to work on it

**Comment by sophia-guo** [comment]
@jnjerin I have a draft for this https://github.com/adoptium/aqa-tests/compare/master...sophia-guo:test?expand=1. Please take a look and try. Any question or problem just ping me. Thanks

**Comment by jnjerin** [comment]
Okay. I'm on it @sophia-guo

**Comment by llxia** [comment]
For the private docker registry, we should also consider supporting user-provided credentials.

**Comment by sophia-guo** [comment]
@llxia for credentails I would suggest to track in a different issue.
