### ISSUE TITLE
Accept ADOPTOPENJDK_SHA in test pipeline

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2674]
In order to support [Reproducible Tests ](https://github.com/adoptium/aqa-tests/issues/2347), our test pipeline should accept  ADOPTOPENJDK_SHA. The user/upstream should be able to set ADOPTOPENJDK_SHA, similar to OPENJ9_SHA. The test pipeline will use `ADOPTOPENJDK_SHA` if it is provided. If not, `ADOPTOPENJDK_BRANCH` will be used.

**Comment by smlambert** [comment]
We need this one before GHC open-source day, but still tagging it in the event it still exists by then.

**Comment by llxia** [comment]
This issue is no longer needed. SHA/tag/branch can be set in `ADOPTOPENJDK_BRANCH`
