### ISSUE TITLE
Add PLATFORM examples in testJobTemplate

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2679]
It would be nice to have PLATFORM examples in testJobTemplate
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L267

We should list commonly used PLATFORM examples and add a link to https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests

For example:
```
Platform to be tested:
aarch64_linux
ppc64_aix
ppc64le_linux
s390x_linux
s390x_zos
x86-64_linux
x86-64_mac
x86-64_windows
x86-32_windows
sparcv9_solaris
riscv64_linux
multiple platforms (comma separated values): x86-64_linux,x86-64_mac
all platforms: all (actual platforms will change based on JDK_VERSION/JDK_IMPL)
Please refer to PLATFORM_MAP in https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests
```

**Comment by Aryamanz29** [comment]
I would like to work on this 🙃

**Comment by smlambert** [comment]
This issue is still up for grabs...

**Comment by vegasood** [comment]
Hi @smlambert, I am interested in working on this. 
I understand what we need to add. But could you provide more clarity on where do I need to add the list of commonly used PLATFORM examples and the link?

**Comment by smlambert** [comment]
yes, so this line `stringParam('PLATFORM', "${ARCH_OS}", "Platform to be tested")` can be updated to include some names of platforms we test, so it could be updated to 
`stringParam('PLATFORM', "${ARCH_OS}", "Platform to be tested:<br/> aarch64_linux<br/> ppc64_aix<br/> ppc64le_linux\n`

where `<br/>` will insert a break, so that the view in the Jenkins job will look like:
```
Platform to be tested:
aarch64_linux
ppc64_aix
ppc64le_linux
s390x_linux
s390x_zos
x86-64_linux
x86-64_mac
x86-64_windows
x86-32_windows
sparcv9_solaris
riscv64_linux
multiple platforms (comma separated values): x86-64_linux,x86-64_mac
all platforms: all (actual platforms will change based on JDK_VERSION/JDK_IMPL)
Please refer to PLATFORM_MAP in https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests
```

**Comment by smlambert** [comment]
Once you have a PR @vegasood, I will help to test it

**Comment by vegasood** [comment]
Okay thank you for clarifying Shelley :) 
Excited to make my first contribution to an OS project
