### ISSUE TITLE
Accept STF sha in test pipeline

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2680]
In order to support [Reproducible Tests ](https://github.com/adoptium/aqa-tests/issues/2347), our test pipeline should accept STF sha from [STF repo](https://github.com/adoptium/STF). The user/upstream should be able to set STF sha. The test pipeline will use STF sha if it is provided. If not, the branch will be used.

In order to avoid parameter explosion, we should reuse `STF_OWNER_BRANCH`, so it can be 
`<owner>:<branch>`, `<owner>:<tag>`, or `<owner>:<sha>`. SImilar to PR https://github.com/adoptium/aqa-tests/pull/2829 (get.sh change)

In this case, code needs to be updated in ant:
https://github.com/adoptium/aqa-tests/blob/master/system/common.xml#L51

Please make sure to test both in local and Grinder.

**Comment by xius666** [comment]
I would like to take this issue thanks

**Comment by xius666** [comment]
-Grinder STF_OWNER_BRANCH example and its output

1. 

adoptium:master
output from grinder:
<img width="1074" alt="Screen Shot 2021-09-23 at 1 20 56 AM" src="https://user-images.githubusercontent.com/55036290/134604034-1c9a501c-9cbd-41d5-b231-b09e3f7f0b13.png">

2.

adoptium:2129b191b1111b665758fb755851025e35888a1b
output from grinder:
<img width="1015" alt="Screen Shot 2021-09-23 at 7 23 49 PM" src="https://user-images.githubusercontent.com/55036290/134604210-f8355817-d595-4f4a-9746-f26c85a2bd78.png">

3.
adoptium:invalid
output from grinder:
<img width="828" alt="Screen Shot 2021-09-23 at 7 13 04 PM" src="https://user-images.githubusercontent.com/55036290/134604326-ba3d4881-78e9-4b00-bbe9-b19a8b4bc225.png">

**Comment by llxia** [comment]
This issue is resolved.
