### ISSUE TITLE
Remove the checks for TESTDIR 

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2690]
In get.sh, we can remove the checks for TESTDIR.

https://github.com/adoptium/aqa-tests/blob/master/get.sh#L157-L161

We are planning to remove `--testdir|-t` parameter as we can use the current dir. Removing the checks for TESTDIR  is the first step of clean up the code.

Related: https://github.com/adoptium/aqa-tests/issues/2682

**Comment by ManasviGoyal** [comment]
working on this

**Comment by ManasviGoyal** [comment]
@smlambert @Mesbah-Alam done please check
