### ISSUE TITLE
Remove remove --testdir|-t parameter in get.sh

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2691]
We would like to remove  --testdir|-t in [get.sh](https://github.com/adoptium/aqa-tests/blob/master/get.sh) as it is no longer needed. get.sh should be run directly under `aqa-tests ` folder.

Step 1: update [get.sh](https://github.com/adoptium/aqa-tests/blob/master/get.sh) to remove  --testdir|-t option
Step 2: update [jenkinsfilebase](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L436) to run .get.sh directly under aqa-tests and do not pass in TESTDIR (-s)

Related: https://github.com/adoptium/aqa-tests/issues/2682 and https://github.com/adoptium/aqa-tests/issues/2690

**Comment by ManasviGoyal** [comment]
@llxia @sophia-guo pls review
