### ISSUE TITLE
Update langtools_custom target

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2692]
Currently we run specific langtools testscase using jdk_custom target, which is a little bit confusing ( especially the description is wrong https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L313, for the target both langtools and jdk custom should use the same target jdk_custom). 

It would be nice to add a separate langtools_custom for langtools tests especially langtools may need different options.

**Comment by smlambert** [comment]
So the task here, to clarify for some new person that does not have any context, is to add a langtools_custom target into https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml, much like the [jdk_custom target](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L17-L38).  

Essentially need to add a new block `<test>` block with the testCaseName called langtools_custom and changing the command to reference a new LANGTOOLS_CUSTOM_TARGET which should get defined in openjdk.mk file (much like the [JDK_CUSTOM_TARGET mentioned on line 30](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L30)), and defined at [openjdk.mkL110](https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L110) and [L115](https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L115).

**Comment by totorororo** [comment]
I can try to solve this

**Comment by smlambert** [comment]
Great @totorororo !
