### ISSUE TITLE
Simplify the git clone repo to openjdk-jdk folder

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2693]
For openjdk tests we need to git clone openjdk repo to specific folder openjdk-jdk. Currently it's done by two steps in a couple places https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L247

1. git clone to default folder
2. ` <move file="${jdkName}" tofile="openjdk-jdk"/>` 

It would be nice to use one single straightforward command `git clone git@github.com:whatever folder-name` to make the code simple and clear.

**Comment by rainadaniella** [comment]
i can work on this

**Comment by smlambert** [comment]
Great, thanks @rainadaniella !

**Comment by yinggzz** [comment]
Can I work on this if it hasn't been resolved? @smlambert

**Comment by smlambert** [comment]
Go for it @yinggzz !  ;)
