### ISSUE TITLE
Comment triggered PR build (run aqa) failed with KeyError: 'custom_openj9_repo'

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2697]
Comment triggered PR build (run aqa) failed with KeyError: 'custom_openj9_repo' in aqa-tests repo

https://github.com/adoptium/aqa-tests/pull/2695#issuecomment-871089710

```
Traceback (most recent call last):
 File "TKG/scripts/testBot/runAqaArgParse.py", line 121, in <module>
 main()
 File "TKG/scripts/testBot/runAqaArgParse.py", line 64, in main
 if config['custom_openj9_repo']:
KeyError: 'custom_openj9_repo'
```

For now, [runAqaConfig.json ](https://github.com/adoptium/aqa-tests/blob/master/.github/workflows/runAqaConfig.json) needs to be updated to set `"custom_openj9_repo": true`.

As mentioned in https://github.com/eclipse-openj9/openj9/pull/13049#issuecomment-867916527, I think we should remove runAqaConfig.json file eventually.

**Comment by keshavgbpecdelhi** [comment]
Assignment

**Comment by llxia** [comment]
PR #2733 is delivered. Close this issue
