### ISSUE TITLE
Read json file to trigger Jenkins Grinder

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2702]
As part of [Create a Disabled tests pipeline](https://github.com/adoptium/aqa-tests/issues/1853), we should read this JSON file and trigger Grinder for GIT_ISSUE_STATUS=closed

- input file:
```
[{
"JDK_VERSION" : 17,
"JDK_IMPL" : "hotspot",
"TARGET" : "jdk_custom",
"CUSTOM_TARGET" : "java/lang/ClassLoader/nativeLibrary/NativeLibraryTest.java",
"GIT_ISSUE" : "https://github.com/adoptium/temurin-build/issues/248",
"PLATFORM" : "all",
"GIT_ISSUE_STATUS": "closed"
},{
"JDK_VERSION" : 16,
"JDK_IMPL" : "openj9",
"TARGET" : "jdk_custom",
"CUSTOM_TARGET" : "java/lang/ClassLoader/Assert.java",
"GIT_ISSUE" : "https://github.com/eclipse-openj9/openj9/issues/6668",
"PLATFORM" : "x86-64_mac",
"GIT_ISSUE_STATUS": "open"
}]
```

- trigger Grinder for GIT_ISSUE_STATUS=closed. This can be a separate Jenkins job that does the following:
  - read JSON file in groovy
  - find the records with GIT_ISSUE_STATUS=closed
  - trigger [Grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/) with the parameters
  - optional: this Jenkins job can take JSON as a parameter instead of reading a file on disk

**Comment by psaunderualberta** [comment]
I'll take this Shelley

**Comment by llxia** [comment]
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/triggerGrinder.groovy

**Comment by amir-waheed** [comment]
Can I have this assigned to me?
