### ISSUE TITLE
Please use a released version of tomcat for the test.

### ISSUE THREAD

**Issue by jfclere** [adoptium/aqa-tests#2703]
https://github.com/adoptium/aqa-tests/blob/97830a294fb593edb3486b82fce39c99f18858c3/external/tomcat/test.properties#L4
10.0.0-M5 is old 10.0.7 is the actual one.

It would be nice to test the 9.0.x branch too as that is the most used version.

**Comment by smlambert** [comment]
related: https://github.com/adoptium/aqa-tests/issues/1971

**Comment by smlambert** [comment]
Adding this to GHC opensource day, as described in the description, what is required is to update:
https://github.com/adoptium/aqa-tests/blob/master/external/tomcat/test.properties#L4 with tag_version=10.0.7 

Reviewer can trigger testing to verify the change.

**Comment by ManasviGoyal** [comment]
@smlambert pls check
