### ISSUE TITLE
Update directoriesFilesChangePR workflow file to test with jdk16 instead of 15

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2715]
With the release cadence of Java marching forward, jdk15 is already done, we have moved to jdk16 and the PR testing needs to reflect that.  This is a good first issue to check the workflow files in the .github directory to ensure they are using jdk16 instead of jdk15 to test against.

For example: 
https://github.com/adoptium/aqa-tests/blob/master/.github/workflows/directoriesFilesChangePR.yml#L37 should get updated.

**Comment by ManasviGoyal** [comment]
@smlambert please check
