### ISSUE TITLE
Unexclude tests related to infra/1274 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#2716]
It is believed that https://github.com/adoptium/infrastructure/issues/1274 has been resolved.  In order to verify it is fixed, we need to remove the excludes relating to it and rerun testing.  

The action to take is to remove the exclude entries from the 4 problemlist files, then we can rerun the tests to verify they are no longer failing.

From https://github.com/adoptium/infrastructure/issues/1274#issuecomment-874174355:  

How to find exclusions? search for https://github.com/adoptium/infrastructure/issues/1274 in this aqa-tests repo results in 4 findings and delete the lines:
- [ProblemList_openjdk8.txt_L317](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk8.txt#L317)
- [ProblemList_openjdk11.txt_L125-126](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk11.txt#L125-L126)
- [ProblemList_openjdk14.txt_L170-171](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk14.txt#L170-L171)
- [ProblemList_openjdk15.txt_L167-168](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk15.txt#L167-L168)

Reviewer of this PR can then run a Grinder to check whether these tests pass on a test run or not (focus on LTS releases, jdk8 and jdk11).

**Comment by unnati914** [comment]
i can work on this

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/aqa-tests/pull/2731
