### ISSUE TITLE
Parallel test jobs do not archive to Jenkins failed testoutput.jar results of children jck jobs

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#2719]
Parallel run tests only get their TAP results copied, the testoutput.jar is not archived by the parent job:
https://github.com/adoptium/aqa-tests/blob/14f5a8348e22e5616dea2ea001ab8d693cddfeee/buildenv/jenkins/JenkinsfileBase#L911

**Comment by sophia-guo** [comment]
@andrew-m-leonard Are this feature still required?

**Comment by andrew-m-leonard** [comment]
probably not
