### ISSUE TITLE
Functional test FileTest.modifyTest() failed on some machines.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2774]
Functional test FileTest.modifyTest() failed on some machines and passed on others.
https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_special.functional_x86-64_linux

```
expected:<2021-07-22T20:29:26Z> but was:<2021-07-22T20:29:26.001Z>
```

Suspect those machines don't support micro seconds. Test should be updated https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/src/FileTest.java#L125-L143

**Comment by smlambert** [comment]
Is this still an issue?

**Comment by smlambert** [comment]
> Suspect those machines don't support micro seconds. Test should be updated https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/src/FileTest.java#L125-L143

FYI - @KKES335 what do you think about the suggestion to make the test more flexible?

**Comment by sophia-guo** [comment]
Failed on [test-ibmcloud-rhel6-x64-1](https://ci.adoptopenjdk.net/computer/test-ibmcloud-rhel6-x64-1)
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_special.functional_x86-64_linux/22/

Passed on test-ibmcloud-rhel7-x64-1, https://ci.adoptopenjdk.net/job/Grinder/3887/console

**Comment by KKES335** [comment]
I think this issue can be addressed by test cases.
Our team is working on a fix.
