### ISSUE TITLE
Functional MBCS_Tests datetime tests are duplicate running twice for each build.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2775]
Functional MBCS_Tests datetime tests are defined in https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/testng.xml and https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/testng11.xml.

Tests are defined running in https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/playlist.xml#L17 and https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/playlist.xml#L38.

That is MBCS_Tests_datetime_formatter actually includes MBCS_Tests_datetime. To avoid the duplicate run `<test name="dateTest">` should be removed from the file https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/datetime/testng11.xml.

**Comment by JasmineEHurst** [comment]
May I work on this issue?

**Comment by llxia** [comment]
Please do. Thanks @JasmineEHurst
