### ISSUE TITLE
Tweetest: Fetching tweets related to external tests

### ISSUE THREAD

**Issue by SAY-droid427** [adoptium/aqa-tests#2785]
For the Tweetest project, we need to fetch the tweets which have certain keywords like external_custom, etc. We will list the criteria that a tweet should match in order to be fetched via the Twitter v2 API in this issue.
@smlambert @sophia-guo @llxia

**Comment by SAY-droid427** [comment]
@smlambert @llxia @sophia-guo I have written the code for fetching the tweets related to the external_custom hashtags. I have currently stored the code in a repository https://github.com/SAY-droid427/testTweet/blob/main/index.js. Where should I put the code in the aqa-test repo?

**Comment by SAY-droid427** [comment]
The outputs now relate to all tests, however we can change it to external_test(currently there are no tweets related to external_custom)
![Uploading SSS.png…]()

**Comment by smlambert** [comment]
Nice @SAY-droid427 !  
I was thinking this can go into a subdir of buildenv called tweetest:
https://github.com/adoptium/aqa-tests/tree/master/buildenv/tweetest

But will ask @sophia-guo and @llxia to weigh in with their thoughts on location.

**Comment by SAY-droid427** [comment]
Should I go ahead with this? @lxia @sophia-guo
