### ISSUE TITLE
java/beans/XMLEncoder/* failed on AIX jdk16 with `java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2810]
java/beans/XMLEncoder/* failed on AIX jdk16 with `_X11TransTRANS(ibmSHMConnect) () can't connect: errno = 78
java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.`

java/beans/XMLEncoder/Test4631471.java.Test4631471
java/beans/XMLEncoder/Test4652928.java.Test4652928
java/beans/XMLEncoder/Test4822050.java.Test4822050
java/beans/XMLEncoder/Test4903007.java.Test4903007
java/beans/XMLEncoder/Test6437265.java.Test6437265
java/beans/XMLEncoder/Test6501431.java.Test6501431
java/beans/XMLEncoder/Test6570354.java.Test6570354
java/beans/XMLEncoder/java_awt_CardLayout.java.java_awt_CardLayout
java/beans/XMLEncoder/java_awt_GridBagLayout.java.java_awt_GridBagLayout
java/beans/XMLEncoder/java_awt_ScrollPane.java.java_awt_ScrollPane
java/beans/XMLEncoder/javax_swing_Box.java.javax_swing_Box
java/beans/XMLEncoder/javax_swing_BoxLayout.java.javax_swing_BoxLayout
java/beans/XMLEncoder/javax_swing_Box_Filler.java.javax_swing_Box_Filler
java/beans/XMLEncoder/javax_swing_DefaultCellEditor.java.javax_swing_DefaultCellEditor
java/beans/XMLEncoder/javax_swing_JButton.java.javax_swing_JButton
java/beans/XMLEncoder/javax_swing_JLayeredPane.java.javax_swing_JLayeredPane
java/beans/XMLEncoder/javax_swing_JSplitPane.java.javax_swing_JSplitPane
java/beans/XMLEncoder/javax_swing_JTree.java.javax_swing_JTree
java/beans/XMLEncoder/javax_swing_OverlayLayout.java.javax_swing_OverlayLayout
java/beans/XMLEncoder/javax_swing_border_TitledBorder.java.javax_swing_border_TitledBorder
java/beans/XMLEncoder/javax_swing_plaf_BorderUIResource_TitledBorderUIResource.java.javax_swing_plaf_BorderUIResource_TitledBorderUIResource

https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_ppc64_aix_testList_1/9/#showFailuresLink

related https://github.com/adoptium/adoptium/issues/63

Looks like the test set up issue: https://github.com/adoptium/aqa-tests/blob/4240e6fb9430017117ad9e41296c91af8bc8a247/buildenv/jenkins/JenkinsfileBase#L594-L599

```
				if (env.SPEC.startsWith('aix')) {
					sh "nohup /usr/bin/X11/X -force -vfb -x abx -x dbe -x GLX :0 &"
					env.DISPLAY = ":0"
					echo "env.DISPLAY is ${env.DISPLAY}"
					makeTest("${RUNTEST_CMD}")
				}
```

**Comment by sophia-guo** [comment]
Trying with `env.DISPLAY = ":1"` will get similar error `_X11TransTRANS(ibmSHMConnect) () can't connect: errno = 68
java.awt.AWTError: Can't connect to X11 window server using ':1' as the value of the DISPLAY variable.`

**Comment by smlambert** [comment]
https://www.ibm.com/docs/en/db2woc?topic=message-tcpip-errors 

errno = 68 -> EADDRNOTAVAIL The specified host name or IP address is not available from the local system.

**Comment by sophia-guo** [comment]
The error code could be different everytime. In the release build, the errno = 78, timeout.

**Comment by sophia-guo** [comment]
Refer to https://github.com/adoptium/aqa-tests/issues/2810, close this one.
