### ISSUE TITLE
com/sun/jndi/dns/ConfigTests/Timeout.java failed on s390 with jdk11, 16

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2820]
com/sun/jndi/dns/ConfigTests/Timeout.java failed on s390 with jdk11, 16 with error message:

```
javax.naming.CommunicationException: DNS error [Root exception is java.net.SocketException: No route to host (Receive failed)]; remaining name ''
```

 https://ci.adoptopenjdk.net/job/Test_openjdk16_hs_extended.openjdk_s390x_linux_testList_1/9/

**Comment by smlambert** [comment]
Should check if this is specific to certain machines, and if so, transfer to infrastructure.

**Comment by sophia-guo** [comment]
Dup of https://github.com/adoptium/aqa-tests/issues/2876
