### ISSUE TITLE
Triage JDK 17 Primary Platform Pipeline

### ISSUE THREAD

**Issue by karianna** [adoptium/aqa-tests#2853]
#### Release Summary Report for openjdk17-pipeline 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=61411ffdc6182d021721328b&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=61411ffdc6182d021721328b) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/187/ 
Started by user Martijn Verburg at 9/14/2021, 6:11:05 PM 

 --- 

[**create_installer_linux**](undefined) ❌ undefined ❌

[**create_installer_mac**](undefined) ❌ undefined ❌

[**create_installer_windows**](undefined) ❌ undefined ❌

[**jdk17-linux-x64-hotspot_SmokeTests**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-x64-hotspot_SmokeTests/28/) ❌ FAILURE ❌

[**jdk17-windows-x64-hotspot_SmokeTests**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17/job/jdk17-windows-x64-hotspot_SmokeTests/28/) ⚠️ UNSTABLE ⚠️
- failing with `java.lang.AssertionError: Expected ZGC to be present but it is absent. expected [0] but found [1]` need to confirm whether it is no longer expected to be present in JDK17 on Win64 - **OK to release** - Smoke test needs to be run on a more modern Windows.  Binary manually tested on Windows 10 and it was OK.

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

 --- 

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux/26/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0/12/) ⚠️ UNSTABLE ⚠️
jdk_security_infra_1 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61417929c6182d021721f6db) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e986&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=61417929c6182d021721f6db&testName=jdk_security_infra_1) 
- 3 testcases failing with `Execution failed: `main' threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status `, deep history shows it passing on test-docker-ubuntu1804-x64-1, rerun on another docker-ubuntu machine in https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1388/ **Passes**: https://ci.adoptopenjdk.net/job/Grinder/1388/testReport/ - This means that some of our docker machines are not setup properly to support these certificate tests, infra issue needs raising, also related: https://github.com/adoptium/aqa-tests/issues/2074

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2/12/) ⚠️ UNSTABLE ⚠️
jdk_jmx_0 => [deep history 1/4 passed](https://trss.adoptium.net/deepHistory?testId=61417939c6182d021721f74f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e989&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61417939c6182d021721f74f&testName=jdk_jmx_0) 
jdk_jfr_0 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61417939c6182d021721f751) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e989&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61417939c6182d021721f751&testName=jdk_jfr_0) 
jdk_jfr_1 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61417939c6182d021721f752) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e989&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61417939c6182d021721f752&testName=jdk_jfr_1) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows/26/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0/13/) ⚠️ UNSTABLE ⚠️
jdk_other_0 => [deep history 1/4 passed](https://trss.adoptium.net/deepHistory?testId=61415e77c6182d02172192b8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415dbcc6182d0217218f77&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0&testId=61415e77c6182d02172192b8&testName=jdk_other_0) 
- 1 testcase failure, com/sun/jndi/dns/ConfigTests/Timeout.java, Deep history shows passes on test-ibmcloud-win2012r2-x64-1, so rerun on that machine in https://ci.adoptopenjdk.net/job/Grinder/1390 **PASSES** - what is different about this machine versus other machines test-azure-win2012r2-x64-* and test-packet-win2012r2-x64-1 that sees test case passes here but not elsewhere?  needs infra issue to investigate
 
jdk_tools_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61415e77c6182d02172192d0) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415dbcc6182d0217218f77&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0&testId=61415e77c6182d02172192d0&testName=jdk_tools_0) 
- WinInstallerIconTest fails (consistently) with `light.exe : error LGHT0217 : Error executing ICE action 'ICE01'. The most common cause of this kind of ICE failure is an incorrectly registered scripting engine. See http://wixtoolset.org/documentation/error217/ for details and how to solve this problem. The following string format was not expected by the external UI message logger: "The Windows Installer Service could not be accessed. This can occur if the Windows Installer is not correctly installed. Contact your support personnel for assistance.".` - related: https://github.com/adoptium/aqa-tests/issues/2384

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/13/) ⚠️ UNSTABLE ⚠️
jdk_tools_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61415e7ec6182d0217219325) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415dbcc6182d0217218f78&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1&testId=61415e7ec6182d0217219325&testName=jdk_tools_1) - same issue as for jdk_tools_0, `[2021-09-15T00:38:44.295Z] STDERR:
[2021-09-15T00:38:44.295Z] java.lang.AssertionError: Expected [0]. Actual [1]: Check command [E:\workspace\Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1\openjdkbinary\j2sdk-image\bin\jpackage.exe --input .\test\input --dest .\test\output --name WinInstallerIconTestWithDefaultIcon --type exe --main-jar hello.jar --main-class Hello --win-console --runtime-image .\test\fake_runtime --verbose](17) exited with 0 code
[2021-09-15T00:38:44.295Z] 	at jdk.jpackage.test.TKit.error(TKit.java:279)` - related: https://github.com/adoptium/aqa-tests/issues/2384

[**Test_openjdk17_hs_sanity.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_windows/78/) ⚠️ UNSTABLE ⚠️
jdk_math_0 => [deep history 6/7 passed](https://trss.adoptium.net/deepHistory?testId=61415d8ec6182d0217218d83) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415cc9c6182d02172188c8&buildName=Test_openjdk17_hs_sanity.openjdk_x86-64_windows&testId=61415d8ec6182d0217218d83&testName=jdk_math_0) 
- java/math/BigInteger fails with `Execution failed: `main' threw exception: java.io.FileNotFoundException: serialtest (Access is denied)` - was passing consistently in deep history, including on this same machine, rerunning at: https://ci.adoptopenjdk.net/job/Grinder/1391 - **Passes**

**Comment by smlambert** [comment]
@karianna - did you see any of the notes I put in the pre-release issue or https://github.com/adoptium/aqa-test-tools/issues/541 - you have pasted the 'old style' report to this issue, below is the new style report...

Also, last week, @sophia-guo and I assigned ourselves to the triage EPIC under which this issue lives, so we will be 'helping' triage today. 

---------------------

#### Release Summary Report for openjdk17-pipeline 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=61411ffdc6182d021721328b&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=61411ffdc6182d021721328b) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/187/ 
Started by user Martijn Verburg at 9/14/2021, 6:11:05 PM 

 --- 

[**create_installer_linux**](undefined) ❌ undefined ❌

[**create_installer_mac**](undefined) ❌ undefined ❌

[**create_installer_windows**](undefined) ❌ undefined ❌

[**jdk17-linux-x64-hotspot_SmokeTests**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17/job/jdk17-linux-x64-hotspot_SmokeTests/28/) ❌ FAILURE ❌

[**jdk17-windows-x64-hotspot_SmokeTests**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk17/job/jdk17-windows-x64-hotspot_SmokeTests/28/) ⚠️ UNSTABLE ⚠️

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

 --- 

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux/26/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0/12/) ⚠️ UNSTABLE ⚠️
jdk_security_infra_1 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61417929c6182d021721f6db) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e986&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0&testId=61417929c6182d021721f6db&testName=jdk_security_infra_1) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2/12/) ⚠️ UNSTABLE ⚠️
jdk_jmx_0 => [deep history 1/4 passed](https://trss.adoptium.net/deepHistory?testId=61417939c6182d021721f74f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e989&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61417939c6182d021721f74f&testName=jdk_jmx_0) 
jdk_jfr_0 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61417939c6182d021721f751) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e989&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61417939c6182d021721f751&testName=jdk_jfr_0) 
jdk_jfr_1 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=61417939c6182d021721f752) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=614177fdc6182d021721e989&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2&testId=61417939c6182d021721f752&testName=jdk_jfr_1) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows/26/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0/13/) ⚠️ UNSTABLE ⚠️
jdk_other_0 => [deep history 1/4 passed](https://trss.adoptium.net/deepHistory?testId=61415e77c6182d02172192b8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415dbcc6182d0217218f77&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0&testId=61415e77c6182d02172192b8&testName=jdk_other_0) 
jdk_tools_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61415e77c6182d02172192d0) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415dbcc6182d0217218f77&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0&testId=61415e77c6182d02172192d0&testName=jdk_tools_0) 

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/13/) ⚠️ UNSTABLE ⚠️
jdk_tools_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=61415e7ec6182d0217219325) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415dbcc6182d0217218f78&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1&testId=61415e7ec6182d0217219325&testName=jdk_tools_1) 

[**Test_openjdk17_hs_sanity.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_x86-64_windows/78/) ⚠️ UNSTABLE ⚠️
jdk_math_0 => [deep history 6/7 passed](https://trss.adoptium.net/deepHistory?testId=61415d8ec6182d0217218d83) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=61415cc9c6182d02172188c8&buildName=Test_openjdk17_hs_sanity.openjdk_x86-64_windows&testId=61415d8ec6182d0217218d83&testName=jdk_math_0)

**Comment by smlambert** [comment]
Shelley on Win64 triage

**Comment by andrew-m-leonard** [comment]
Andrew looking at win64 smoke test issue: failing with java.lang.AssertionError: Expected ZGC to be present but it is absent.

**Comment by sophia-guo** [comment]
Sophia on Linux triage

**Comment by sophia-guo** [comment]
Sophia on Linux triage .

- [ ] Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_0 ⚠️ UNSTABLE ⚠️ - **OK to Release**

jdk_security_infra_1 => deep history 1/3 passed | possible issues From @andrew-m-leonard 

3 testcases failing with Execution failed: main' threw exception: java.lang.RuntimeException: TEST FAILED: couldn't determine EE certificate status `, deep history shows it passing on test-docker-ubuntu1804-x64-1, rerun on another docker-ubuntu machine in https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1388/ Passes: https://ci.adoptopenjdk.net/job/Grinder/1388/testReport/

- [ ] Test_openjdk17_hs_extended.openjdk_x86-64_linux_testList_2 ⚠️ UNSTABLE ⚠️

jdk_jmx_0 => deep history 1/4 passed | possible issues
jdk_jfr_0 => deep history 1/3 passed | possible issues
jdk_jfr_1 => deep history 1/3 passed | possible issues

**Comment by karianna** [comment]
@ShelleyLambert and @sophia-guo - Looks like this is now complete thank you! Are you happy for me to close this?

**Comment by smlambert** [comment]
Yes, all primary platforms are "OK to release"
