### ISSUE TITLE
Cannot run `make compile` twice with openjdk tests 

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2879]
In the local run, if we follow [the doc](https://github.com/eclipse-openj9/openj9/wiki/Reproducing-Test-Failures-Locally#run-specific-test-class-from-openjdk-tests-on-jdk11-linux-s390x-openj9-sdk) to run openjdk test. We found that we cannot run `make compile` twice with openjdk tests.

```
getJtreg:
    [mkdir] Created dir: /root/TEST/jvmtest/openjdk
     [exec] gzip: jtreg_6_1.tar already exists; not overwritten
BUILD FAILED
/root/TEST/aqa-tests/TKG/scripts/build_test.xml:76: The following error occurred while executing this line:
/root/TEST/aqa-tests/openjdk/build.xml:278: The following error occurred while executing this line:
/root/TEST/aqa-tests/openjdk/build.xml:76: exec returned: 2
```

I suspect when we run it the second time, the jtreg.jar is download and it fails to unzip again https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L76

**Comment by amandanguyeen** [comment]
I can take this!

**Comment by sophia-guo** [comment]
The reason is jtreg.tar exists so gzip would exit as error as failonerror has been set. The solution is using -f option in https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L77. 

`<arg line="-df ${jtregTar}.tar.gz" />`

**Comment by amandanguyeen** [comment]
Updated with the new -f option! Here's the grinder job for the recent change: https://ci.adoptopenjdk.net/job/Grinder/1475/

**Comment by llxia** [comment]
Thanks @amandanguyeen for the update. Either solution is fine with me.
