### ISSUE TITLE
Generate property file with SHA info

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2889]
Currently, we generate [SHA.txt](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/1452/artifact/aqa-tests/TKG/SHA.txt) for capture test repo shas. This file is easy to read, but it can not be used directly to set env value.

Maybe it is easier to create a property file with key and value pairs. The key should match with [get.sh parameters](https://github.com/adoptium/aqa-tests/blob/master/get.sh#L17) and values in ant build.xml. For example in `testenv.properties` file, we have
```
TKG_REPO=https://github.com/adoptium/TKG.git
TKG_BRANCH=3f1b8746bb6dd25870cac3fc116ad4754ec5d700
JDK_REPO=xxx
JDK_BRANCH=xxx
...
```

In get.sh, we can simply add `source ./testenv.properties` to load the variables (i.e., TKG_REPO, TKG_BRANCH, etc).
For ant (build.xml) to work, the variables need to be set as env variables (i.e., JDK_REPO, JDK_BRANCH, etc).
- option1: use Jenkins readProperties. Similar to https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L460
- option2: add a warper script for [make compile in Jenkinsfilebase](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L490)
```
source ./testenv.properties
make compile
```
or 
```
while read line; do
    export $line
done < testenv.properties
make compile
```

IMO, option2 seems better as it will cover the local run as well.

In Grinder, add a boolean flag `USE_TESTENV_PROPERTIES`. If it is set to true, ignore the params in Grinder, read `testenv.properties` and set values as env variable (override params if set) for ant scripts and run get.sh. 
And If the flag is set to true, we are expecting to find the file under root `testenv.properties`. Print error and exit the build if this file cannot be found. This logic should be in get.sh.
If it is set to false, proceed as a regular run (that is take the parameters from Grinder).

Please test both the local and Grinder run.

Update: broken into several steps:
- [generate the `testenv.properties` file and archive `testenv.properties`](https://github.com/adoptium/aqa-tests/issues/2916)
- [add `USE_TESTENV_PROPERTIES ` flag, consume `testenv.properties` in get.sh](https://github.com/adoptium/aqa-tests/issues/2917)
- [consume `testenv.properties` in system tests](https://github.com/adoptium/aqa-tests/issues/2918)
- [consume `testenv.properties` in openjdk tests](https://github.com/adoptium/aqa-tests/issues/2963)

**Comment by psaunderualberta** [comment]
I will take this for now, I'll likely end up breaking it into smaller issues like recommended.

**Comment by llxia** [comment]
Thanks @psaunderualberta . Please check [meeting recording](https://drive.google.com/file/d/1wUIsszOU4jR1q9Zcljzkd--byy8CesQa/view?usp=sharing) for details.

For the first issue - generate the testenv.properties file and archive testenv.properties
I think it is easier just update the existing logic of generating SHA.txt :
https://github.com/adoptium/aqa-tests/blob/master/get.sh#L619
https://github.com/adoptium/aqa-tests/blob/master/get.sh#L626
https://github.com/adoptium/TKG/blob/07171520f8b0849d922125d35380d45193f9c5bf/scripts/getSHA.sh

**Comment by llxia** [comment]
preliminary `testenv.properties` is created: https://github.com/adoptium/aqa-tests/pull/2921

**Comment by smlambert** [comment]
I believe this one is now addressed, closing as complete.
