### ISSUE TITLE
External wildfly, spring, system-test, and functional-test failed with “git not found” error

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/aqa-tests#2900]
Testname: external/wildfly, external/spring, external/system-test, external/functional-test
jdk_impl: openj9
jdk_verison: 11
platform: xlinux
test_link: 
- https://ci.adoptopenjdk.net/job/Grinder_wildfly/2/console
- https://ci.adoptopenjdk.net/job/Grinder_spring/2/console
- https://ci.adoptopenjdk.net/job/Grinder_system-test/2/console
- https://ci.adoptopenjdk.net/job/Grinder_functional-test/2/console
```
20:09:22       [exec] Step 14/18 : RUN git clone
20:09:22       [exec]  ---> Running in fbbde2c78917
20:09:23       [exec] [91m/bin/sh: 1: git: not found
20:09:23       [exec] The command '/bin/sh -c git clone' returned a non-zero code: 127
20:09:23       [exec] [0m
20:09:23  
20:09:23  BUILD FAILED
20:09:23  /home/jenkins/workspace/Grinder_functional-test/aqa-tests/TKG/scripts/build_test.xml:76: The following error occurred while executing this line:
20:09:23  /home/jenkins/workspace/Grinder_functional-test/aqa-tests/external/functional-test/build.xml:25: The following error occurred while executing this line:
20:09:23  /home/jenkins/workspace/Grinder_functional-test/aqa-tests/external/build.xml:87: exec returned: 127
```

**Comment by sophia-guo** [comment]
Looking at the output `Step 8/18 : RUN apt-get update 	&& apt-get install -y --no-install-recommends  	&& rm -rf /var/lib/apt/lists/*`, which means no git installed. That is the docker file is not correctly generated. Might be related with https://github.com/adoptium/aqa-tests/pull/2761,  see https://github.com/adoptium/aqa-tests/pull/2761#issuecomment-887479474

**Comment by smlambert** [comment]
Note also we will have to do a major overhaul of external tests, as we are currently pulling from the AdoptOpenJDK docker location, which I do not know whether is being updated with new images or not... suspect not.

This is not an excuse for why it should not work with the latest available 'nightly' tag, but perhaps we need to look at what is being generated 'FROM' that nightly image.

**Comment by sophia-guo** [comment]
Another issue is `${test_tag}` was replaced correctly when dockerfile was generated. 
`Step 13/18 : ENV SPRING_TAG=$SPRING_TAG`
