### ISSUE TITLE
Correct wrong OSNAME-ARCH in problemlist*.txt

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2908]
In Openjdk list of quarantined tests followed by labels as:

-  generic-all   Problems on all platforms
-  generic-ARCH  Where ARCH is one of: sparc, sparcv9, x64, i586, etc.
-  OSNAME-all    Where OSNAME is one of: solaris, linux, windows, macosx, aix
-  OSNAME-ARCH   Specific on to one OSNAME and ARCH, e.g. solaris-amd64
-  OSNAME-REV    Specific on to one OSNAME and REV, e.g. solaris-5.8

There are couple of tests are not listed as this format, which means tests are actually not excluded. 

Known tests:
- arm-linux: https://github.com/adoptium/aqa-tests/blob/7f6856420179eb7088a6b51861b9c9b529f7460b/openjdk/excludes/ProblemList_openjdk8.txt#L51
- x86-64_windows: https://github.com/adoptium/aqa-tests/blob/034e5c2dc64dfb92ca336ecf12b4949a946c78ef/openjdk/excludes/ProblemList_openjdk11-openj9.txt#L30

 For example test compiler/tiered/Level2RecompilationTest.java is still running and failed on linux-arm https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk8_hs_extended.openjdk_arm_linux_testList_1/10/#showFailuresLink

`arm-linux` should update to `linux-arm`, and `x86-64_windows` should be `windows-x86`

**Comment by mittaljethwa** [comment]
I would like to work on this issue.
