### ISSUE TITLE
generate the testenv.properties file and archive testenv.properties

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2916]
For detail: https://github.com/adoptium/aqa-tests/issues/2889

I think it is easier just update the existing logic of generating SHA.txt :
https://github.com/adoptium/aqa-tests/blob/master/get.sh#L619
https://github.com/adoptium/aqa-tests/blob/master/get.sh#L626
https://github.com/adoptium/TKG/blob/07171520f8b0849d922125d35380d45193f9c5bf/scripts/getSHA.sh

**Comment by psaunderualberta** [comment]
Currently working on this

**Comment by llxia** [comment]
preliminary testenv.properties is added: https://github.com/adoptium/aqa-tests/blob/master/testenv/testenv.properties

**Comment by llxia** [comment]
Close this issue as PRs are delivered.
