### ISSUE TITLE
add USE_TESTENV_PROPERTIES flag

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2917]
Add USE_TESTENV_PROPERTIES boolean flag in [Jenkinsfilebase](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase). If it is set, consume [testenv.properties](https://github.com/adoptium/aqa-tests/blob/master/testenv/testenv.properties) in get.sh

details in https://github.com/adoptium/aqa-tests/issues/2889

**Comment by xius666** [comment]
Can I take this issue?

**Comment by llxia** [comment]
Thanks @xius666

**Comment by llxia** [comment]
[The grinder](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder) is updated to have USE_TESTENV_PROPERTIES

**Comment by llxia** [comment]
PR is delivered. Close this issue.
