### ISSUE TITLE
Clean platform_map  in generateDisabledTestListJson

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2923]
We would like to clean platform_map  in generateDisabledTestListJson.py.

- remove  `"arm-linux": ["arm_linux"],`
https://github.com/adoptium/aqa-tests/blob/master/disabledTestParser/generateDisabledTestListJson.py#L8
- `"windows-x86": ["x86-64_windows", "x86-32_windows"],` should be `"windows-x86": ["x86-32_windows"],`
 https://github.com/adoptium/aqa-tests/blob/master/disabledTestParser/generateDisabledTestListJson.py#L16

**Comment by tejaswini0604** [comment]
I would like to work on this issue

**Comment by llxia** [comment]
Thanks @tejaswini0604

**Comment by llxia** [comment]
Thanks @tejaswini0604 for the PR https://github.com/adoptium/aqa-tests/pull/2925
