### ISSUE TITLE
Switch to the Adoptium api to get the latest nightly builds testimage

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2931]
Currently we are still using the Adoptopenjdk api to get expected jdk testimage, which should switch to the Adoptium api.

Update
`https://api.adoptopenjdk.net/v3/binary/latest/${JDK_VERSION}/${release_type}/${os}/${arch}/testimage/${JDK_IMPL}/${heap_size}/adoptopenjdk`

to 
`https://api.adoptium.net.net/v3/binary/latest/${JDK_VERSION}/${release_type}/${os}/${arch}/testimage/${JDK_IMPL}/${heap_size}/adoptium?project=jdk`

https://github.com/adoptium/aqa-tests/blob/master/get.sh#L230-L231

**Comment by sophia-guo** [comment]
Similar to #https://github.com/adoptium/aqa-tests/issues/2909

**Comment by dingx170** [comment]
Hi @sophia-guo, can I try to solve this issue?

**Comment by sophia-guo** [comment]
Yes, please go ahead.
