### ISSUE TITLE
Update ITERATIONS description in testJobTemplate

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#2941]
It would be nice to have `ITERATIONS` description updated as following in testJobTemplate
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L358

```
Optional. Number of times to repeat execution of make target. <br/>
Use ITERATIONS with PARALLEL=None, run the same test(s) in a loop on one machine <br/>
Use ITERATIONS and NUM_MACHINES with PARALLEL=NodesByIterations, run the same test(s) in x (NUM_MACHINES) parallel runs with y (ITERATIONS) in each run<br/>
```

**Comment by prahasR** [comment]
@llxia please assign this to me. I want to contribute to this.

**Comment by prahasR** [comment]
@llxia please review

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/aqa-tests/pull/2945
