### ISSUE TITLE
Remove redundant dependent properties in test.properties files under external category

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2962]
Remove all redundant properties declaration in all test.properties files under external category.

For example file https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties

we'd like to remove the following 4 lines as those are redundant dependent properties.

https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties#L8
https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties#L9
https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties#L12
https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties#L14

**Comment by ManasviGoyal** [comment]
I would like to work on this
