### ISSUE TITLE
enhance the function getProperty() to deal with quotations

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#2966]
There are duplicate[ logic of removing the quotations](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L210, https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L212, https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L217) after calling [getProperty() ](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L175), it would be nice to move the logic to the getProperty() if needed.

Meanwhile it would be also nice to update test.properties files to remove all the unnecessary quotations for property values. That is if property value doesn't include a space the quotation would be unnecessary.

**Comment by norbline** [comment]
Hi, i am Norbline an outreachy applicant, I would like to work on this issue

**Comment by julian55455** [comment]
Hi @andrew-m-leonard  can I take on this

**Comment by smlambert** [comment]
@norbline is assigned to this issue

**Comment by julian55455** [comment]
Oooops sorry I was so fast I dint notice that it was assigned.... I will see through others
Thanks

**Comment by smlambert** [comment]
Closed via #3008
