### ISSUE TITLE
Remove JRE_IMAGE in jck.mk

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3033]
JRE_IMAGE and JRE_COMMAND  are defined in [TKG](https://github.com/adoptium/TKG/blob/master/settings.mk#L63). We can remove the logic in jck.mk.

Please remove the following lines:
https://github.com/adoptium/aqa-tests/blob/599df39672904dec9b3ffb7670bf15d9dfb4e7e4/jck/jck.mk#L75-L79

The change can be verified using USE_JRE in Grinder (USE_JRE will be added via PR https://github.com/adoptium/aqa-tests/pull/3024)

**Comment by harshikaninawe** [comment]
Can I work on this please?

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/aqa-tests/pull/3159
