### ISSUE TITLE
exclude jdk_tools testcases due to upsteam known issue

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3061]
We'd like to exclude following tests due to the know upstream issue in our problem list on linux-all.

sun/tools/jstatd/TestJstatdExternalRegistry.java
sun/tools/jstatd/TestJstatdPort.java
sun/tools/jstatd/TestJstatdPortAndServer.java

https://bugs.openjdk.java.net/browse/JDK-8081569

**Comment by LizyBbethy** [comment]
I can take this on !

**Comment by LizyBbethy** [comment]
@sophia-guo  
1. do these qualify  under the # jdk_management ?
2. are these to be excluded on all openjdks (8 -18)?

**Comment by sophia-guo** [comment]
@LizyBbethy 

> do these qualify under the # jdk_management ?
 Under jdk_tools

> are these to be excluded on all openjdks (8 -18)?
yes, 8, 11, 17
