### ISSUE TITLE
exclude two security tests in jdk11 for upstream know issue

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3065]
sun/security/krb5/auto/ReplayCacheTestProc.java
sun/security/krb5/auto/rcache_usemd5.sh

https://bugs.openjdk.java.net/browse/JDK-8258855
platform: linux

**Comment by LizyBbethy** [comment]
@sophia-guo  are these to e excluded under # jdk_management section?

**Comment by LizyBbethy** [comment]
i have had to close two PRs due to another contributor using the same branch name .their contribution landed into my branch...i think the naming convention using issue numbers deserves emphasis
working around it
