### ISSUE TITLE
Set TAP file name Jenkins pipeline

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3066]
We need to set TAP file name Jenkins pipeline. This work needs to be delivered together with https://github.com/adoptium/TKG/issues/236.

In [Jenkinsfilebase](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L74), we need to set `env.TAP_NAME=JOB_NAME`.

Please verify the result in Grinder in both regular and parallel cases:
- PARALLEL=None
- PARALLEL=Dynamic and NUM_MACHINES=2

**Comment by amandanguyeen** [comment]
I can take this!
