### ISSUE TITLE
Update external tests to use different Docker images

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3078]
- [x] #3079
- [x] #3080
- [x] For other testing, support being able to use images from other registries (https://github.com/adoptium/aqa-tests/issues/2645)

**Comment by sophia-guo** [comment]
Current using adoptopenjdk image get intermittent failure `  [exec] no matching manifest for linux/amd64 in the manifest list entries`, which blocks other jobs.  @jnjerin I have a PR for #3079 and #3080 https://github.com/adoptium/aqa-tests/compare/master...sophia-guo:test?expand=1 could you take a look and try if it works? Let's first get those two done.

**Comment by sophia-guo** [comment]
Done, close it.
