### ISSUE TITLE
update external test to run with docker images provided by adoptium 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3116]
For external tests we support images defined by following variables. That is 10 * 2 * 8 * 2 * 2 * 20=12800. That is a huge number. As we moved to adoptium official adoptium images  of the Eclipse Temurin Distribution has been adjusted we will also adjust our supported images. 
```
# Supported versions
supported_versions="8 9 10 11 12 13 14 15 16 17"

# Supported JVMs
supported_jvms="hotspot openj9"

# Supported distros
supported_os="alpine debian debianslim ubi ubi-minimal centos clefos ubuntu"

# Supported packges
supported_packages="jdk jre"

# Supported builds
supported_builds="slim full"

# Supported tests
supported_tests="external_custom camel derby elasticsearch jacoco jenkins functional-test kafka lucene-solr openliberty-mp-tck payara-mp-tck quarkus quarkus_quickstarts scala system-test thorntail-mp-tck tomcat tomee wildfly wycheproof netty spring"
```

For now we will adjust to 

```
# Supported versions
supported_versions="8 11 17"

# Supported JVMs
supported_jvms="hotspot" (add openj9 later?)

# Supported distros
supported_os="ubuntu" (add alpine, windows, ubi later?)

# Supported packges
supported_packages="jdk jre"

# Supported builds
supported_builds="full"

# Supported tests
supported_tests="external_custom camel derby elasticsearch jacoco jenkins functional-test kafka lucene-solr openliberty-mp-tck payara-mp-tck quarkus quarkus_quickstarts scala system-test thorntail-mp-tck tomcat tomee wildfly wycheproof netty spring"
```

The definition is in https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh.

Along with this test.properties under each third party application directory will need to update. For example test.properties in camel https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties 

```
debian_packages="git maven"
 alpine_packages="bash git maven"
 centos_packages="git maven"
 ubi_packages="git maven"
```
will be replaced by

```
ubuntu_packages="git maven"
```

Function function set_test_info()  and set_external_custom_test_info() in https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh will also need to update to make this work.

**Comment by LizyBbethy** [comment]
hi @sophia-guo i would like to give this a spin

**Comment by jnjerin** [comment]
I would like to work on this too as it gives a better understanding to another issue I've been working on. @sophia-guo @ShelleyLambert

**Comment by LizyBbethy** [comment]
Hi @sophia-guo @smlambert  here is the PR for the cleanup as required https://github.com/adoptium/aqa-tests/pull/3131
