### ISSUE TITLE
TEST_JDK_HOME should be detected in get.sh

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3128]
In the current logic, CI layer (i.e., Jenkins, etc) sets a TEST_JDK_HOME value. And get.sh will try to detect TEST_JDK_HOME if the path `openjdkbinary/j2sdk-image` is not correct. Only when this happens, we will generate job.properties for CI layer to consume.

https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L59
https://github.com/adoptium/aqa-tests/blob/master/get.sh#L625

As discussed with @renfeiw , in order to make CI layer more generic, we should always output TEST_JDK_HOME in `job.properties` in job.properties and the CI layer should always read it and set `TEST_JDK_HOME`. In this way, the CI layer does not need to set a default TEST_JDK_HOME value.

**Comment by JeromeJu** [comment]
@llxia I'd like to take this :)

Following the `we should always output TEST_JDK_HOME in job.properties`, I'd like to ask what shall we output under this condition here where there's `$TEST_JDK_HOME` is not empty and the `$javac_path` has not been set?
https://github.com/adoptium/aqa-tests/blob/master/get.sh#L634

Thanks!
