### ISSUE TITLE
OpenJDK tests on jdk18 result in error about wrong jtreg version

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#3136]
i.e. https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/367/console

`Error: The testsuite at /home/jenkins/workspace/Grinder/aqa-tests/openjdk/openjdk-jdk/test/jdk requires jtreg version 6.1 b1 or higher and this is jtreg version 6-dev+0.`

@llxia fyi

**Comment by smlambert** [comment]
This one was also needed and has just been merged: https://github.com/adoptium/ci-jenkins-pipelines/pull/212

**Comment by llxia** [comment]
PR #3112 and https://github.com/adoptium/TKG/pull/247 are merged. test.getDependency job at 3 Jenkins servers are updated.
Running Grinder: https://openj9-jenkins.osuosl.org/view/Test/job/Grinder/390/

**Comment by llxia** [comment]
Noticed the failure in Grinder https://github.com/adoptium/TKG/pull/247#issuecomment-970346423. We are working on the fix.

**Comment by llxia** [comment]
https://openj9-jenkins.osuosl.org/job/Grinder/395/

**Comment by llxia** [comment]
Grinder passed with JDK18. The issue is resolved.
