### ISSUE TITLE
Update github workflows to use LTS jdk versions

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3156]
We should check what is currently being used in all of the various workflow yaml files and update them if they are found to be using versions that are no longer interesting:

For example, 16 can be updated to 17 (which is an LTS version):
https://github.com/adoptium/aqa-tests/blob/master/.github/workflows/directoriesFilesChangePR.yml#L37

**Comment by nadeensami** [comment]
I'll take this one
