### ISSUE TITLE
Remove runAqaConfig.json

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3163]
I think [runAqaConfig.json](https://github.com/adoptium/aqa-tests/blob/master/.github/workflows/runAqaConfig.json) was originally created to track if the user can set a custom value or not. As a result, every new custom param needs to be added to the file. And we store the copy in all three repos (i.e, aqa-tests, TKG and openj9). This causes unnecessary updates and confusion.

Related issues and PRs:
https://github.com/adoptium/aqa-tests/issues/2697
https://github.com/adoptium/aqa-tests/pull/2733
https://github.com/eclipse-openj9/openj9/pull/13049
https://github.com/adoptium/TKG/pull/254/
https://github.com/adoptium/TKG/issues/219

We should allow all custom repos to be set by the users. In runAqaArgParse.py, if users set custom values, then use them. Otherwise, use the default values. runAqaConfig.json should be removed from all three repos.

https://github.com/adoptium/TKG/blob/c92a1022f774e64b9aa28943ffafbc196d06b161/scripts/testBot/runAqaArgParse.py#L60

**Comment by nadeensami** [comment]
Can I have this assigned to me?
