### ISSUE TITLE
systemtest.getDependency is broken

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3175]
https://ci.adoptopenjdk.net/job/systemtest.getDependency/ has been broken for a while

```
Cloning into 'STF'...
[Pipeline] sh
+ ant -f ./openjdk-systemtest/openjdk.build/build.xml -Djava.home=/home/jenkins/workspace/systemtest.getDependency/j2sdk-image/jre -Dprereqs_root=/home/jenkins/workspace/systemtest.getDependency/systemtest_prereqs configure
Buildfile: ./openjdk-systemtest/openjdk.build/build.xml does not exist!
Build failed
```
The above is the most common error ([link to job](https://ci.adoptopenjdk.net/job/systemtest.getDependency/147/)), but I have seen other errors.

**Comment by sophia-guo** [comment]
Looks like all others are error:

```
+ ant -f ./openjdk-systemtest/openjdk.build/build.xml -Djava.home=/home/jenkins/workspace/systemtest.getDependency/j2sdk-image/jre -Dprereqs_root=/home/jenkins/workspace/systemtest.getDependency/systemtest_prereqs configure
Error: JAVA_HOME is not defined correctly.
  We cannot execute java
```

And running on docker machines.

**Comment by llxia** [comment]
`Buildfile: ./openjdk-systemtest/openjdk.build/build.xml does not exist!` is a common error on all Jenkins (including internal).
https://openj9-jenkins.osuosl.org/job/systemtest.getDependency/

**Comment by sophia-guo** [comment]
Ok, I didn't count the internal. Only checked https://ci.adoptopenjdk.net/job/systemtest.getDependency/.

**Comment by llxia** [comment]
I suspect the issue is due to system test repo rename.
