### ISSUE TITLE
Remove external/example-test and update relating documentation

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3181]
There is no reason to keep [example-test](https://github.com/adoptium/aqa-tests/tree/master/external/example-test) any more.  It is outdated (uses a static docker file rather than the auto-generated dockerfile) and is no longer useful as a copy/paste example to introduce new external tests.  

We should update our documentation, specifically this section: https://github.com/adoptium/aqa-tests/tree/master/external#how-to-add-new-tests and begin to using [external_custom](https://github.com/adoptium/aqa-tests/tree/master/external/external_custom) as a way to introduce new types of third-party applications.

**Comment by sophia-guo** [comment]
Closed as #3235 is merged.
