### ISSUE TITLE
Remove external/thorntail-mp-tck 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3182]
We have had the [thorntail_microprofile_tck disabled](https://github.com/adoptium/aqa-tests/blob/master/external/thorntail-mp-tck/playlist.xml#L31-L34) for a while now, and there is no intention of re-enabling it, since it announced its end-of-life (see https://github.com/adoptium/aqa-tests/issues/1855#issuecomment-707764068).  

We should fully remove the subfolder and test and any related documentation (search the repo and wikis for references to thorntail).

**Comment by sophia-guo** [comment]
<img width="1199" alt="Screen Shot 2021-12-14 at 2 53 23 PM" src="https://user-images.githubusercontent.com/18030625/146069845-086d048c-67af-4a5d-a66e-788877c90c22.png">

Probably take a look why we need to define the supported_tests twice, which can be done in a separate issue or pr.

**Comment by jnjerin** [comment]
@smlambert I'll take this up

**Comment by smlambert** [comment]
Thanks @jnjerin !
