### ISSUE TITLE
Clean the function parse_tag() in external/external.sh

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3186]
[External tests has been updated to run with docker images provided by adoptium](https://github.com/adoptium/aqa-tests/issues/3116), [function parse_tag() in external/external.sh](https://github.com/adoptium/aqa-tests/blob/master/external/external.sh#L120) should also been cleaned up.

**Comment by LizyBbethy** [comment]
hi @ShelleyLambert @sophia-guo  here are some changes for review
