### ISSUE TITLE
Assess the health of external test group

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3187]
For each of the tests listed in https://github.com/adoptium/aqa-tests/tree/master/external we should assess their current health and status for all versions and implementations.

- [Hotspot spreadsheet](https://docs.google.com/spreadsheets/d/1kcHs1f7H1bmlLvkRBZ0CMdTaGBa3DWEXP86bYRefxg8/edit?usp=sharing)
- [OpenJ9 spreadsheet](https://docs.google.com/spreadsheets/d/197JBPA9hyYDLwc7xNncUKoXiKj9B7BH2Itx8ktdYgE4/edit?usp=sharing)

**Comment by smlambert** [comment]
Based on the work done to date and the notes in the spreadsheet, here is a recent activity update:
- Wycheproof - a prereq for this test is bazel which is no longer being correctly added to the auto-generated Dockerfile ([dockerfile_functions.sh](https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L361-L388)  and likely [wycheproof/test.properties](https://github.com/adoptium/aqa-tests/blob/master/external/wycheproof/test.properties#L6) needs to be updated)
- Scala - a prereq is sbt and it is out of date and no longer correctly being added to the auto-generatated Dockerfile ([dockerfile_functions.sh](https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L256-L276) and [scala/test.properties](https://github.com/adoptium/aqa-tests/blob/master/external/scala/test.properties#L5) needs to be updated
- example-test is no longer needed and can be removed (see #3181) 
- thorntail-mp-tck is no longer needed and can be removed (see #3182)

**Comment by sophia-guo** [comment]
Scala: https://github.com/adoptium/aqa-tests/issues/3356

**Comment by sophia-guo** [comment]
Using the change https://github.com/adoptium/aqa-tests/compare/master...sophia-guo:health?expand=1 running target

- sanity.external: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/436/

- extended.external: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/437/

waiting for the result

**Comment by sophia-guo** [comment]
rerun:
8: sanity.external: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/438/

8: extended.external: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/439/

**Comment by sophia-guo** [comment]
11: sanity.external https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/440/console
openliberty_microprofile_tck failed. Issue raised https://github.com/adoptium/aqa-tests/issues/3380

```
13:15:04  16 errors
13:15:04  
13:15:04  FAILURE: Build failed with an exception.
13:15:04  
13:15:04  * What went wrong:
13:15:04  Execution failed for task ':com.ibm.ws.componenttest:compileJava'.
13:15:04  > Compilation failed; see the compiler error output for details.
13:15:04  
13:15:04  * Try:
13:15:04  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```

17: sanity.external https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/442/console

openliberty_microprofile_tck_0 failed. Issue raised https://github.com/adoptium/aqa-tests/issues/3381

```
20:00:41  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
20:00:57  java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
20:00:57  	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
20:00:57  	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
20:00:57  	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:107)
20:00:57  	at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:95)
20:00:57  	at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:39)
20:00:57  	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:210)
...
20:00:57  FAILURE: Build failed with an exception.
20:00:57  
20:00:57  * What went wrong:
20:00:57  Could not initialize class org.codehaus.groovy.reflection.ReflectionCache
20:00:57  
20:00:57  * Try:
20:00:57  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
20:00:57  
20:00:57  * Get more help at https://help.gradle.org/
20:00:57  
20:00:57  BUILD FAILED in 14s
20:00:57  
20:00:57  openliberty_microprofile_tck_0_FAILED
```

quarkus_quickstarts_test_0 failed. Issue raised https://github.com/adoptium/aqa-tests/issues/3382

```
20:00:35  /quarkus-quickstarts
20:00:35  Compile and run quarkus_quickstarts tests
20:00:35  Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8 -Djava.security.egd=file:/dev/./urandom
20:00:38  [[1;31mERROR[m] Error executing Maven.
20:00:38  [[1;31mERROR[m] java.lang.IllegalStateException: Unable to load cache item
20:00:38  [[1;31mERROR[m] Caused by: Unable to load cache item
20:00:38  [[1;31mERROR[m] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
20:00:38  Build quarkus_quickstarts completed
```

**Comment by sophia-guo** [comment]
Closed by wrong PR. Reopen

**Comment by sophia-guo** [comment]
extended.external, the console output is too big to load. The summary shows most tests failed. Suggest to run each failed application separately in grinder to see the detailed failure message. 

> jdk8: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/439/
  Stoped due to timeout. No summary. Same suggestion, run each application separately in grinder to see the status.

> jdk11: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/441/console

```
19:52:57  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
19:52:57  DISABLED test targets:
19:52:57  	quarkus_native_test_0
19:52:57  
19:52:57  PASSED test targets:
19:52:57  	jacoco_test_0
19:52:57  	quarkus_test_0
19:52:57  	lucene_solr_nightly_smoketest_0
19:52:57  
19:52:57  FAILED test targets:
19:52:57  	tomcat_test_0
19:52:57  	netty_test_0
19:52:57  	wycheproof_test_0
19:52:57  	scala_test_0
19:52:57  	camel_test_0
19:52:57  	kafka_test_0
19:52:57  	derby_test_junit_all_0
19:52:57  	jenkins_test_0
19:52:57  	external_custom_0
19:52:57  	spring_test_0
19:52:57  	wildfly_test_0
19:52:57  
19:52:57  TOTAL: 15   EXECUTED: 14   PASSED: 3   FAILED: 11   DISABLED: 1   SKIPPED: 0
```


> jdk17: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/444/console

```
19:50:07  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
19:50:07  DISABLED test targets:
19:50:07  	quarkus_native_test_0
19:50:07  
19:50:07  PASSED test targets:
19:50:07  	spring_test_0
19:50:07  
19:50:07  FAILED test targets:
19:50:07  	jacoco_test_0
19:50:07  	tomcat_test_0
19:50:07  	quarkus_test_0
19:50:07  	netty_test_0
19:50:07  	wycheproof_test_0
19:50:07  	elasticsearch_test_hotspot_0
19:50:07  	scala_test_0
19:50:07  	lucene_solr_nightly_smoketest_0
19:50:07  	camel_test_0
19:50:07  	kafka_test_0
19:50:07  	derby_test_junit_all_0
19:50:07  	jenkins_test_0
19:50:07  	wildfly_test_0
19:50:07  
19:50:07  TOTAL: 15   EXECUTED: 14   PASSED: 1   FAILED: 13   DISABLED: 1   SKIPPED: 0
19:50:07  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

**Comment by sophia-guo** [comment]
Tests have different behaviors with different jdk version.
passed with jdk11 and failed with jdk17.
jacoco_test : Grinder: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/449/
quarkus_test: Grinder https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/451
lucene_solr_nightly_smoketest:  Grinder https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/450/

Failed with jdk11 and passed with jdk17:
spring_test: Grinder https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/452

**Comment by sophia-guo** [comment]
Jdk11:
tomcat_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/459/
netty_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/460/
wycheproof_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/461/
scala_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/462/
camel_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/463/
kafka_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/464/
derby_test_junit_all_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/465/
jenkins_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/467/
wildfly_test_0 https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/468/

**Comment by sophia-guo** [comment]
Update health of sanity
[sanity.extended sheet](https://docs.google.com/spreadsheets/d/152xI0hk3qUpe4EdIFDXEvusHgVAdxEtz5nV3KYRFEac/edit?usp=sharing)

**Comment by sophia-guo** [comment]
[extended.external sheet](https://docs.google.com/spreadsheets/d/1ojQTYGtxwdNShKYxYZgZO4nmj3d-FBB4hjb-_LEmtz0/edit#gid=0)

**Comment by sophia-guo** [comment]
[extended.external sheet](https://docs.google.com/spreadsheets/d/1ojQTYGtxwdNShKYxYZgZO4nmj3d-FBB4hjb-_LEmtz0/edit#gid=0) updated. Close this one.
