### ISSUE TITLE
Assess the health of the perf test group

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3189]
- Look at weekly perf runs and check that all perf targets that are enabled are passing (on all versions/impls/platforms), if not then annotate the failing targets (first in this issue - then we can assess and if needed find existing issues or raise new ones as required.  
- Likely easiest to start by looking at the grid view of the latest weekly run to assess what is running and its status, example: [latest weekly hotspot run for jdk8](https://trss.adoptium.net/resultSummary?parentId=61b494c5a7df1a2924c74087) shows which sanity.perf and extended.perf runs are green (passing), yellow (some targets failing) or red (job completely failed to run)
- Tracking status through the shared spreadsheet at this [link](https://docs.google.com/spreadsheets/d/1jcRO5fsrqXOBT7DxqNhaCCZa9Emupg3rw-iIdbbNo3k/edit?usp=sharing)

**Comment by smlambert** [comment]
Activity update:
- many of the failures in the perf group are due to certain benchmarks in the renaissance suite that check whether the environment where they are running is sufficient.  These benchmarks use Apache Spark and this is related to the [Apache Spark configuration](https://books.japila.pl/apache-spark-internals/spark-properties/).  We currently are using the default values found in  spark-defaults.conf (the calculation that occurs is found in the [UnifiedMemoryManager.scala](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/memory/UnifiedMemoryManager.scala#L194-L208) file and can inform us on what we may need to change in our environment or configuration in order to be able to run the affected renaissance benchmarks on our machines at the project).  

FYI @sxa

**Comment by norbline** [comment]
As Mentioned by @smlambert  These two platforms below seem to be affected after [running tests](https://ci.adoptopenjdk.net/job/Grinder/2903/console) check on the failed Benchmarks.

**Affected Platforms**
- arm_linux
- x86-32_windows

**Failed Benchmarks**
- renaissance-als
- renaissance-chi-square
- renaissance-dec-tree
- renaissance-gauss-mix	
- renaissance-log-regression 	
- renaissance-movie-lens
`17:36:36  Exception occurred in org.renaissance.apache.spark.GaussMix@143529a: System memory 259522560 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.
17:36:36  java.lang.IllegalArgumentException: System memory 259522560 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.
17:36:36  	at org.apache.spark.memory.UnifiedMemoryManager$.getMaxMemory(UnifiedMemoryManager.scala:212)
17:36:36  	at org.apache.spark.memory.UnifiedMemoryManager$.apply(UnifiedMemoryManager.scala:194)
17:36:36  	at org.apache.spark.SparkEnv$.create(SparkEnv.scala:308)
17:36:36  	at org.apache.spark.SparkEnv$.createDriverEnv(SparkEnv.scala:165)
17:36:36  	at org.apache.spark.SparkContext.createSparkEnv(SparkContext.scala:259)
17:36:36  	at org.apache.spark.SparkContext.<init>(SparkContext.scala:423)
17:36:36  	at org.renaissance.apache.spark.GaussMix.setUpSpark(GaussMix.scala:68)
17:36:36  	at org.renaissance.apache.spark.GaussMix.setUpBeforeAll(GaussMix.scala:57)
17:36:36  	at org.renaissance.RenaissanceBenchmark.runBenchmark(RenaissanceBenchmark.java:74)
17:36:36  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2(renaissance-suite.scala:308)
17:36:36  	at org.renaissance.RenaissanceSuite$.$anonfun$main$2$adapted(renaissance-suite.scala:306)
17:36:36  	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
17:36:36  	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
17:36:36  	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
17:36:36  	at org.renaissance.RenaissanceSuite$.main(renaissance-suite.scala:306)
17:36:36  	at org.renaissance.RenaissanceSuite.main(renaissance-suite.scala)
17:36:36  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
17:36:36  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
17:36:36  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
17:36:36  	at java.lang.reflect.Method.invoke(Method.java:498)
17:36:36  	at org.renaissance.Launcher.main(Launcher.java:18)
17:36:36  The following benchmarks failed: gauss-mix`

**Comment by smlambert** [comment]
As mentioned in all-hands call, @norbline will create a PR to exclude these 6 benchmarks from those 2 platforms for now (by disabling each of the 6 tests in the playlist, for reference: https://github.com/adoptium/aqa-tests/blob/master/doc/userGuide.md#exclude-a-test-against-specific-platform).

**Comment by smlambert** [comment]
We have done all that we will do at this time, closing issue now.
