### ISSUE TITLE
Re-enable tests excluded by issue 248

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3214]
Re-enable tests excluded by [issue 248](https://github.com/adoptium/temurin-build/issues/248)

[ Issue 248](https://github.com/adoptium/temurin-build/issues/248) has been resolved, that is testImage is generated by jenkins build jobs. Also corresponding option -nativepath has also been added and updated gradually. Those tests should be re-enabled.

**Comment by sophia-guo** [comment]
Related with #2368

**Comment by llxia** [comment]
Detail Steps:
- do a search in https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes, and find all exclude that are related to `https://github.com/adoptium/temurin-build/issues/248` in the Problem List.

For example https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk18.txt#L51

```
java/lang/ClassLoader/nativeLibrary/NativeLibraryTest.java	https://github.com/adoptium/temurin-build/issues/248	generic-all
```
- To reenable, we just need to remove the entry.
- If have permission, please run Grinder to verify the result.

**Comment by sophia-guo** [comment]
Probably keep it as is for the retired openjdk. That is we will only re-enable for jdk11, jdk17+ ( native tests has been disabled for jdk8 ).

**Comment by tommytwm** [comment]
I can take jdk 11 :)

**Comment by yinggzz** [comment]
I can do jdk 17

**Comment by gervaisj** [comment]
I can do jdk 18
