### ISSUE TITLE
Create Rerun failed tests in Grinder link

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3219]
**Background**: 
We have  `Rerun in Grinder` link in Jenkins job. It captures all parameters and allows the users to rerun the job easily.

![image](https://user-images.githubusercontent.com/19273206/149536166-f31c3bec-da85-4844-b3d0-64456d73944e.png)

https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/

However, one common use case is that users need to rerun for failed test target(s). `TARGET` parameter captures the test target for the build. If the users need to run the specific failed target(s), they need to modify the `TARGET` value to the specific failed target(s). This takes time and is not very convenient for the users. I think we should further simplify the workflow for the users.

**Proposal**:
Create `Rerun failed tests in Grinder` link. Instead of generating the `Rerun in Grinder` link with `TARGET` matches with the test build, we should generate `TARGET` value for the failed test(s). 

**Details**:
After the test execution, we can get failed test target from one of two places (failed.mk or *.tap file). We can have a parser to get the failed test target name(s). Set the` TARGET` value in the `Rerun failed tests in Grinder` link. For simplification, we should use testlist regardless of the number of failed tests. For example:

```
TARGET=testList TESTLIST=jit_jitt,jit_recognizedMethod_1,abcTest_2
```

**Comment by aixtools** [comment]
YES! Wonderful!

The links are often hard to find - until you already know _exactly_ what to look for.

**Comment by YeeSkywalker** [comment]
Hi there, it would be greatly appreciated if you could assign this to me.

**Comment by gervaisj** [comment]
@YeeSkywalker To get started with the parsing, I think you can import this stuff in "JenkinsfileBase":

```groovy
import org.tap4j.consumer.TapConsumer
import org.tap4j.model.TestResult
import org.tap4j.model.TestSet
```

Then, from the docs, it seems something like this might work:

```groovy
echo "Finding tap files..."
def tapFiles = findFiles(glob: "**/*.tap")
for (def tapFile : tapFiles) {
	echo "${tapFile}"
	def content = readFile(file: "${tapFile}")
	TapConsumer tc = TapConsumerFactory.makeTap13Consumer()
	TestSet r = tc.load(content)
	TestResult tr = r.testResults[0]
}
```

But then I don't know what `TestResult` and `TestSet` actually contain, so this page might be helpful: http://tap4j.sourceforge.net/apidocs/org/tap4j/model/TestResult.html

**Comment by YeeSkywalker** [comment]
> @YeeSkywalker To get started with the parsing, I think you can import this stuff in "JenkinsfileBase":
> 
> ```groovy
> import org.tap4j.consumer.TapConsumer
> import org.tap4j.model.TestResult
> import org.tap4j.model.TestSet
> ```
> 
> Then, from the docs, it seems something like this might work:
> 
> ```groovy
> echo "Finding tap files..."
> def tapFiles = findFiles(glob: "**/*.tap")
> for (def tapFile : tapFiles) {
> 	echo "${tapFile}"
> 	def content = readFile(file: "${tapFile}")
> 	TapConsumer tc = TapConsumerFactory.makeTap13Consumer()
> 	TestSet r = tc.load(content)
> 	TestResult tr = r.testResults[0]
> }
> ```
> 
> But then I don't know what `TestResult` and `TestSet` actually contain, so this page might be helpful: http://tap4j.sourceforge.net/apidocs/org/tap4j/model/TestResult.html

Thanks @gervaisj ! It really helps a lot!
