### ISSUE TITLE
Test failures on openjdk8_hs_extended.openjdk solaris hotspot

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3242]
Failure link https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_solaris_testList_0/16/

`javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh.BadPluginConfigurationTest`
Error:
`jdk/jdk/test/javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh: syntax error at line 183: PLUGINDST_DIR=$' unexpected`
Trss link https://trss.adoptium.net/output/test?id=61e87a86a7df1a292402d899

`sun/net/www/protocol/https/HttpsURLConnection/ImpactOnSNI.java.ImpactOnSNI`
**EDIT**: Found an upstream issue for this test case https://bugs.openjdk.java.net/browse/JDK-8155049
Error:
```
[2022-01-19T18:58:19.678Z] java.lang.Exception: No expected Server Name Indication
[2022-01-19T18:58:19.678Z] 	at ImpactOnSNI.doServerSide(ImpactOnSNI.java:143)
[2022-01-19T18:58:19.678Z] 	at ImpactOnSNI.access$100(ImpactOnSNI.java:40)
[2022-01-19T18:58:19.678Z] 	at ImpactOnSNI$1.run(ImpactOnSNI.java:341)
[2022-01-19T18:58:19.678Z] 
[2022-01-19T18:58:19.678Z] JavaTest Message: Test threw exception: java.lang.Exception: No expected Server Name Indication
```
Trss link https://trss.adoptium.net/output/test?id=61e87a86a7df1a292402d872

`compiler/floatingpoint/8165673/TestFloatJNIArgs.sh.TestFloatJNIArgs`
`compiler/floatingpoint/8207838/TestFloatSyncJNIArgs.sh.TestFloatSyncJNIArgs`
Error:
`[2022-01-19T18:15:10.183Z] TEST RESULT: Failed. Execution failed: exit code 1`
Trss link https://trss.adoptium.net/output/test?id=61e87a86a7df1a292402d85a

`gc/concurrentMarkSweep/GuardShrinkWarning.java.GuardShrinkWarning`
**EDIT**: found an upstream issue https://bugs.openjdk.java.net/browse/JDK-8023356 for this test failure
Error:
```
[2022-01-19T18:19:50.233Z]  stdout: [#
[2022-01-19T18:19:50.233Z] # A fatal error has been detected by the Java Runtime Environment:
[2022-01-19T18:19:50.233Z] #
[2022-01-19T18:19:50.233Z] ];
[2022-01-19T18:19:50.233Z]  stderr: [openjdk version "1.8.0_322"
[2022-01-19T18:19:50.233Z] OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
[2022-01-19T18:19:50.233Z] OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
```
Trss link https://trss.adoptium.net/output/test?id=61e87a86a7df1a292402d85a

**Comment by Haroon-Khel** [comment]
Fails for sparc too

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_0/25/testReport/

**Comment by Haroon-Khel** [comment]
Rerunning xSolaris failures https://ci.adoptopenjdk.net/job/Grinder/3274/console

**Comment by smlambert** [comment]
Some of the failures in this list look like issues with running some of the tools and sh scripts on these platforms.  It may be useful to log onto the machines and try to run the scripts directly to see how they do.  We have had the situation before where openjdk tests that are shell scripts are not written with solaris in mind and do not run well.  If this is the case with some failures, we should report upstream (with suggested amendments if we have them) and exclude the tests against the upstream issues.


GuardShrinkWarning failure ... is it actually hiding a crash (fatal error)?  Will have to look at what this test is actually doing.

```
13:19:50  STDERR:
13:19:50   stdout: [#
13:19:50  # A fatal error has been detected by the Java Runtime Environment:
13:19:50  #
13:19:50  ];
13:19:50   stderr: [openjdk version "1.8.0_322"
13:19:50  OpenJDK Runtime Environment (Temurin)(build 1.8.0_322-b06)
13:19:50  OpenJDK 64-Bit Server VM (Temurin)(build 25.322-b06, mixed mode)
13:19:50  
13:19:50  ]
13:19:50   exitValue = 0
13:19:50  
13:19:50  java.lang.RuntimeException: 'error' found in stdout 
13:19:50  
13:19:50  	at com.oracle.java.testlibrary.OutputAnalyzer.shouldNotContain(OutputAnalyzer.java:176)
13:19:50  	at GuardShrinkWarning.main(GuardShrinkWarning.java:51)
13:19:50  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:19:50  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:19:50  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:19:50  	at java.lang.reflect.Method.invoke(Method.java:498)
13:19:50  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
13:19:50  	at java.lang.Thread.run(Thread.java:750)
```

**Comment by Haroon-Khel** [comment]
While testing javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh.BadPluginConfigurationTest on build-packet_esxi-solaris10u11-x64-1 in an ssh environment, it still fails with 

`jdk/jdk/test/javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh: syntax error at line 183: PLUGINDST_DIR=$ unexpected`

https://github.com/adoptium/jdk8u/blob/master/jdk/test/javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh#L183
The failed command is
`PLUGINDST_DIR=$(mktemp -d ${TMP}/iio_test.XXXXXXXX)`, where `${TMP}` is `/tmp`

This command runs fine outside of the test. When running this shell script test on its own (without jtreg), the output suggests that it does not hit the same error. So I am uncertain as to why it is only hitting this error when run in the test suite. The error suggests that everything between the `( )` is ignored

**Comment by jiekang** [comment]
@Haroon-Khel I would run the commands manually outside of the script in a ksh instance to confirm their correctness. Based on the error and my quick read of ksh syntax, I'd suspect the mktemp command is failing, but I don't have ideas on what might cause it to failure. Permissions of the user running jtreg? No space in /tmp?

**Comment by sxa** [comment]
(Apologies - I typed this immediately after our call earlier but apparently didn't hit the "comment" button)

This will be because the test is running under `sh` which does not support tthe `$()` syntax. I would normally suggest replacing it with backticks e.g.
```
PLUGINDST_DIR=`mktemp -d ${TMP}/iio_test.XXXXXXXX`
```
but that will probably fall foul of the linter, so perhaps we'd have to feed it to a different shell (I'll be honest I throught we resolved such problems before but perhaps not universally, or it got retracted)

**Comment by jiekang** [comment]
Can machines be setup with ksh? That's the intended shell for this script and would reduce occurrences of these issues.

**Comment by sxa** [comment]
> Can machines be setup with ksh? That's the intended shell for this script and would reduce occurrences of these issues.

They all have `ksh` and `bash` available and in general I would expect the scripts to be fine with either, but for some reason the automation is not feeding them to the correct shell. We may have lost some of the configuration that helped secondary plaltforms such as Solaris from executing properly in recent months (Seen elsewhere...) which has caused this.

@Haroon-Khel Did you manage to retry the failure you saw running over an ssh connection using `ksh`? as per @jiekang's suggestion?

**Comment by Haroon-Khel** [comment]
`Bash` and `ksh` are able to run the falling command successfully, that is to create the temp directory. I've just now found that running the script with `sh` causes the failure

```
-bash-3.2$ sh jdk8u/jdk/test/javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh   
JDK under test is: /export/home/jenkins/test_dir/jdk8u322-b06/
cp: cannot access /*.class
cp: cannot access /*.java

------ PREPARE TEST PLUGIN ---------
jdk8u/jdk/test/javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh: syntax error at line 183: `PLUGINDST_DIR=$' unexpected
```
(Ignore the cp errors since I'm running this script outside of a test suite)

So I guess the jtreg runs the script with `sh`? An exception should be made for Solaris

**Comment by Haroon-Khel** [comment]
In the jtreg test report, it suggests the shell used is user specificed
```
run=USER_SPECIFIED compile IIOPluginTest.java\nUSER_SPECIFIED compile DummyReaderPluginSpi.java\nUSER_SPECIFIED shell  BadPluginConfigurationTest.sh\n
```

**Comment by sxa** [comment]
The question is therefore where do we specify it? :-)

**Comment by Haroon-Khel** [comment]
Same error. I used both `bash` and `ksh`

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3242#issuecomment-1025686169 - the default shell for jenkins user profile on that system (guessing this does not currently get explicitly set via ansible when a machine is initially set up?).

**Comment by sxa** [comment]
> re: [#3242 (comment)](https://github.com/adoptium/aqa-tests/issues/3242#issuecomment-1025686169) - the default shell for jenkins user profile on that system (guessing this does not currently get explicitly set via ansible when a machine is initially set up?).

Looks like [we do fix it to `bash`](https://github.com/adoptium/infrastructure/blob/4e72854b2635357d923daf59636c74218d52a48f/ansible/playbooks/AdoptOpenJDK_Unix_Playbook/roles/Jenkins_User/tasks/main.yml#L25). I thought we left it as the OS default :-) 

> From the jtreg report, it still uses sh to execute the script

OK that really needs to be fixed then. I thought we'd resolved all of those in the past.

**Comment by jiekang** [comment]
The jtreg shell action looks to execute with 'sh': https://github.com/openjdk/jtreg/blob/17bbd21a805ff0ee3a7b197613a899bd9b4b45c5/src/share/classes/com/sun/javatest/regtest/exec/ShellAction.java#L273

But I doubt this the only test that mentions being written for 'ksh'. I'm hoping there's more to it, or maybe I'm looking at the wrong place. I imagine we can modify it to run with a different shell, but would have to ask more experienced jtreg users. We're not the only ones running these jtreg tests right?

**Comment by sxa** [comment]
For the purposes of this release have we verified that all the failing tests on Solaris X64 and SPARC pass when run through an alternate shell?

**Comment by Haroon-Khel** [comment]
I have been running the remaining failing tests on x64 solaris in both `bash` and `ksh` shell environment. They still fail since jtreg insists on running the tests using `sh`
I'll run them on a sparc solaris machine right now

**Comment by Haroon-Khel** [comment]
While running the test javax/imageio/spi/AppletContextTest/BadPluginConfigurationTest.sh.BadPluginConfigurationTest in a `bash` environment (still on x64), Is get this stack trace

```
Sm is java.lang.SecurityManager@7852e922
java.util.ServiceConfigurationError: javax.imageio.spi.ImageReaderSpi: Provider BadReaderPluginSpi not found
        at java.util.ServiceLoader.fail(ServiceLoader.java:239)
        at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
        at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
        at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
        at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
        at java.security.AccessController.doPrivileged(Native Method)
```
But I do not think this is a failure/error since the test still passes

```
image/gif 
image/test_5076692 
The test passed!!!

Removing PLUGINDST_DIR /tmp/iio_test.XX7LaGcc

```

**Comment by Haroon-Khel** [comment]
Re compiler/floatingpoint/8207838/TestFloatSyncJNIArgs.sh.TestFloatSyncJNIArgs

https://github.com/AdoptOpenJDK/openjdk-jdk8u/blob/2544d2a351eca1a3d62276f969dd2d95e4a4d2b6/hotspot/test/compiler/floatingpoint/8207838/TestFloatSyncJNIArgs.sh#L44 suggests that this test is only to be run on linux aarch64

Either way, the test returns
`"Test passed; only valid for linux-aarch64"`

**Comment by Haroon-Khel** [comment]
Test compiler/floatingpoint/8165673/TestFloatJNIArgs.sh.TestFloatJNIArgs (x64 solaris) passes too

```
VM_OS=solaris
VM_CPU=amd64
Test passed; only valid for linux-aarch64
```

**Comment by Haroon-Khel** [comment]
I got the same exact result for sparcv9.

@sxa I don't think any of the tests in this issue are now blocking solaris, both x64 and sparc

**Comment by sophia-guo** [comment]
Based on the test @Haroon-Khel tried looks like those three tests https://github.com/adoptium/aqa-tests/issues/3242#issuecomment-1026118025 passed when running without jtreg and failed running with jtreg, which meant running by jtreg VM_OS and VM_CPU can not be detected correctly. Could we open an issue in upstream?
