### ISSUE TITLE
Extended openjdk jdk_jfr tests failed for sparc solaris jdk8 hotspot

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3254]
Some tests failed on sparc solaris from the extended openjdk suite for JDK 8 hotspot

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/23/testReport/

jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventDefNewSerial.java.TestHeapSummaryEventDefNewSerial
jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventG1.java.TestHeapSummaryEventG1
jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventPSParOld.java.TestHeapSummaryEventPSParOld
jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventPSSerial.java.TestHeapSummaryEventPSSerial
jdk/jfr/event/gc/heapsummary/TestHeapSummaryEventParNewCMS.java.TestHeapSummaryEventParNewCMS
jdk/jfr/event/io/TestInstrumentation.java.TestInstrumentation
Error log
```
java.lang.RuntimeException: Value not atLeast0, field='start', value='-3217031168': expected -3217031168 >= 0
	at jdk.test.lib.Asserts.fail(Asserts.java:594)
	at jdk.test.lib.Asserts.assertGreaterThanOrEqual(Asserts.java:288)
```

jdk/jfr/event/runtime/TestNetworkUtilizationEvent.java.TestNetworkUtilizationEvent
jdk/jfr/javaagent/TestPremainAgent.java.TestPremainAgent
jdk/jfr/jvm/TestDumpOnCrash.java.TestDumpOnCrash
jdk/jfr/api/flightrecorder/TestGetEventTypes.java.TestGetEventTypes
Error log
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0xffffffff7d768d04, pid=5108, tid=0x0000000000000011
#
# JRE version: OpenJDK Runtime Environment (8.0_322-b06) (build 1.8.0_322-b06)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06 mixed mode solaris-sparc compressed oops)
# Problematic frame:
# V  [libjvm.so+0x768d04]  void JfrNetworkInterfaceName::serialize(JfrCheckpointWriter&)+0xf4
```

**Comment by smlambert** [comment]
I will close this issue in favour of https://github.com/adoptium/aqa-tests/issues/4150
