### ISSUE TITLE
Archive the metadata file for AQAvit certification use case

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3264]
In https://github.com/adoptium/TKG/issues/260, we will generate a metadata file for AQAvit certification use case. In this issue, we need to update the Jenkins pipeline to archive this file. Similar to archiveTestenvFile() in JenkinsfileBase:

https://github.com/adoptium/aqa-tests/blob/1ee46d349543e08b42714b40ab89107c7b9eb4dd/buildenv/jenkins/JenkinsfileBase#L884

**Comment by yinggzz** [comment]
I'd like to take this one

**Comment by smlambert** [comment]
You do not have to wait, if you have PRs in the queue waiting for review, you most certainly can be working on a next issue.  :) thanks @yinggzz !
