### ISSUE TITLE
Set failIfNoResultsValue to true for all types of test jobs

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3269]
We should set failIfNoResultsValue to true for all types of test jobs:

Remove the following logic:
https://github.com/adoptium/aqa-tests/blob/1ee46d349543e08b42714b40ab89107c7b9eb4dd/buildenv/jenkins/JenkinsfileBase#L681-L683

Test:
- set PARALLEL=None
- set PARALLEL=Dynamic and NUM_MACHINES=2

**Comment by amir-waheed** [comment]
I would like to work on this issue.

**Comment by llxia** [comment]
This issue is fixed via https://github.com/adoptium/aqa-tests/pull/3275
