### ISSUE TITLE
jdk_jfr tests fail on jdk17 windows32

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3277]
jdk/jfr/event/compiler/TestCodeCacheFull.java.TestCodeCacheFull
jdk/jfr/event/compiler/TestCompilerInlining.java.TestCompilerInlining 
jdk/jfr/event/compiler/TestCompilerPhase.java.TestCompilerPhase https://github.com/adoptium/aqa-tests/issues/3045
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1/26/#showFailuresLink

jdk/jfr/event/compiler/TestCodeCacheFull.java.TestCodeCacheFull tests also failed on mac with different information https://github.com/adoptium/aqa-tests/issues/3042

```
[0.497s][warning][codecache] CodeHeap 'non-profiled nmethods' is full. Compiler has been disabled.
[0.497s][warning][codecache] Try increasing the code heap size using -XX:NonProfiledCodeHeapSize=
CodeHeap 'non-profiled nmethods': size=27328Kb used=1332Kb max_used=1332Kb free=25996Kb
 bounds [0x019e0000, 0x03490000, 0x03490000]
CodeHeap 'non-nmethods': size=5440Kb used=617Kb max_used=617Kb free=4822Kb
 bounds [0x01490000, 0x01530000, 0x019e0000]
 total_blobs=1266 nmethods=1062 adapters=133
 compilation: disabled (not enough contiguous free space left)
              stopped_count=1, restarted_count=0
 full_count=0
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x711ec9f9, pid=27176, tid=23580
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.2+8 (17.0.2+8) (build 17.0.2+8)
# Java VM: OpenJDK Server VM Temurin-17.0.2+8 (17.0.2+8, mixed mode, emulated-client, sharing, tiered, g1 gc, windows-x86)
# Problematic frame:
# V  [jvm.dll+0x27c9f9]
#
# Core dump will be written. Default location: C:\Users\jenkins\workspace\Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1\aqa-tests\TKG\output_16426787086111\jdk_jfr_2\work\scratch\hs_err_pid27176.mdmp
#
# JFR recording file will be written. Location: C:\Users\jenkins\workspace\Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1\aqa-tests\TKG\output_16426787086111\jdk_jfr_2\work\scratch\hs_err_pid27176.jfr
#
Unsupported internal testing APIs have been used.
```

jdk/jfr/event/compiler/TestCompilerInlining.java

```
java.lang.RuntimeException: not all events found at lavel 2. found = '[jdk.CompilerInlining {
  startTime = 13:42:59.683
  compileId = 1873
  caller = java.security.AccessController.executePrivileged(PrivilegedAction, AccessControlContext, Class)
  callee = {
    type = "java/security/PrivilegedAction"
    name = "run"
    descriptor = "()Ljava/lang/Object;"
  }
  succeeded = false
  message = "no static binding"
  bci = 29
  eventThread = "C1 CompilerThread0" (javaThreadId = 8)
}

```

**Comment by sophia-guo** [comment]
Failures are not machine related. 
https://ci.adoptopenjdk.net/job/Grinder/3315/
https://ci.adoptopenjdk.net/job/Grinder/3316/

Tests passed with earlier releases
https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.1%2B12/OpenJDK17U-jdk_x86-32_windows_hotspot_17.0.1_12.zip
https://ci.adoptopenjdk.net/job/Grinder/3310/
https://ci.adoptopenjdk.net/job/Grinder/3311/

Both test cases haven't been updated since last release.

**Comment by smlambert** [comment]
Running same test case (jdk/jfr/event/compiler/TestCompilerInlining) against azul win32 build https://cdn.azul.com/zulu/bin/zulu17.32.13-ca-jdk17.0.2-win_i686.zip in https://ci.adoptopenjdk.net/job/Grinder/3342/ indicates a passing run.  

Given this passed last release and therefore is a regression for this release, we will need to understand why this is now consistently failing.

**Comment by jiekang** [comment]
The hs_err for TestCodeCacheFull has:

```
---------------  T H R E A D  ---------------

Current thread (0x24ff4818):  JavaThread "MainThread" [_thread_in_vm, id=23580, stack(0x25f60000,0x25fb0000)]

Stack: [0x25f60000,0x25fb0000],  sp=0x25faf01c,  free space=316k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0x27c9f9]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  sun.hotspot.WhiteBox.allocateCodeBlob(II)J+0
j  sun.hotspot.WhiteBox.allocateCodeBlob(JI)J+36
j  jdk.jfr.event.compiler.TestCodeCacheFull.testWithBlobType(Lsun/hotspot/code/BlobType;J)V+27
j  jdk.jfr.event.compiler.TestCodeCacheFull.main([Ljava/lang/String;)V+31
v  ~StubRoutines::call_stub
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Ljava/lang/reflect/Method;Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+0 java.base@17.0.2
j  jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+133 java.base@17.0.2
j  jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+6 java.base@17.0.2
j  java.lang.reflect.Method.invoke(Ljava/lang/Object;[Ljava/lang/Object;)Ljava/lang/Object;+59 java.base@17.0.2
j  com.sun.javatest.regtest.agent.MainWrapper$MainThread.run()V+172
j  java.lang.Thread.run()V+11 java.base@17.0.2
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), reading address 0x0000007c
```

This is a failure in the WhiteBox, but may be caused by an issue in the VM.

For TestCompilerInlining, it is failing at level 2 of inlining:
```
****** Testing level 2 *******
WB error: invalid compilation level 2
```

This one is a bit strange in that the test checks what levels are available before trying them, so there's something strange with WhiteBox and/or the VM again. All the other JFR tests I've analyzed have been issues when running through WhiteBox code paths.

The stdout for the passing Grinder run for this test on the old release that Sophia linked (https://ci.adoptopenjdk.net/job/Grinder/3311/) suggests only level 1 is being tested, which is passing for both the old and new release. Same for the Azul grinder that Shelley linked (https://ci.adoptopenjdk.net/job/Grinder/3342/), there's only stdout for level 1.

So something is up with the new Temurin builds/configs around WhiteBox or VM flags for it to also be testing level 2, and failing.

**Comment by jiekang** [comment]
At this point I'd like to compare the configure output and build log output between a failed and successful release.

**Comment by sophia-guo** [comment]
same in jdk18 https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_1/31/#showFailuresLink

**Comment by sophia-guo** [comment]
Not in recent rerun https://github.com/adoptium/aqa-tests/issues/4352#issuecomment-1915239392, close it.
