### ISSUE TITLE
Archive Dockerfile generated during external test runs

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3289]
We auto-generate Dockerfiles as part of the external test runs.  We should archive the Dockerfile as an artifact to the Jenkins test job (during the [post stage](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L649) of the test pipeline).  This will help us debug issues as we encounter them.

**Comment by sophia-guo** [comment]
My Draft https://github.com/adoptium/aqa-tests/compare/master...sophia-guo:Docker?expand=1

Need more work

**Comment by yinggzz** [comment]
I can work on this issue!

**Comment by yinggzz** [comment]
Grinder tests ran for
jacoco: https://ci.adoptopenjdk.net/job/Grinder/3758/ 
derby: https://ci.adoptopenjdk.net/job/Grinder/3764/ 
jenkins: https://ci.adoptopenjdk.net/job/Grinder/3765/  

I've noticed the below is shown:
<img width="817" alt="001257 Archiving artifacts" src="https://user-images.githubusercontent.com/74112748/156462898-2d871be8-85c5-44bf-9ca3-387ce7ffffe3.png">

Should I change the path for dockerfile?

**Comment by smlambert** [comment]
This is how Dockerfiles are named and where they get put when they are generated: https://github.com/adoptium/aqa-tests/blob/master/external/build_image.sh#L83 so perhaps you need to try to change the regex that is used, so the search finds the generated file.

You can see in your console output where the Dockerfile gets put and its name, example from your jacoco grinder:
```
07:58:00       [exec] INFO: docker build  --no-cache -t adoptopenjdk-jacoco-test:8-jdk-ubuntu-hotspot-full -f /home/jenkins/workspace/Grinder/jvmtest/external/jacoco/dockerfile/8/jdk/ubuntu/Dockerfile.hotspot.full /home/jenkins/workspace/Grinder/jvmtest/external/
```
shows the full path to the file is: /home/jenkins/workspace/Grinder/jvmtest/external/jacoco/dockerfile/8/jdk/ubuntu/Dockerfile.hotspot.full

Is it a matter of changing https://github.com/yinggzz/aqa-tests/blob/issue3289/buildenv/jenkins/JenkinsfileBase#L726 from 
using: 
`"**/Dockerfile.*"` which will search in any directory
instead of 
`"./**/Dockerfile.*"` which uses a relative path
 
good to reference docs at: https://www.jenkins.io/doc/pipeline/steps/core/#archiveartifacts-archive-the-artifacts for examples of wildcards and try some things to see what can best address it.
