### ISSUE TITLE
Some external projects (wycheproof, scala) Dockefile can't be generated correctly.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3320]
Some external projects ( wycheproof) Dockefile can't be generated correctly, some contents are missing.

For example: wycheproof need bazel installed however there is no installation step when build the image by dockerfile.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Tether/73/console

Believe some information are missing in [set_test_info() ](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L195-L213)

A quick look shows that we need to add following test info, similar way as ant_version [ant_version=$(getProperty "ant_version")](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L205)

gradle_version
sbt_version
bazel_version
openssl_version

**Comment by smlambert** [comment]
yes, thanks for raising the issue, these were identified as part of https://github.com/adoptium/aqa-tests/issues/3187

also, we should close related / dup reports for those failing tests:
https://github.com/adoptium/aqa-tests/issues/1211
https://github.com/adoptium/aqa-tests/issues/1824
https://github.com/adoptium/aqa-tests/issues/3153

As a note, we should remind everyone to check for dups before raising new issues.

https://github.com/adoptium/aqa-tests/pull/3216 is for bazel update.

**Comment by LizyBbethy** [comment]
i am up for it
