### ISSUE TITLE
Enhance the archive***File() with filename parameter

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3325]
With the requirements expand we have three functions to archive files.
archiveSHAFile()
archiveTestenvFile()
archiveAQACertFile()

The only difference of those function is the specific file we need to archive, which can be done by adding one function parameter. Like:

archiveFile(fileName) {
}

This way to reduce the redundant and be easy to maintain and expand.

**Comment by Stergios13** [comment]
Hello. I can work on this if it is possible, please. Happy to help on this issue

**Comment by smlambert** [comment]
Definitely @Stergios13 - note that before we can merge any PR from you, you will need to create an Eclipse profile and sign the ECA (details [here](https://github.com/adoptium/documentation/blob/main/documentation-documentation/eca-sign-off.adoc)).

**Comment by Stergios13** [comment]
Sure i will. Can you please navigate me to the file or files containing those three functions? i have trouble finding them. Thank you for assigning me!

**Comment by smlambert** [comment]
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L688-L690
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L881-L912

**Comment by sophia-guo** [comment]
Can be closed by #3333 and #3394
