### ISSUE TITLE
Update Triage.md documentation 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3327]
As reported in https://github.com/adoptium/adoptium/issues/104#issuecomment-1016365317, the Triage documentation includes out of date information that should be removed.

https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md#trss-parser-for-release-builds section can be removed and replaced with the guidance to use the TRSS release summary report button on trss.adoptium.net as a way to summarize the health of a build/test pipeline.

**Comment by AyBims** [comment]
Hi, can I be assigned this issue

**Comment by bopesha** [comment]
Hi @smlambert ! May I be a second in the queue for this issue assignment, please?

**Comment by Nuel-Eneji** [comment]
hello @smlambert Good day! can i please be assigned this issue?

**Comment by Tishly** [comment]
Hi @smlambert, I would like to work on this issue. Could I get it assigned to me?

**Comment by vedant-z** [comment]
@smlambert May I take this issue? Please

**Comment by vedant-z** [comment]
Hey @smlambert, I need to remove the entire section named "[TRSS Parser for Release Builds](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md#trss-parser-for-release-builds)" and add some information on how to use "TRSS release summary report button on trss.adoptium.net" right?

I just want to know exactly how should I frame this information? Like is it acceptable "Get the entire summary for the health of a build/test pipeline by clicking on '[Test Results Summary Service](https://trss.adoptium.net/dashboard)' button on this [Webpage](trss.adoptium.net).

**Comment by smlambert** [comment]
Hi @vedant-z - yes, remove the entire section called TRSS Parser for Release Builds
in its place add a section something like this:

---

## Generate a Release Summary Report
Locate the pipeline you wish to triage in the ["By Pipeline" view](https://trss.adoptium.net/tests/Test) of TRSS.  
<img width="627" alt="gridLink" src="https://user-images.githubusercontent.com/2836948/216163492-254380dd-6c2d-4ce6-bf36-f8db2112d40f.png">

Navigate to the Grid view by clicking on the Grid link for the pipeline you wish to triage and click on the Release Summary Report button at the top of the Grid view page.

<img width="430" alt="releaseSummaryReport" src="https://user-images.githubusercontent.com/2836948/216163581-a1303c38-a736-46d4-91a4-1e696b91f8b8.png">

Click on the 'Copy` icon and paste the .md formatted content into a new Github issue that you wish to use to track triage investigation.

<img width="1376" alt="mdSummary" src="https://user-images.githubusercontent.com/2836948/216167236-7d59a42d-82c2-4fb6-855e-9a76d57697a6.png">
