### ISSUE TITLE
Remove target MachineInfo in external/external_custom

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3334]
Target MachineInfo is used a placeholder in case that there is no test case in jenkins test job and fails the job.  external/external_custom is a customized external test for developer, which wouldn't be part of nightly or release run. So no need to keep this target. 

Action: [remove MachineInfo in playlist.xml under external/external_custom](https://github.com/adoptium/aqa-tests/blob/master/external/external_custom/playlist.xml#L16-L28)

**Comment by LizyBbethy** [comment]
i am up for it

**Comment by smlambert** [comment]
@LizyBbethy - assigned to you now. 👍
