### ISSUE TITLE
Update the code for logic of USE_TESTENV_PROPERTIES

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3337]
Boolean parameter USE_TESTENV_PROPERTIES is used to decide use the environment variables defined in testenv.properties file or defined by user.

Currently the codes are scattered in different places, which make it hard to maintain and understand. 

https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L32-L45
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L401-L406
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L425-L429
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L419-L423
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L413-L417

All those can be moved to one place https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L32-L45

As function getGitRepoBranch() requires the defaultOwnerBranch, the second condition is unnecessary. 
For example  ` if(!params.USE_TESTENV_PROPERTIES && params.ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH)` the condition `params.ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH` can just be removed.

**Comment by LizyBbethy** [comment]
i am up for this one

**Comment by abhijeetjejurkar** [comment]
@sophia-guo I was unable to understand the Problem Correctly, Will you Please Help me
Do we need to Replace

-  [!params.USE_TESTENV_PROPERTIES && params.ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L418)
-  [!params.USE_TESTENV_PROPERTIES && params.OPENJ9_SYSTEMTEST_OWNER_BRANCH](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L424)
- [!params.USE_TESTENV_PROPERTIES && params.STF_OWNER_BRANCH](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L430) 

with `!params.USE_TESTENV_PROPERTIES` in code


I am new to groovy But I can try if this is only thing to do. Please Guide me.

**Comment by sophia-guo** [comment]
> @sophia-guo I was unable to understand the Problem Correctly, Will you Please Help me
Do we need to Replace

[!params.USE_TESTENV_PROPERTIES && params.ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L418)
[!params.USE_TESTENV_PROPERTIES && params.OPENJ9_SYSTEMTEST_OWNER_BRANCH](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L424)
[!params.USE_TESTENV_PROPERTIES && params.STF_OWNER_BRANCH](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L430)
with !params.USE_TESTENV_PROPERTIES in code

Yes, @abhijeetjejurkar  that is correct. And all three block can be combined to one !params.USE_TESTENV_PROPERTIES  block.

**Comment by julian55455** [comment]
Hi @smlambert would like to take this issue

**Comment by zdtsw** [comment]
@julian55455 has this issue been accomplished?

**Comment by julian55455** [comment]
@zdtsw do you mean this https://github.com/adoptium/aqa-tests/pull/4023

**Comment by zdtsw** [comment]
> @zdtsw do you mean this #4023?

if #4023 is enough to close this issue, we should mark it as done.

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/aqa-tests/pull/4023
