### ISSUE TITLE
Add JDK_VERSION and JDK_IMPL in AutoReenableJob

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3347]
Add JDK_VERSION and JDK_IMPL in AutoReenableJob https://ci.adoptopenjdk.net/view/Test_grinder/job/AutoReenableJob/
A user is able to run AutoReenableJob with specific JDK_VERSION and JDK_IMPL. Both JDK_VERSION and JDK_IMPL values can be comma-separated. The default value is 11 and hotspot respectively.

Once the user provides the values, the pipeline script should loop through output.json and only trigger the matched tests.

Related: https://github.com/adoptium/aqa-tests/issues/1853

**Comment by amir-waheed** [comment]
Can I have this issue assigned to me? Thank you!
