### ISSUE TITLE
Remove MachineInfo from external

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3355]
Due to historical reasons, we set MachineInfo as the special target in external tests. MachineInfo belongs to the sanity/extended/special level. However, In order for DYNAMIC_COMPILE to work in external tests, we need to remove MachineInfo from [external](https://github.com/adoptium/aqa-tests/blob/master/external). For example:

https://github.com/adoptium/aqa-tests/blob/master/external/camel/playlist.xml#L16-L28

FYI @renfeiw @LongyuZhang

**Comment by yinggzz** [comment]
I can take this issue 😄
