### ISSUE TITLE
Update static mermaid-based documentation diagrams with live mermaid code

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3360]
We were using mermaid for some of the diagrams in this repository.  Now that github supports mermaid format directly (see https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/), we can migrate our diagrams to use their live mermaid 'code' versus static captured images of the diagrams that we currently have in the docs/diagrams folder.

Example:

```
graph TD;

style elasticsearch fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style openliberty fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style derby fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style solr/lucene fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style specJBB2015 fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style libertyDayTrader fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5

aqa-tests--make _openjdk-->openjdk;

aqa-tests--make _system-->system;

aqa-tests==make _perf==>perf;
aqa-tests--make _functional-->functional;
aqa-tests--make _jck-->jck;
aqa-tests--make _external-->external;

perf==>idleMicroBenchmark;
perf==>libertyDayTrader;
perf==>specJBB2015;

external-->scala;
external-->tomcat;
external-->jenkins;
external-->example;
external-->openliberty;
external-->elasticsearch;
external-->derby;
external-->solr/lucene;
```

can become:

```mermaid
graph TD;

style elasticsearch fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style openliberty fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style derby fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style solr/lucene fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style specJBB2015 fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5
style libertyDayTrader fill:#eee,stroke:#cca,stroke-width:2px,stroke-dasharray: 5, 5

aqa-tests--make _openjdk-->openjdk;

aqa-tests--make _system-->system;

aqa-tests==make _perf==>perf;
aqa-tests--make _functional-->functional;
aqa-tests--make _jck-->jck;
aqa-tests--make _external-->external;

perf==>idleMicroBenchmark;
perf==>libertyDayTrader;
perf==>specJBB2015;

external-->scala;
external-->tomcat;
external-->jenkins;
external-->example;
external-->openliberty;
external-->elasticsearch;
external-->derby;
external-->solr/lucene;
```

**Comment by julian55455** [comment]
Hi @ShelleyLambert  I would like to work on this

**Comment by Emidowojo** [comment]
Hello @smlambert can I work on this?

**Comment by smlambert** [comment]
@julian55455 - since you have already done a couple of good first issues, I will direct you to take on a good second issue (I will send you a Slack msg with a suggestion).  Next in line for this issue will be @Emidowojo .

**Comment by Emidowojo** [comment]
Thank you @smlambert

**Comment by smlambert** [comment]
@Emidowojo - I should clarify what is needed to resolve this issue.

Ultimately we can delete the 3 .svg files that are referenced in this comment, and the document where they are referenced can be updated with the mermaid code that can replace them.

So updating https://github.com/adoptium/aqa-tests/blob/master/README.md on  
Line 26 - to replace ![overview of tests](doc/diagrams/overviewOfAdoptTests.svg)
Line 42 - to replace ![external tests](doc/diagrams/externaltests.svg)
Line 48 - to replace ![perf tests](doc/diagrams/perftests.svg)
with the mermaid code.

**Comment by Emidowojo** [comment]
@smlambert Alright then, I'd get to it. Thank you!

**Comment by Emidowojo** [comment]
I have now made the changes to the README.md file, please let me know if there's anything else.
