### ISSUE TITLE
Querying for issues status reaches rate limit of GitHub APIs

### ISSUE THREAD

**Issue by gervaisj** [adoptium/aqa-tests#3378]
`issue_status.py` uses unauthenticated endpoints, which are limited to a small (~50) number of API calls. This won't do for https://github.com/adoptium/aqa-tests/issues/1853.

- Improve querying efficiency by grouping issues
- Use a Git Token, provided in the pipeline, to raise rate limit.
- Ignore issue [1297 ](https://github.com/adoptium/aqa-tests/issues/1297) (permanently disabled tests)

**Comment by gervaisj** [comment]
@llxia @smlambert Working on this, I discovered some corner cases that I'd like to run by you.

I'll still open a PR with the implementation I have, which simply logs an error for each of the cases I list below. We can always open separate issues to improve the script later.

1. These two files have an odd "double-issue" format. I _could_ handle comma-separated issues, but maybe it would be cleaner to create a "parent issue" for both of them in GitHub to track the overall status. https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk8.txt#L425
https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk8-openj9.txt#L350
2. https://bugs.openjdk.java.net/browse/JDK-8031145 is found in a few different places for JDK8 and it seems it's only accessible with a login (so my queries fail)
3. This issue doesn't seem to exist:
https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk11.txt#L137
4. Numbers I don't know how to handle:
https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk9-openj9.txt#L315
https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk9.txt#L47-L69
5. I am not sure there's an API for this IBM-specific endpoint. I guess it doesn't matter much since this is for JDK12. https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk12-openj9.txt#L35

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3378#issuecomment-1060035349

1) 100% agree, a single issue should be used (2355 is the correct one, 2350 references a different test case class, not sure why its present on that line).  I was not aware we had 2 listed in a problem list.
2) if some JBS defects are not accessible, we will skip doing any action upon them, they are classified as special and we will need to manually deal with them (someone with an elevated account to look at them to determine status).  It will be useful to report that they are inaccessible, so we can give someone a list to check.
3) I hit a login for JDK-82472 (just like the one mentioned in 2)
4) We used to not enforce putting a full link, https://github.com/adoptium/aqa-tests/issues/206 is the issue (now closed)
5) If we can not access it, we treat it like 2) reported upon so it can be checked/addressed manually but no action can be taken.

**Comment by llxia** [comment]
The issue opened for case 1 https://github.com/adoptium/aqa-tests/issues/3426
