### ISSUE TITLE
KEEP_REPORTDIR should be boolean

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3384]
KEEP_REPORTDIR is boolean https://github.com/adoptium/aqa-tests/blob/098041520884daafaa3d0b7c30eab6ab93800f41/buildenv/jenkins/JenkinsfileBase#L66

However, we set it as String in testJobTemplate. 
https://github.com/adoptium/aqa-tests/blob/8a55c344d1b9847d4d083aaae4e903a675b659b5/buildenv/jenkins/testJobTemplate#L40
https://github.com/adoptium/aqa-tests/blob/8a55c344d1b9847d4d083aaae4e903a675b659b5/buildenv/jenkins/testJobTemplate#L417

ToDo:
- Verify if we can use KEEP_REPORTDIR as a boolean in Grinder
   -> run a passed test (i.e., jdk_math) with KEEP_REPORTDIR as boolean (true and false) and check if junit result file shows up accordingly 
- if so, update testJobTemplate to use boolean

**Comment by amir-waheed** [comment]
I would like to work on this issue :)

**Comment by amir-waheed** [comment]
I am not able to configure Grinder to be able to set KEEP_REPORTDIR as boolean (I don't think I have premisses to). Perhaps, I didn't understand the task? I am not sure how I am supposed to change KEEP_REPORTDIR to boolean in Grinder.

**Comment by smlambert** [comment]
I've created [Grinder_New](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_New/build?delay=0sec) which you can use for step 1 of the ToDo list. 

If the changes are made as @llxia suggested to testJobTemplate, when we regenerate the test jobs, it will be changed to a boolean type.  Reviewers of your PR will run the Test_Job_Auto_Gen job to verify that the change will do as we hope.

**Comment by amir-waheed** [comment]
@smlambert Thank you for the help! Also, it seems I am missing the Job/Build permission.

**Comment by smlambert** [comment]
Should now have permission, thanks for heads-up!
