### ISSUE TITLE
add timestamp{} in test pipeline

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3396]
We have `timestamp{}` in various stages. For example:
https://github.com/adoptium/aqa-tests/blob/25c804602873d503ec596371875c33a49fa88ad2/buildenv/jenkins/JenkinsfileBase#L513
https://github.com/adoptium/aqa-tests/blob/25c804602873d503ec596371875c33a49fa88ad2/buildenv/jenkins/JenkinsfileBase#L583

However,  we do not have `timestamp` in other sections (i.e., Queue, git clone, parallel runs, etc)

It would be nice to display timestamp for the whole pipeline. For example, in multiple node cases, it will help to understand how long we waited (see in In https://github.com/adoptium/aqa-tests/issues/2841).

TODO:
- [ ] add `timestamp{}` to provide more info https://github.com/adoptium/aqa-tests/blob/25c804602873d503ec596371875c33a49fa88ad2/buildenv/jenkins/openjdk_tests#L100-L236
- [ ] if we can have `timestamp{}` that covers all the sections, we can remove individual timestamp{} in each stage. 
- [ ] if the above does not work, then just add timestamp within Queue stage https://github.com/adoptium/aqa-tests/blob/25c804602873d503ec596371875c33a49fa88ad2/buildenv/jenkins/openjdk_tests#L169

**Comment by llxia** [comment]
FYI @YeeSkywalker

**Comment by YeeSkywalker** [comment]
Hi there, I am wondering if I could take this one? It would be much appreciated!

**Comment by llxia** [comment]
@momanm can you take a look at this issue? Thanks
