### ISSUE TITLE
Remove rerun.sh

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3397]
As we have the solution for [reproducible tests](https://github.com/adoptium/aqa-tests/issues/2347), we can remove https://github.com/adoptium/aqa-tests/blob/master/rerun.sh from the repo.

**Comment by abhijeetjejurkar** [comment]
Hey, can I take up this issue?

**Comment by smlambert** [comment]
Please do @abhijeetjejurkar !

**Comment by jhanvi831** [comment]
Hi @llxia I am Jhanvi, a contributor to OpenForce 2022. Is this issue still open to work with ?

**Comment by abhijeetjejurkar** [comment]
Hi @jhanvi831 I have already worked on issue and made a PR. Waiting for second Review to close the issue.

**Comment by jhanvi831** [comment]
@abhijeetjejurkar Okay, Thank you for letting me know.

**Comment by abhijeetjejurkar** [comment]
@jhanvi831 welcome!
