### ISSUE TITLE
set_test_info() doesn't set home_path

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3408]
[set_test_info() ](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L194-L217) is used to set external third party application test properties set in test.properties files (for example https://github.com/adoptium/aqa-tests/blob/master/external/camel/test.properties). `home_path` is set as the third party application home directory, which is supposed to be an environment variable in generated Dockerfile. It need to be set as `home_path=$(getProperty "home_path")` in https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L194-L217 to be consumed by each application's shell script.

**Comment by abhijeetjejurkar** [comment]
Hey, can I take up this issue?

**Comment by smlambert** [comment]
Hi @abhijeetjejurkar - I have assigned you https://github.com/adoptium/aqa-tests/issues/3397, once you have a PR ready for review, we can assign a next issue.

**Comment by abhijeetjejurkar** [comment]
Sure, Thankyou
will you please give me slack channel link to  connect with community.

**Comment by smlambert** [comment]
You can invite yourself to the Slack workspace at this page: https://adoptium.net/slack.html

Once you are in, the [#testing-aqavit](https://adoptium.slack.com/archives/C5219G28G) is a good one to ask questions regarding AQAvit issues.  Also useful to note, here is our [Contributing guide](https://github.com/adoptium/aqa-tests/blob/master/Contributing.md).

**Comment by abhijeetjejurkar** [comment]
thankyou
