### ISSUE TITLE
Simplify external test by rename all test script to test.sh

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3419]
Each third party application has a a shell script file defined the way to run tests in external test. ( for example: [camel-test.sh](https://github.com/adoptium/aqa-tests/blob/master/external/camel/dockerfile/camel-test.sh) ). The shell script file is called as the entrypoint in the generated Dockerfile.

To make it simple we'd like to rename all ${test}-test.sh to test.sh. Steps:
1. rename all ${test}-test.sh to test.sh.
2. remove property `script` in all test.properties files
3. update [function set_test_info()](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L195-L217) no need to set `script`. same for  [function set_external_custom_test_info()](https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L182-L192)
4. update [print_entrypoint() function](https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L475-L485), parameter ${script} is not needed anymore. The way the function is called is also need to update. Same for [print_test_script()](https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L417-L432)
5. some other minor cleanup.

**Comment by abhijeetjejurkar** [comment]
Hi, I am Abhijeet Jejurkar, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you

**Comment by abhijeetjejurkar** [comment]
Hi, I am Abhijeet Jejurkar, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!

**Comment by nik132-eng** [comment]
Hi, I am Nikunj Rohit, a contributor to OpenForce 2022. If this issue is still open I would like to work on this issue and try better to enhance it more. I would be making a PR as soon as I am done with resolving the issue. Thank you
@smlambert

**Comment by smlambert** [comment]
@nik132-eng - this issue is currently assigned and PR https://github.com/adoptium/aqa-tests/pull/3437 is under review.  If there are further enhancements to be made after the initial PR is merged, let's identify them so they can be addressed.

**Comment by nik132-eng** [comment]
ok ma'am @smlambert
