### ISSUE TITLE
LdapDnsProviderTest should associate with one issue

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3426]
In the problem list, one test should associate with one issue. Please updated LdapDnsProviderTest to associate with https://github.com/adoptium/aqa-tests/issues/2355 Only. We should remove https://github.com/adoptium/aqa-tests/issues/2350

https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk8.txt#L425

https://github.com/adoptium/aqa-tests/blob/57b6ea136264168339c54d4bbfdfff017986c1e8/openjdk/excludes/ProblemList_openjdk8-openj9.txt#L350

Related: https://github.com/adoptium/aqa-tests/issues/3378#issuecomment-1061270944

**Comment by abhijeetjejurkar** [comment]
Hi, I am Abhijeet Jejurkar, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you
