### ISSUE TITLE
Auto rerun failed tests in test pipeline

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3431]
We have added `Rerun in Grinder with failed test targets` link recently. We should try to auto-rerun failed tests in test pipeline.

Details:

- [x] add a flag RERUN_ITERATIONS - Number of times to repeat execution of failed test target(s). The default value is 0 (do not trigger rerun build)
- [x] if RERUN_ITERATIONS > 0 and failedTestList is not empty, generate xxx_rerun test job (i.e., Test_openjdk8_hs_sanity.openjdk_ppc64_aix_rerun) if it does not exist and rerun failed test target(s) based on RERUN_ITERATIONS.
Note: rerun job will be generated for parent test job level, not child job level (i.e., xxx_testList_xxx) 
- [x] https://github.com/adoptium/aqa-test-tools/issues/734 in TRSS

**Comment by llxia** [comment]
FYI @JasonFengJ9 @pshipton

**Comment by JasonFengJ9** [comment]
> if the flag is set to true and test build result is UNSTABLE, auto rerun failed tests 3 times using FAILED_TEST_TARGET via a special job (i.e., Grinder_Release)

Thanks @llxia 
Can the original failure be still included in TRSS? Just to avoid that the re-run marks an intermittent failure.
I think this feature will be very helpful for compliance or network sensitive tests though it is not required by other functionality tests, so ideally this feature option is configurable (to save some machine resources).

**Comment by smlambert** [comment]
In discussions on this feature, we most certainly would plan to keep original failure results in TRSS.  There are still lots of details to work out, but ultimately we intend to add a visual indicator that something had to be rerun (and the number of times to rerun and pass).  Perhaps something like this:

<img width="154" alt="Screen Shot 2022-03-09 at 7 45 35 PM" src="https://user-images.githubusercontent.com/2836948/157564912-83c0e19c-4c7e-4169-aaa9-f2880d42b0ed.png">

Which would then link to the list view which would list the history of the runs:
<img width="1079" alt="systemList" src="https://user-images.githubusercontent.com/2836948/157565467-3851a4e8-52d4-4b8d-8400-4a93a38e273e.png">

**Comment by llxia** [comment]
> ideally this feature option is configurable

Yes, this feature will be configurable at the test job level. For example, we can set AUTO_RERUN_FAILED_TESTS to true for extended.openjdk, but set it to false for sanity.functonal.

**Comment by llxia** [comment]
The main feature is delivered. Close this issue.
