### ISSUE TITLE
Simplify getBaseJDKImpl logic

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3438]
Simplify getBaseJDKImpl logic

from
https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/testJobTemplate#L21-L26

to

```
def getBaseJDKImpl(JDK_IMPL) {
	if (JDK_IMPL != "openj9" && JDK_IMPL != "ibm" ) {
		return "hotspot"
	}
	return JDK_IMPL
}
```

**Comment by SarveshLimaye** [comment]
@llxia  Hi, I am Sarvesh Limaye, a contributor to OpenForce 2022. I would like to work on this issue. I would be making a PR as soon as I am done with resolving the issue. Thank you!

**Comment by smlambert** [comment]
Please do @SarveshLimaye !
