### ISSUE TITLE
Cleanup external tests dockerfile directory

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3466]
Each external test has the dockerfile directory, which originally set as the location of docker related files( dockefile, shell script). For example https://github.com/adoptium/aqa-tests/tree/master/external/elasticsearch/dockerfile . External tests story has been updated to dynamically generate dockefile there is no need to keep the directory.

We'd like to remove the dockefile directory in external tests and move the shell script file to be the same level of all other files.

**Comment by sophia-guo** [comment]
[print_test_files()](https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L415-L434) will be affected. The line https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L423 and https://github.com/adoptium/aqa-tests/blob/master/external/dockerfile_functions.sh#L427 will need to update.

**Comment by abhijeetjejurkar** [comment]
Hey, Can I work on this?

**Comment by abhijeetjejurkar** [comment]
@sophia-guo Except test.sh Can we delete other related files in dockerfile directory (eg: dockerfile) or we have to move those to  external test directories

**Comment by smlambert** [comment]
For the subdirectories that still have static dockerfiles in that directory (system-test and functional-test), we have to check that they will work if we switch them over to use the autogenerated dockerfiles.  If they do, we can remove the static dockerfiles.  Handling these 2 cases can be done under a separate issue / PR.

**Comment by abhijeetjejurkar** [comment]
Thankyou @smlambert , So I will keep those 2 dockerfile directory(inside system-test and functional-test) as it is. And just move test.sh script in both subdirectories to external test directories

**Comment by smlambert** [comment]
Yes, thanks @abhijeetjejurkar

**Comment by abhijeetjejurkar** [comment]
> Yes, thanks @abhijeetjejurkar

Welcome😊
