### ISSUE TITLE
Support jdk-18+36 release: triage latest jdk18 build

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3486]
#### Release Summary Report for openjdk18-pipeline 
**Report generated at:** Wed, 23 Mar 2022 13:49:36 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=623a0f7b72761a4c5cf70265&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=623a0f7b72761a4c5cf70265) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/151/ 
Started by user Shelley Lambert at 3/22/2022, 2:02:56 PM 

 --- 

[**Test_Job_Auto_Gen**](https://ci.adoptopenjdk.net/job/Test_Job_Auto_Gen/327/) ❌ FAILURE ❌

[**create_installer_mac**](undefined) ❌ undefined ❌

[**create_installer_windows**](undefined) ❌ undefined ❌

[**jdk18u-aix-ppc64-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-aix-ppc64-temurin/5/) ❌ FAILURE ❌

[**jdk18u-linux-ppc64le-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-linux-ppc64le-temurin/5/) ❌ FAILURE ❌

[**jdk18u-linux-s390x-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-linux-s390x-temurin/5/) ❌ FAILURE ❌

[**jdk18u-mac-aarch64-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-mac-aarch64-temurin/5/) ❌ FAILURE ❌

[**jdk18u-mac-x64-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-mac-x64-temurin/5/) ❌ FAILURE ❌

[**jdk18u-windows-x64-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-windows-x64-temurin/5/) ❌ FAILURE ❌

[**jdk18u-windows-x86-32-temurin**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-windows-x86-32-temurin/5/) ❌ FAILURE ❌

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

 --- 

[**Test_openjdk18_hs_extended.openjdk_aarch64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_linux/27/) ⚠️ UNSTABLE ⚠️
jdk_net_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623aa15c72761a4c5cf7c4f8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623aa07672761a4c5cf7bf31&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_linux&testId=623aa15c72761a4c5cf7c4f8&testName=jdk_net_0) 
jdk_net_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623aa15c72761a4c5cf7c504) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623aa07672761a4c5cf7bf31&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_linux&testId=623aa15c72761a4c5cf7c504&testName=jdk_net_1) 
jdk_management_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623aa15c72761a4c5cf7c517) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623aa07672761a4c5cf7bf31&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_linux&testId=623aa15c72761a4c5cf7c517&testName=jdk_management_0) 
jdk_management_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623aa15c72761a4c5cf7c518) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623aa07672761a4c5cf7bf31&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_linux&testId=623aa15c72761a4c5cf7c518&testName=jdk_management_1) 
jdk_jfr_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623aa15c72761a4c5cf7c523) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623aa07672761a4c5cf7bf31&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_linux&testId=623aa15c72761a4c5cf7c523&testName=jdk_jfr_1) 

[**Test_openjdk18_hs_extended.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux/25/) ❌ ABORTED ❌

[**Test_openjdk18_hs_extended.openjdk_arm_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_0/23/) ❌ ABORTED ❌
jvm_compiler_2 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623ac04a72761a4c5cf81c4e) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623abf8c72761a4c5cf81b95&buildName=Test_openjdk18_hs_extended.openjdk_arm_linux_testList_0&testId=623ac04a72761a4c5cf81c4e&testName=jvm_compiler_2) 
jdk_security4_2 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623ac04a72761a4c5cf81c4b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623abf8c72761a4c5cf81b95&buildName=Test_openjdk18_hs_extended.openjdk_arm_linux_testList_0&testId=623ac04a72761a4c5cf81c4b&testName=jdk_security4_2) 
jdk_management_2 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623ac04a72761a4c5cf81c4d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623abf8c72761a4c5cf81b95&buildName=Test_openjdk18_hs_extended.openjdk_arm_linux_testList_0&testId=623ac04a72761a4c5cf81c4d&testName=jdk_management_2) 

[**Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1/23/) ⚠️ UNSTABLE ⚠️
jdk_net_2 => [deep history 1/3 passed](https://trss.adoptium.net/deepHistory?testId=623ac04072761a4c5cf81c24) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623abf8c72761a4c5cf81b93&buildName=Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1&testId=623ac04072761a4c5cf81c24&testName=jdk_net_2) 

[**Test_openjdk18_hs_extended.openjdk_ppc64le_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_ppc64le_linux/27/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_ppc64le_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_ppc64le_linux_testList_0/27/) ⚠️ UNSTABLE ⚠️
jdk_jfr_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a740572761a4c5cf761e6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a71f772761a4c5cf75446&buildName=Test_openjdk18_hs_extended.openjdk_ppc64le_linux_testList_0&testId=623a740572761a4c5cf761e6&testName=jdk_jfr_1) 

[**Test_openjdk18_hs_extended.openjdk_s390x_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_s390x_linux/26/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_0/25/) ⚠️ UNSTABLE ⚠️
jvm_compiler_1 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=623a657772761a4c5cf73dfe) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a647e72761a4c5cf73ba7&buildName=Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_0&testId=623a657772761a4c5cf73dfe&testName=jvm_compiler_1) 
jdk_jfr_1 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=623a657772761a4c5cf73e09) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a647e72761a4c5cf73ba7&buildName=Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_0&testId=623a657772761a4c5cf73e09&testName=jdk_jfr_1) 

[**Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_1/25/) ⚠️ UNSTABLE ⚠️
jvm_compiler_0 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=623a658672761a4c5cf73eb6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a647e72761a4c5cf73ba9&buildName=Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_1&testId=623a658672761a4c5cf73eb6&testName=jvm_compiler_0) 
jdk_jfr_0 => [deep history 0/3 passed](https://trss.adoptium.net/deepHistory?testId=623a658672761a4c5cf73ebc) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a647e72761a4c5cf73ba9&buildName=Test_openjdk18_hs_extended.openjdk_s390x_linux_testList_1&testId=623a658672761a4c5cf73ebc&testName=jdk_jfr_0) 

[**Test_openjdk18_hs_extended.openjdk_x86-32_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows/27/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0/27/) ⚠️ UNSTABLE ⚠️
jvm_compiler_2 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a783a72761a4c5cf771f9) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a776e72761a4c5cf76ef9&buildName=Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_0&testId=623a783a72761a4c5cf771f9&testName=jvm_compiler_2) 

[**Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_1/27/) ⚠️ UNSTABLE ⚠️
jdk_net_2 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a783272761a4c5cf771c7) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a776e72761a4c5cf76ef8&buildName=Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_1&testId=623a783272761a4c5cf771c7&testName=jdk_net_2) 

[**Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_2/27/) ⚠️ UNSTABLE ⚠️
jdk_nio_2 => [deep history 1/4 passed](https://trss.adoptium.net/deepHistory?testId=623a784272761a4c5cf7723c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a776e72761a4c5cf76efa&buildName=Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_2&testId=623a784272761a4c5cf7723c&testName=jdk_nio_2) 
jdk_time_2 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a784272761a4c5cf7724f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a776e72761a4c5cf76efa&buildName=Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_2&testId=623a784272761a4c5cf7724f&testName=jdk_time_2) 
jdk_tools_2 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a784272761a4c5cf7724b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a776e72761a4c5cf76efa&buildName=Test_openjdk18_hs_extended.openjdk_x86-32_windows_testList_2&testId=623a784272761a4c5cf7724b&testName=jdk_tools_2) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux/27/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_0/18/) ⚠️ UNSTABLE ⚠️
jdk_net_0 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=623a751f72761a4c5cf765cf) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a73c272761a4c5cf75bd3&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_0&testId=623a751f72761a4c5cf765cf&testName=jdk_net_0) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_1/18/) ⚠️ UNSTABLE ⚠️
jdk_net_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=623a752e72761a4c5cf76645) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a73c272761a4c5cf75bd6&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_1&testId=623a752e72761a4c5cf76645&testName=jdk_net_1) 
jdk_management_1 => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=623a752e72761a4c5cf76652) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a73c272761a4c5cf75bd6&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_alpine-linux_testList_1&testId=623a752e72761a4c5cf76652&testName=jdk_management_1) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux/22/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_0/20/) ⚠️ UNSTABLE ⚠️
jdk_net_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a750872761a4c5cf764cd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a735172761a4c5cf75ad6&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_0&testId=623a750872761a4c5cf764cd&testName=jdk_net_0) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_1/20/) ⚠️ UNSTABLE ⚠️
jdk_net_1 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a751772761a4c5cf76582) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a735172761a4c5cf75ad8&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_1&testId=623a751772761a4c5cf76582&testName=jdk_net_1) 
jdk_management_1 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a751772761a4c5cf7657b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a735172761a4c5cf75ad8&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_1&testId=623a751772761a4c5cf7657b&testName=jdk_management_1) 
jdk_imageio_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a751772761a4c5cf76587) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a735172761a4c5cf75ad8&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_1&testId=623a751772761a4c5cf76587&testName=jdk_imageio_0) 
jdk_imageio_1 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a751772761a4c5cf76583) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a735172761a4c5cf75ad8&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_1&testId=623a751772761a4c5cf76583&testName=jdk_imageio_1) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2/20/) ⚠️ UNSTABLE ⚠️
jdk_management_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a751072761a4c5cf7653d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a735172761a4c5cf75ad7&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2&testId=623a751072761a4c5cf7653d&testName=jdk_management_0) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac/26/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_0/26/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1/26/) ⚠️ UNSTABLE ⚠️
jdk_time_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a62db72761a4c5cf73584) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a61d272761a4c5cf73179&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1&testId=623a62db72761a4c5cf73584&testName=jdk_time_0) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_2/16/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows/27/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_0/27/) ⚠️ UNSTABLE ⚠️
jdk_net_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a91d072761a4c5cf7a2f3) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a910272761a4c5cf79eee&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_0&testId=623a91d072761a4c5cf7a2f3&testName=jdk_net_0) 
jdk_tools_0 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a91d072761a4c5cf7a2f8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a910272761a4c5cf79eee&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_0&testId=623a91d072761a4c5cf7a2f8&testName=jdk_tools_0) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1/27/) ⚠️ UNSTABLE ⚠️
jdk_net_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a91c872761a4c5cf7a2c8) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a910272761a4c5cf79eed&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1&testId=623a91c872761a4c5cf7a2c8&testName=jdk_net_1) 

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2/27/) ⚠️ UNSTABLE ⚠️
jdk_nio_0 => [deep history 3/4 passed](https://trss.adoptium.net/deepHistory?testId=623a91c072761a4c5cf7a270) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a910272761a4c5cf79eec&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2&testId=623a91c072761a4c5cf7a270&testName=jdk_nio_0) 
jdk_tools_1 => [deep history 0/4 passed](https://trss.adoptium.net/deepHistory?testId=623a91c072761a4c5cf7a292) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a910272761a4c5cf79eec&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2&testId=623a91c072761a4c5cf7a292&testName=jdk_tools_1) 

[**Test_openjdk18_hs_extended.perf_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.perf_x86-64_mac/26/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.system_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.system_x86-64_mac/83/) ❌ FAILURE ❌

[**Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux/84/) ⚠️ UNSTABLE ⚠️
cmdLineTester_libpathTestRtfChild_0 => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=623a73d972761a4c5cf75f9a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a717272761a4c5cf74e62&buildName=Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux&testId=623a73d972761a4c5cf75f9a&testName=cmdLineTester_libpathTestRtfChild_0) 

[**Test_openjdk18_hs_sanity.functional_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.functional_x86-64_mac/83/) ❌ FAILURE ❌

[**Test_openjdk18_hs_sanity.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_arm_linux/84/) ⚠️ UNSTABLE ⚠️
jdk_lang_2 => [deep history 7/13 passed](https://trss.adoptium.net/deepHistory?testId=623abf6b72761a4c5cf819ae) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623abe8172761a4c5cf81576&buildName=Test_openjdk18_hs_sanity.openjdk_arm_linux&testId=623abf6b72761a4c5cf819ae&testName=jdk_lang_2) 

[**Test_openjdk18_hs_sanity.openjdk_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_x86-64_alpine-linux/84/) ⚠️ UNSTABLE ⚠️
jdk_lang_0 => [deep history 0/8 passed](https://trss.adoptium.net/deepHistory?testId=623a73b172761a4c5cf75b5f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a717272761a4c5cf74e4d&buildName=Test_openjdk18_hs_sanity.openjdk_x86-64_alpine-linux&testId=623a73b172761a4c5cf75b5f&testName=jdk_lang_0) 
jdk_lang_1 => [deep history 0/8 passed](https://trss.adoptium.net/deepHistory?testId=623a73b172761a4c5cf75b61) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a717272761a4c5cf74e4d&buildName=Test_openjdk18_hs_sanity.openjdk_x86-64_alpine-linux&testId=623a73b172761a4c5cf75b61&testName=jdk_lang_1) 

[**Test_openjdk18_hs_sanity.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_x86-64_windows/85/) ⚠️ UNSTABLE ⚠️
jdk_lang_0 => [deep history 8/15 passed](https://trss.adoptium.net/deepHistory?testId=623a90c172761a4c5cf79a8a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a901272761a4c5cf798e2&buildName=Test_openjdk18_hs_sanity.openjdk_x86-64_windows&testId=623a90c172761a4c5cf79a8a&testName=jdk_lang_0) 
jdk_lang_1 => [deep history 8/15 passed](https://trss.adoptium.net/deepHistory?testId=623a90c172761a4c5cf79a8c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a901272761a4c5cf798e2&buildName=Test_openjdk18_hs_sanity.openjdk_x86-64_windows&testId=623a90c172761a4c5cf79a8c&testName=jdk_lang_1) 
jdk_util_0 => [deep history 8/15 passed](https://trss.adoptium.net/deepHistory?testId=623a90c172761a4c5cf79a94) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a901272761a4c5cf798e2&buildName=Test_openjdk18_hs_sanity.openjdk_x86-64_windows&testId=623a90c172761a4c5cf79a94&testName=jdk_util_0) 
jdk_util_1 => [deep history 8/15 passed](https://trss.adoptium.net/deepHistory?testId=623a90c172761a4c5cf79a95) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a901272761a4c5cf798e2&buildName=Test_openjdk18_hs_sanity.openjdk_x86-64_windows&testId=623a90c172761a4c5cf79a95&testName=jdk_util_1) 

[**Test_openjdk18_hs_special.functional_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_special.functional_x86-64_linux/22/) ⚠️ UNSTABLE ⚠️
MBCS_Tests_datetime_0 => [deep history 1/2 passed](https://trss.adoptium.net/deepHistory?testId=623a734a72761a4c5cf75a52) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=623a716072761a4c5cf74e3a&buildName=Test_openjdk18_hs_special.functional_x86-64_linux&testId=623a734a72761a4c5cf75a52&testName=MBCS_Tests_datetime_0) : intermittent, machine-related: https://github.com/adoptium/aqa-tests/issues/2774

**Comment by smlambert** [comment]
@Haroon-Khel @sophia-guo - thanks so much for your triage assessment leadership and please ensure to coordinate - https://github.com/adoptium/adoptium/issues/133

**Comment by sophia-guo** [comment]
Didn't realize the issue opened, close this one.
