### ISSUE TITLE
jdk18 [windows64]: test failed [Unexpected exit from test [exit code: 1] with `There is insufficient memory for the Java Runtime Environment to continue`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3488]
java/util/regex/NegativeArraySize.java

```
16:56:48  ACTION: testng -- Failed. Unexpected exit from test [exit code: 1]
16:56:48  REASON: User specified action: run testng/othervm -Xms5G -Xmx5G NegativeArraySize 
16:56:48  TIME:   0.078 seconds
16:56:48  messages:
16:56:48  command: testng -Xms5G -Xmx5G NegativeArraySize
16:56:48  reason: User specified action: run testng/othervm -Xms5G -Xmx5G NegativeArraySize 
16:56:48  Mode: othervm [/othervm specified]
16:56:48  elapsed time (seconds): 0.078
16:56:48  configuration:
16:56:48  STDOUT:
16:56:48  #
16:56:48  # There is insufficient memory for the Java Runtime Environment to continue.
16:56:48  # Native memory allocation (mmap) failed to map 5368709120 bytes for G1 virtual space
16:56:48  # An error report file with more information is saved as:
16:56:48  # E:\workspace\Test_openjdk18_hs_sanity.openjdk_x86-64_windows\aqa-tests\TKG\output_16479812973657\jdk_util_0\work\scratch\1\hs_err_pid17752.log
16:56:48  STDERR:
16:56:48  OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000006c0000000, 5368709120, 0) failed; error='The paging file is too small for this operation to complete' (DOS error/errno=1455)
```

https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_x86-64_windows/85/consoleFull

Tests has been updated to [@requires os.maxMemory >= 5g & vm.bits == 64](https://github.com/openjdk/jdk/commit/683e30db79789ee44b3cc0b44c085de4615bca7b) 

https://bugs.openjdk.java.net/browse/JDK-8273169

**Comment by sophia-guo** [comment]
Same error with java/nio/channels/FileChannel/LargeGatheringWrite.java.LargeGatheringWrite

https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2/27/

```
Stacktrace
Unexpected exit from test [exit code: 1]    
Standard Output
Seed from RandomFactory = 5106480740934277067L
Writing 5368709122 bytes of data...
Wrote 5368709122 bytes
Total of 5368709122 bytes written
Checking length 1073741824
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1308622848 bytes for G1 virtual space
# An error report file with more information is saved as:
# E:\workspace\Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_2\aqa-tests\TKG\output_16479892684575\jdk_nio_0\work\scratch\0\hs_err_pid29116.log
```

**Comment by jiekang** [comment]
The console log mentions

16:32:57  Total memory (bytes) : 134217728
16:32:57  Free memory (bytes) : 131147576

That's less than 1 gb?

**Comment by sophia-guo** [comment]
Passed on https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk18_hs_sanity.openjdk_x86-64_windows/86/.

The console log is misleading, which is actually the info of  java process org.openj9.envInfo.EnvDetector

**Comment by sophia-guo** [comment]
Issue opened https://github.com/adoptium/TKG/issues/302

**Comment by sophia-guo** [comment]
Reran https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3935/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/3936/console

Passed. And update the console output to printout proper information

**Comment by sophia-guo** [comment]
Close it as can not be reproduced. Guess the machine's in corner unhealthy status.
