### ISSUE TITLE
Check ProblemLists for incorrect platform entries

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3500]
During jdk18 triage, we have seen that there are incorrect entries in the [ProblemList](https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk18.txt) file (linux_s390x, linux_ppc64le, etc) so the test will still run, even though we thought it was excluded.

We should also add a readme or a comment at the top of problemlist files to remind people of what formats are accepted by the upstream tools.

Refs: 
https://github.com/adoptium/adoptium/issues/133#issuecomment-1076500605
https://github.com/adoptium/adoptium/issues/133#issuecomment-1076456053

**Comment by Haroon-Khel** [comment]
https://github.com/adoptium/aqa-tests/tree/master/openjdk#exclude-a-testcase for the proper annotation when excluding

**Comment by smlambert** [comment]
And noting that the problemlist parser (exclude_parser.py) that will run as part of the Auto reenablement pipeline will help this problem. 

https://github.com/adoptium/aqa-tests/blob/master/scripts/disabled_tests/exclude_parser.py#L189-L203
https://github.com/adoptium/aqa-tests/tree/master/scripts/disabled_tests#dry-run-to-see-errors-and-warnings

**Comment by Nuel-Eneji** [comment]
Hello @smlambert trust you're very well. 
Can i also take on this issue please.

**Comment by Adeosunomoshalewa** [comment]
I would like to work on this issue.

**Comment by Emidowojo** [comment]
Hi @smlambert Can I take this issue?

**Comment by smlambert** [comment]
I am assigning all 3 of you to this issue.

I think the starting point is to read the documentation at https://github.com/adoptium/aqa-tests/blob/master/scripts/disabled_tests/README.md and try running the disabled_tests scripts and sharing some of your output files (by attaching them as comments to this issue, with any notes you have regarding running the scripts or questions about the documentation).

**Comment by Emidowojo** [comment]
Hi @smlambert thank you

**Comment by Adeosunomoshalewa** [comment]
Thank you @smlambert

**Comment by Nuel-Eneji** [comment]
[

[errors.log](https://github.com/adoptium/aqa-tests/files/9916495/errors.log)



[problem_list.json.txt](https://github.com/adoptium/aqa-tests/files/9916502/problem_list.json.txt)

](url)

Greetings @smlambert Hope you're well?
These are my output files from runing the exclude_parser command in the disabled tests 
it seems one of the problem files in openjdk/excludes/vendors/azul/ is failing

From the docs, the first command below was  reading vendor directory so I used  the later command to run my exclude parser test
`ls -1dq openjdk/excludes/* |
python scripts/disabled_tests/exclude_parser.py > problem_list.json 2> errors.log`

` find openjdk/excludes/* -name "*.txt" | python3 scripts/disabled_tests/exclude_parser.py  > problem_list.json 2> errors.log
`

Please I'll like to know if I'm on the right track
Thanks

**Comment by Nuel-Eneji** [comment]
Hello @Emidowojo and @Adeosunomoshalewa 
Did you also notice a similar case with the `ls -1dq openjdk/excludes/* | python scripts/disabled_tests/exclude_parser.py > problem_list.json 2> errors.log` command ?

**Comment by Adeosunomoshalewa** [comment]
Hi @Nuel-Eneji , haven’t being able to get it from my end , it kept flagging syntax error

**Comment by Nuel-Eneji** [comment]
Maybe you should also try using this command `find openjdk/excludes/* -name "*.txt" | python3 scripts/disabled_tests/exclude_parser.py > problem_list.json 2> errors.log` @Adeosunomoshalewa

**Comment by Adeosunomoshalewa** [comment]
Okay i will do that , Thank you very much

**Comment by smlambert** [comment]
To your question @Nuel-Eneji re: https://github.com/adoptium/aqa-tests/issues/3500#issuecomment-1299597527

This is what we hoped to do.  Your findings have shown that there is an _error_ in the azul/ProblemList_openjdk8.txt file, and the script has found it:
https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/vendors/azul/ProblemList_openjdk8.txt#L74

There should be 3 items per line, the test case to exclude, a link to an issue describing the problem, and the platform on which to apply the exclusion.  We see on line 74 that only 1 of those three things are present.

**Comment by Nuel-Eneji** [comment]
Greetings @ slambert I've bben going over the code for some time now but I don't seem to know the how next to proceed 
please i need further guidiance 
Thanks

**Comment by smlambert** [comment]
The task here was to run the scripts and identify incorrect entries in our ProblemLists files.  You found one, so now we can raise an issue stating the problem and then a PR to fix it (if we know the appropriate way to do so).  

Raise an aqa-tests issue entitle "Incorrect formating in vendors/azul/ProblemList_openjdk8.txt file" and describe the issue in the description (you can take the text from my comment above https://github.com/adoptium/aqa-tests/issues/3500#issuecomment-1301367184).  We should then create a PR to fix that line in that file to have 3 sections to it, we need to determine what issue that testcase needs to be excluded under and on what platforms, perhaps defaulting to `generic-all`.

**Comment by Nuel-Eneji** [comment]
Thanks @smlambert 
I'll get on with it now

**Comment by Nuel-Eneji** [comment]
Hello, @smlambert I hope everything is good with you.
I did as advised and opened issue #4138.
I'm about to submit a pull request to address the problem.

**Comment by Adeosunomoshalewa** [comment]
Hi @smlambert , have been working with @Nuel-Eneji on this issue and the output I got from my end. 
[errors.log](https://github.com/adoptium/aqa-tests/files/9984491/errors.log)

**Comment by smlambert** [comment]
hi @Adeosunomoshalewa - your errors.log file shows that you do not have Python installed which is needed to run these scripts.

**Comment by Adeosunomoshalewa** [comment]
Hello @smlambert, after rerunning the text this is what I got 
[errors.log](https://github.com/adoptium/aqa-tests/files/9996102/errors.log)

**Comment by Adeosunomoshalewa** [comment]
hello @smlambert, I have rerun the text and have uploaded the file for you to view, kindly acknowledge

**Comment by smlambert** [comment]
hi @Adeosunomoshalewa - if you look inside the error.log you have produced, you now appear to have python installed, but there is an error.

You get a no such file or directory error.  You will have to figure out where the file actually is in order to get a proper result.  The error message is telling you that `C:\\Users\\USER\\OneDrive\\Documents\\GitHub\\Adeosunomoshalewa\\outreachy\\aqa-tests\\scripts\\disabled_tests\\scripts\\disabled_tests\\exclude_parser.py` does not exist.  Find where it actually is located in your environment so python3.exe can run it.

```
python3 : C:\Users\USER\AppData\Local\Microsoft\WindowsApps\python3.exe: can't open file C:\\Users\\USER\\OneDrive\\Documents\\GitHub\\Adeosunomoshalewa\\outreachy\\aqa-tests\\scripts\\disabled_tests\\scripts\\disabled_tests\\exclude_parser.py 

[Errno 2] No such file or directory
...
```

**Comment by Adeosunomoshalewa** [comment]
okay @smlambert , will look into it, Thank you

**Comment by smlambert** [comment]
Marked as complete (by finding and raising https://github.com/adoptium/aqa-tests/issues/4138).
