### ISSUE TITLE
Automation to grab all tap files and AQAcert.log file and push them to either releases repo or artifactory

### ISSUE THREAD

**Issue by JeromeJu** [adoptium/aqa-tests#3522]
Automation to grab all tap files and AQAcert.log file and push them to either releases repo or artifactory

1.  Creating a standalone groovy script that given the name/id of a pipeline job can fetch all the artifacts from all of the jobs in a pipeline from top-level parent all the way down and then zip those files up.  

    Required inputs:
    - JOB_NAME
    - JOB_ID
    - JOB_CREDENTIALS

  Cases:

-   1 parent (the top-level pipeline as a starting point, restricted access, if you try clicking on the example or querying it, you need proper credentials), example: [openjdk18-pipeline/153/](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/153/)

-   10 to 15 children (1 per platform), example: [jdk18u-linux-ppc64le-temurin/6/](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-linux-ppc64le-temurin/6/)

  each of the 10-15 nodes in level 2 has 9-12 children typically (top-level test jobs, open access, for initial testing you can start here), example: [Test_openjdk18_hs_extended.openjdk_ppc64le_linux/28/](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_ppc64le_linux/28/)

-   each of the 9-12 nodes of level 3 could have multiple child test jobs (when run with PARALLEL=Dynamic for example), example: [Test_openjdk18_hs_extended.openjdk_ppc64le_linux_testList_0/](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_ppc64le_linux_testList_0/)

2. Pushing that zip file to a 'final' destination point (github releases repo and/or artifactory are 2 probable locations we will need to support).

Reference: https://github.com/adoptium/aqa-tests/issues/3443

**Comment by JeromeJu** [comment]
Regarding Task 1:

**Comment by JeromeJu** [comment]
Hi @llxia , according to your pointers and https://github.com/adoptium/aqa-tests/pull/3536, I'd like to confirm for now, the tapfiles from child builds should be archived. But for the 1st part of this issue, I still need to fetch all artifacts other than the tap files?

**Comment by smlambert** [comment]
Believe this is partially completed - @llxia I think the push to artifactory is done, is that the case?  what remains is how to attach Grinder reruns.  For push to releases repo, we likely would do the work either in [ci-jenkins-pipeline](https://github.com/adoptium/ci-jenkins-pipelines) repo or [github-release-scripts](https://github.com/adoptium/github-release-scripts) repo.

**Comment by smlambert** [comment]
Going to close this one, as work was delivered via:
https://github.com/adoptium/ci-jenkins-pipelines/pull/330
https://github.com/adoptium/github-release-scripts/pull/110

We can create a new issue to incorporate the workflow of including Grinder runs.
