### ISSUE TITLE
Upgrade renaissance to 0.14.0 release

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3561]
Currently, the renaissance test is running with https://github.com/renaissance-benchmarks/renaissance/releases/tag/v0.9.0. We should upgrade to the[ latest version 0.14.0 release](https://github.com/renaissance-benchmarks/renaissance/releases/tag/v0.14.0).

https://github.com/adoptium/aqa-tests/blob/f9255ef564716df2be39e076d488739896a783c6/perf/renaissance/build.xml#L37

**Comment by smlambert** [comment]
I will close https://github.com/adoptium/aqa-tests/issues/3560 as dup (even though it was created a few minutes earlier, haha).
