### ISSUE TITLE
RedefineCrossEvent.java makes jdk_jfr failed on JDK8 Hotspot xLinux

### ISSUE THREAD

**Issue by ChangLu0607** [adoptium/aqa-tests#3573]
**Describe the bug**
RedefineCrossEvent.java failed because of class file not found

**To Reproduce**
make _jdk_jfr_0

**Expected behavior**
all test cases pass

**Screenshots**
![image](https://user-images.githubusercontent.com/38229679/163151788-fcff0a18-ebc6-4e7f-a26d-bb31b915d020.png)

**Additional context**
related issue in JDK11: https://bugs.openjdk.java.net/browse/JDK-8283479
patch: https://github.com/openjdk/jdk11u-dev/commit/426873751c710061d0f9bc713a0de47373e51418
the change for TestScaffold.java in this patch has been locally verified that solve this test case failure

**Comment by smlambert** [comment]
Thanks @ChangLu0607 - we can exclude this testcase at our layer.
