### ISSUE TITLE
https://adoptium.net/docs/aqavit-verification/ give a wrong link for "test prerequisites"

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3581]
**Describe the bug**
[A clear and concise description of what the bug is.](https://adoptium.net/docs/aqavit-verification/ give a wrong link about "test prerequisites")

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
1. open web by chrome : https://adoptium.net/docs/aqavit-verification/
2. click the link of "test prerequisites"
![image](https://user-images.githubusercontent.com/24123821/163779429-273470f5-5c11-4176-849b-13c3a62a63af.png)

**Expected behavior**
relink to the correct web for "test prerequisites"
https://github.com/adoptium/aqa-tests/blob/master/doc/Prerequisites.md

**Actualed behavior**
relink to wrong web for "test prerequisites"
https://adoptium.net/https://github.com/adoptium/aqa-tests/blob/master/doc/Prerequisites.md

**Screenshots**
![image](https://user-images.githubusercontent.com/24123821/163779604-0b36f4c2-9b6a-4841-9d96-52f259ea92e7.png)

**Additional context**
NA

**Comment by smlambert** [comment]
Fixed via https://github.com/adoptium/website-v2/pull/405
