### ISSUE TITLE
jck_custom target appears to be 'broken'

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3598]
At some point between January release to March release the ability to run jck_custom target appears to be broken.  Need to investigate what changes went into JavaTestRunner and related files that may have caused the breakage.

**Comment by smlambert** [comment]
Closing as likely user error (me) as 2 separate people reported no problem and we do not discuss specifics around this test material in the open.

**Comment by smlambert** [comment]
Hitting a case where this line is printed out, https://github.com/adoptium/aqa-tests/blob/master/jck/jtrunner/JavaTestRunner.java#L295, which means, we are not setting the default, https://github.com/adoptium/aqa-tests/blob/master/jck/jck.mk#L65 

See temurin-compliance/Grinder/1290 for TARGET and CUSTOM_TARGET values

**Comment by sophia-guo** [comment]
For test case jck-runtime-api-java_nio, configAltPath is explicitly set up [configAltPath=$(CONFIG_ALT_PATH)](https://github.com/adoptium/aqa-tests/blob/master/jck/runtime.api/playlist.xml#L630), which was not handled by jck_custom yet. There may be other testcases with specific parameteres to JCK_CMD_TEMPLATE, which might not be handled correctly by jck_custom.
