### ISSUE TITLE
_SecurityTests_0 fail

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3601]
**Describe the bug**
_SecurityTests_0 fail
The testcase file "functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java" test four website bellow:
            "https://www.cloudflare.com/",
            "https://www.google.com/",
            "https://services.gradle.org/",
            "https://repo1.maven.org/"
But www.google.com can't be reache normally in CHINA. Can we change the test website from "https://www.google.com/" to "https://www2.bing.com/"?

**To Reproduce _in CHINA_**
```bash
export TEST_JDK_HOME=~/software/jdk/jdk8u322-b06
export JAVA_HOME=$TEST_JDK_HOME
export PATH=$JAVA_HOME/bin:$PATH
export USE_TESTENV_PROPERTIES=true
export JDK_VERSION=8
export JDK_IMPL=hotspot
export BUILD_LIST=functional
./compile.sh
cd TKG/
make _SecurityTests_0
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24123821/164587880-b60a6947-e22f-4621-a23a-ed6dbd74f626.png)

**Additional context**

```patch
git diff functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java
diff --git a/functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java b/functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java
index b7e9f03..4e6a7dd 100644
--- a/functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java
+++ b/functional/security/src/net/adoptopenjdk/test/DefaultTlsFunctionalTest.java
@@ -43,7 +43,7 @@ public class DefaultTlsFunctionalTest {
 
     private final static String[] TLS_HOSTS = {
             "https://www.cloudflare.com/",
-            "https://www.google.com/",
+            "https://www2.bing.com/",
             "https://services.gradle.org/", // Ensure that Gradle can be downloaded.
             "https://repo1.maven.org/" // Ensure that Maven artifacts can be resolved.
     };
@@ -171,4 +171,4 @@ public class DefaultTlsFunctionalTest {
             return socket;
         }
     }
-}
\ No newline at end of file
+}
```

**Comment by llxia** [comment]
@sendaoYan do you mind creating a PR for this? Thanks
You will need to sign the ECA before submitting a PR (as per https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#eclipse-contributor-agreement - which has a link to [further documentation](https://github.com/adoptium/documentation/blob/main/documentation-documentation/eca-sign-off.adoc) if you need more details).

**Comment by sendaoYan** [comment]
> @sendaoYan do you mind creating a PR for this? Thanks You will need to sign the ECA before submitting a PR (as per https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#eclipse-contributor-agreement - which has a link to [further documentation](https://github.com/adoptium/documentation/blob/main/documentation-documentation/eca-sign-off.adoc) if you need more details).

I will glad to do it
