### ISSUE TITLE
dacapo-eclipse_0 run fail because of can't find dacapo.jar when test trigger by command line

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3606]
**Describe the bug**
dacapo-eclipse_0 run fail because of can't find dacapo.jar

**To Reproduce**
```bash
git clone -depth 1 -branch v0.9.1-release git@github.com:adoptium/aqa-tests.git
export TEST_JDK_HOME=~/software/jdk/jdk8u322-b06
export JAVA_HOME=$TEST_JDK_HOME
export PATH=$JAVA_HOME/bin:$PATH
export USE_TESTENV_PROPERTIES=true
export JDK_VERSION=8
export JDK_IMPL=hotspot
export BUILD_LIST=perf
cd aqa-tests
./get.sh
./compile.sh
cd TKG
make _sanity.perf
```

**Expected behavior**
run success by command line.

**Screenshots**
![image](https://user-images.githubusercontent.com/24123821/165055910-835360cb-6678-4ec1-bd94-2ceb5a45fbe8.png)

**Additional context**

when test is trigger by command line, the dacapo.jar is download to $HOME/aqa-tests/perf/dacapo/dacapo.jar, not to $HOME/jvmtest/perf/dacapo/dacapo.jar?

![image](https://user-images.githubusercontent.com/24123821/165057387-e7a2f3f6-0496-4028-a387-cdb1f136d2d0.png)

**Comment by sendaoYan** [comment]
And every time we execute the ./compile.sh script, it deletes the folder and re-downloads the dacapo.jar. Can we use the last downloaded file instead of getting the file from the internet again.

![image](https://user-images.githubusercontent.com/24123821/165062579-61d6144c-6e94-40f9-8cf2-d438494ac8d1.png)

**Comment by sendaoYan** [comment]
> And every time we execute the ./compile.sh script, it deletes the folder and re-downloads the dacapo.jar. Can we use the last downloaded file instead of getting the file from the internet again.
> 
> Download the dacapo.jar from internet cost a lot of time.
> 
> ![image](https://user-images.githubusercontent.com/24123821/165062579-61d6144c-6e94-40f9-8cf2-d438494ac8d1.png)

This is my patch:

```diff
yansendao.ysd@nu1l04366:[TKG]> git diff
diff --git a/makefile b/makefile
index 9a62bf1..24904d3 100644
--- a/makefile
+++ b/makefile
@@ -63,7 +63,7 @@ endif
 # compile test materials
 #######################################
 compile: buildListGen
-       $(MAKE) -f clean.mk cleanBuild
+#      $(MAKE) -f clean.mk cleanBuild
        $(MAKE) -f compile.mk compile
 
 #######################################
yansendao.ysd@nu1l04366:[TKG]> cd ..
yansendao.ysd@nu1l04366:[aqa-tests-oraclejdk8]> git diff perf/dacapo/
diff --git a/perf/dacapo/build.xml b/perf/dacapo/build.xml
index a62bb47..96a072c 100644
--- a/perf/dacapo/build.xml
+++ b/perf/dacapo/build.xml
@@ -30,10 +30,16 @@
                <var name="curl_options" value="-Lks https://sourceforge.net/projects/dacapobench/files/latest/download -o dacapo.jar"/>
                <retry retrycount="3">
                        <sequential>
-                               <echo message="curl ${curl_options}" />
-                               <exec executable="curl" failonerror="true">
-                                       <arg line="${curl_options}" />
-                               </exec>
+                               <available property="isExist" file="dacapo.jar" type="file" />
+                               <if>
+                                       <equals arg1="${isExist}" arg2="false" />
+                                       <then>
+                                                       <echo message="curl ${curl_options}" />
+                                                       <exec executable="curl" failonerror="true">
+                                                               <arg line="${curl_options}" />
+                                                       </exec>
+                                       </then>
+                               </if>
                        </sequential>
                </retry>
        </target>
```

**Comment by llxia** [comment]
- The error is about `unable to access to jarfile`, not cannot find the jarfile. To me, it looks like a permission issue. Could you check if you can see dacapo.jar under jvmtest folder?
- Re https://github.com/adoptium/aqa-tests/issues/3606#issuecomment-1108470567, this patch will cause an outdated jar never get removed. If you want to not re-download the jar if it exists, I think we need to ensure the sha matches with the current version. Otherwise, delete and re-download. And I think we already have this logic in TKG and we should add it for dacapo.jar. However, this should be a feature enhancement, it does not cause the problem in this issue.

**Comment by sendaoYan** [comment]
> * The error is about `unable to access jarfile`, not cannot find the jarfile. To me, it looks like a permission issue. Could you check if you can see dacapo.jar under jvmtest folder?
> * Re [dacapo-eclipse_0 run fail because of can't find dacapo.jar when test trigger by command line #3606 (comment)](https://github.com/adoptium/aqa-tests/issues/3606#issuecomment-1108470567), this patch will cause an outdated jar never get removed. If you want to not re-download the jar if it exists, we need to ensure the sha matches with the current version. Otherwise, delete and re-download. And I think we already have this logic in TKG and we should add it for dacapo.jar. However, this should be a feature enhancement, it does not cause the problem in this issue.

Yes, the patch just for speed up test, not for about "unable to access jarfile". And I found the perf test renaissance has check it exist or not before get binary from internet.

![image](https://user-images.githubusercontent.com/24123821/165096928-c797abe3-0ffd-47f1-88dd-bb9b12d8b923.png)

**Comment by sendaoYan** [comment]
On my linux machine, the curl command get dacapo.jar always fail. So I think is necessary to improve the process.

```bash
for i in `seq 10` ; do time curl -Lk https://sourceforge.net/projects/dacapobench/files/latest/download -o dacapo-$i.jar &>$i.log ; echo $? ; ls -lh dacapo-$i.jar ; done 
```

![image](https://user-images.githubusercontent.com/24123821/165242444-7ef979b3-9294-4fba-a24a-b6d76f79efbd.png)


![image](https://user-images.githubusercontent.com/24123821/165242709-afec5fa4-3885-4379-8ee0-be234b3477ed.png)

**Comment by llxia** [comment]
In general, we resolve this type of download/network issue by using a separate staging job - https://ci.adoptopenjdk.net/job/test.getDependency/

In order to do this, please see the following:
- add the download dacapo.jar logic into TKG.
For example https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl#L63-L66
This will also resolve the re-download issue that we discussed earlier.
- add `<property name="LIB" value="dacapo" />` in build.xml. 
**Note**: the value has to match the jar name in Perl
For example https://github.com/eclipse-openj9/openj9/blob/master/test/functional/Java8andUp/build.xml#L84
- for Jenkins runs, no additional steps are needed
- for local runs, run the Perl script and download all jars under TKG/lib

**Comment by sendaoYan** [comment]
> 

Thanks, I will try it later.
