### ISSUE TITLE
jvm_compiler_2 testcases in /compiler/codecache,compilercontrol FAILED in Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3620]
**Test Info**
Test Name: jvm_compiler_2
Test Duration: 22 min 59 sec
Machine: build-ibmcloud-win2012r2-x64-2
TRSS link for the test output: https://trss.adoptium.net/output/test?id=625f58c272761a4c5c1408b2

**Build Info**
Build Name: Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0
Jenkins Build start time: Apr 19 2022, 07:07 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/40/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=625f57cf72761a4c5c14063b

**Java Version**
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, emulated-client, sharing)

**This test has been failed 3 times since Sep 14 2021, 09:03 pm**
**Java Version when the issue first seen**
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK Client VM Temurin-17+35 (build 17+35, mixed mode, emulated-client)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/8/

The test failed on machine build-ibmcloud-win2012r2-x64-2 2 times 
The test failed on machine test-azure-win2012r2-x64-1 1 times 

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=&amp;TARGET=jvm_compiler_2&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=Test_openjdk17_hs_extended.openjdk_x86-32_windows&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-32_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk17u%2Fjdk17u-windows-x86-32-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-17.0.3%2B7_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=60&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;UPSTREAM_JOB_NUMBER=29&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

---

CompiledInvokeDynamic2NativeTest, etc fail with 
```
19:36:44  STDOUT:
19:36:44  CompileCommand: exclude compiler/calls/common/InvokeDynamic.callee bool exclude = true
19:36:44  STDERR:
19:36:44  java.lang.RuntimeException: assertTrue: expected true, was false
19:36:44  	at jdk.test.lib.Asserts.fail(Asserts.java:594)
19:36:44  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:486)
19:36:44  	at jdk.test.lib.Asserts.assertTrue(Asserts.java:472)
19:36:44  	at compiler.calls.common.CallsBase.compileMethod(CallsBase.java:194)
19:36:44  	at compiler.calls.common.CallsBase.runTest(CallsBase.java:164)
19:36:44  	at compiler.calls.common.InvokeDynamic.main(InvokeDynamic.java:43)
19:36:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
19:36:44  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
19:36:44  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
19:36:44  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
19:36:44  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
19:36:44  	at java.base/java.lang.Thread.run(Thread.java:833)
```

Same failures also seen against Azul as a reference (see https://ci.adoptopenjdk.net/job/Grinder/4585/consoleFull).

**Comment by sophia-guo** [comment]
Same for jdk18
