### ISSUE TITLE
DockerBasicTest.java run fail on aarch64 platform

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3629]
**Describe the bug**
DockerBasicTest.java run fail on aarch64 platform, because of can't get the "aarch64/ubuntu:latest" docker image.

**To Reproduce**
jtreg -va -nr -w tmp hotspot/test/runtime/containers/docker/DockerBasicTest.java

docker pull aarch64/ubuntu:latest

**Expected behavior**
run success

**Screenshots**

![image](https://user-images.githubusercontent.com/24123821/167145729-5aabc8d8-be94-440a-8f50-ec7ea0708ab8.png)

![image](https://user-images.githubusercontent.com/24123821/167145831-e3206e3e-e220-414a-8b3c-451370149443.png)

![image](https://user-images.githubusercontent.com/24123821/167145868-73975791-671a-4ad9-ab4e-96a9d9400b6b.png)

**Additional context**
dockerfile generate by testcase:

![image](https://user-images.githubusercontent.com/24123821/167146001-4ee07a6f-3f34-4c97-92bf-7b586bce8372.png)

hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java:

![image](https://user-images.githubusercontent.com/24123821/167146298-5f9fcdf7-8841-4b70-9cd3-436a2a6c3984.png)

```diff
git diff hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java 
diff --git a/hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java b/hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java
index e000f0eed4..f8d424a3a1 100644
--- a/hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java
+++ b/hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java
@@ -44,7 +44,7 @@ public class DockerfileConfig {
 
         switch (Platform.getOsArch()) {
             case "aarch64":
-                return "aarch64/ubuntu";
+                return "ubuntu";
             case "ppc64le":
                 return "ppc64le/ubuntu";
             case "s390x":
```

**Comment by sophia-guo** [comment]
Test passed in grinder https://ci.adoptopenjdk.net/job/Grinder/4604/console, which is using temurin jdk8 aarch64. Not sure the real reason for the failure.

**Comment by sendaoYan** [comment]
> Test passed in grinder https://ci.adoptopenjdk.net/job/Grinder/4604/console, which is using temurin jdk8 aarch64. Not sure the real reason for the failure.

If you want to run this test really, you should make sure the docker service work normally.
Testcase will check docker service before test start.

![image](https://user-images.githubusercontent.com/24123821/167232999-0574becf-53fd-4dee-be8e-555107e95d6f.png)

![image](https://user-images.githubusercontent.com/24123821/167233044-457af0b0-c75b-43c0-91ae-d7115bdf1f3a.png)

**Comment by sendaoYan** [comment]
testcase list：
```
runtime/containers/docker/DockerBasicTest.java
runtime/containers/docker/TestCPUAwareness.java
runtime/containers/docker/TestCPUSets.java
runtime/containers/docker/TestMemoryAwareness.java
runtime/containers/docker/TestMisc.java
```

**Comment by sophia-guo** [comment]
@sendaoYan Could you confirm that we need to open an issue in JBS to update hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java to fix this issue?

**Comment by sendaoYan** [comment]
> @sendaoYan Could you confirm that we need to open an issue in JBS to update hotspot/test/testlibrary/com/oracle/java/testlibrary/DockerfileConfig.java to fix this issue?

I think it's necessaty to creat open an issue in upstream JBS. But I don't have an account.
After this issue has been fixed, we can enable these testcase again.

**Comment by sophia-guo** [comment]
@andrew-m-leonard could you help this? Reopen and will close when issue is opened in jbs

**Comment by sophia-guo** [comment]
Same issue with arm32 https://ci.adoptopenjdk.net/job/Grinder/5314/

**Comment by andrew-m-leonard** [comment]
What is the correct fix here? removing aarch64 from the docker image name doesn't look right to me?

**Comment by jerboaa** [comment]
The correct fix for this is to specify `-Djdk.test.docker.image.name=<base-image-name>` and `-Djdk.test.docker.image.version=<image-version>` when running the test. That is, if you wanted to run the test on a `registry.fedoraproject.org/fedora:37` base image, one would set:

```
-Djdk.test.docker.image.name=registry.fedoraproject.org/fedora \
-Djdk.test.docker.image.version=37
```

It's not a good idea to rely on the defaults for those container tests.

**Comment by jerboaa** [comment]
There really is nothing to report upstream, as that's the way to handle mismatches on the base image versions. See https://bugs.openjdk.org/browse/JDK-8221342

**Comment by sendaoYan** [comment]
> jdk.test.docker.image.name

Thanks for your advice.
