### ISSUE TITLE
[jdk18 arm32, aarch64] jdk_net failures related with IPv6

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3637]
Following jdk_net test failed on arm32 with jdk18, those tests suppose that IPv6 are supported on all platforms, which is not true for arm_linux.
https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1/28/

[com/sun/net/httpserver/simpleserver/CommandLinePositiveTest.java.CommandLinePositiveTest](https://ci.adoptopenjdk.net/job/Grinder/4567/testReport/junit/com_sun_net_httpserver_simpleserver_CommandLinePositiveTest/java/CommandLinePositiveTest/)
[com/sun/net/httpserver/simpleserver/jwebserver/CommandLinePositiveTest.java.CommandLinePositiveTest](https://ci.adoptopenjdk.net/job/Grinder/4567/testReport/junit/com_sun_net_httpserver_simpleserver_jwebserver_CommandLinePositiveTest/java/CommandLinePositiveTest/)
[java/net/InetAddress/HostsFileOrderingTest.java.HostsFileOrderingTest](https://ci.adoptopenjdk.net/job/Grinder/4567/testReport/junit/java_net_InetAddress_HostsFileOrderingTest/java/HostsFileOrderingTest/)
[java/net/InetAddress/InternalNameServiceTest.java.InternalNameServiceTest](https://ci.adoptopenjdk.net/job/Grinder/4567/testReport/junit/java_net_InetAddress_InternalNameServiceTest/java/InternalNameServiceTest/)
[java/net/InetAddress/InternalNameServiceWithHostsFileTest.java.InternalNameServiceWithHostsFileTest](https://ci.adoptopenjdk.net/job/Grinder/4567/testReport/junit/java_net_InetAddress_InternalNameServiceWithHostsFileTest/java/InternalNameServiceWithHostsFileTest/)

For example [java/net/InetAddress/HostsFileOrderingTest.java](https://github.com/openjdk/jdk18u/blob/master/test/jdk/java/net/InetAddress/HostsFileOrderingTest.java) has testcases with [-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true ](https://github.com/openjdk/jdk18u/blob/master/test/jdk/java/net/InetAddress/HostsFileOrderingTest.java#L53-L61)

or IPv6 tests is not conditional [java/net/InetAddress/InternalNameServiceTest.java](https://github.com/openjdk/jdk18u/blob/master/test/jdk/java/net/InetAddress/InternalNameServiceTest.java#L130-L141)

https://github.com/adoptium/aqa-tests/issues/3599#issuecomment-1105959116

**Comment by sophia-guo** [comment]
Same for jdk18 linux-aarch64 https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_linux/30/#showFailuresLink

**Comment by LongyuZhang** [comment]
TEST: `jdk/net/ExtendedSocketOption/DontFragmentTest.java` is also failing with IPv6 for JDK19 on xlinux
```
00:47:07  STDERR:
00:47:07  java.lang.UnsupportedOperationException: IPv6 not available
00:47:07  	at java.base/sun.nio.ch.DatagramChannelImpl.<init>(DatagramChannelImpl.java:183)
00:47:07  	at java.base/sun.nio.ch.SelectorProviderImpl.openDatagramChannel(SelectorProviderImpl.java:59)
00:47:07  	at java.base/java.nio.channels.DatagramChannel.open(DatagramChannel.java:197)
00:47:07  	at DontFragmentTest.testDatagramChannel(DontFragmentTest.java:107)
00:47:07  	at DontFragmentTest.main(DontFragmentTest.java:51)
00:47:07  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
00:47:07  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
00:47:07  	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
00:47:07  	at java.base/java.lang.Thread.run(Thread.java:858)
```

**Comment by sophia-guo** [comment]
same for alpine-linux https://ci.adoptium.net/job/Test_openjdk20_hs_extended.openjdk_x86-64_alpine-linux_testList_2/23/#showFailuresLink

**Comment by sophia-guo** [comment]
Looks like this have been fixed in upstream https://bugs.openjdk.org/browse/JDK-8314517?jql=text%20~%20%22com%2Fsun%2Fnet%2Fhttpserver%2Fsimpleserver%2FCommandLinePositiveTest.java%22.

Grinder :
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10710/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10711/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10712/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10716/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10717/
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10718/
