### ISSUE TITLE
Gather TAP/metadata files for April Temurin builds (for marketplace)

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3640]
In prep for first listing in the Adoptium marketplace, we should grab the TAP and metadata files from the April release.  Since the runs did not go very cleanly during the release, it will likely be easier to rerun (once we backport excludes to v0.9.1) using the [AQA Test pipeline job](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/).

We may want to augment the gathering of the TAP files from a parent job beyond what the recent changes do for pushing to artifactory (or alternatively, set up an artifactory instance to push to).

We will ultimately want to store a zip file containing all of the TAP and metadata files in the releases repository alongside the binaries (for releases only, not for EA/nightly builds).

| JDK version | JDK platform | link to results files | 
| --- | --- | --- | 
| 17 | all | | 
| 17 | x86-64_linux | [tap_jdk17_xlinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8712360/tap_jdk17_xlinux_temurin.zip) |
| 17 | x86-64_mac | [tap_jdk17_x64mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8710419/tap_jdk17_x64mac_temurin.zip) |
| 17 | x86-64_windows | [tap_jdk17_x64windows_temurin.zip](https://github.com/adoptium/aqa-tests/files/8746869/tap_jdk17_x64windows_temurin.zip) |
| 17 | ppc64le_linux | [tap_jdk17_ppc64leLinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8757063/tap_jdk17_ppc64leLinux_temurin.zip) |
| 17 | s390x_linux | [tap_jdk17_s390xLinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8758536/tap_jdk17_s390xLinux_temurin.zip) |
| 17 | aarch64_mac | [tap_jdk17_aarch64Mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8761920/tap_jdk17_aarch64Mac_temurin.zip) |
| 17 | aarch64_linux | [tap_jdk17_aarch64Linux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8756764/tap_jdk17_aarch64Linux_temurin.zip)|
| 17 | arm_linux |  |
| 17 | x86-32_windows |  |
| 17 | x86-64_alpine-linux |  |
| 17 | ppc64_aix | |
| 11 | all | |
| 11 | x86-64_linux | [tap_jdk11_xlinxu_temurin.zip](https://github.com/adoptium/aqa-tests/files/8717397/tap_jdk11_xlinxu_temurin.zip) |
| 11 | x86-64_mac | [tap_jdk11_x64mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8722842/tap_jdk11_x64mac_temurin.zip) |
| 11 | x86-64_window | [tap_jdk11_x64windows_temurin.zip](https://github.com/adoptium/aqa-tests/files/8743613/tap_jdk11_x64windows_temurin.zip) |
| 11 | ppc64le_linux | [tap_jdk11_ppc64leLinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8761931/tap_jdk11_ppc64leLinux_temurin.zip) |
| 11 | aarch64_mac | [tap_jdk11_aarch64_mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8775792/tap_jdk11_aarch64_mac_temurin.zip) |
| 11 | s390x_linux | issues running sanity.perf, unable to rerun due to [infra/2578](https://github.com/adoptium/infrastructure/issues/2578) |
| 11 | aarch64_linux | [tap_jdk11_aarch64Linux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8761938/tap_jdk11_aarch64Linux_temurin.zip) |
| 11 | arm_linux | [tap_jdk11_armLinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8775234/tap_jdk11_armLinux_temurin.zip) |
| 11 | x86-32_windows |  |
| 11 | x86-64_alpine-linux |  |
| 11 | ppc64_aix |  |
| 8 | all | |
| 8 | x86-64_linux | [tap_jdk8_xlinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8743366/tap_jdk8_xlinux_temurin.zip) |
| 8 | x86-64_mac | [tap_jdk8_x64mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8740982/tap_jdk8_x64mac_temurin.zip)|
| 8 | x86-64_windows | [tap_jdk8_x64windows_temurin.zip](https://github.com/adoptium/aqa-tests/files/8746887/tap_jdk8_x64windows_temurin.zip)|
| 8 | ppc64le_linux | [tap_jdk8_ppc64le_linux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8775935/tap_jdk8_ppc64le_linux_temurin.zip) |
| 18 | all | |
| 18 | x86-64_linux | [tap_jdk18_xlinux_temurin.zip](https://github.com/adoptium/aqa-tests/files/8734566/tap_jdk18_xlinux_temurin.zip) |
| 18 | x86-64_mac | [tap_jdk18_x64mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8734560/tap_jdk18_x64mac_temurin.zip)|
| 18 | x86-64_windows |[tap_jdk18_x64windows_temurin.zip](https://github.com/adoptium/aqa-tests/files/8746876/tap_jdk18_x64windows_temurin.zip) |

**Comment by smlambert** [comment]
I will start with the 3 primary jdk17 platforms:

Pulling builds from https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348 and running tests from:
[AQA_Test_Pipeline/17](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/17/).

**Comment by sophia-guo** [comment]
Build failed. [sdk_resource=customized, sdk_url](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/aqaTestPipeline.groovy#L43) might not work @llxia

**Comment by smlambert** [comment]
https://github.com/adoptium/aqa-tests/issues/3649 - raised as the problem we encounter for Temurin builds.

I also created https://github.com/adoptium/aqa-tests/issues/3650 (but do not think it is a real problem, as I need to add those parameters to the Jenkins config and try using those params instead).

**Comment by llxia** [comment]
PR [Support nested zip file](https://github.com/adoptium/aqa-tests/commit/baa9589a1df7edabdd97471ffcceb53acafa2600) needs to be backported into v0.9.1-release

**Comment by smlambert** [comment]
jdk17 x64 mac (via [AQA_Test_Pipeline/23](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/23/) and [Grinder/4635](https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4635/)): 
[tap_jdk17_x64mac_temurin.zip](https://github.com/adoptium/aqa-tests/files/8710419/tap_jdk17_x64mac_temurin.zip)

jdk17 x64 linux (via [AQA_Test_Pipeline/21](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/21/) and [Grinder/4636](https://ci.adoptopenjdk.net/job/Grinder/4636/)):


jdk17 x64 windows (via [AQA_Test_Pipeline/23](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/23/) and Grinder/xxxxx):

**Comment by sophia-guo** [comment]
Primaries for jdk11:

 jdk11 x64 mac ( via [AQA_Test_Pipeline/26](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/26/) and [Grider/****](https://):

 jdk11 x64 linux ( via [AQA_Test_Pipeline/25](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/25/) and [Grider/****](https://):

 jdk11 x64 windows ( via [AQA_Test_Pipeline/26](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/26/) and [Grider/****](https://)

**Comment by sophia-guo** [comment]
Primaries for jdk18:

jdk18 x64 mac ( via [AQA_Test_Pipeline/27](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/27/) and [Grider/****](https://) ):

jdk18 x64 linux ( via [AQA_Test_Pipeline/27](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/27/) and [Grider/****](https://) ):

jdk18 x64 windows ( via [AQA_Test_Pipeline/28](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/28/) and [Grider/****](https://) ):

**Comment by sophia-guo** [comment]
Windows zip file empty issue https://github.com/adoptium/aqa-tests/issues/3668

**Comment by sophia-guo** [comment]
Primaries for jdk8:

jdk8 x64 mac ( via [AQA_Test_Pipeline/27](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/29/) and [Grider/****](https://) ):

jdk8 x64 linux ( via [AQA_Test_Pipeline/29](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/29/) and [Grider/****](https://) ):

**Comment by sophia-guo** [comment]
Done. Close.

**Comment by smlambert** [comment]
Thanks @sophia-guo !  This is great!

I am going to re-open and do the same exercise for the secondary and 3rd tier platforms as I suspect some of them will not need much intervention.  Getting the primaries completed is a big relief though, as now we will for sure have a Temurin listing in the marketplace on launch day. 😄

**Comment by smlambert** [comment]
Secondary platforms, jdk17:
aarch64_linux,,aarch64_mac,ppc64le_linux,s390x_linux: [AQA_Test_Pipeline/51/](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/51/)

**Comment by smlambert** [comment]
Tertiary platforms jdk17: [AQA Test Pipeline 54](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/54/)

arm_linux: 

ppc64_aix: 

x86-32_windows:

x86-64_alpine-linux:

**Comment by smlambert** [comment]
Tertiary platforms jdk11:  [AQA Test Pipeline 55](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/55/)

arm_linux: 

ppc64_aix: 

x86-32_windows:

x86-64_alpine-linux:

**Comment by smlambert** [comment]
jdk8 2/3rd tier platforms:  [AQA Test Pipeline 56](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/56/)

aarch64_linux:
ppc64le_linux:
ppc64_aix:
sparcv9_solaris:
x86-64_solaris:
x86-64_alpine-linux:

[AQA Test Pipeline 57](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/57/) 
x86-32_windows:

**Comment by smlambert** [comment]
jdk18 2/3rd tier platforms: [AQA Test Pipeline 59](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/59/)

**Comment by steelhead31** [comment]
Working on x86-64_alpine-linux

**Comment by steelhead31** [comment]
Working on JDK8 x86-64_solaris:

**Comment by steelhead31** [comment]
> > Only the 2 failures ( which should be excluded ) outstanding :-
> > Openjdk_Sanity : 2 Failures ( jdk_util_0 - java/util/Currency/CurrencyTest.java.CurrencyTest & java/util/Currency/ValidateISO4217.java )
> 
> [#3640 (comment)](https://github.com/adoptium/aqa-tests/issues/3640#issuecomment-1141264794)
> 
> @steelhead31 what's the failures of those two jdk_util tests? Is there issue opened so I can use it as a track to exclude them?

@sophia-guo I think it was related to this issue, being fixed in JDK11.. https://github.com/adoptium/aqa-tests/issues/678 , if that isnt sufficient, let me know and I'll raise a new issue.

**Comment by sophia-guo** [comment]
Thanks @steelhead31! So did you mean that the failure is because https://bugs.openjdk.org/browse/JDK-8150324 wan't backport to jdk8? And this only happen to solaris jdk8?

**Comment by steelhead31** [comment]
@sophia-guo  thats how I read it yes.

**Comment by sophia-guo** [comment]
I have rerun 
java/util/Currency/CurrencyTest.java.CurrencyTest & java/util/Currency/ValidateISO4217.java , both passed. 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4969/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4968/

10x 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4976/
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/4977/

**Comment by steelhead31** [comment]
Well done, I tried a few times, and couldnt get them to pass, must be an intermittent thing, or resource issue when running the full set, rather than an individual test...  I've had a look at those grinder runs, so I can get the paramters to try myself on  a future run :)

**Comment by sophia-guo** [comment]
https://github.com/adoptium/aqa-tests/issues/3640#issuecomment-1135026844

Tertiary platforms jdk17: [AQA Test Pipeline 54](https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/54/)
SL/May 25: https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/60

arm_linux:
[Test_openjdk17_hs_sanity.system_arm_linux #163](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.system_arm_linux/163/) completed with status FAILURE (propagate: false to ignore) : **not available any more**
[Test_openjdk17_hs_sanity.functional_arm_linux #132](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.functional_arm_linux/132/) completed with status FAILURE (propagate: false to ignore): **not available any more**
[Test_openjdk17_hs_special.functional_arm_linux #49](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_special.functional_arm_linux/49/) completed with status FAILURE (propagate: false to ignore)

```
Running on [test-sxa-armv7l-ubuntu2004-odroid-1](https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-1/) in /ssd/jenkins/workspace/Test_openjdk17_hs_special.functional_arm_linux
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: java.nio.file.AccessDeniedException: /ssd/jenkins
```
[Test_openjdk17_hs_sanity.perf_arm_linux #133](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.perf_arm_linux/133/) completed with status FAILURE (propagate: false to ignore): **not available any more**
[Test_openjdk17_hs_extended.perf_arm_linux #49](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.perf_arm_linux/49/) completed with status FAILURE (propagate: false to ignore)

```
[Pipeline] node
Running on [test-sxa-armv7l-ubuntu2004-odroid-1](https://ci.adoptopenjdk.net/computer/test-sxa-armv7l-ubuntu2004-odroid-1/) in /ssd/jenkins/workspace/Test_openjdk17_hs_extended.perf_arm_linux
[Pipeline] {
[Pipeline] timeout
Timeout set to expire in 1 hr 0 min
[Pipeline] {
[Pipeline] cleanWs
[Pipeline] }
[Pipeline] // timeout
[Pipeline] echo
Exception: java.nio.file.AccessDeniedException: /ssd/jenkins
```
[Test_openjdk17_hs_extended.functional_arm_linux #132](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.functional_arm_linux/132/) completed with status FAILURE (propagate: false to ignore): **not available any more**
[Test_openjdk17_hs_extended.system_arm_linux #135](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.system_arm_linux/135/) completed with status FAILURE (propagate: false to ignore): **not available any more**
[Test_openjdk17_hs_sanity.openjdk_arm_linux #132](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_sanity.openjdk_arm_linux/132/) completed with status FAILURE (propagate: false to ignore): **not available any more**
[Test_openjdk17_hs_extended.openjdk_arm_linux #49](https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux/49/) completed with status FAILURE (propagate: false to ignore)

Three child jobs
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0/43/
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_2/43/
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_1/43/

**Comment by sophia-guo** [comment]
Trying rerun jdk17 arm32 aqa-test with jdk17 build pipeline and looks like artifacts are not available any more. Take aarch64 as example, which works before and now not. [https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348/artifact/target/linux/aarch64/temurin/*.tar.gz/*zip*/temurin.zip](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348/artifact/target/linux/aarch64/temurin/*.tar.gz/*zip*/temurin.zip)

I remember the artifacts of release job will be kept some kinds of forever instead only last 60 number of builds? @sxa any comments?

**Comment by sophia-guo** [comment]
jdk11 windows32 https://github.com/adoptium/aqa-tests/issues/3640#issuecomment-1135031367

Only 3 jobs are available and all of them failed with 

```
09:06:28  + ./get.sh -s /cygdrive/j/jenkins/workspace/Test_openjdk11_hs_special.functional_x86-32_windows/aqa-tests/.. -p x86-32_windows -r customized -j 11 -i hotspot -c 'https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1910/artifact/target/windows/x32/temurin/*.zip/*zip*/temurin.zip'
09:06:28  TESTDIR: /cygdrive/j/jenkins/workspace/Test_openjdk11_hs_special.functional_x86-32_windows/aqa-tests
09:06:28  load ./testenv/testenv.properties
09:06:28  get jdk binary...
09:06:28  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/1910/artifact/target/windows/x32/temurin/*.zip/*zip*/temurin.zip
09:06:28  temurin.zip is a nested zip
09:06:28  [temurin.zip]
09:06:28    End-of-central-directory signature not found.  Either this file is not
```

The artifacts url is incorrect.

**Comment by sophia-guo** [comment]
x86-64_alpine https://github.com/adoptium/aqa-tests/issues/3640#issuecomment-1155338974
sanity.openjdk is not available any more https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_x86-64_alpine-linux/90/

rerun: https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/82/

**Comment by sxa** [comment]
> Trying rerun jdk17 arm32 aqa-test with jdk17 build pipeline and looks like artifacts are not available any more. Take aarch64 as example, which works before and now not. [https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348/artifact/target/linux/aarch64/temurin/*.tar.gz/_zip_/temurin.zip](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk17-pipeline/348/artifact/target/linux/aarch64/temurin/*.tar.gz/*zip*/temurin.zip)
> 
> I remember the artifacts of release job will be kept some kinds of forever instead of only last 60 number of builds? @sxa any comments?

Now recovered. Apologies for that - I think it was user error on my part.
