### ISSUE TITLE
Update AQA Test pipeline to also handle the case where a CUSTOMIZED_SDK_URL is passed in

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3650]
This can allow us to use this pipeline on a per platform basis and run with specific builds from vendors (useful to help out for AQAvit verification).

While we can 'sort of' accomplish this via Grinder, this can be helpful as it creates named jobs and can be monitored via TRSS (which we do not do with Grinder jobs).

**Comment by llxia** [comment]
CUSTOMIZED_SDK_URL is supported in AQA Test pipeline. We just need to add CUSTOMIZED_SDK_URL param in https://ci.adoptopenjdk.net/job/AQA_Test_Pipeline

**Comment by llxia** [comment]
CUSTOMIZED_SDK_URL is added in https://ci.adoptopenjdk.net/job/AQA_Test_Pipeline

**Comment by llxia** [comment]
For future enhancement, I think we can consolidate TOP_LEVEL_SDK_URL and CUSTOMIZED_SDK_URL into one parameter.

**Comment by smlambert** [comment]
Ok, closing this, we can create a separate issue for the enhancement when we next review our parameters list.  :)
