### ISSUE TITLE
MBCS_Tests_jaxp14_zh_CN_linux_0 fail on same linux machine

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3676]
**Describe the bug**
MBCS_Tests_jaxp14_zh_CN_linux_0 fail on same linux machine.
The XSLTTest testcase check the output, which strict match the contents the expected data "[expected_zh-cn.html](https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/jaxp14/data/expected_zh-cn.html)"
The content of the actual output and the expected is the same, just only two lines sequence is diffrent.
I think it's not a jdk bug, but is only a envirent issue.
But I don't known how to make this testcast run pass. Anyone has any idea?

vimdiff: 

![image](https://user-images.githubusercontent.com/24123821/169291117-feb65f2e-536a-4a82-9083-622ef5c385ea.png)

beyond compare:

![image](https://user-images.githubusercontent.com/24123821/169291207-7edefb39-01c0-4e7a-8ae0-19d9e32dfe22.png)

**To Reproduce**
```bash
tar xf MBCS_Tests_jaxp14_zh_CN_linux_0.tar.gz 
cd MBCS_Tests_jaxp14_zh_CN_linux_0/
javac XSLTTest.java
java XSLTTest drinks_zh-cn.xml drinks_zh-cn.xsl > alios.html
vimdiff alios.html expected_zh-cn.html
```

**Expected behavior**

**Screenshots**

**Additional context**

[MBCS_Tests_jaxp14_zh_CN_linux_0.tar.gz](https://github.com/adoptium/aqa-tests/files/8728917/MBCS_Tests_jaxp14_zh_CN_linux_0.tar.gz)

java version:

![image](https://user-images.githubusercontent.com/24123821/169291950-f40d3b67-1922-4c8a-9fa6-98b800e01df9.png)

[XSLTTest.java](https://github.com/adoptium/aqa-tests/blob/master/functional/MBCS_Tests/jaxp14/src/XSLTTest.java)

locale:

![image](https://user-images.githubusercontent.com/24123821/169292443-3ff2aa87-bf0a-40b0-a99b-6c4c9f83e23f.png)

original test log:

```
===============================================
Running test MBCS_Tests_jaxp14_zh_CN_linux_0 ...
===============================================
MBCS_Tests_jaxp14_zh_CN_linux_0 Start Time: Thu May 19 14:35:07 2022 Epoch Time (ms): 1652942107127
Nothing to be done for setup.
variation: NoOptions
JVM_OPTIONS:
{ itercnt=1; \
mkdir -p "/mnt_array/yansendao.ysd/aqa-tests/TKG/../TKG/output_16529421012521/MBCS_Tests_jaxp14_zh_CN_linux_0"; \
cd "/mnt_array/yansendao.ysd/aqa-tests/TKG/../TKG/output_16529421012521/MBCS_Tests_jaxp14_zh_CN_linux_0"; \
LANG=zh_CN.UTF-8 bash /mnt_array/yansendao.ysd/aqa-tests/TKG/../../jvmtest/functional/MBCS_Tests/jaxp14/test.sh; \
if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_jaxp14_zh_CN_linux_0""_PASSED"; echo ""; cd /mnt_array/yansendao.ysd/aqa-tests/TKG/..;  else echo ""; echo "MBCS_Tests_jaxp14_zh_CN_linux_0""_FAILED";
echo ""; fi; } 2>&1 | tee -a "/mnt_array/yansendao.ysd/aqa-tests/TKG/../TKG/output_16529421012521/TestTargetResult";

MBCS_Tests_jaxp14_zh_CN_linux_0_FAILED

Nothing to be done for teardown.
MBCS_Tests_jaxp14_zh_CN_linux_0 Finish Time: Thu May 19 14:35:07 2022 Epoch Time (ms): 1652942107529
```

**Comment by sendaoYan** [comment]
I found for the same input.txt, the result for `sort input.txt` on macos and on linux(alios) is diffrent. The sort result is similar to the testcase output.




macOS:

![image](https://user-images.githubusercontent.com/24123821/169294280-6bf01512-73fa-4289-b64e-1920076b2ccb.png)



linux(alios):

![image](https://user-images.githubusercontent.com/24123821/169294458-8364a2f2-b12b-41bc-ad89-f596be3620b7.png)


I create a docker container which image is ubuntu:latese, the sort result is same to the alios:

![image](https://user-images.githubusercontent.com/24123821/169295340-95f46027-aa92-4dfa-a56e-02fa036f8ae1.png)

**Comment by sendaoYan** [comment]
set LANG=zh_CN.UTF-8 doesn't work

![image](https://user-images.githubusercontent.com/24123821/169299454-0aa1a87f-2eba-413f-93ee-ed0397d6b933.png)

**Comment by smlambert** [comment]
@KKES335 @takiguc - will you be able to help to answer @sendaoYan 's question?

**Comment by takiguc** [comment]
Hello @sendaoYan .
I think yor docker image or your machine defined LC_ALL environment variable like LC_ALL=en_US.UTF-8.
```
$ export LANG=zh_CN.UTF-8
$ ~/jdk-17.0.3+7/bin/java -XshowSettings:properties -version 2>&1 | grep 'user\.[cl]'
    user.country = CN
    user.language = zh
$ export LC_ALL=en_US.UTF-8
$ ~/jdk-17.0.3+7/bin/java -XshowSettings:properties -version 2>&1 | grep 'user\.[cl]'
    user.country = US
    user.language = en
```
If LC_ALL is defined, java picks up locale setting from LC_ALL instead of LANG.
```
$ locale
LANG=zh_CN.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
$ 
```
MBCS testcases checked locale setting via `locale charmap`.
Like `${LANG%.*}.$(locale charmap)`

So above case, testcase generated zh_CN.UTF-8 locale, but actual locale was en_US.UTF-8.
I ran CI jobs and these worked fine as expected.
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/312/console
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Simple/313/console

I put may fix into https://github.com/takiguc/aqa-tests/tree/3676
Repo: https://github.com/takiguc/aqa-tests
Branch: 3676
If possible, could you run my fix with your jobs setting ?

**Comment by sendaoYan** [comment]
@takiguc 

> 
I have no idea, why my machine(alios linux) test still fail after apply your patch
```
LANG=zh_CN.UTF-8 bash /mnt_array/yansendao.ysd/output-aqa-tests/jdk17/20220519-1919/jvmtest-functional/functional/MBCS_Tests/jaxp14/test.sh; \
if [ $? -eq 0 ] ; then echo ""; echo "MBCS_Tests_jaxp14_zh_CN_linux_0""_PASSED"; echo ""; cd /mnt_array/yansendao.ysd/aqa-tests/TKG/..;  else echo ""; echo "MBCS_Tests_jaxp14_zh_CN_linux_0""_FAILED";
echo ""; fi; } 2>&1 | tee -a "/mnt_array/yansendao.ysd/aqa-tests/TKG/../TKG/output_16530588093973/TestTargetResult";
locale: Cannot set LC_ALL to default locale: No such file or directory
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "zh_CN.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

This is run result by command: 
```bash
LANG=zh_CN.UTF-8 bash -x /mnt_array/yansendao.ysd/output-aqa-tests/jdk17/20220519-1919/jvmtest-functional/functional/MBCS_Tests/jaxp14/test.sh
```

![image](https://user-images.githubusercontent.com/24123821/169560333-4ffe3c89-0239-4eec-a12e-0f2a0c6db9af.png)


On my other machine(linux ubuntu20.04, not docker contanier), the test is skip after apply your patch:


![image](https://user-images.githubusercontent.com/24123821/169561107-f1659dc4-817a-4b11-83e8-58cea3ab2270.png)

[3676.patch.txt](https://github.com/adoptium/aqa-tests/files/8741513/3676.patch.txt)

**Comment by takiguc** [comment]
Hello @sendaoYan .
Thank you for your testing.
I assume that `locale charmap` command returns `ANSI_X3.4-1968` if the Linux machine does not have specified locale.
But your machine's `locale charmap` returned `UTF-8`.
Please give me more time to reconsider about another solution.

**Comment by sendaoYan** [comment]
> 

Thanks very much.

**Comment by sendaoYan** [comment]
> Hello @sendaoYan . Thank you for your testing. I assume that `locale charmap` command returns `ANSI_X3.4-1968` if the Linux machine does not have specified locale. But your machine's `locale charmap` returned `UTF-8`. Please give me more time to reconsider about another solution.


Thanks very much.

**Comment by takiguc** [comment]
Hello @sendaoYan .
Could you test following patch on your machine (alios linux), please ?

https://github.com/adoptium/aqa-tests/compare/master...takiguc:3676.diff

**Comment by sendaoYan** [comment]
> Hello @sendaoYan . Could you test following patch on your machine (alios linux), please ?
> 
> https://github.com/adoptium/aqa-tests/compare/master...takiguc:3676.diff

I have fixed this enviromental problem by execute below command:

```bash
sudo localedef -v -c -i en_US -f UTF-8 en_US.UTF-8
sudo localedef -v -c -i zh_CN -f UTF-8 zh_CN.UTF-8
sudo localedef -v -c -i zh_TW -f UTF-8 zh_TW.UTF-8
sudo localedef -v -c -i ja_JP -f UTF-8 ja_JP.UTF-8
sudo localedef -v -c -i ko_KR -f UTF-8 ko_KR.UTF-8
```

So I can't replay the failure now. May be we can close this issue now?

**Comment by takiguc** [comment]
Thanks @sendaoYan  .

If possible, I'd like to use this issue for PR creation.
Is it OK ?
