### ISSUE TITLE
AQA_TEST_Pipeline job exit unexpected without error message with jdk8

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3677]
AQA_TEST_Pipeline job exit unexpected without error message with jdk8
https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/29/

All test jobs exit right after download the zip file
For example
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.functional_x86-64_mac/307/
```
09:19:28  load ./testenv/testenv.properties
09:19:28  get jdk binary...
09:19:28  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/2087//artifact/target/linux/x64/temurin/*.tar.gz/*zip*/temurin.zip
09:20:44  temurin.zip is a nested zip
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
```

rerun got same issue https://ci.adoptopenjdk.net/view/Test_grinder/job/AQA_Test_Pipeline/34/

Manually check download zip file and unzip, all good.

See also #3640

**Comment by smlambert** [comment]
likely not the issue, but I will update the 'helper text' below the param to not include the extra '/' `openjdk8-pipeline/2087//artifact/`

**Comment by sophia-guo** [comment]
The reason is for jdk8 there is no testimage. So bash command return status is error even if the stderr is redirected.
[jar_files=`ls *jdk*.tar.gz *jre*.tar.gz *testimage*.tar.gz *debugimage*.tar.gz *jdk*.zip *jre*.zip *testimage*.zip *debugimage*.zip 2> /dev/null`](https://github.com/adoptium/aqa-tests/blob/master/get.sh#L306)

**Comment by sophia-guo** [comment]
As https://github.com/adoptium/aqa-tests/pull/3669 add *.zip this will affect all jdk versions.
