### ISSUE TITLE
[jdk8 windows-x64]: sun/jvmstat/monitor/MonitoredVm/CR6672135.java failed `Caused by: java.io.IOException: Could not determine PerfMemory size`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3691]
[jdk8 windows-x64]: sun/jvmstat/monitor/MonitoredVm/CR6672135.java failed `Caused by: java.io.IOException: Could not determine PerfMemory size`

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_windows_testList_2/44/console

**Comment by smlambert** [comment]
Close as stale/not enough info to investigate.  This test case remains excluded but for all platforms (related:  https://github.com/adoptium/aqa-tests/issues/5741).
