### ISSUE TITLE
MemoryTestZGC.sh fail by dragonwell11, should this testcase excluded when vendor is dragonwell

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3731]
**Describe the bug**
test/jdk/java/lang/management/MemoryMXBean/MemoryTestZGC.sh fail by dragonwell11

```
STDOUT:
runOne -XX:+UnlockExperimentalVMOptions -XX:+UseZGC MemoryTest 1 1
STDERR:
Exception in thread "main" java.lang.RuntimeException: TEST FAILED: Number of memory managers = 4 but expected = 3
        at MemoryTest.checkMemoryManagers(MemoryTest.java:171)
        at MemoryTest.main(MemoryTest.java:100)
```

**To Reproduce**
```bash
jtreg test/jdk/java/lang/management/MemoryMXBean/MemoryTestZGC.sh
```

The WhiteBox API ManagementFactory.getMemoryManagerMXBeans() return by dragonwell11:
![image](https://user-images.githubusercontent.com/24123821/172034362-125ece93-de5b-49be-ad99-1468aa729554.png)

The WhiteBox API ManagementFactory.getMemoryManagerMXBeans() return by temurin11:
![image](https://user-images.githubusercontent.com/24123821/172034416-8e54b2f3-7df0-4ebe-ba16-dea5efe4f36b.png)

**Expected behavior**
I think there is some diffrence between dragonwell11 and temurin return from ManagementFactory.getMemoryManagerMXBeans(), but it shoule not treat a bug.

**Screenshots**

**Additional context**
temurin11 version:
```
openjdk version "11.0.15" 2022-04-19
OpenJDK Runtime Environment Temurin-11.0.15+10 (build 11.0.15+10)
OpenJDK 64-Bit Server VM Temurin-11.0.15+10 (build 11.0.15+10, mixed mode)
```

draonwell11 version:
```
openjdk version "11.0.15.11" 2022-04-19
OpenJDK Runtime Environment (Alibaba Dragonwell)-11.0.15.11+9-GA (build 11.0.15.11+9)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell)-11.0.15.11+9-GA (build 11.0.15.11+9, mixed mode)
```

**Comment by sendaoYan** [comment]
> @sendaoYan The test has been added to alibaba problemlist. [openjdk/excludes/vendors/alibaba/ProblemList_openjdk11.txt](https://github.com/adoptium/aqa-tests/pull/3740/files#diff-fb1a3203e64d68a200c78fcfae69ce206930dce3013c3223f4f88eb355d566fe). For other tests not working with Alibaba and not being a bug similar steps can do done. Add to vendor's specific problemlist.txt in the same format as other problemlist files.

Thanks very much. But I have made a mistake for the testcase name, the fail testcase is MemoryTestZGC.sh but not MemoryTestAllGC.sh. Could you change the testcase name in [ProblemList_openjdk11.txt](https://github.com/adoptium/aqa-tests/pull/3740/files#diff-fb1a3203e64d68a200c78fcfae69ce206930dce3013c3223f4f88eb355d566fe).

**Comment by karianna** [comment]
> > @sendaoYan The test has been added to alibaba problemlist. [openjdk/excludes/vendors/alibaba/ProblemList_openjdk11.txt](https://github.com/adoptium/aqa-tests/pull/3740/files#diff-fb1a3203e64d68a200c78fcfae69ce206930dce3013c3223f4f88eb355d566fe). For other tests not working with Alibaba and not being a bug similar steps can do done. Add to vendor's specific problemlist.txt in the same format as other problemlist files.
> 
> @sophia-guo Thanks very much. But I have made a mistake for the testcase name, the fail testcase is MemoryTestZGC.sh but not MemoryTestAllGC.sh. Could you change the testcase name in [ProblemList_openjdk11.txt](https://github.com/adoptium/aqa-tests/pull/3740/files#diff-fb1a3203e64d68a200c78fcfae69ce206930dce3013c3223f4f88eb355d566fe).

I fixed that in the PR
