### ISSUE TITLE
openjdk tests are running all three modes on aarch64_alpine-linux

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3796]
Openjdk tests are running all three modes on aarch64_alpine-linux
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_sanity.openjdk_aarch64_alpine-linux/15/console

```
16:56:35  TEST TARGETS SUMMARY
16:56:35  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
16:56:35  PASSED test targets:
16:56:35  	jdk_math_0
16:56:35  	jdk_math_1
16:56:35  	jdk_math_2
16:56:35  	jdk_util_0
16:56:35  	jdk_util_1
16:56:35  	jdk_util_2
16:56:35  	jdk_jdi_jdk8_0
16:56:35  	jdk_jdi_jdk8_1
16:56:35  	jdk_jdi_jdk8_2
16:56:35  
16:56:35  FAILED test targets:
16:56:35  	jdk_lang_0
16:56:35  	jdk_lang_1
16:56:35  	jdk_lang_2
```

Mode1000 is for 32 bit only. @renfeiw should ottawa.csv need to be updated? Feel free to transfer the issue to TKG repo if that is the case.

**Comment by renfeiw** [comment]
I think it is the issue, which column should we copy for the value. linux_aarch64? @llxia

**Comment by llxia** [comment]
We should add default value for Mode150, Mode650, and Mode1000.

**Comment by sophia-guo** [comment]
I think we should we use alpine-linux_aarch64 instead of aarch64_apline-linux in ottawa.csv? The PR https://github.com/adoptium/TKG/pull/332 is in for a while I can still see all modes are running on aarch64_alpine-linux. 
July 3rd jenkins job https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.openjdk_aarch64_alpine-linux/28/tapResults/

https://github.com/adoptium/TKG/blob/f573007d7be53b2212d916912b6ba329552d414b/resources/buildPlatformMap.properties#L17

**Comment by renfeiw** [comment]
PR: https://github.com/adoptium/TKG/pull/334

**Comment by sophia-guo** [comment]
Fixed.
