### ISSUE TITLE
jdk11/17/19 alpine-linux test jobs all hanging

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#3799]
eg.https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.system_aarch64_alpine-linux/
end of example log:
```
05:35:13  
05:35:13  build-java:
05:35:13      [javac] Compiling 2 source files to /home/jenkins/workspace/Test_openjdk11_hs_extended.system_aarch64_alpine-linux/aqa-tests/system/aqa-systemtest/openjdk.test.jck/bin
...
```

**Comment by andrew-m-leonard** [comment]
There are many hung old test jobs on all the alpine nodes, I will try and remove them

**Comment by andrew-m-leonard** [comment]
I've cleaned the hung old jobs, re-submitted a test job: https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.openjdk_aarch64_alpine-linux/13/

**Comment by andrew-m-leonard** [comment]
Another hang, x64 this time: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk19/job/jdk19-alpine-linux-x64-temurin_SmokeTests/6/console

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3799#issuecomment-1170954910, that job appears to do a full thread dump and fails to compile the test material.  Snippet from console:

```
05:37:01  2022-06-30 09:21:41
05:37:01  Full thread dump OpenJDK 64-Bit Server VM (19-beta+28-202206300341 mixed mode, sharing):
05:37:01  
05:37:01  Threads class SMR info:
05:37:01  _java_thread_list=0x00007ff3b2fd7f90, length=11, elements={
05:37:01  0x00007ff3cdc4d010, 0x00007ff3cdc4e990, 0x00007ff3b84ee030, 0x00007ff3b84ee6b0,
05:37:01  0x00007ff3b84eed20, 0x00007ff3b84ef3b0, 0x00007ff3b84ef9b0, 0x00007ff3b84df050,
05:37:01  0x00007ff3b84df6c0, 0x00007ff3b84dfcf0, 0x00007ff3b84e0340
05:37:01  }
...
...
05:46:13  143
05:46:13  make[1]: *** [compile.mk:45: compile] Error 1
05:46:13  make[1]: Leaving directory '/home/jenkins/workspace/build-scripts/jobs/jdk19/jdk19-alpine-linux-x64-temurin_SmokeTests/aqa-tests/TKG'
05:46:13  make: *** [makefile:67: compile] Error 2
```

**Comment by smlambert** [comment]
Have these been observed lately?

**Comment by smlambert** [comment]
This problem has not been seen in a long while, so closing it.
