### ISSUE TITLE
Failed to copy artifacts from ..jdk11u-linux-s390x-temurin with filter: workspace/target/AQATestTaps/*.tap

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#3800]
Build pipelines failing as no AQATestTaps and copyArtifact is not optional
https://ci.adoptopenjdk.net/view/Failing%20Temurin%20jobs/job/build-scripts/job/openjdk11-pipeline/1995/console
```
05:15:23  Copied 0 artifacts from "[build-scripts » jobs » jdk11u » jdk11u-linux-s390x-temurin](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-temurin/)" build number [66](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-temurin/66/)
[Pipeline] }
[Pipeline] // timeout
[Pipeline] }
05:15:23  ERROR: Failed to copy artifacts from build-scripts/jobs/jdk11u/jdk11u-linux-s390x-temurin with filter: workspace/target/AQATestTaps/*.tap
[Pipeline] // catchError
[Pipeline] }
```

**Comment by sophia-guo** [comment]
This should be fixed by https://github.com/adoptium/ci-jenkins-pipelines/pull/336

**Comment by sophia-guo** [comment]
Close this one. The new builds are good. https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2001/console. The reason for without any aritifacts should be fixed by  https://github.com/adoptium/ci-jenkins-pipelines/pull/341
