### ISSUE TITLE
jdk17+ : jdk/jfr/event/gc/detailed/TestGCLockerEvent.java timeout on windows

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3817]
https://ci.adoptopenjdk.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0/49/testReport/junit/jdk_jfr_event_gc_detailed_TestGCLockerEvent/java/TestGCLockerEvent/

Stacktrace
Program `E:\jenkins\workspace\Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0\openjdkbinary\j2sdk-image\bin\java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960256ms).    
Standard Output
Timeout refired 960 times
    
Standard Error

**Comment by smlambert** [comment]
That link is now stale.  When possible, issues should be created with Re-run links to aid in the assignment of the issue to others.  (related: https://github.com/adoptium/aqa-tests/blob/master/.github/ISSUE_TEMPLATE/bug_report.md and https://github.com/adoptium/aqa-tests/issues/3793)

**Comment by sophia-guo** [comment]
Didn't see the error in recent run, close it. https://github.com/adoptium/aqa-tests/issues/4352#issuecomment-1915204757
