### ISSUE TITLE
[Solaris]: [exec] error: unknown option `reference-if-able'git clone --depth 1 -q --reference-if-able 

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#3831]
Recent sparcv9_solaris and x86-64_solaris openjdk tests failed when git clone openjdk repo with error message:

```
18:45:20  getOpenjdk:
18:45:20       [echo]  Using user specified repo and branch
18:45:20       [exec] error: unknown option `reference-if-able'git clone --depth 1 -q --reference-if-able /export/home/jenkins//openjdk_cache -b dev https://github.com/adoptium/jdk8u openjdktemp
18:45:20       [exec] 
18:45:20       [exec] usage: git clone [options] [--] <repo> [<dir>]error code: 129. Sleep 300 secs, then retry 1...
18:45:20       [exec] 
18:45:20       [exec] 
18:45:20       [exec]     -v, --verbose         be more verbose
18:45:20       [exec]     -q, --quiet           be more quiet
```

https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_0/38/console
https://ci.adoptopenjdk.net/job/Test_openjdk8_hs_extended.openjdk_x86-64_solaris_testList_0/35/consoleFull

**Comment by sophia-guo** [comment]
https://github.com/adoptium/aqa-tests/pull/3789

If it's the git version issue? @sxa what's the git version on solaris sparcv9?

**Comment by sxa** [comment]
> what's the git version on solaris_x86-64 and solaris_sparcv9?

Looks like it's 2.3.1 that comes from the CSW repositories

**Comment by sxa** [comment]
@steelhead31 How do you fancy picking up a Solaris issue? ;-) Likely needs git to be compiled from source, which could be a bit of a rabbit hole ;-) Looks like the GIT_Source role is being skipped even when run through VPC for some reason that isn't immediately apparent.

**Comment by steelhead31** [comment]
@sxa  can you assign this one to me, I cant do it in this repository

**Comment by steelhead31** [comment]
@sophia-guo  I believe this has now been fixed.

**Comment by llxia** [comment]
@sophia-guo could you confirm if we can close this issue? Thanks

**Comment by sophia-guo** [comment]
Fixed. Close it.
