### ISSUE TITLE
jdk-11.0.16+8 Release Triage

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3868]
Jenkins build pipeline ID: https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2028/

Result summary (Failed/Passed/Disabled/Skipped/Total): 

Link to the TRSS Grid view of the pipeline: https://trss.adoptium.net/resultSummary?parentId=62d71586250c3c428c9e2196

Link to table of failed test targets from TRSS: 

Copy & paste table of failed test targets:

#### Release Summary Report for openjdk11-pipeline 
**Report generated at:** Wed, 20 Jul 2022 10:26:01 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=62d71586250c3c428c9e2196&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=62d71586250c3c428c9e2196) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2028/ 
Started by user sophia-guo at 19/07/2022, 21:23:33 

 --- 

[**create_installer_mac**](undefined) ❌ undefined ❌

[**create_installer_windows**](undefined) ❌ undefined ❌

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

[**sign_temurin_gpg**](undefined) ❌ undefined ❌

 --- 

**Problem Platforms**

x86-64_alpine-linux ✅ 
aarch64 mac ✅ 
ppc64 aix ✅ 
x86-64 linux ✅ 
x86-64 mac✅ 

[**Test_openjdk11_hs_extended.functional_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-64_alpine-linux/107/) ❌ ABORTED ❌ ✅ 

see https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190170394

[**Test_openjdk11_hs_extended.openjdk_aarch64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_mac/18/) ❌ FAILURE ❌

[**Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_0/18/) ❌ FAILURE ❌
[jdk_nio_0](https://trss.adoptium.net/output/test?id=62d7d4f9250c3c428ca02918) => [deep history 4/6 passed](https://trss.adoptium.net/deepHistory?testId=62d7d4f9250c3c428ca02918) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d7d43d250c3c428ca0285b&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_0&testId=62d7d4f9250c3c428ca02918&testName=jdk_nio_0)

[**Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_1/18/) ❌ FAILURE ❌
[jdk_nio_1](https://trss.adoptium.net/output/test?id=62d7d4f1250c3c428ca028f6) => [deep history 4/6 passed](https://trss.adoptium.net/deepHistory?testId=62d7d4f1250c3c428ca028f6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d7d43d250c3c428ca0285a&buildName=Test_openjdk11_hs_extended.openjdk_aarch64_mac_testList_1&testId=62d7d4f1250c3c428ca028f6&testName=jdk_nio_1)

[**Test_openjdk11_hs_extended.openjdk_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix/75/) ⚠️ UNSTABLE ⚠️ ✅ 

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190184056

[**Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_0/49/) ⚠️ UNSTABLE ⚠️ ✅
[jdk_build_1](https://trss.adoptium.net/output/test?id=62d7c61b250c3c428ca001ff) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d7c61b250c3c428ca001ff) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d7c56f250c3c428c9ffeae&buildName=Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_0&testId=62d7c61b250c3c428ca001ff&testName=jdk_build_1)

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190184056

[**Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_2/49/) ⚠️ UNSTABLE ⚠️ ✅
[jdk_build_0](https://trss.adoptium.net/output/test?id=62d7c622250c3c428ca00230) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d7c622250c3c428ca00230) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d7c56f250c3c428c9ffeaf&buildName=Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_2&testId=62d7c622250c3c428ca00230&testName=jdk_build_0)

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190184056

[**Test_openjdk11_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux/82/) ⚠️ UNSTABLE ⚠️  ✅ 

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190192703

[**Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0/52/) ⚠️ UNSTABLE ⚠️ ✅ 
[jvm_compiler_1](https://trss.adoptium.net/output/test?id=62d78171250c3c428c9efe5d) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d78171250c3c428c9efe5d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d78032250c3c428c9ef37a&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_0&testId=62d78171250c3c428c9efe5d&testName=jvm_compiler_1)

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190192703

[**Test_openjdk11_hs_extended.openjdk_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/86/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_0/56/) ⚠️ UNSTABLE ⚠️
[jdk_net_0](https://trss.adoptium.net/output/test?id=62d785e0250c3c428c9f1618) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d785e0250c3c428c9f1618) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d784db250c3c428c9f0f53&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_0&testId=62d785e0250c3c428c9f1618&testName=jdk_net_0)
[jvm_compiler_1](https://trss.adoptium.net/output/test?id=62d785e0250c3c428c9f162c) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d785e0250c3c428c9f162c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d784db250c3c428c9f0f53&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_mac_testList_0&testId=62d785e0250c3c428c9f162c&testName=jvm_compiler_1)

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190217628

[**Test_openjdk11_hs_sanity.perf_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-64_alpine-linux/110/) ❌ ABORTED ❌ ✅ 

See https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1190189355

**Comment by sophia-guo** [comment]
[Test_openjdk11_hs_extended.functional_x86-64_alpine-linux](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-64_alpine-linux/107/) timeout 

rerun
https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.functional_x86-64_alpine-linux/108/

**Comment by Haroon-Khel** [comment]
[**Test_openjdk11_hs_extended.openjdk_ppc64_aix**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix/75/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_0**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_0/49/) ⚠️ UNSTABLE ⚠️
[jdk_build_1](https://trss.adoptium.net/output/test?id=62d7c61b250c3c428ca001ff) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d7c61b250c3c428ca001ff) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d7c56f250c3c428c9ffeae&buildName=Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_0&testId=62d7c61b250c3c428ca001ff&testName=jdk_build_1)

[**Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_2/49/) ⚠️ UNSTABLE ⚠️
[jdk_build_0](https://trss.adoptium.net/output/test?id=62d7c622250c3c428ca00230) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=62d7c622250c3c428ca00230) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=62d7c56f250c3c428c9ffeaf&buildName=Test_openjdk11_hs_extended.openjdk_ppc64_aix_testList_2&testId=62d7c622250c3c428ca00230&testName=jdk_build_0)

**Comment by Haroon-Khel** [comment]
[**Test_openjdk11_hs_sanity.perf_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-64_alpine-linux/110/) ❌ ABORTED ❌

Rerunning https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.perf_x86-64_alpine-linux/111/console

**Comment by sophia-guo** [comment]
All issues are under investigation..

**Comment by sophia-guo** [comment]
window64 [with](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2029/ )

 #### Release Summary Report for openjdk11-pipeline 
**Report generated at:** Wed, 20 Jul 2022 20:15:40 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=62d7efc2250c3c428ca02b26&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=62d7efc2250c3c428ca02b26) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk11-pipeline/2029/ 
Started by user George Adams at 7/20/2022, 7:55:05 AM 

 --- 

[**create_installer_windows**](undefined) ❌ undefined ❌

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

[**sign_temurin_gpg**](undefined) ❌ undefined ❌

 ---

**Comment by sophia-guo** [comment]
All good.

**Comment by Haroon-Khel** [comment]
Tap files for each test job of the jdk-11.0.16+8 pipeline

[aarch64_linuxAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160777/aarch64_linuxAQAvitTaps.zip)
[aarch64_macAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160778/aarch64_macAQAvitTaps.zip)
[arm_linuxAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160779/arm_linuxAQAvitTaps.zip)
[ppc64_aixAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160780/ppc64_aixAQAvitTaps.zip)
[ppc64le_linuxAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160781/ppc64le_linuxAQAvitTaps.zip)
[s390x_linuxAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160782/s390x_linuxAQAvitTaps.zip)
[x86-32_windowsAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160783/x86-32_windowsAQAvitTaps.zip)
[x86-64_alpine-linuxAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160784/x86-64_alpine-linuxAQAvitTaps.zip)
[x86-64_linuxAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160785/x86-64_linuxAQAvitTaps.zip)
[x86-64_macAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160786/x86-64_macAQAvitTaps.zip)
[x86-64_windowsAQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9160787/x86-64_windowsAQAvitTaps.zip)

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/3868#issuecomment-1191649585, thanks @Haroon-Khel !
