### ISSUE TITLE
jck runner launched agent needs larger stack on AIX for vm/jdwp testcases

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#3929]
When running jck tests manually I found some hung repeatedly with typical output of:
```
<testcase> has timed out and is not responding after 38,000 interrupts
....
```

Launching the agent with -Xmx1024m seems to prevent this hang.

Also worth noting once one hung like that the Agent seem to get stuck!

Similar hang loops like this have been seen on other platforms/tests, so possibly worth changing generally?

**Comment by andrew-m-leonard** [comment]
So what seemed to work run manually, seems still to fail via jenkins:
```
18:32:01  Starting sub-process: com.sun.javatest.agent.AgentMain
18:32:01  Full command: [/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java, -Xmx1024m, -Djavatest.security.allowPropertiesAccess=true, -Djava.security.policy=/home/jenkins/jck_root/JCK11-unzipped/JCK-runtime-11/lib/jck.policy, -classpath, /home/jenkins/jck_root/JCK11-unzipped/JCK-runtime-11/lib/javatest.jar:/home/jenkins/jck_root/JCK11-unzipped/JCK-runtime-11/classes, com.sun.javatest.agent.AgentMain, -passive]
18:32:01  Running JCK in multijvm way with Agent off
18:32:01  Starting sub-process: jck
18:32:01  Full command: [/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/java, -jar, /home/jenkins/jck_root/JCK11-unzipped/JCK-runtime-11/lib/javatest.jar, -config, /home/jenkins/workspace/Grinder/aqa-tests/TKG/../jck/jtrunner/config/jck11/runtime.jti,  @/home/jenkins/workspace/Grinder/aqa-tests/TKG/output_16613623558705/jck-runtime-vm-jdwp_0/JTB/generated.jtb]
18:32:02  Aug 24, 2022, 5:32:37 PM Harness starting test run with configuration "jck_runtime"...
18:46:01  Test vm/jdwp/Method/Bytecodes/bytecodes002/bytecodes002.html has timed out and is not responding after 1,000 interrupts
18:47:44  Test vm/jdwp/Method/Bytecodes/bytecodes002/bytecodes002.html has timed out and is not responding after 2,000 interrupts
18:49:12  Test vm/jdwp/Method/Bytecodes/bytecodes002/bytecodes002.html has timed out and is not responding after 3,000 interrupts
18:50:56  Test vm/jdwp/Method/Bytecodes/bytecodes002/bytecodes002.html has timed out and is not responding after 4,000 interrupts
```

**Comment by andrew-m-leonard** [comment]
Trying various re-runs manually, and I think I must have just been lucky with the several test runs I did with -Xmx1024m, as today even with that I am getting random hangs running manually.

**Comment by andrew-m-leonard** [comment]
I have a suspicion this might be a combination of two things:
1) An intermittent issue running vm/jdwp tests that causes them to hang/timeout
2) An upstream timing issue with https://github.com/openjdk/jtharness/blob/master/src/com/sun/javatest/TestResult.java when such a (1) timeout occurs, resulting in the AgentMain process becoming un-responsive

**Comment by smlambert** [comment]
Should we keep this issue open, or is it now determined to be an "elsewhere" problem?

**Comment by andrew-m-leonard** [comment]
I believe the problem is elsewhere... from my testing, as to where... it's not conclusive!
