### ISSUE TITLE
AQAvit Meeting: Sept 7, 2022

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#3930]
Join via https://bluejeans.com/917304424

This meeting is part of the public [Adoptium community calendar](https://calendar.google.com/calendar/embed?src=c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com), if you wish to import the calendar use this [link](https://calendar.google.com/calendar/ical/c_uannoums5ho0olhjk3ulecdkbc%40group.calendar.google.com/public/basic.ics)

**Proposed Agenda**:
- Project review
  - Close out [August plan](https://github.com/orgs/adoptium/projects/14/views/4)
  - Review items in [September plan](https://github.com/orgs/adoptium/projects/18/views/4)
- AOB

**Comment by d3r3kk** [comment]
@smlambert I don't see a ticket for the Sept. 21st community meeting?

I'd love to discuss next steps for including Annie's work in the TRSS at the next meeting, if time allows! ;)

**Comment by smlambert** [comment]
hi @d3r3kk - I've put a note in the channel today, as many are travelling we will not have a regularly scheduled meeting to discuss that work.  We will have to organize something off schedule.  I should be back in Canada next week and will plan to book something with you, @JL03-Yue and @llxia.  As the branch stands right now, we would not be able to merge it (it would break our current approach).  The 4 of us can chat (as you'd originally requested), then bring it to the broader call after.
