### ISSUE TITLE
JDK 18.0.2.1+1 Release Triage

### ISSUE THREAD

**Issue by Haroon-Khel** [adoptium/aqa-tests#3940]
SL/Aug26: removed aarch64_windows from this report as that platform is not yet supported

#### Release Summary Report for openjdk18-pipeline 
**Report generated at:** Fri, 26 Aug 2022 11:53:45 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=6307aa7d93ac60470bed7072&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=6307aa7d93ac60470bed7072) 
Jenkins Build URL https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk18-pipeline/250/ 
Started by user Stewart X Addison at 8/25/2022, 12:53:28 PM 

 --- 

[**Test_Job_Auto_Gen**](https://ci.adoptopenjdk.net/job/Test_Job_Auto_Gen/658/) ❌ FAILURE ❌

[**jdk18u-linux-arm-temurin_SmokeTests**](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk18u/job/jdk18u-linux-arm-temurin_SmokeTests/57/) ❌ FAILURE ❌

 --- 

[**Test_openjdk18_hs_extended.openjdk_aarch64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_mac/39/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_aarch64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_mac_testList_1/36/) ⚠️ UNSTABLE ⚠️
[jdk_net_1](https://trss.adoptium.net/output/test?id=63082d1893ac60470befaec2) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=63082d1893ac60470befaec2) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63082ba293ac60470befa00a&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_mac_testList_1&testId=63082d1893ac60470befaec2&testName=jdk_net_1)

[**Test_openjdk18_hs_extended.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux/43/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1/41/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_arm_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_2/40/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux/41/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2/39/) ⚠️ UNSTABLE ⚠️
[jdk_nio_0](https://trss.adoptium.net/output/test?id=6308049993ac60470bee9f28) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=6308049993ac60470bee9f28) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6308033e93ac60470bee8fe6&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2&testId=6308049993ac60470bee9f28&testName=jdk_nio_0)

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac/48/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1/47/) ⚠️ UNSTABLE ⚠️
[jdk_net_1](https://trss.adoptium.net/output/test?id=6307ed5693ac60470bee1b52) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=6307ed5693ac60470bee1b52) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6307ec5a93ac60470bee16cd&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1&testId=6307ed5693ac60470bee1b52&testName=jdk_net_1)

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows/48/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1/46/) ⚠️ UNSTABLE ⚠️
[jdk_io_0](https://trss.adoptium.net/output/test?id=63084d8593ac60470bf0ae7d) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=63084d8593ac60470bf0ae7d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63084bd693ac60470bf09bd0&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1&testId=63084d8593ac60470bf0ae7d&testName=jdk_io_0)

[**Test_openjdk18_hs_extended.system_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.system_arm_linux/142/) ❌ FAILURE ❌

[**Test_openjdk18_hs_sanity.functional_aarch64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.functional_aarch64_alpine-linux/44/) ⚠️ UNSTABLE ⚠️
Rerun [all](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=&amp;TARGET=sanity.functional&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_alpine-linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.4.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk18u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-alpine-linux-aarch64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-18.0.2.1%2B1_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=64&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
```
</details>

[cmdLineTester_libpathTestRtfChild_0](https://trss.adoptium.net/output/test?id=63083bb893ac60470bf01d48) => [deep history 0/17 passed](https://trss.adoptium.net/deepHistory?testId=63083bb893ac60470bf01d48) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63083a7b93ac60470bf00ce3&buildName=Test_openjdk18_hs_sanity.functional_aarch64_alpine-linux&testId=63083bb893ac60470bf01d48&testName=cmdLineTester_libpathTestRtfChild_0)

[**Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux/143/) ⚠️ UNSTABLE ⚠️
Rerun [all](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=&amp;TARGET=sanity.functional&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_alpine-linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.4.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk18u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-alpine-linux-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-18.0.2.1%2B1_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=97&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
```
</details>

[cmdLineTester_libpathTestRtfChild_0](https://trss.adoptium.net/output/test?id=630805aa93ac60470beea444) => [deep history 0/16 passed](https://trss.adoptium.net/deepHistory?testId=630805aa93ac60470beea444) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6308041c93ac60470bee98a1&buildName=Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux&testId=630805aa93ac60470beea444&testName=cmdLineTester_libpathTestRtfChild_0)

[**Test_openjdk18_hs_sanity.perf_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.perf_arm_linux/142/) ❌ FAILURE ❌

[**Test_openjdk18_hs_sanity.perf_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.perf_x86-64_linux/137/) ❌ FAILURE ❌

**Comment by Haroon-Khel** [comment]
[**Test_openjdk18_hs_extended.openjdk_x86-64_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux/41/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2/39/) ⚠️ UNSTABLE ⚠️
[jdk_nio_0](https://trss.adoptium.net/output/test?id=6308049993ac60470bee9f28) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=6308049993ac60470bee9f28) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6308033e93ac60470bee8fe6&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_linux_testList_2&testId=6308049993ac60470bee9f28&testName=jdk_nio_0)

**Comment by Haroon-Khel** [comment]
Arm linux 

[**Test_openjdk18_hs_extended.openjdk_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux/43/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_1/41/) ❌ FAILURE ❌

[**Test_openjdk18_hs_extended.openjdk_arm_linux_testList_2**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_arm_linux_testList_2/40/) ❌ FAILURE ❌

Rerunning extended openjdk https://ci.adoptopenjdk.net/job/Grinder/5499/console

[**Test_openjdk18_hs_extended.perf_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.perf_arm_linux/42/) ❌ FAILURE ❌

Rerunning extended perf https://ci.adoptopenjdk.net/job/Grinder/5500/console

[**Test_openjdk18_hs_extended.system_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.system_arm_linux/142/) ❌ FAILURE ❌

Rerunning extended system https://ci.adoptopenjdk.net/job/Grinder/5501/console

[**Test_openjdk18_hs_sanity.perf_arm_linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.perf_arm_linux/142/) ❌ FAILURE ❌

Rerunning sanity perf https://ci.adoptopenjdk.net/job/Grinder/5502/console

**Comment by Haroon-Khel** [comment]
x64 Mac

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac/48/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1/47/) ⚠️ UNSTABLE ⚠️
[jdk_net_1](https://trss.adoptium.net/output/test?id=6307ed5693ac60470bee1b52) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=6307ed5693ac60470bee1b52) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6307ec5a93ac60470bee16cd&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_mac_testList_1&testId=6307ed5693ac60470bee1b52&testName=jdk_net_1)

**Comment by Haroon-Khel** [comment]
x64 Windows

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows/48/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1/46/) ⚠️ UNSTABLE ⚠️
[jdk_io_0](https://trss.adoptium.net/output/test?id=63084d8593ac60470bf0ae7d) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=63084d8593ac60470bf0ae7d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63084bd693ac60470bf09bd0&buildName=Test_openjdk18_hs_extended.openjdk_x86-64_windows_testList_1&testId=63084d8593ac60470bf0ae7d&testName=jdk_io_0)

**Comment by smlambert** [comment]
aarch64_alpine-linux ✅
- known non-blocking issue, check why exclusion has not been ported to the openj9 branch defined in the testenv.properties file of the 0.9.4.1-release branch (related: https://github.com/eclipse-openj9/openj9/pull/15486/) 

[**Test_openjdk18_hs_sanity.functional_aarch64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.functional_aarch64_alpine-linux/44/) ⚠️ UNSTABLE ⚠️
Rerun [all](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=&amp;TARGET=sanity.functional&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_alpine-linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.4.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk18u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-alpine-linux-aarch64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-18.0.2.1%2B1_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=64&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
```
</details>

[cmdLineTester_libpathTestRtfChild_0](https://trss.adoptium.net/output/test?id=63083bb893ac60470bf01d48) => [deep history 0/17 passed](https://trss.adoptium.net/deepHistory?testId=63083bb893ac60470bf01d48) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63083a7b93ac60470bf00ce3&buildName=Test_openjdk18_hs_sanity.functional_aarch64_alpine-linux&testId=63083bb893ac60470bf01d48&testName=cmdLineTester_libpathTestRtfChild_0)

**Comment by Haroon-Khel** [comment]
aarch64 mac

[**Test_openjdk18_hs_extended.openjdk_aarch64_mac**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_mac/39/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk18_hs_extended.openjdk_aarch64_mac_testList_1**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_extended.openjdk_aarch64_mac_testList_1/36/) ⚠️ UNSTABLE ⚠️
[jdk_net_1](https://trss.adoptium.net/output/test?id=63082d1893ac60470befaec2) => [deep history 5/6 passed](https://trss.adoptium.net/deepHistory?testId=63082d1893ac60470befaec2) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=63082ba293ac60470befa00a&buildName=Test_openjdk18_hs_extended.openjdk_aarch64_mac_testList_1&testId=63082d1893ac60470befaec2&testName=jdk_net_1)

**Comment by smlambert** [comment]
x86-64_alpine-linux  ✅
- known non-blocking issue, check why exclusion has not been ported to the openj9 branch defined in the testenv.properties file of the 0.9.4.1-release branch (related: https://github.com/eclipse-openj9/openj9/pull/15486/) 


[**Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux**](https://ci.adoptopenjdk.net/job/Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux/143/) ⚠️ UNSTABLE ⚠️
Rerun [all](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=&amp;TARGET=sanity.functional&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_alpine-linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.4.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=18&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk18u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk18u%2Fjdk18u-alpine-linux-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-18.0.2.1%2B1_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=functional&amp;UPSTREAM_JOB_NUMBER=97&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "18.0.2.1" 2022-08-18
OpenJDK Runtime Environment Temurin-18.0.2.1+1 (build 18.0.2.1+1)
OpenJDK 64-Bit Server VM Temurin-18.0.2.1+1 (build 18.0.2.1+1, mixed mode, sharing)
```
</details>

[cmdLineTester_libpathTestRtfChild_0](https://trss.adoptium.net/output/test?id=630805aa93ac60470beea444) => [deep history 0/16 passed](https://trss.adoptium.net/deepHistory?testId=630805aa93ac60470beea444) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6308041c93ac60470bee98a1&buildName=Test_openjdk18_hs_sanity.functional_x86-64_alpine-linux&testId=630805aa93ac60470beea444&testName=cmdLineTester_libpathTestRtfChild_0)

**Comment by smlambert** [comment]
All platforms are completed, last task to do before closing this issue is to gather TAP files.

**Comment by Haroon-Khel** [comment]
[windows_x86-64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785181/windows_x86-64_AQAvitTaps.zip)
[windows_x86-32_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785182/windows_x86-32_AQAvitTaps.zip)
[mac_aarch64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785183/mac_aarch64_AQAvitTaps.zip)
[mac_x64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785184/mac_x64_AQAvitTaps.zip)
[linux_s390x_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785185/linux_s390x_AQAvitTaps.zip)
[linux_ppc64le_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785186/linux_ppc64le_AQAvitTaps.zip)
[linux_arm_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785187/linux_arm_AQAvitTaps.zip)
[linux_aarch64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785188/linux_aarch64_AQAvitTaps.zip)
[linux_x64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785189/linux_x64_AQAvitTaps.zip)
[alpine-linux_aarch64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785190/alpine-linux_aarch64_AQAvitTaps.zip)
[alpine-linux_x64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785191/alpine-linux_x64_AQAvitTaps.zip)
[aix_ppc64_AQAvitTaps.zip](https://github.com/adoptium/aqa-tests/files/9785192/aix_ppc64_AQAvitTaps.zip)
