### ISSUE TITLE
Set default USE_TESTENV_PROPERTIES value to false

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#3959]
https://github.com/adoptium/aqa-tests/blob/53127a9ac659fe1d32706fdace5d3b5c9a37faa4/buildenv/jenkins/aqaTestPipeline.groovy#L7

This means USE_TESTENV_PROPERTIES will be true regardless. We should set the default USE_TESTENV_PROPERTIES value to false.

Related: https://github.com/adoptium/aqa-tests/pull/3941#issuecomment-1242169027

**Comment by julian55455** [comment]
Hi @smlambert  I would like to work on this
