### ISSUE TITLE
upstream_openjdk_tests Jenkinsfile is no longer used

### ISSUE THREAD

**Issue by jerboaa** [adoptium/aqa-tests#3963]
OpenJDK Project Builds have since been retired
and `upstream_openjdk_tests` Jenkins file was used
to facilitate testing (via aqa-tests) of those builds.

The Job using this file is here (it needs to get removed):
https://ci.adoptopenjdk.net/view/Test_upstream/job/UpstreamAutotest

**Comment by jerboaa** [comment]
After this, the entire view `Test_upstream` can be removed:
https://ci.adoptopenjdk.net/view/Test_upstream/

**Comment by smlambert** [comment]
I have additionally removed the related jobs and Jenkins tab/view.

**Comment by jerboaa** [comment]
Thank you!
