### ISSUE TITLE
Failures reported in a grinder appears to be exaggerated

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#3974]
**Describe the bug**
The number of failures reported in a grinder appears to be exaggerated.
When examining the console output https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_7/477 only seems to have a single failure, but the "TAP Stream Results" and "Test Result" report 2 failures.

[consoleText.txt](https://github.com/adoptium/aqa-tests/files/9601917/consoleText.txt)

**To Reproduce**
I used the following grinder, but the failure itself is intermittent and may or may not occur.
https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/parambuild/?TARGET=jdk_custom&SDK_RESOURCE=nightly&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Grinder&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=30&EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&VENDOR_TEST_DIRS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=true&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=2&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=https%3A%2F%2Fopenj9-artifactory.osuosl.org%2Fartifactory%2Fci-openj9%2FBuild_JDK%24%7BJDK_VERSION%7D_%24%7BPLATFORM%7D_Nightly%2F&DAYS_TO_KEEP=20&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&ARTIFACTORY_SERVER=na.artifactory.swg-devops&USE_JRE=false&KEEP_WORKSPACE=false&CURL_OPTS=&JDK_VERSION=11&USER_CREDENTIALS_ID=&DOCKER_REGISTRY_URL=&ITERATIONS=20&VENDOR_TEST_REPOS=&JCK_GIT_BRANCH=master&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=git%40github.ibm.com%3Aruntimes%2FJCKnext-unzipped.git&RELEASE_TAG=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&CUSTOM_TARGET=sun%2Fsecurity%2Fssl%2FSSLSocketImpl%2FSSLSocketLeak.java&DEBUG_IMAGES_REQUIRED=false&CODE_COVERAGE=false&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=ci.project.openj9&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=27803&DOCKERIMAGE_TAG=nightly&JDK_IMPL=openj9&TEST_TIME=&SSH_AGENT_CREDENTIAL=83181e25-eea4-4f55-8b3e-e79615733226&AUTO_DETECT=true&SLACK_CHANNEL=%23rt-jenkins&DYNAMIC_COMPILE=true&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&TRSS_URL=http%3A%2F%2Ftrss1.fyre.ibm.com&OPENJDK_SHA=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&BUILDS_TO_KEEP=60&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None

**Expected behavior**
The number of failures reported should be the same as actually occurred.

**Screenshots**
![image](https://user-images.githubusercontent.com/18122812/191102258-a57581ae-1bd3-42ac-aaef-67981342fb20.png)
![image](https://user-images.githubusercontent.com/18122812/191102376-95f5b55c-5879-4976-a55d-551b8f85cf67.png)

**Comment by llxia** [comment]
It looks like we have two copies of the same TAP file. One is under aqa-tests/TKG/output_16636148928013 and the other one is under jvmtest/TKG/output_16636148928013.

[aqa-tests/TKG/output_16636148928013/Grinder_iteration_7_20220919190813.tap](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_7/477/artifact/aqa-tests/TKG/output_16636148928013/Grinder_iteration_7_20220919190813.tap/*view*/)
[jvmtest/TKG/output_16636148928013/Grinder_iteration_7_20220919190813.tap](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_iteration_7/477/artifact/jvmtest/TKG/output_16636148928013/Grinder_iteration_7_20220919190813.tap/*view*/)

@renfeiw any idea why we have two copies?

**Comment by renfeiw** [comment]
The tap file in the jvmtest folder was copied from the previous iteration. This problem will solved when the latest TKG iteration work is done. Related issue: https://github.com/adoptium/TKG/issues/352

**Comment by llxia** [comment]
Yes, we can also see this from collected TAP files. 39 TAP files were captured for 20 iterations. The 20 TAP files under aqa-tests/TKG were from the real runs. The 19 TAP files under jvmtest/TKG were copies from the previous iteration.

![image](https://user-images.githubusercontent.com/19273206/191363782-c29bdb80-076f-42be-ab1a-24926a1d953f.png)

**Comment by llxia** [comment]
While waiting for https://github.com/adoptium/TKG/issues/352, I am wondering if we can exclude `jvmtest` folder.
