### ISSUE TITLE
Debug image loaded when not requested?

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#3985]
**Describe the bug**
Not that it matters too much, just happened to notice the grinder loaded the debug image (when using a nightly build), although debug image is disabled.
https://openj9-jenkins.osuosl.org/job/Grinder/1292/console
`--debug_images_required false`
```
15:28:41  _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks  https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Build_JDK19_s390x_linux_Nightly/77/debug-image.tar.gz
```

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by llxia** [comment]
Yes, this is a known issue. Due of https://github.com/adoptium/aqa-tests/issues/3957
