### ISSUE TITLE
jdk_svc_sanity and jdk_jdi has 32 duplicated testcases, which both include jdk_jdi_sanity

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#3993]
**Describe the bug**
jdk_svc_sanity and jdk_jdi has 32 duplicate testcases, which both include jdk_jdi_sanity

jdk_svc_sanity:

![image](https://user-images.githubusercontent.com/24123821/192280806-062baaa6-b50e-4a11-ba85-92cd97ea8068.png)

jdk_jdi:

![image](https://user-images.githubusercontent.com/24123821/192280925-a3544545-b642-4a88-b8ff-a4a1bbfe4475.png)

jdk_svc_sanity include jdk_jdi_sanity:

![image](https://user-images.githubusercontent.com/24123821/192277256-71057501-bd7d-4356-84d6-e9ea0263cf1e.png)

jdk_jdi_sanity:

![image](https://user-images.githubusercontent.com/24123821/192277449-3b072789-010e-4543-80b8-2d59e740c509.png)

jdk_jdi:

![image](https://user-images.githubusercontent.com/24123821/192282083-3ff9f4fa-b828-45e6-bd91-5e7e8d97dc57.png)

duplicate testcases:

[jdk_jdi_sanity.txt](https://github.com/adoptium/aqa-tests/files/9646353/jdk_jdi_sanity.txt)

**Expected behavior**
The sanity.openjdk and extended.openjdk test target has no any duplicate testcases.

**Comment by sendaoYan** [comment]
Mine solution: delete jdk_jdi_sanity in jdk_svc_sanity:

```diff
diff --git a/openjdk/playlist.xml b/openjdk/playlist.xml
index 9dd53626..5e71eac5 100644
--- a/openjdk/playlist.xml
+++ b/openjdk/playlist.xml
@@ -1442,7 +1442,11 @@
        -exclude:$(Q)$(TEST_RESROOT)$(D)$(PROBLEM_LIST_FILE)$(Q) \
        ${FEATURE_PROBLEM_LIST_FILE} \
        ${VENDOR_PROBLEM_LIST_FILE} \
-       $(Q)$(JTREG_JDK_TEST_DIR):jdk_svc_sanity$(Q); \
+       $(Q)$(JTREG_JDK_TEST_DIR):jdk_management_sanity$(Q) \
+       $(Q)$(JTREG_JDK_TEST_DIR):jdk_instrument_sanity(Q) \
+       $(Q)$(JTREG_JDK_TEST_DIR):jdk_jmx_sanity(Q) \
+       $(Q)$(JTREG_JDK_TEST_DIR):jdk_jfr_sanity(Q) \
+       $(Q)$(JTREG_JDK_TEST_DIR):svc_tools_sanity(Q); \
        $(TEST_STATUS)</command>
                <versions>
                        <version>11+</version>
```

**Comment by smlambert** [comment]
This approach seems reasonable.

**Comment by sophia-guo** [comment]
jdk_jfr_sanity( also a subset of jdk_svc_sanity) and jdk_jfr have the exactly same issue. We may need to open an issue for that too.

@sendaoYan Is there a way to do a minus jdk_jdi_sanity from jdk_jdi instead of minus jdk_jdi_sanity from jdk_svc_sanity? jdk_svc_sanity is part of sanity level. The solution of https://github.com/adoptium/aqa-tests/issues/3993#issuecomment-1259419584 will move jdk_jdi_sanity from sanity to extended. If the solution can keep the tests in same level that would be great.

**Comment by sendaoYan** [comment]
> jdk_jfr_sanity( also a subset of jdk_svc_sanity) and jdk_jfr have the exactly same issue. We may need to open an issue for that too.
> 
> @sendaoYan Is there a way to do a minus jdk_jdi_sanity from jdk_jdi instead of minus jdk_jdi_sanity from jdk_svc_sanity? jdk_svc_sanity is part of sanity level. The solution of [#3993 (comment)](https://github.com/adoptium/aqa-tests/issues/3993#issuecomment-1259419584) will move jdk_jdi_sanity from sanity to extended. If the solution can keep the tests in same level that would be great.

I have no idea how to minus jdk_jdi_sanity from jdk_jdi.
The solution of [#3993 (comment)](https://github.com/adoptium/aqa-tests/issues/3993#issuecomment-1259419584) is delete jdk_jdi_sanity from sanity. I think extended.openjdk may include some of the sanity test targets(jdk_jdi include jdk_jdi_sanity).
