### ISSUE TITLE
Update references to openjdk-test with aqa-tests in the buildenv/docker/README

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4004]
Search for the 3 places where openjdk-tests is used and replace with aqa-tests instead (in this file: https://github.com/adoptium/aqa-tests/blob/master/buildenv/docker/README.md)

**Comment by jabrena** [comment]
I will do later

**Comment by jabrena** [comment]
PR: https://github.com/adoptium/aqa-tests/pull/4008

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/aqa-tests/pull/4008
