### ISSUE TITLE
jtreg fail to excluded testcase when the case excluded twice and the first exclude condition is not match

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#4032]
**Describe the bug**
jtreg fail to excluded testcase when the case excluded twice and the first exclude condition not match

**To Reproduce**
Steps to reproduce the behavior (or Grinder rerun link):
```bash
jtreg -nr -w tmp -exclude:jdk-problemlist.txt -exclude:jdk11_tier1_buffer-list.txt -l test/jdk/java/nio/Buffer/EqualsCompareTest.java
```

![image](https://user-images.githubusercontent.com/24123821/195567505-825a6af7-9a9a-4e0f-bc3e-841954af41f5.png)

**Expected behavior**
The testcase "java/nio/Buffer/EqualsCompareTest.java" should be excluded?

**Screenshots**
![image](https://user-images.githubusercontent.com/24123821/195568789-3e17a5a7-b3a8-467b-89f4-ff10294d98cc.png)

![image](https://user-images.githubusercontent.com/24123821/195569254-0e3c1ddb-7e56-46ca-8c8e-5f7608aa6248.png)

**Comment by sophia-guo** [comment]
This is expected jtreg feature that if same testcase has been excluded twice the first one is overridden or ignored even if the exclude condition is different. ( exclude from different os-arch, or exclude for different reason - url).
