### ISSUE TITLE
Add jtreg doc link in openjdk/README.md

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4033]
It would be helpful if we provide jtreg doc https://openjdk.org/jtreg/command-help.html for some advanced users in openjdk/README.md. After https://github.com/adoptium/aqa-tests/blob/master/openjdk/README.md?plain=1#L17

**Comment by yukiyuli** [comment]
@llxia Can you please assign this to me? Thanks.

**Comment by llxia** [comment]
The change is delivered via https://github.com/adoptium/aqa-tests/pull/4036
