### ISSUE TITLE
Rerun in Grinder with failed test targets link does not capture all params

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4049]
**Describe the bug**
Rerun in Grinder with failed test targets link on test job does not capture all parameters info. For example, in https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_mac/96/ , Rerun in Grinder with failed test targets link only has params for SDK_RESOURCE and TARGET : `https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jvm_compiler_0%20,jdk_net_1`

It does not have all the params info and it will cause failure in Grinder: https://ci.adoptopenjdk.net/job/Grinder/5790/console

```
11:35:57  Exception: hudson.AbortException: Unable to find project for artifact copy: 
11:35:57  This may be due to incorrect project name or permission settings; see help for project name in job configuration.
```
Also, there is a space between tests in testList, which should be removed.

**Expected behavior**
It should capture all params same as [Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=extended.openjdk&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=11&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk11u%2Fjdk11u-mac-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=3&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=openjdk&UPSTREAM_JOB_NUMBER=132&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=Dynamic)

**Screenshots**
![image](https://user-images.githubusercontent.com/19273206/196476100-5b3795b3-2def-4968-8a57-d0a338b4caa2.png)

**Comment by momanmalik** [comment]
_"Rerun in Grinder with failed test targets:"_ returns incorrect TESTLIST. Observed in: https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk11_j9_sanity.functional_aarch64_linux/285/.


**current output:** `TARGET=testList+TESTLIST=stringConcatOptTest_0 (success rate: 0/3),stringConcatOptTest_1 (success rate: 0/3)`. 

**expected output example:**
`TARGET=testList+TESTLIST=jvm_compiler_0,jdk_net_1`

**Comment by llxia** [comment]
re https://github.com/adoptium/aqa-tests/issues/4049#issuecomment-1304169974, it is related to TKG_ITERATIONS. @renfeiw could you please take a look? Thanks

**Comment by smlambert** [comment]
Now that TKG#373 is merged we should verify that this issue can be closed.

**Comment by renfeiw** [comment]
It generated the correct target in my grinder: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/6208/ @momanmalik Could you please verify if this solves your issue?

**Comment by momanmalik** [comment]
@renfeiw The issue appears to be resolved on my end.
