### ISSUE TITLE
external test aot_test is running with no TEST_FLAG is set

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4062]
external test aot_test is setting with feature AOT, which means it should only run when TEST_FLAG is setting to AOT. However it runs with no TEST_FLAT is set

https://ci.adoptopenjdk.net/job/Test_openjdk11_hs_sanity.external_x86-64_linux/550/consoleFull

```
		<features>
			<feature>AOT:applicable</feature>
		</features>

```

@LongyuZhang is that expected?

**Comment by LongyuZhang** [comment]
For aot_test, we are testing the jdk inside of the docker image, instead of the mounted jdk, so it also runs without TEST_FLAG `AOT`.
I just manually tested the docker image `eclipse-temurin`, it doesn't recognize `-Xjit:verbose`, so maybe we need to limit this test to `openj9` only.
