### ISSUE TITLE
Rerun build with failed targets has an unnecessary extra space in front of comma

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4063]
TARGET parameter is populated with the list of failed targets and there is an unneeded space inserted, see this example:

`testList TESTLIST=jdk_nio_0 ,jdk_imageio_0 ,jdk_net_0 ,jdk_security3_0 ,jdk_security3_1 ,jdk_tools_1 ,jdk_imageio_1`

We should determine where this extra space is coming from and remove the extra space, see the code that generates the link in the [addFailedTestsGrinderLink method of the Jenkinsfilebase file](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/JenkinsfileBase#L1070-L1097)

**Comment by Nuel-Eneji** [comment]
Salutations, @smlambert I hope everything is good with you. I appreciate you giving me this assignment.
I kindly ask for assistance in setting up and executing the tests on my personal computer. I followed the instructions [here](https://github.com/adoptium/aqa-tests/blob/master/doc/userGuide.md#jenkins-configuration-with-customized-url) but I was unable to move past the process. I need assistance conducting the tests, please. Thanks

**Comment by smlambert** [comment]
hi @Nuel-Eneji - those instructions are out-of-date.  For Jenkinsfile changes, the reviewers will run some tests on your branch or draft PR on our Jenkins server, or I can temporarily enable you to do so and together we can assess whether it resolves the problem or needs more adjustments.  Once you have some changes pushed to a draft PR, we can start to test it.  I am guessing for this issue, it is a matter of applying "trim()" in the appropriate place.

**Comment by Nuel-Eneji** [comment]
Hello, @smlambert I hope everything is good with you.
I just made a draft pull request #4074 as directed and used the trim() function where it was thought to be suitable.
I would like to take part in the PR review process.
Thanks

**Comment by Nuel-Eneji** [comment]
Hello @smlambert Hope you're well?
Can you please make this task as done?
Thanks

**Comment by llxia** [comment]
Resolved via https://github.com/adoptium/aqa-tests/pull/4074

**Comment by Nuel-Eneji** [comment]
Thanks alot @llxia
