### ISSUE TITLE
"Rerun in Grinder with failed test targets" uses wrong platform

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#4080]
The "Rerun in Grinder with failed test targets" link from https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_x86-64_mac_Nightly/32/ creates a grinder on the default platform (x86-64_linux) instead of the same platform where the failure occurred (x86-64_mac). It doesn't set the BUILD_LIST or JDK_VERSION properly either.

https://openj9-jenkins.osuosl.org/job/Grinder/parambuild/?SDK_RESOURCE=customized&TARGET=testList+TESTLIST=jdk_foreign_0

**Comment by llxia** [comment]
We noticed that `Rerun in Grinder with failed test targets ` link does not capture all parameters for some reason. For now, please use `Rerun in Grinder` link. Close as dup of https://github.com/adoptium/aqa-tests/issues/4049
