### ISSUE TITLE
jdk20 jtreg needs to run on aarch64 macos 11.5.2?

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#4090]
I tried to run jdk20 sanity.openjdk tests on amac, nothing ran due to the following error.
https://openj9-jenkins.osuosl.org/job/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Nightly/2/console
```
16:29:51      java.home:    /Users/jenkins/workspace/Test_openjdknext_j9_sanity.openjdk_aarch64_mac_Nightly/openjdkbinary/j2sdk-image
16:29:51      java.version: 20-internal
16:29:51      os.version:   11.4  (expected: 11.5.2)
16:29:51  Use a more recent update of this version of JDK, or a newer version of JDK.
```

It ran on https://openj9-jenkins.osuosl.org/computer/mac11-aarch64-7 and although this machine has a `sw.os.mac.11_5` label, `sw_vers` reports the following
```
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71
```

I'm not sure where the 11.5.2 requirement comes from. It doesn't seem right for jtreg to enforce a minimum os level.
We do have one 11.5.2 machine, running a grinder on it https://openj9-jenkins.osuosl.org/job/Grinder/1456/console seems to be working.

@llxia fyi

**Comment by llxia** [comment]
It looks like the error is from jtreg:
https://github.com/openjdk/jtreg/blob/7767297ca1946d2752cdb8a92b9659f8bae77d81/make/CheckJavaOSVersion.java#L42

**Comment by pshipton** [comment]
I think it's from here
https://github.com/openjdk/jtreg/blob/7767297ca1946d2752cdb8a92b9659f8bae77d81/make/build.sh#L400-L410

Something wrong with the machines? I did open the Openj9 intra issue, but if we can't fix the machines before we want to start running the test regularly, we'll be stuck only being able to use a single machine.

**Comment by pshipton** [comment]
Opened a new dedicated infra issue https://github.ibm.com/runtimes/infrastructure/issues/7412

**Comment by pshipton** [comment]
I'll close this for now, and reopen later if we get desperate for another solution other than fixing the machines..
