### ISSUE TITLE
Jenkins: Parallel option should be ignored when num machines is 1

### ISSUE THREAD

**Issue by AdamBrousseau** [adoptium/aqa-tests#4093]
**Describe the bug**
If the number of machines, and therefore the number of child jobs, equals 1, I don't think we need to bother launching a child job.

**To Reproduce**
Launch a test with a parallel option and a build node label that only matches 1 machine

**Expected behavior**
Don't do parallel as it will create unnecessary overhead

**Screenshots**

**Additional context**

**Comment by pshipton** [comment]
If we make this change, we could also change the parallel default in a grinder from "None" to (my preferred) "NodesByIterations".
