### ISSUE TITLE
Improve shell scripts by using shellcheck

### ISSUE THREAD

**Issue by ultramancoder** [adoptium/aqa-tests#4098]
https://www.shellcheck.net/ is an awesome tool to find bugs in shell scripts. There are many shell scripts in the repo, and doing a quick test on compile.sh shellcheck gives many warnings. It would probably be good to fix these to improve the script. Thoughts?

**Comment by karianna** [comment]
Would be good to add this as a GH Action (I believe it is in the temurin-build repo)
