### ISSUE TITLE
Failures occurred, TAP results and TEST TARGETS SUMMARY don't report failures

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#4115]
https://openj9-jenkins.osuosl.org/job/Test_openjdk19_j9_sanity.openjdk_aarch64_mac_Nightly/44/

jenkins (correctly) reports unstable. There is a Test Result reporting failures. 
```
Test Result (6 failures / +6)

    jdk/incubator/vector/Byte128VectorTests.java.Byte128VectorTests
    jdk/incubator/vector/Double128VectorTests.java.Double128VectorTests
    jdk/incubator/vector/Float128VectorTests.java.Float128VectorTests
    jdk/incubator/vector/Int128VectorTests.java.Int128VectorTests
    jdk/incubator/vector/Long128VectorTests.java.Long128VectorTests
    jdk/incubator/vector/Short128VectorTests.java.Short128VectorTests
```

The TAP results don't report any failures, and TEST TARGETS SUMMARY shows ALL TESTS PASSED
```
21:48:27  TEST TARGETS SUMMARY
21:48:27  ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
21:48:27  DISABLED test targets:
21:48:27  	jdk_foreign_native_0
21:48:27  	jdk_foreign_native_1
21:48:27  	jdk_foreign_native_2
21:48:27  	jdk_svc_sanity_0
21:48:27  	jdk_svc_sanity_1
21:48:27  	jdk_svc_sanity_2
21:48:27  
21:48:27  PASSED test targets:
21:48:27  	jdk_lang_1 
21:48:27  	jdk_lang_native_1 
21:48:27  	jdk_math_1 
21:48:27  	jdk_util_1 
21:48:27  	jdk_foreign_1 
21:48:27  	jdk11_tier1_buffer_1 
21:48:27  	jdk11_tier1_iso8859_1 
21:48:27  	jdk_vector_float128_j9_0 
21:48:27  	jdk_vector_double128_j9_0 
21:48:27  	jdk_vector_int128_j9_0 
21:48:27  	jdk_vector_short128_j9_0 
21:48:27  	jdk_vector_byte128_j9_0 
21:48:27  	jdk_vector_long128_j9_0 
21:48:27  	jdk_vector_byte64_j9_0 
21:48:27  
21:48:27  TOTAL: 37   EXECUTED: 14   PASSED: 14   FAILED: 0   DISABLED: 6   SKIPPED: 17
21:48:27  ALL TESTS PASSED
```

@llxia

**Comment by pshipton** [comment]
I've also got some grinders that don't show any failures, but there are tests failing in the grinders.

https://openj9-jenkins.osuosl.org/job/Grinder/1492/consoleFull
```
11:08:17  PASSED test targets:
11:08:17  	jdk_vector_byte128_j9_0 
11:08:17  
11:08:17  TOTAL: 1   EXECUTED: 1   PASSED: 1   FAILED: 0   DISABLED: 0   SKIPPED: 0
11:08:17  ALL TESTS PASSED

but

11:08:17  test Byte128VectorTests.ABSMaskedByte128VectorTests(byte[i * 5], mask[i % 2]): failure
11:08:17  java.lang.AssertionError: at index #33, input = -91, mask = false expected [-91] but found [91]
11:08:17  	at org.testng.Assert.fail(Assert.java:99)
11:08:17  	at org.testng.Assert.failNotEquals(Assert.java:1037)
11:08:17  	at org.testng.Assert.assertEqualsImpl(Assert.java:140)
11:08:17  	at org.testng.Assert.assertEquals(Assert.java:122)
11:08:17  	at org.testng.Assert.assertEquals(Assert.java:841)
11:08:17  	at Byte128VectorTests.assertArraysEquals(Byte128VectorTests.java:109)
11:08:17  	at Byte128VectorTests.ABSMaskedByte128VectorTests(Byte128VectorTests.java:5265)
```

Similarly in https://openj9-jenkins.osuosl.org/job/Grinder/1493/consoleFull

**Comment by pshipton** [comment]
This problem is impacting development and the ability to diagnose problems. Grinders are not reporting failures that occur. It needs to be fixed ASAP.

**Comment by llxia** [comment]
The test runs multiple commands. The first one failed and the last cmd was successful. As we only capture the last cmd result, the test result is successful. 

We should not continue until the previous cmd is completed successfully. I will have a PR to fix this issue soon.

**Comment by pshipton** [comment]
Pls also check https://openj9-jenkins.osuosl.org/job/Grinder/1494/ is the same situation.
i.e. https://github.com/eclipse-openj9/openj9/issues/16259#issuecomment-1303781779

**Comment by llxia** [comment]
re https://github.com/adoptium/aqa-tests/issues/4115#issuecomment-1303860897, I do not think https://openj9-jenkins.osuosl.org/job/Grinder/1494/ is the same problem as vector tests.

**Comment by babsingh** [comment]
its the test report view: https://openj9-jenkins.osuosl.org/job/Grinder/1494/testReport/

**Comment by llxia** [comment]
@babsingh are you referring to the following case that it is in the failed test section, but showed passed?

![image](https://user-images.githubusercontent.com/19273206/200048028-cc3d38f2-dee7-463c-a3d9-831f3fc9a86f.png)



This is a different issue than vector test above. In this case, a 3rd party Jenkins JUnit plugin that reads jtr files that are generated from openjdk tests. We do not do any modifications to the test report. If you refresh [Jenkins test report page](https://openj9-jenkins.osuosl.org/job/Grinder/1494/testReport/), the test link change from time to time (not all the time). 
I got the following links for `PinALot.java#id0.PinALot_id0`:
https://openj9-jenkins.osuosl.org/job/Grinder/1494/testReport/java_lang_Thread_virtual_stress_PinALot/java_id0/PinALot_id0/
https://openj9-jenkins.osuosl.org/job/Grinder/1494/testReport/java_lang_Thread_virtual_stress_PinALot/java_id0/PinALot_id0_2/
https://openj9-jenkins.osuosl.org/job/Grinder/1494/testReport/java_lang_Thread_virtual_stress_PinALot/java_id0/PinALot_id0_7/
...

Also,  the content on the above test link changes from time to time (see the recording below):

https://user-images.githubusercontent.com/19273206/200051845-3c21b03f-44bd-410a-a260-f4dfdddc0e9e.mp4


Just my two cents, I think it is related to the test was executed in iteration. As a result, it had mutiplt result jtr files with the same test name. When the Jenkins plugin renders it, it quires the database and it displays the first return result, which may or may not be the failed one. I think this is something that we should report to the Jenkins JUnit plugin repo.


cc @smlambert @renfeiw

**Comment by babsingh** [comment]
> are you referring to the following case that it is in the failed test section, but showed passed?

Yes. The same issue is also seen for `GetStackTraceALot.java`. For actual failures (`NullStackTrace.java`), I don't see the error output related to the segfault:

![image](https://user-images.githubusercontent.com/8634038/200053848-cea44e35-c068-4864-8ec9-dbe745f9841f.png)

**Comment by llxia** [comment]
It suggested `check console log for any additional details` in the message. You can see full result in jtf file. For example: 

aqa-tests/TKG/output_16675036039469/jdk_lang_1/work/java/lang/Thread/NullStackTrace.jtr in the Grinder [Artifacts](https://openj9-artifactory.osuosl.org/artifactory/ci-openj9/Test/Grinder/1494/)

Or you can check [console output](https://openj9-jenkins.osuosl.org/job/Grinder/1494/consoleFull) for segfault.

**Comment by babsingh** [comment]
re https://github.com/adoptium/aqa-tests/issues/4115#issuecomment-1304028629:

I generally look at the `Console Output`. I didn't know `console log` meant `Console Output`. Also, `Agent communication error: java.io.EOFException;` suggests a failure in the test framework. So, I was under the assumption that the test framework had an error
