### ISSUE TITLE
cleanWS does not appear to work on sparcv9 solaris

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4128]
We are seeing multiple TAP files and JUnit files on the sparcv9 solaris machine, some from weeks ago, indicating that cleaning the Jenkins workspace does not appear to be working.

Example:
Mentioned in https://github.com/adoptium/aqa-tests/issues/4041#issuecomment-1306419643

From https://ci.adoptopenjdk.net/job/Grinder/6065/
<img width="653" alt="Screen Shot 2022-11-08 at 3 26 34 PM" src="https://user-images.githubusercontent.com/2836948/200668358-26bdd5b8-8b1c-4987-b7cc-b65262dc8b31.png">

See 5 TAP files at: https://ci.adoptopenjdk.net/job/Grinder/6048/tapResults/

<img width="490" alt="Screen Shot 2022-11-08 at 3 23 26 PM" src="https://user-images.githubusercontent.com/2836948/200668710-5c4cfc1f-4579-4c66-bdea-3b020c24e16d.png">

Dated:
- Wed Oct 26 08:45:31 2022 UTC
- Wed Oct 26 09:03:30 2022 UTC
- Wed Oct 26 09:21:36 2022 UTC
- Wed Oct 26 09:39:37 2022 UTC
- Wed Oct 26 09:57:39 2022 UTC

**Comment by Haroon-Khel** [comment]
That grinder had 5 iterations, maybe thats why it created 5 TAP files?

**Comment by Haroon-Khel** [comment]
build-siteox-solaris10u11-sparcv9-1 has older TAP files in its Grinder directory which I have cleared

**Comment by sophia-guo** [comment]
So probably we can close this ? @smlambert

**Comment by smlambert** [comment]
yep, I didn't even look to see ITERATIONS=5 !
