### ISSUE TITLE
Add hotspot_container tests to the openjdk test group

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4143]
We should be adding the hotspot_containers target to the openjdk/[playlist](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml) nearby the other [hotspot_misc](https://github.com/openjdk/jdk17u-dev/blob/master/test/hotspot/jtreg/TEST.groups#L58-L66) targets that we already have (see [hotspot_compiler, hotspot_gc, hotspot_runtime, hotspot_serviceability](https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L93-L219))

```
	<test>
		<testCaseName>hotspot_container</testCaseName>
		<variations>
			<variation>Mode150</variation>
			<variation>Mode650</variation>
			<variation>Mode1000</variation>
		</variations>
		<command>$(JAVA_COMMAND) -Xmx512m -jar $(Q)$(TEST_RESROOT)$(D)jtreg$(D)lib$(D)jtreg.jar$(Q) \
	$(JTREG_BASIC_OPTIONS) $(JVM_NATIVE_OPTIONS) -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS) $(VMOPTION_HEADLESS)$(Q) \
	-w $(Q)$(REPORTDIR)$(D)work$(Q) \
	-r $(Q)$(REPORTDIR)$(D)report$(Q) \
	-jdk:$(Q)$(TEST_JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_HOTSPOT_TEST_DIR)$(D)ProblemList.txt$(Q) \
	-exclude:$(Q)$(TEST_RESROOT)$(D)$(PROBLEM_LIST_FILE)$(Q) \
	${FEATURE_PROBLEM_LIST_FILE} \
	${VENDOR_PROBLEM_LIST_FILE} \
	$(Q)$(JTREG_HOTSPOT_TEST_DIR):hotspot_container$(Q); \
	$(TEST_STATUS)</command>
		<versions>
			<version>17+</version>
		</versions>
		<levels>
			<level>extended</level>
		</levels>
		<groups>
			<group>openjdk</group>
		</groups>
		<impls>
			<impl>hotspot</impl>
		</impls>
	</test>
```

There may be an implication here that we need the test machines to have Docker installed, so presume we may need to check whether we need an infrastructure issue also created and of course disable these container tests from the appropriate platforms where it is not available).  For now we can create a PR and run some tests across platforms to see how these tests behave.

The tests may skip themselves from running if machine ![canTestDocker](https://github.com/openjdk/jdk17u-dev/blob/3486bb2f8f89c6266e67b6efbc68dac14b2e6e74/test/lib/jdk/test/lib/containers/docker/DockerTestUtils.java#L93) in which case we may not need to add restrictions in the playlist as to where they can run, TBD.

**Comment by jerboaa** [comment]
These tests verify that the container detection code in OpenJDK works as expected. They'd be relevant for JDK 8, 11, 17 and latest. The basic mode of operation of those tests is that they build a `Dockerfile` (for the specific test) and then run the test JDK inside a container expecting specific behaviour. There will be some setup required (I think) as it's probably not a wise idea to run those tests already in a container (container in container?). Also, it would be good to know the setup where those tests run. In particular its useful to know which cgroup version the test-host is using (cgroup v1 vs cgroup v2). Those tests are relevant for Linux only. Other OSes don't have the feature.

**Comment by jerboaa** [comment]
I've opened an infra request ticket for cg v1 and cg v2 setups for Linux (x86_64 should be fine for starters): https://github.com/adoptium/infrastructure/issues/2817

**Comment by jerboaa** [comment]
Once this is fixed, we should remove excluded tests for JDK 8 done by https://github.com/adoptium/aqa-tests/pull/3885. I see that those are excluded not only for `linux-aarch64`, but for `linux-all` by now.

The real fix is to use a base image which is available on those architectures. The [proposed UBI 8](https://github.com/jerboaa/aqa-tests/commit/ac2d774badac2d5b8e5b44c08e4d2675d8c7b0d6#diff-c3d02f1e9a9f5dfed049a450b5d0fba4727b7b3d42f0a0771f2e41e408d6ef14R161) image is available for x86_64, ppc64, aarch64 and s390x (s390x for JDK 11+)
