### ISSUE TITLE
Run aqa github workflow does not work in aqa-test repo

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4178]
**Describe the bug**
Tried to run `run aqa --sdk_resource nightly --build_list functional --target floatSanityTests --jdk_version 11 --jdk_impl hotspot --platform x86-64_linux` in PR https://github.com/adoptium/aqa-tests/pull/4177 and got the error:

![image](https://user-images.githubusercontent.com/19273206/205311704-b9ca9e24-b36b-4c51-98d4-8e87ac373d63.png)
https://github.com/adoptium/aqa-tests/actions/runs/3602342375/jobs/6069188399#step:9:42

The same issue with `run aqa --help`:

![image](https://user-images.githubusercontent.com/19273206/205311832-9973f074-dfcd-431f-9b91-77b711b99b08.png)
https://github.com/adoptium/aqa-tests/actions/runs/3602363358/jobs/6069232819#step:5:7

**To Reproduce**
Run the above cmd in PR

**Expected behavior**
run aqa github workflow should be triggered successfully. 
Previous working example: https://github.com/adoptium/aqa-tests/pull/3258

**Additional context**
This seems only happens in aqa-tests repo. I can run `run aqa` in the openj9 repo without a problem. For example: https://github.com/eclipse-openj9/openj9/pull/16190

**Comment by sophia-guo** [comment]
This is due to the uplift actions/github-script from v3 to v6 https://github.com/adoptium/aqa-tests/pull/3919/files. Need to update the workflow method. The reason it works in openj9 as https://github.com/eclipse-openj9/openj9/blob/master/.github/workflows/runAqa.yml doesn't update with same change.
