### ISSUE TITLE
AQA_TEST_PIPELINE builds needs Jenkins job "displayName" set to easily identify

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#4181]
AQA_TEST_PIPELINE pipelines are not easy to identify what version or platform they are testing. It would seem sensible to label the job displayName appropriately eg:
```
currentBuild.setDisplayName("jdk-19.0.1_adopt:ppc64aix:jck.sanity")
```

**Comment by llxia** [comment]
I agree that we need a better way to distinguish between `AQA_Test_Pipeline` pipelines. 
Just a note, this pipeline is very versatile and people use it for different purposes. The pipeline can be launched with multiple versions, impl, platforms, targets, SDK, and labels, so we may need to be careful about what should be in the displayName. Otherwise, the name can be very long. :)

**Comment by smlambert** [comment]
I will assume displayName is separate from jobName and will not affect the [monitoring of the AQA_Test_Pipeline in TRSS](https://trss.adoptium.net/builds?buildName=AQA_Test_Pipeline&url=https%3A%2F%2Fci.adoptopenjdk.net&type=Test).

**Comment by andrew-m-leonard** [comment]
> I will assume displayName is separate from jobName and will not affect the [monitoring of the AQA_Test_Pipeline in TRSS](https://trss.adoptium.net/builds?buildName=AQA_Test_Pipeline&url=https%3A%2F%2Fci.adoptopenjdk.net&type=Test).

@ShelleyLambert yes, it is the Build name, so in TRSS instead of:
  Build #104
you would have
  Build jdk-20+5_adopt:ppc64aix

**Comment by andrew-m-leonard** [comment]
> I agree that we need a better way to distinguish between `AQA_Test_Pipeline` pipelines. Just a note, this pipeline is very versatile and people use it for different purposes. The pipeline can be launched with multiple versions, impl, platforms, targets, SDK, and labels, so we may need to be careful about what should be in the displayName. Otherwise, the name can be very long. :)

@llxia yes, so I maybe see the build name as an optional parameter, which otherwise defaults to usual jenkins #3744, callee can decide on the build name format

**Comment by llxia** [comment]
```
In TRSS instead of:
Build https://github.com/adoptium/aqa-tests/pull/104
you would have
Build jdk-20+5_adopt:ppc64aix
```

Do you mean we will see `Build jdk-20+5_adopt:ppc64aix` in TRSS? I do not think so. TRSS does not keep track of the displayName. It will still display `Build #104`.

**Comment by andrew-m-leonard** [comment]
> ```
> In TRSS instead of:
> Build https://github.com/adoptium/aqa-tests/pull/104
> you would have
> Build jdk-20+5_adopt:ppc64aix
> ```
> 
> Do you mean we will see `Build jdk-20+5_adopt:ppc64aix` in TRSS? I do not think so. TRSS does not keep track of the displayName. It will still display `Build #104`.

Yes of course you're right, it's just the Jenkins display name that would be different, the job number is unchanged.
