### ISSUE TITLE
Support jdk 20 tests with jtreg 7.1.1+1

### ISSUE THREAD

**Issue by jerboaa** [adoptium/aqa-tests#4190]
JDK 20 head will need [JTreg 7.1.1+1 at least](https://mail.openjdk.org/pipermail/jdk-dev/2022-December/007229.html). openjdk tests need to update to  support this.

- [x] Build jtreg7.1.1+1: Related issue for the 7 update: https://github.com/adoptium/ci-jenkins-pipelines/issues/404
- [x] openjdk tests category update (old issue for the jtreg 7 update https://github.com/adoptium/aqa-tests/pull/3966)
- [x] dependency job update: old issue for the jtreg 7 update was: https://ci.adoptopenjdk.net/view/all/job/test.getDependency/1563/

**Comment by luhenry** [comment]
- [ ] https://github.com/adoptium/ci-jenkins-pipelines/pull/532
- [ ] https://github.com/adoptium/aqa-tests/pull/4192

**Comment by jerboaa** [comment]
@luhenry Can we close this now?

**Comment by luhenry** [comment]
@jerboaa seems like everything is working fine. Let's close it.
