### ISSUE TITLE
Remove jtreg_7_1

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4198]
jtreg 7.1.1+1 is added for JDK20+ (see https://github.com/adoptium/aqa-tests/issues/4190 ). We should remove the old jtreg_7_1 https://github.com/adoptium/TKG/blob/d5854d5d113835b850dc097a69c8edfb8d1679b2/scripts/getDependencies.pl#L146

**Comment by llxia** [comment]
Sure, thanks @vedant-z .

**Comment by vedant-z** [comment]
Hey @llxia I need to remove the older version of **jtreg** i.e. jtreg_7_1 from [this file](https://github.com/adoptium/TKG/blob/d5854d5d113835b850dc097a69c8edfb8d1679b2/scripts/getDependencies.pl#L146) right? But this one is in another subrepo named TKG.

Let me know if I am on wrong path.

**Comment by llxia** [comment]
Yes, https://github.com/adoptium/TKG is part of AQAvit. Please see https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#developer-resources

**Comment by vedant-z** [comment]
So should I remove the specific part from the given file and make a PR in TKG repository?
