### ISSUE TITLE
Functional tests on z/OS failing with SHA checksum error while downloading asmtools.jar

### ISSUE THREAD

**Issue by psoujany** [adoptium/aqa-tests#4206]
**Describe the bug**
Functional tests on z/OS failing with SHA checksum error while downloading asmtools.jar

**To Reproduce**
Grinder_CR/1019

Error:
[mkdir] Created dir: /home/jenkins/workspace/Grinder_CR/aqa-tests/functional/Java8andUp/bin/DupClassNameTest/version2
18:09:52  
18:09:52  getDependentLibs:
18:09:55       [exec] --------------------------------------------
18:09:55       [exec] path is set to /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib
18:09:55       [exec] task is set to default
18:09:55       [exec] dependencyList is set to asm_all,javassist,testng,jcommander,commons_cli,jaxb_api,asmtools
18:09:55       [exec] --------------------------------------------
18:09:55       [exec] Starting download third party dependent jars
18:09:55       [exec] --------------------------------------------
18:09:55       [exec] downloading dependent third party jars to /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib
18:09:55       [exec] /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/jcommander.jar exists with correct hash, not downloading
18:09:55       [exec] /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/jaxb-api.jar exists with correct hash, not downloading
18:09:55       [exec] WARNING: cannot get the sha from /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/asmtools.jar.sha256sum.txt.
18:09:55       [exec] File content: /ÄÄÁÁÀÃÀÁ/ÂÀÄÂÃ/ÂÃÁÂÄÃ///Ë_È??%Ë¦/Ê
18:09:55       [exec] 
18:09:55       [exec] downloading https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/lastSuccessfulBuild/artifact/asmtools/asmtools.jar.sha256sum.txt
18:09:55       [exec] --> file downloaded to /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/asmtools.jar.sha256sum.txt
18:09:55       [exec] downloading https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/lastSuccessfulBuild/artifact/asmtools/asmtools.jar
18:09:55       [exec] --> file downloaded to /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/asmtools.jar
18:09:55       [exec] downloading https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/lastSuccessfulBuild/artifact/asmtools/asmtools.jar.sha256sum.txt
18:09:55       [exec] --> file downloaded to /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/asmtools.jar.sha256sum.txt
18:09:55       [exec] Expected sha is: <html>
18:09:55       [exec] <head>
18:09:55       [exec] <meta,
18:09:55       [exec] Actual sha is  : c2fe494b27d78d0190fe2933eb9770d9909d7eced8b38d5b9152208d29019edd.
18:09:55       [exec] Please delete /home/jenkins/workspace/Grinder_CR/aqa-tests/TKG/../TKG/lib/asmtools.jar and rerun the program!
18:09:55       [exec] ERROR: sha checksum error.

**Comment by llxia** [comment]
@sophia-guo is this related to the latest asmtool change? https://github.com/adoptium/ci-jenkins-pipelines/pull/519

**Comment by llxia** [comment]
Instead of `asmtools.jar`, should we use `asmtools-8.0.b02-ea.jar` from https://ci.adoptopenjdk.net/view/Dependencies/job/dependency_pipeline/?

**Comment by sophia-guo** [comment]
Yes, https://github.com/adoptium/TKG/issues/383

**Comment by llxia** [comment]
Could you create PR in TKG to fix this? Thanks

**Comment by mamatha-jv** [comment]
May I know latest status on this issue, also do we have any workarounds?

**Comment by Mesbah-Alam** [comment]
@mamatha-jv , Sophia has already fixed the related TKG issue (https://github.com/adoptium/TKG/issues/383) to update asmtools jar. Restarted the failing Grinder : Grinder_CR/1148. 

Please verify and close this issue.

**Comment by Mesbah-Alam** [comment]
sanity.functional in Grinder_CR/1148 is green. Closing this issue as fixed. 

Thanks @sophia-guo !
