### ISSUE TITLE
Unable to run jck-19 test material against a jdk-20 build

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#4223]
When trying to say run jck-19 material against a jdk-20 target, the stage material tries to checkout the jck19-unzipped material into the jck19-unzipped folder rather than the jck20-unzipped that will be used to run the tests.
https://ci.eclipse.org/temurin-compliance/view/JCK19/job/Test_openjdk19_hs_special.jck_ppc64_aix/27/
```
12:50:06  build:
12:50:06       [echo] === JCK_GIT_REPO_USED is set to git@github.com:temurin-compliance/JCK19-unzipped.git ===
12:50:06       [echo] === JCK_ROOT_USED is set to /home/jenkins/jck_root/JCK20-unzipped ===
12:50:06       [echo] === JCK_VERSION_USED is set to jck20 ===
12:50:06       [echo] start staging jck materials
12:50:06  
12:50:06  stage-jck-material:
12:50:06       [echo] /home/jenkins/jck_root/JCK20-unzipped does not exist,      clone from git@github.com:temurin-compliance/JCK19-unzipped.git, master branch, to /home/jenkins/jck_root/JCK20-unzipped
12:50:06       [exec] fatal: destination path 'JCK19-unzipped' already exists and is not an empty directory.
```

**Comment by andrew-m-leonard** [comment]
Fixing the clone does allow the jck-19 tests to run against the jdk-20 target as the JavaTestRunner makes assumptions of the jck runtime folders:
```
16:32:08  Error: Unable to access jarfile /home/jenkins/jck_root/JCK20-unzipped/JCK-runtime-20/lib/javatest.jar
```

This scenario needs handling differently, for the JavaTestRunner to recognise it is using jck-19 material to test jdk-20, rather than assuming jck-20 to test jdk-20...

**Comment by smlambert** [comment]
Noting this is a very "edge case" scenario, that I would not want to state that we officially support.
