### ISSUE TITLE
Remove unused file machineRes.groovy

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4227]
As we arrived at a different solution for relating multiple Jenkins test nodes (via Nested node for server and client testing https://github.com/adoptium/aqa-tests/pull/3364), we do not need a separate [buildenv/jenkins/machineRes.groovy](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/machineRes.groovy) file.  It can and should be deleted.

**Comment by SajjanYadav** [comment]
Hello sir, I would like to start my first contribution by removing this file. May I do it?

**Comment by smlambert** [comment]
Yes, please do @SajjanYadav !

Note, in our [Contributing guide](https://github.com/adoptium/aqa-tests/blob/master/Contributing.md#eclipse-contributor-agreement), that you will need to sign the ECA in order for us to merge a PR from you since we are an Eclipse Foundation project (extra details at: https://adoptium.net/docs/eca-sign-off/).
