### ISSUE TITLE
Mauve* test targets FAILED in Test_openjdk20_hs testing on all platforms

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4341]
MauveSingleThrdLoad_HS_5m, MauveSingleInvocLoad_HS_5m, MauveMultiThrdLoad_5m fail across all platforms for in JDK20 testing of Temurin.  MiniMix_5m and MiniMix_aot_5m also fail (they use mauve tests).

---

**Test Info**
Test Name: MauveSingleThrdLoad_HS_5m_0
Test Duration: 10 sec
Machine: test-docker-ubuntu2110-armv8l-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=63e888dbed0b30773bfe3537

**Build Info**
Build Name: Test_openjdk20_hs_sanity.system_aarch64_linux
Jenkins Build start time: Feb 11 2023, 06:44 pm
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk20_hs_sanity.system_aarch64_linux/67/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=63e8880ded0b30773bfe2fa6

**Java Version**
openjdk version "20" 2023-03-21
OpenJDK Runtime Environment Temurin-20+35 (build 20+35)
OpenJDK 64-Bit Server VM Temurin-20+35 (build 20+35, mixed mode, sharing)

**This test has been failed 29 times since Nov 01 2022, 11:44 pm**
**Java Version when the issue first seen**
openjdk version "20-beta" 2023-03-21
OpenJDK Runtime Environment Temurin-20+21-202211020331 (build 20-beta+21-202211020331)
OpenJDK 64-Bit Server VM Temurin-20+21-202211020331 (build 20-beta+21-202211020331, mixed mode, sharing)
Jenkins Build URL: https://ci.adoptopenjdk.net/job/Test_openjdk20_hs_sanity.system_aarch64_linux/28/

The test failed on machine test-docker-ubuntu2110-armv8l-1 5 times 
The test failed on machine test-docker-ubuntu2010-armv8l-2 2 times 
The test failed on machine test-docker-ubi8-armv8-1 2 times 
The test failed on machine test-docker-ubuntu2204-armv8l-2 6 times 
The test failed on machine test-docker-debian11-armv8-1 3 times 
The test failed on machine test-docker-ubuntu1804-armv8l-2 4 times 
The test failed on machine test-docker-ubuntu1804-armv8l-4 1 times 
The test failed on machine test-docker-fedora35-armv8l-1 1 times 
The test failed on machine test-docker-ubuntu2004-armv8l-3 3 times 
The test failed on machine build-osuosl-ubuntu2204-aarch64-1 1 times 
The test failed on machine test-docker-ubuntu2004-armv8l-2 1 times 

[Rerun in Grinder](https://ci.adoptopenjdk.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=MauveSingleThrdLoad_HS_5m_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=0&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=aarch64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=20&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk20%2Fjdk20-linux-aarch64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=system&amp;UPSTREAM_JOB_NUMBER=22&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Console output from [MiniMix_5m](https://ci.adoptopenjdk.net/job/Test_openjdk20_hs_extended.system_aarch64_linux/67/):
```
[2023-02-11T23:53:46.658Z] LT  JUnit Test Results for: net.adoptopenjdk.test.bigdecimal.TestSuite055
[2023-02-11T23:53:46.658Z] LT    Ran    : 923
[2023-02-11T23:53:46.658Z] LT    Passed : 922
[2023-02-11T23:53:46.658Z] LT    Failed : 1
[2023-02-11T23:53:46.658Z] LT    Ignored: 0
[2023-02-11T23:53:46.658Z] LT    Result : FAILED
```

**Comment by smlambert** [comment]
Need to verify if this issue is fixed by https://github.com/adoptium/aqa-systemtest/pull/480

**Comment by Mesbah-Alam** [comment]
Test for adopt : https://ci.adoptium.net/job/Grinder/6726. 

We have the multithreaded version of the test still failing : 

```
14:54:17  	MauveSingleThrdLoad_HS_5m_0 
14:54:17  	MauveSingleThrdLoad_HS_5m_1 
14:54:17  	MauveSingleInvocLoad_HS_5m_0 
14:54:17  	MauveSingleInvocLoad_HS_5m_1 
14:54:17  
14:54:17  FAILED test targets:
14:54:17  	MauveMultiThrdLoad_5m_0 
14:54:17  	MauveMultiThrdLoad_5m_1 
```

Added the equivalent exclusion for the multithreaded version here: https://github.com/adoptium/aqa-systemtest/pull/481.

All tests are passing with the second PR: https://ci.adoptium.net/job/Grinder/6727/console

```
15:33:14  PASSED test targets:
15:33:14  	MauveSingleThrdLoad_HS_5m_0 
15:33:14  	MauveSingleThrdLoad_HS_5m_1 
15:33:14  	MauveSingleInvocLoad_HS_5m_0 
15:33:14  	MauveSingleInvocLoad_HS_5m_1 
15:33:14  	MauveMultiThrdLoad_5m_0 
15:33:14  	MauveMultiThrdLoad_5m_1 
```

**Comment by smlambert** [comment]
thanks kindly @Mesbah-Alam !

**Comment by sophia-guo** [comment]
Still failed on  arm, aarch64_Linux, aarch64_mac. @Mesbah-Alam 

[Test_openjdk20_hs_sanity.system_aarch64_linux](https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.system_aarch64_linux/83/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=MauveSingleThrdLoad_HS_5m_0,MauveSingleThrdLoad_HS_5m_1,MauveSingleInvocLoad_HS_5m_0,MauveSingleInvocLoad_HS_5m_1,MauveMultiThrdLoad_5m_0,MauveMultiThrdLoad_5m_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.6-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk20%2Fjdk20-release-linux-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-20%2B36_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

java -version
[MauveSingleThrdLoad_HS_5m_0](https://trss.adoptium.net/output/test?id=641a332417052c6715545093) => [deep history 10/15 passed](https://trss.adoptium.net/deepHistory?testId=641a332417052c6715545093) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a2de917052c6715543b29&buildName=Test_openjdk20_hs_sanity.system_aarch64_linux&testId=641a332417052c6715545093&testName=MauveSingleThrdLoad_HS_5m_0)
[MauveSingleThrdLoad_HS_5m_1](https://trss.adoptium.net/output/test?id=641a332417052c6715545094) => [deep history 10/15 passed](https://trss.adoptium.net/deepHistory?testId=641a332417052c6715545094) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a2de917052c6715543b29&buildName=Test_openjdk20_hs_sanity.system_aarch64_linux&testId=641a332417052c6715545094&testName=MauveSingleThrdLoad_HS_5m_1)
[MauveSingleInvocLoad_HS_5m_0](https://trss.adoptium.net/output/test?id=641a332417052c671554509d) => [deep history 10/15 passed](https://trss.adoptium.net/deepHistory?testId=641a332417052c671554509d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a2de917052c6715543b29&buildName=Test_openjdk20_hs_sanity.system_aarch64_linux&testId=641a332417052c671554509d&testName=MauveSingleInvocLoad_HS_5m_0)
[MauveSingleInvocLoad_HS_5m_1](https://trss.adoptium.net/output/test?id=641a332417052c6715545097) => [deep history 10/15 passed](https://trss.adoptium.net/deepHistory?testId=641a332417052c6715545097) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a2de917052c6715543b29&buildName=Test_openjdk20_hs_sanity.system_aarch64_linux&testId=641a332417052c6715545097&testName=MauveSingleInvocLoad_HS_5m_1)
[MauveMultiThrdLoad_5m_0](https://trss.adoptium.net/output/test?id=641a332417052c6715545099) => [deep history 11/15 passed](https://trss.adoptium.net/deepHistory?testId=641a332417052c6715545099) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a2de917052c6715543b29&buildName=Test_openjdk20_hs_sanity.system_aarch64_linux&testId=641a332417052c6715545099&testName=MauveMultiThrdLoad_5m_0)
[MauveMultiThrdLoad_5m_1](https://trss.adoptium.net/output/test?id=641a332417052c671554509a) => [deep history 11/15 passed](https://trss.adoptium.net/deepHistory?testId=641a332417052c671554509a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a2de917052c6715543b29&buildName=Test_openjdk20_hs_sanity.system_aarch64_linux&testId=641a332417052c671554509a&testName=MauveMultiThrdLoad_5m_1)

[Test_openjdk20_hs_sanity.system_aarch64_mac](https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.system_aarch64_mac/82/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=MauveSingleThrdLoad_HS_5m_0,MauveSingleThrdLoad_HS_5m_1,MauveSingleInvocLoad_HS_5m_0,MauveSingleInvocLoad_HS_5m_1,MauveMultiThrdLoad_5m_0,MauveMultiThrdLoad_5m_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.6-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk20%2Fjdk20-release-mac-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-20%2B36_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

java -version
[MauveSingleThrdLoad_HS_5m_0](https://trss.adoptium.net/output/test?id=641a305b17052c671554424e) => [deep history 12/16 passed](https://trss.adoptium.net/deepHistory?testId=641a305b17052c671554424e) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a243f17052c67155412ae&buildName=Test_openjdk20_hs_sanity.system_aarch64_mac&testId=641a305b17052c671554424e&testName=MauveSingleThrdLoad_HS_5m_0)
[MauveSingleThrdLoad_HS_5m_1](https://trss.adoptium.net/output/test?id=641a305b17052c671554424f) => [deep history 12/16 passed](https://trss.adoptium.net/deepHistory?testId=641a305b17052c671554424f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a243f17052c67155412ae&buildName=Test_openjdk20_hs_sanity.system_aarch64_mac&testId=641a305b17052c671554424f&testName=MauveSingleThrdLoad_HS_5m_1)
[MauveSingleInvocLoad_HS_5m_0](https://trss.adoptium.net/output/test?id=641a305b17052c6715544251) => [deep history 12/16 passed](https://trss.adoptium.net/deepHistory?testId=641a305b17052c6715544251) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a243f17052c67155412ae&buildName=Test_openjdk20_hs_sanity.system_aarch64_mac&testId=641a305b17052c6715544251&testName=MauveSingleInvocLoad_HS_5m_0)
[MauveSingleInvocLoad_HS_5m_1](https://trss.adoptium.net/output/test?id=641a305b17052c6715544258) => [deep history 12/16 passed](https://trss.adoptium.net/deepHistory?testId=641a305b17052c6715544258) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a243f17052c67155412ae&buildName=Test_openjdk20_hs_sanity.system_aarch64_mac&testId=641a305b17052c6715544258&testName=MauveSingleInvocLoad_HS_5m_1)
[MauveMultiThrdLoad_5m_1](https://trss.adoptium.net/output/test?id=641a305b17052c6715544255) => [deep history 12/16 passed](https://trss.adoptium.net/deepHistory?testId=641a305b17052c6715544255) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a243f17052c67155412ae&buildName=Test_openjdk20_hs_sanity.system_aarch64_mac&testId=641a305b17052c6715544255&testName=MauveMultiThrdLoad_5m_1)
[MauveMultiThrdLoad_5m_0](https://trss.adoptium.net/output/test?id=641a305b17052c6715544254) => [deep history 12/16 passed](https://trss.adoptium.net/deepHistory?testId=641a305b17052c6715544254) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a243f17052c67155412ae&buildName=Test_openjdk20_hs_sanity.system_aarch64_mac&testId=641a305b17052c6715544254&testName=MauveMultiThrdLoad_5m_0)

[Test_openjdk20_hs_sanity.system_arm_linux](https://ci.adoptium.net/job/Test_openjdk20_hs_sanity.system_arm_linux/75/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=MauveSingleThrdLoad_HS_5m_2,MauveSingleInvocLoad_HS_5m_2,MauveMultiThrdLoad_5m_2&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=arm_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=v0.9.6-release&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk20%2Fjdk20-release-linux-arm-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-20%2B36_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=5&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

java -version
[MauveSingleInvocLoad_HS_5m_2](https://trss.adoptium.net/output/test?id=641a3ddc17052c671554828d) => [deep history 11/15 passed](https://trss.adoptium.net/deepHistory?testId=641a3ddc17052c671554828d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a3cc717052c6715547c64&buildName=Test_openjdk20_hs_sanity.system_arm_linux&testId=641a3ddc17052c671554828d&testName=MauveSingleInvocLoad_HS_5m_2)
[MauveSingleThrdLoad_HS_5m_2](https://trss.adoptium.net/output/test?id=641a3ddc17052c671554828a) => [deep history 11/15 passed](https://trss.adoptium.net/deepHistory?testId=641a3ddc17052c671554828a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a3cc717052c6715547c64&buildName=Test_openjdk20_hs_sanity.system_arm_linux&testId=641a3ddc17052c671554828a&testName=MauveSingleThrdLoad_HS_5m_2)
[MauveMultiThrdLoad_5m_2](https://trss.adoptium.net/output/test?id=641a3ddc17052c6715548292) => [deep history 11/15 passed](https://trss.adoptium.net/deepHistory?testId=641a3ddc17052c6715548292) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=641a3cc717052c6715547c64&buildName=Test_openjdk20_hs_sanity.system_arm_linux&testId=641a3ddc17052c6715548292&testName=MauveMultiThrdLoad_5m_2)
