### ISSUE TITLE
Add support for testing JDK binaries packaged in tar.xz format 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4374]
We fetch and install JDK binaries that are packaged in several forms (.tar.gz, .zip), we should additionally support .tar.xz files, so we can ensure to support all vendors listed in the marketplace.  Currently the Red Hat builds listed in the Adoptium marketplace use that format (example: [jdk17 RH binary](https://developers.redhat.com/content-gateway/file/pub/openjdk/adoptium/January_2023/java-17-openjdk-17.0.6.0.10-2.portable.jdk.el.x86_64.tar.xz)).

See a Grinder run that tries to fetch and test it: https://ci.adoptium.net/view/Test_grinder/job/Grinder/6747/

`tar xf java-17-openjdk-17.0.6.0.10-2.portable.jdk.el.x86_64.tar.xz` and requires xz-utils to be present on test machines (`sudo apt-get install xz-utils` if needs installation)

**Comment by judovana** [comment]
//me watching  issue

TY!
