### ISSUE TITLE
Add jdk20 repo and branch to v0.9.6-release release branch

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4392]
We can use the v0.9.6-release branch for the March release (jdk20), but need to add the information to the testenv.properties file at https://github.com/adoptium/aqa-tests/blob/v0.9.6-release/testenv/testenv.properties#L18

**Comment by sophia-guo** [comment]
Since January release there are quite a lot of updates in master. Should we pick all those changes in v0.9.6-release?

**Comment by sophia-guo** [comment]
@steelhead31 when will  jdk20u "https://github.com/adoptium/jdk20u.git" available?

**Comment by smlambert** [comment]
re: https://github.com/adoptium/aqa-tests/issues/4392#issuecomment-1462705860 - no, we do not need all of those changes, only excludes that pertain to healthy, happy JDK 20 test runs are needed.

**Comment by steelhead31** [comment]
> @steelhead31 when will jdk20u "https://github.com/adoptium/jdk20u.git" available?

I think it will be made available after the jdk20 release itself, the base release is just referred to as jdk20.. [https://github.com/adoptium/jdk20](https://github.com/adoptium/jdk20)  , so Im assuming that it will become jdk20u after the initial release, but before the April one..  at least that's my understanding...

**Comment by smlambert** [comment]
both parts are now in.
