### ISSUE TITLE
Run hotspot_custom with impl=openj9

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4408]
`serviceability_jvmti_j9` is a test target for openj9. https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L370

When it fails, the `Rerun failed hotspot test cases in Grinder with hotspot_custom target` link sets TARGET=`hotspot_custom` and CUSTOM_TARGET=`<subtest>` (i.e., `serviceability/jvmti/vthread/BreakpointInYieldTest/BreakpointInYieldTest.java`). 

This link could trigger an invalid job as openj9 cannot run with `hotspot_custom` target. https://github.com/adoptium/aqa-tests/blob/master/openjdk/playlist.xml#L90

To resolve the problem, I think we can allow `hotspot_custom` to run with openj9 and change the default HOTSPOT_CUSTOM_TARGET to a common subtest. https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk#L133

**Comment by sophia-guo** [comment]
If there is a test works both for openj9 and hotspot that would be great. Seems serviceability/jvmti/GetSystemProperty/JvmtiGetSystemPropertyTest.java only works for jdk19+, so not a good one.

**Comment by llxia** [comment]
serviceability jvmti are the only tests that we need so far. It only works for 19+.
Close this issue as the changes are delivered.
