### ISSUE TITLE
sanity.perf tests failing to find `specjbb2015.jar`

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#4409]
**Describe the bug**
sanity.perf runs failing in build phase:
```
12:43:50  
12:43:50  isRunnable:
12:43:50       [exec] Error: Unable to access jarfile ${env.SPECJBB_SRC}/specjbb2015.jar
12:43:50       [exec] Result: 1
12:43:50  
12:43:50  BUILD FAILED
```

**To Reproduce**
Any recent run of https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.perf_aarch64_linux

**Expected behavior**
Build passes and tests tart to run

**Screenshots**

**Additional context**

I believe @smlambert understands why this would be occurring and can resolve it. [Also fails on Linux/x64](https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.perf_x86-64_linux/778) so not specific to one platform/machine

**Comment by smlambert** [comment]
Yep, it is across the board, and either because we are not filtering out this out with the playlist <vendor> tags, or because the build.xml needs an update.
