### ISSUE TITLE
Extended.system tests failed with jdk20 from enabled.

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4428]
aarch64_linux

[Test_openjdk20_hs_extended.system_aarch64_linux](https://ci.adoptium.net/job/Test_openjdk20_hs_extended.system_aarch64_linux/77/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=MiniMix_5m_0,MiniMix_5m_1,MiniMix_aot_5m_0,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk20%2Fjdk20-linux-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=34&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

java -version
[MiniMix_5m_1](https://trss.adoptium.net/output/test?id=640d978a17052c671540d279) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=640d978a17052c671540d279) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640d96bf17052c671540c509&buildName=Test_openjdk20_hs_extended.system_aarch64_linux&testId=640d978a17052c671540d279&testName=MiniMix_5m_1)
[MiniMix_5m_0](https://trss.adoptium.net/output/test?id=640d978a17052c671540d277) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=640d978a17052c671540d277) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640d96bf17052c671540c509&buildName=Test_openjdk20_hs_extended.system_aarch64_linux&testId=640d978a17052c671540d277&testName=MiniMix_5m_0)
[MiniMix_aot_5m_0](https://trss.adoptium.net/output/test?id=640d978a17052c671540d27d) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=640d978a17052c671540d27d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640d96bf17052c671540c509&buildName=Test_openjdk20_hs_extended.system_aarch64_linux&testId=640d978a17052c671540d27d&testName=MiniMix_aot_5m_0)
[HCRLateAttachWorkload_previewEnabled_1](https://trss.adoptium.net/output/test?id=640d978a17052c671540d28a) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=640d978a17052c671540d28a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640d96bf17052c671540c509&buildName=Test_openjdk20_hs_extended.system_aarch64_linux&testId=640d978a17052c671540d28a&testName=HCRLateAttachWorkload_previewEnabled_1)
[HCRLateAttachWorkload_previewEnabled_0](https://trss.adoptium.net/output/test?id=640d978a17052c671540d289) => [deep history 1/7 passed](https://trss.adoptium.net/deepHistory?testId=640d978a17052c671540d289) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640d96bf17052c671540c509&buildName=Test_openjdk20_hs_extended.system_aarch64_linux&testId=640d978a17052c671540d289&testName=HCRLateAttachWorkload_previewEnabled_0)
rerun: https://ci.adoptium.net/job/Grinder/6866/ --failed.

Same for aarch64_mac
[Test_openjdk20_hs_extended.system_aarch64_mac](https://ci.adoptium.net/job/Test_openjdk20_hs_extended.system_aarch64_mac/76/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=MiniMix_5m_0,MiniMix_5m_1,MiniMix_aot_5m_0,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=0&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=20&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk20&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk20%2Fjdk20-mac-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=dev&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=false&BUILD_LIST=system&UPSTREAM_JOB_NUMBER=34&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=10&JVM_OPTIONS=&PARALLEL=None)

java -version
[MiniMix_5m_0](https://trss.adoptium.net/output/test?id=640e440617052c6715443bcd) => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=640e440617052c6715443bcd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640e432317052c6715443492&buildName=Test_openjdk20_hs_extended.system_aarch64_mac&testId=640e440617052c6715443bcd&testName=MiniMix_5m_0)
[MiniMix_5m_1](https://trss.adoptium.net/output/test?id=640e440617052c6715443bcf) => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=640e440617052c6715443bcf) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640e432317052c6715443492&buildName=Test_openjdk20_hs_extended.system_aarch64_mac&testId=640e440617052c6715443bcf&testName=MiniMix_5m_1)
[MiniMix_aot_5m_0](https://trss.adoptium.net/output/test?id=640e440617052c6715443bd0) => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=640e440617052c6715443bd0) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640e432317052c6715443492&buildName=Test_openjdk20_hs_extended.system_aarch64_mac&testId=640e440617052c6715443bd0&testName=MiniMix_aot_5m_0)
[HCRLateAttachWorkload_previewEnabled_0](https://trss.adoptium.net/output/test?id=640e440617052c6715443bdf) => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=640e440617052c6715443bdf) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640e432317052c6715443492&buildName=Test_openjdk20_hs_extended.system_aarch64_mac&testId=640e440617052c6715443bdf&testName=HCRLateAttachWorkload_previewEnabled_0)
[HCRLateAttachWorkload_previewEnabled_1](https://trss.adoptium.net/output/test?id=640e440617052c6715443be0) => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=640e440617052c6715443be0) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=640e432317052c6715443492&buildName=Test_openjdk20_hs_extended.system_aarch64_mac&testId=640e440617052c6715443be0&testName=HCRLateAttachWorkload_previewEnabled_1)

Similar to other platforms. Generic one.

**Comment by smlambert** [comment]
Check if these are similar to or related to these other recent issues (which have been fixed):
https://github.com/adoptium/aqa-systemtest/pull/480
https://github.com/adoptium/aqa-systemtest/pull/481

**Comment by sophia-guo** [comment]
Not the same according to the output. Both https://github.com/adoptium/aqa-systemtest/pull/480 and 
https://github.com/adoptium/aqa-systemtest/pull/481 are merged in a few weeks ago. Those tests failed with jdk20 since jdk20 test jobs enabled. Failed with both aqa-tests master or v0.9.6.

**Comment by smlambert** [comment]
Minimix contains Mauve tests, so that is why I thought there may be similarities and also https://github.com/eclipse-openj9/openj9-systemtest/issues/147#issuecomment-1423455810

**Comment by smlambert** [comment]
Ya, I see it is a different failure:

```
[2023-03-12T13:12:25.948Z] LT  JUnit Test Results for: net.adoptopenjdk.test.bigdecimal.TestSuite002
[2023-03-12T13:12:25.948Z] LT    Ran    : 935
[2023-03-12T13:12:25.948Z] LT    Passed : 933
[2023-03-12T13:12:25.948Z] LT    Failed : 2
[2023-03-12T13:12:25.948Z] LT    Ignored: 0
[2023-03-12T13:12:25.948Z] LT    Result : FAILED
```

**Comment by sophia-guo** [comment]
[HCRLateAttachWorkload_previewEnabled](https://trss.adoptium.net/output/test?id=640e440617052c6715443bdf) https://github.com/adoptium/aqa-systemtest/issues/479

**Comment by smlambert** [comment]
bigdecimal issue summarized here: https://github.com/adoptium/aqa-systemtest/issues/482

**Comment by Mesbah-Alam** [comment]
https://github.com/adoptium/aqa-systemtest/pull/483 should fix the failures related to bigdecimal (e.g. MiniMix_5m).

**Comment by sophia-guo** [comment]
Closed by https://github.com/adoptium/aqa-systemtest/pull/483

**Comment by Mesbah-Alam** [comment]
Hi @sophia-guo , I don't think https://github.com/adoptium/aqa-systemtest/pull/483 would fix errors you see in system tests that don't run bigdecimal tests , e.g. [HCRLateAttachWorkload_previewEnabled_0](https://trss.adoptium.net/output/test?id=640e440617052c6715443bdf). They are likely failing due to some other reasons.

**Comment by sophia-guo** [comment]
@Mesbah-Alam 

[HCRLateAttachWorkload_previewEnabled_0](https://trss.adoptium.net/output/test?id=640e440617052c6715443bdf).  see comment

https://github.com/adoptium/aqa-tests/issues/4428#issuecomment-1474399642
