### ISSUE TITLE
criu-ubi-portable-restore_test does not clean properly

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4464]
[Grinder](https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder/31845/console)

```
00:10:26.656  criu-ubi-portable-restore_test_0_PASSED
00:10:26.656  -----------------------------------
00:10:26.656  DOCKERIMAGE_TAG nightly has been recognized.
00:10:26.656  The test here is criu-ubi-portable-restore
00:10:26.656  The directory in the external.sh is criu-ubi-portable-restore
00:10:26.656  node_label_micro_architecture is hw.arch.x86.broadwell
00:10:26.656  node_label_current_os is sw.os.ubuntu.22
00:10:26.656  Error: no container with name or ID "criu-ubi-portable-restore-test" found: no such container
```

I believe this is due to the incorrect container name.

**Comment by llxia** [comment]
@LongyuZhang we can either clean the specific image or I think we can prune them all in dev.external?

**Comment by LongyuZhang** [comment]
When we run the docker image, we already have `--rm` which atomically removes the container if complete successfully; the above command is to force remove the container in case it fails, I can add command to mute the output.
If we prune them just in dev.external, grinder with the single test may keep the image on machine.

**Comment by llxia** [comment]
Thanks @LongyuZhang for clarification. I think we can close this issue.
