### ISSUE TITLE
April 2023 Release JDK17 triage

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4515]
#### Release Summary Report for release-openjdk17-pipeline 
**Report generated at:** Wed, 19 Apr 2023 06:45:07 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=643f10db17052c67156eb8d8&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=643f10db17052c67156eb8d8) 
Jenkins Build URL https://ci.adoptium.net/job/build-scripts/job/release-openjdk17-pipeline/25/ 
Started by upstream project "build-scripts/utils/releaseTrigger_jdk17u" build number 1002 at 4/18/2023, 5:43:11 PM 

| Platforms | Details | Status |
| --- | --- | --- |
|[**jdk17u-release-aix-ppc64-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-aix-ppc64-temurin/7/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512403144) |✔️ |
| [**jdk17u-release-alpine-linux-x64-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-alpine-linux-x64-temurin/7/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512408680)| ✔️ |
| [**jdk17u-release-linux-aarch64-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-aarch64-temurin/7/) ❌ FAILURE ❌ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512407747) | ✔️|
| [**jdk17u-release-linux-arm-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-arm-temurin/7/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512404678)| ✔️|
| [**jdk17u-release-linux-ppc64le-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-ppc64le-temurin/8/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512408136)| ✔️|
| [**jdk17u-release-linux-s390x-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-s390x-temurin/7/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512405434)| ✔️|
| [**jdk17u-release-linux-x64-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-x64-temurin/7/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512846110)| ✔️|
| [**jdk17u-release-mac-x64-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-mac-x64-temurin/9/) ❌ ABORTED ❌ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1513814154)| ✔️|
| [**jdk17u-release-windows-x64-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-windows-x64-temurin/8/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512409817)| ✔️|
| [**jdk17u-release-windows-x86-32-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-windows-x86-32-temurin/8/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1512406375)|✔️ |
| [**jdk17u-release-linux-arm-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-linux-arm-temurin/7/) ⚠️ UNSTABLE ⚠️ | [link](https://github.com/adoptium/aqa-tests/issues/4515#issuecomment-1516716784)|already listed in 4th row, see above |

**Comment by smlambert** [comment]
ppc64_aix

[**Test_openjdk17_hs_extended.openjdk_ppc64_aix**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix/88/) ❌ ABORTED ❌

[**Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0/72/) ❌ ABORTED ❌
[jdk_net_0](https://trss.adoptium.net/output/test?id=6438f93e17052c67154de517) => [deep history 7/10 passed](https://trss.adoptium.net/deepHistory?testId=6438f93e17052c67154de517) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438f85d17052c67154ddfd0&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0&testId=6438f93e17052c67154de517&testName=jdk_net_0)
[jdk_jmx_0](https://trss.adoptium.net/output/test?id=6438f93e17052c67154de538) => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6438f93e17052c67154de538) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438f85d17052c67154ddfd0&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0&testId=6438f93e17052c67154de538&testName=jdk_jmx_0)
[jdk_jmx_1](https://trss.adoptium.net/output/test?id=6438f93e17052c67154de539) => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6438f93e17052c67154de539) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438f85d17052c67154ddfd0&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0&testId=6438f93e17052c67154de539&testName=jdk_jmx_1)
[jdk_net_1](https://trss.adoptium.net/output/test?id=6438f93e17052c67154de523) => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6438f93e17052c67154de523) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438f85d17052c67154ddfd0&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0&testId=6438f93e17052c67154de523&testName=jdk_net_1)
[jdk_vector_0](https://trss.adoptium.net/output/test?id=6438f93e17052c67154de55f) => [deep history 0/1 passed](https://trss.adoptium.net/deepHistory?testId=6438f93e17052c67154de55f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438f85d17052c67154ddfd0&buildName=Test_openjdk17_hs_extended.openjdk_ppc64_aix_testList_0&testId=6438f93e17052c67154de55f&testName=jdk_vector_0)

**Comment by smlambert** [comment]
arm_linux

[**Test_openjdk17_hs_extended.openjdk_arm_linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux/95/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0/87/) ⚠️ UNSTABLE ⚠️
[jvm_compiler_2](https://trss.adoptium.net/output/test?id=6438192217052c6715486f56) => [deep history 1/9 passed](https://trss.adoptium.net/deepHistory?testId=6438192217052c6715486f56) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643817c717052c67154864aa&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0&testId=6438192217052c6715486f56&testName=jvm_compiler_2)
[jdk_vector_2](https://trss.adoptium.net/output/test?id=6438192217052c6715486f5b) => [deep history 4/9 passed](https://trss.adoptium.net/deepHistory?testId=6438192217052c6715486f5b) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643817c717052c67154864aa&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0&testId=6438192217052c6715486f5b&testName=jdk_vector_2)

**Comment by smlambert** [comment]
s390x_linux

[**Test_openjdk17_hs_extended.openjdk_s390x_linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux/104/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0/87/) ⚠️ UNSTABLE ⚠️
[jdk_beans_0](https://trss.adoptium.net/output/test?id=6438484f17052c671549544d) => [deep history 2/9 passed](https://trss.adoptium.net/deepHistory?testId=6438484f17052c671549544d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438478717052c67154953a1&buildName=Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0&testId=6438484f17052c671549544d&testName=jdk_beans_0)
[jdk_imageio_1](https://trss.adoptium.net/output/test?id=6438484f17052c6715495465) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=6438484f17052c6715495465) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438478717052c67154953a1&buildName=Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0&testId=6438484f17052c6715495465&testName=jdk_imageio_1)
[jdk_tools_1](https://trss.adoptium.net/output/test?id=6438484f17052c6715495461) => [deep history 0/6 passed](https://trss.adoptium.net/deepHistory?testId=6438484f17052c6715495461) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438478717052c67154953a1&buildName=Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0&testId=6438484f17052c6715495461&testName=jdk_tools_1)
[jdk_net_0](https://trss.adoptium.net/output/test?id=6438484f17052c6715495451) => [deep history 2/9 passed](https://trss.adoptium.net/deepHistory?testId=6438484f17052c6715495451) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438478717052c67154953a1&buildName=Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_0&testId=6438484f17052c6715495451&testName=jdk_net_0)

[**Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1/88/) ⚠️ UNSTABLE ⚠️
[jdk_tools_0](https://trss.adoptium.net/output/test?id=6438485717052c6715495491) => [deep history 2/8 passed](https://trss.adoptium.net/deepHistory?testId=6438485717052c6715495491) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438478717052c67154953a2&buildName=Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_1&testId=6438485717052c6715495491&testName=jdk_tools_0)

[**Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_2**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_2/87/) ⚠️ UNSTABLE ⚠️
[jdk_nio_0](https://trss.adoptium.net/output/test?id=6438484717052c67154953f7) => [deep history 2/8 passed](https://trss.adoptium.net/deepHistory?testId=6438484717052c67154953f7) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438478717052c67154953a0&buildName=Test_openjdk17_hs_extended.openjdk_s390x_linux_testList_2&testId=6438484717052c67154953f7&testName=jdk_nio_0)

**Comment by smlambert** [comment]
x86-32_windows

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows/109/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/85/) ⚠️ UNSTABLE ⚠️
[jvm_compiler_2](https://trss.adoptium.net/output/test?id=6438b84417052c67154c0d91) => [deep history 0/10 passed](https://trss.adoptium.net/deepHistory?testId=6438b84417052c67154c0d91) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438b77d17052c67154c0296&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0&testId=6438b84417052c67154c0d91&testName=jvm_compiler_2)

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1/91/) ⚠️ UNSTABLE ⚠️
[jdk_tools_2](https://trss.adoptium.net/output/test?id=6438b83c17052c67154c0d7c) => [deep history 3/10 passed](https://trss.adoptium.net/deepHistory?testId=6438b83c17052c67154c0d7c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438b77d17052c67154c0295&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_1&testId=6438b83c17052c67154c0d7c&testName=jdk_tools_2)

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2/87/) ⚠️ UNSTABLE ⚠️
[jdk_other_2](https://trss.adoptium.net/output/test?id=6438b83517052c67154c0d26) => [deep history 8/9 passed](https://trss.adoptium.net/deepHistory?testId=6438b83517052c67154c0d26) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438b77d17052c67154c0294&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_2&testId=6438b83517052c67154c0d26&testName=jdk_other_2)

**Comment by smlambert** [comment]
aarch64_linux

[**Test_openjdk17_hs_extended.openjdk_aarch64_linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux/108/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_0/7/) ⚠️ UNSTABLE ⚠️
[jdk_beans_0](https://trss.adoptium.net/output/test?id=64382de917052c671548d5b6) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=64382de917052c671548d5b6) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=64382ce317052c671548cd6b&buildName=Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_0&testId=64382de917052c671548d5b6&testName=jdk_beans_0)
[jdk_imageio_1](https://trss.adoptium.net/output/test?id=64382de917052c671548d5cd) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=64382de917052c671548d5cd) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=64382ce317052c671548cd6b&buildName=Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_0&testId=64382de917052c671548d5cd&testName=jdk_imageio_1)

**Comment by smlambert** [comment]
ppc64le_linux

[**Test_openjdk17_hs_extended.openjdk_ppc64le_linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux/110/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_0/93/) ⚠️ UNSTABLE ⚠️
[jdk_beans_0](https://trss.adoptium.net/output/test?id=6438296917052c671548b5f9) => [deep history 6/9 passed](https://trss.adoptium.net/deepHistory?testId=6438296917052c671548b5f9) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438284d17052c671548aa2a&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_0&testId=6438296917052c671548b5f9&testName=jdk_beans_0)

[**Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1/93/) ⚠️ UNSTABLE ⚠️
[jvm_compiler_0](https://trss.adoptium.net/output/test?id=6438296217052c671548b5b3) => [deep history 7/9 passed](https://trss.adoptium.net/deepHistory?testId=6438296217052c671548b5b3) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438284d17052c671548aa28&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=6438296217052c671548b5b3&testName=jvm_compiler_0)
[jdk_tools_0](https://trss.adoptium.net/output/test?id=6438296217052c671548b5c3) => [deep history 6/9 passed](https://trss.adoptium.net/deepHistory?testId=6438296217052c671548b5c3) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438284d17052c671548aa28&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=6438296217052c671548b5c3&testName=jdk_tools_0)
[jdk_management_1](https://trss.adoptium.net/output/test?id=6438296217052c671548b5b7) => [deep history 6/9 passed](https://trss.adoptium.net/deepHistory?testId=6438296217052c671548b5b7) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438284d17052c671548aa28&buildName=Test_openjdk17_hs_extended.openjdk_ppc64le_linux_testList_1&testId=6438296217052c671548b5b7&testName=jdk_management_1)

**Comment by smlambert** [comment]
x86-64_alpine-linux

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux/106/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0/83/) ⚠️ UNSTABLE ⚠️
[jdk_beans_0](https://trss.adoptium.net/output/test?id=6438399f17052c6715491168) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=6438399f17052c6715491168) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643838a717052c6715490f9d&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_0&testId=6438399f17052c6715491168&testName=jdk_beans_0)

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_1**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_1/82/) ⚠️ UNSTABLE ⚠️
[jdk_imageio_0](https://trss.adoptium.net/output/test?id=643839a717052c6715491193) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=643839a717052c6715491193) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643838a717052c6715490f9e&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_1&testId=643839a717052c6715491193&testName=jdk_imageio_0)
[jdk_imageio_1](https://trss.adoptium.net/output/test?id=643839a717052c6715491194) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=643839a717052c6715491194) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643838a717052c6715490f9e&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_1&testId=643839a717052c6715491194&testName=jdk_imageio_1)

[**Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2/67/) ⚠️ UNSTABLE ⚠️
[jdk_beans_1](https://trss.adoptium.net/output/test?id=6438399817052c6715491108) => [deep history 0/7 passed](https://trss.adoptium.net/deepHistory?testId=6438399817052c6715491108) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643838a717052c6715490f9b&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_alpine-linux_testList_2&testId=6438399817052c6715491108&testName=jdk_beans_1)

**Comment by smlambert** [comment]
x86-64_windows

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows/109/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0/90/) ⚠️ UNSTABLE ⚠️
[jdk_tools_1](https://trss.adoptium.net/output/test?id=6438315617052c671548e992) => [deep history 2/10 passed](https://trss.adoptium.net/deepHistory?testId=6438315617052c671548e992) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438302817052c671548dca0&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_0&testId=6438315617052c671548e992&testName=jdk_tools_1)

[**Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1/90/) ⚠️ UNSTABLE ⚠️
[jdk_tools_0](https://trss.adoptium.net/output/test?id=6438314e17052c671548e93c) => [deep history 4/10 passed](https://trss.adoptium.net/deepHistory?testId=6438314e17052c671548e93c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438302817052c671548dc9f&buildName=Test_openjdk17_hs_extended.openjdk_x86-64_windows_testList_1&testId=6438314e17052c671548e93c&testName=jdk_tools_0)

**Comment by smlambert** [comment]
x86-64_linux

jdk11
[**Test_openjdk11_hs_extended.openjdk_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux/130/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_1**](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_1/93/) ⚠️ UNSTABLE ⚠️
[jdk_tools_0](https://trss.adoptium.net/output/test?id=64382bf817052c671548c97a) => [deep history 5/7 passed](https://trss.adoptium.net/deepHistory?testId=64382bf817052c671548c97a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=64382a9817052c671548bcae&buildName=Test_openjdk11_hs_extended.openjdk_x86-64_linux_testList_1&testId=64382bf817052c671548c97a&testName=jdk_tools_0)


[**Test_openjdk11_hs_sanity.external_x86-64_linux**](https://ci.adoptium.net/job/Test_openjdk11_hs_sanity.external_x86-64_linux/580/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=testList+TESTLIST=openliberty_microprofile_tck_0&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=true&amp;ACTIVE_NODE_TIMEOUT=0&amp;EXTRA_DOCKER_ARGS=-v+%24%7BTEST_JDK_HOME%7D%3A%2Fopt%2Fjava%2Fopenjdk&amp;VENDOR_TEST_DIRS=&amp;TKG_OWNER_BRANCH=AdoptOpenJDK%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2FAdoptOpenJDK%2Fopenjdk-tests.git&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;ADOPTOPENJDK_BRANCH=v0.9.7-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;JDK_VERSION=11&amp;USER_CREDENTIALS_ID=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk11u&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk11u%2Fjdk11u-release-linux-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse%2Fopenj9.git&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-11.0.19%2B6_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=nightly&amp;JDK_IMPL=hotspot&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;DYNAMIC_COMPILE=true&amp;TKG_SHA=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=external&amp;UPSTREAM_JOB_NUMBER=32&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "11.0.19" 2023-04-18
OpenJDK Runtime Environment Temurin-11.0.19+6 (build 11.0.19+6)
OpenJDK 64-Bit Server VM Temurin-11.0.19+6 (build 11.0.19+6, mixed mode)
```
</details>

[openliberty_microprofile_tck_0](https://trss.adoptium.net/output/test?id=64382ade17052c671548c1da) => [deep history 0/5 passed](https://trss.adoptium.net/deepHistory?testId=64382ade17052c671548c1da) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6438292517052c671548b490&buildName=Test_openjdk11_hs_sanity.external_x86-64_linux&testId=64382ade17052c671548c1da&testName=openliberty_microprofile_tck_0)

**Comment by sophia-guo** [comment]
arm_linux:
[**Test_openjdk17_hs_extended.openjdk_arm_linux**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux/96/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0/88/) ⚠️ UNSTABLE ⚠️
[jdk_vector_2](https://trss.adoptium.net/output/test?id=643f651117052c67156fe597) => [deep history 4/10 passed](https://trss.adoptium.net/deepHistory?testId=643f651117052c67156fe597) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643f63fb17052c67156fd971&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0&testId=643f651117052c67156fe597&testName=jdk_vector_2)
[jvm_compiler_2](https://trss.adoptium.net/output/test?id=643f651117052c67156fe591) => [deep history 1/10 passed](https://trss.adoptium.net/deepHistory?testId=643f651117052c67156fe591) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=643f63fb17052c67156fd971&buildName=Test_openjdk17_hs_extended.openjdk_arm_linux_testList_0&testId=643f651117052c67156fe591&testName=jvm_compiler_2)
