### ISSUE TITLE
April release tap files

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4525]
JDK17:
[Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_1.tap ](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_1/9/artifact/aqa-tests/TKG/output_16819064432949/Test_openjdk17_hs_extended.openjdk_aarch64_linux_testList_1.tap)

[Test_openjdk17_hs_special.functional_x86-64_mac.tap](https://ci.adoptium.net/job/Test_openjdk17_hs_special.functional_x86-64_mac/107/artifact/aqa-tests/TKG/output_16818889014973/Test_openjdk17_hs_special.functional_x86-64_mac.tap)
release build: 
[AQAvitTapFiles.zip](https://github.com/adoptium/aqa-tests/files/11289394/AQAvitTapFiles.zip)

Grinder: 
[jdk17.zip](https://github.com/adoptium/aqa-tests/files/11332124/jdk17.zip)

Combined:
[AQAvitTapFiles.tar.gz](https://github.com/adoptium/aqa-tests/files/11436132/AQAvitTapFiles.tar.gz)

**Comment by sophia-guo** [comment]
JDK11:
[Test_openjdk11_hs_extended.openjdk_ppc64le_linux_testList_0.tap](https://ci.adoptium.net/job/Test_openjdk11_hs_extended.openjdk_ppc64le_linux_testList_0/90/artifact/aqa-tests/TKG/output_16818599012186/Test_openjdk11_hs_extended.openjdk_ppc64le_linux_testList_0.tap/*view*/)

release build:
[AQAvitTapFiles.zip](https://github.com/adoptium/aqa-tests/files/11289655/AQAvitTapFiles.zip)

grinder:

**Comment by sophia-guo** [comment]
jdk8:
[Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_2.tap](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_2/100/artifact/aqa-tests/TKG/output_16818966199129/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_testList_2.tap/*view*/)

[Test_openjdk8_hs_extended.openjdk_sparcv9_solaris.tap](https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris/84/artifact/aqa-tests/TKG/output_16822719961616/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris.tap)

release build: (arm32 is not available yet)
[AQAvitTapFiles.zip](https://github.com/adoptium/aqa-tests/files/11328469/AQAvitTapFiles.zip)

grinder

**Comment by smlambert** [comment]
Updated with zips of Grinders and reruns of test jobs required for the release, not including jdk8 arm32.  48 reruns needed.  This can/should be used as a release metric, the fewer required, indicates the stability and consistency of the infrastructure and test material.
