### ISSUE TITLE
Increase keep builds for certain jobs

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/aqa-tests#4578]
For several test pipelines, e.g. dev.external_imageUpload and dev.external_imagePull, each job generates multiple builds, which makes it hard to view historical builds since the default [BUILDS_TO_KEEP](https://github.com/adoptium/aqa-tests/blob/4220eef1f3c99141c45a72f60a6286add60126ca/buildenv/jenkins/testJobTemplate#L70) is `10` for all jobs.

Since `BUILDS_TO_KEEP` parameter is always re-set in multiple pipelines, we plan to use another parameter `BUILDS_MULTIPLE_TO_KEEP` to increase the keep builds number for pipeline name with `imageUpload` and `imagePull`.

**Comment by LongyuZhang** [comment]
FYI @llxia @smlambert @tajila

**Comment by smlambert** [comment]
Does this actually require a new parameter for this?  Could it not be accomplished by hard-coding to a certain factor that is then multiplied by BUILDS_TO_KEEP.

**Comment by LongyuZhang** [comment]
As discussed in the meeting, we plan to set a multiplier number with these pipelines for now, and if needed later, we can modify it to be a parameter then.

**Comment by karianna** [comment]
Has infra been informed - this will mean more space requirements

**Comment by smlambert** [comment]
@karianna - nothing changes at ci.adoptium.net, this just allows for other servers and people to set a multiplier and 'tune' should they want to adjust the default settings.
