### ISSUE TITLE
LargeGatheringWrite test runs out of memory on test-azure-win2012r2-x64-3

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#4583]
extended.openjdk job ran on [test-azure-win2012r2-x64-3](https://ci.adoptium.net/computer/test-azure-win2012r2-x64-3) and didn't find enough memory to launch the LargeGatheringWrite unit test.

Link: https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_1/8/

Error message:
```
09:02:37  ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Unable to allocate 536870912 bytes
09:02:37  REASON: User specified action: run main/othervm/timeout=480 -Xmx4G LargeGatheringWrite 
```

My first theory is that something else on that machine is using up all the memory during the test, as test-azure-win2012r2-x64-3 *should* have (according to MACHINE INFO) over 3g of available physical memory (4.3g total).

Next action: Will open an infra issue to start, to see what else is running on that machine.

Links: [This issue](https://github.com/adoptium/infrastructure/issues/2663) *might* be related, as it identifies a number of machines that had low memory during mid-2022, but this is a separate issue for the time being as that issue doesn't mention LargeGatheringWrite.

**Comment by smlambert** [comment]
I would rather not raise 2 issues (test and infra) for one failure.  As per the test triage guidance, triage determines which repo an issue should initially be raised in, and that singular issue could then be transferred to a different repo if needed (when more info is gathered if the source of the problem would need to be fixed elsewhere).

**Comment by adamfarley** [comment]
> I would rather not raise 2 issues (test and infra) for one failure. As per the test triage guidance, triage determines which repo an issue should initially be raised in, and that singular issue could then be transferred to a different repo if needed (when more info is gathered if the source of the problem would need to be fixed elsewhere).

I didn't actually know you could move issues between repositories last that. Something new every day. :)

In any case, it's clear I need to refresh myself on the triage guidance, so I'll go have a read now. Thanks for the reminder 👍

**Comment by adamfarley** [comment]
As for this issue, I'll close it and copy the information into the infra issue.
