### ISSUE TITLE
Test Failure: SEGSEGV from TestGetEventTypes.java during JfrNetworkInterfaceName frame

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#4613]
**Core Facts**

Frequency: Seen once so far.
Platform: Solaris SparcV9
JDK Version: JDK8u382
Test Super Target: extended.OpenJDK
Test Target: jdk_jfr_0
Test: jdk/jfr/api/flightrecorder/TestGetEventTypes.java
Link: https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_sparcv9_solaris_testList_1/81/consoleFull

**Additional Data**

This is an upstream issue that I've raised [here](https://bugs.openjdk.org/browse/JDK-8309729)

Finally, here's a copy of the full error message: 
[full_test_output.txt](https://github.com/adoptium/aqa-tests/files/11706933/full_test_output.txt)

**Comment by adamfarley** [comment]
I'm raising this issue here to:
- track the progress of the upstream issue associated with this failure ([link](https://bugs.openjdk.org/browse/JDK-8309729)).
- provide updates when we're close to a fix
- allowing non-OpenJDK contributors to add related comments
- and to track the temporary exclusion of this test, as well as the unexclusion once we have a proven fix.

**Comment by smlambert** [comment]
Also see other crashes, reported https://github.com/adoptium/aqa-tests/issues/4359 (appears to crash on stop events).

**Comment by adamfarley** [comment]
There I was trying to find the log files in the empty workspace. :)

Thanks for the information Shelley! I didn't see those issues. Will close this one and append the information to #4359.

I'll leave the upstream issue open, and I'll add the core+log files and the names of the other affected tests.

**Comment by smlambert** [comment]
Thanks for raising the upstream one, I was just noting the others because it seems to have arisen in same and slightly different forms before.  :)
