### ISSUE TITLE
Error message enhancement: Multijvm tests with Agent turned off

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#4637]
### Problem 1: Wrong Error

In JavaTestRunner.java, there's an error that reads:

```
System.out.println("Only non-multijvm tests are supported with Agent turned off");
```

[Link.](https://github.com/adoptium/aqa-tests/blob/4a4f3aa15ef338ed8feba3a1353ba922612755c2/jck/jtrunner/JavaTestRunner.java#L1024)

However, the if statement that must fail in order to produce this error is:

```
if (testExecutionType.equals("multijvm") && withAgent.equals("off")) {
```

[Link.](https://github.com/adoptium/aqa-tests/blob/4a4f3aa15ef338ed8feba3a1353ba922612755c2/jck/jtrunner/JavaTestRunner.java#LL901C3-L901C73)

@Mesbah-Alam - Could you please review this? These seem to contradict each other. Either Multijvm tests **can** run with the agent turned off, or they **cannot**, surely?

### Problem 2: Unused keyword

On [line 608](https://github.com/adoptium/aqa-tests/blob/21c8dd1eeb39e90c8eac00cbcdba25129a80ca4f/jck/jtrunner/JavaTestRunner.java#L608) the string "&!robot" is appended to the "keyword" variable.

The keyword/s have already been added to fileContent for RUNTIME, so this keyword will never be used.

@Mesbah-Alam - Can you verify this? Perhaps we should move that logic further up?

**Comment by smlambert** [comment]
The code in question is a carryover from SVT-contributed code of long ago (so carries with it need for cleanup and maintenance, technical debt).  The creation of JavaTestUtil was a first cut at removing this layer all-together, for now see some cleanup in #4750

**Comment by adamfarley** [comment]
Thanks Shelley! :)
