### ISSUE TITLE
Adoptium exclude files contain duplicate tests

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#4650]
**Summary**

Duplicate tests in the exclude files are causing failures. Will fix and take action to help prevent future duplicates.

**Details**

When a test appears in an exclude file multiple times, the platforms in the final instance override the platforms in the other instances.

Scenario:
- Test is excluded on platform A.
- Test is excluded on platform B.
- Platform B's exclude file entry overrides the entry for platform A.
- Test subsequently re-enters the test bucket for platform A, despite the exclusion.

However, as the exclude files are not always kept alphabetical, duplicate entries can be overlooked when excluding tests.

Several instances of this have been found, including a long-running test that I tried to exclude last week, so I'm just as guilty of this as anyone.

**Plan of action**

I plan to do this:
- [x] 1) Comment out the duplicate entries in the exclude files.
- [x] 2) Ensure that the commented-out tests have their platforms appended to the non-excluded duplicate entries.
- [x] 3) Tidy up the exclude files to make them easier to read.
- [x] 4) Add a comment to Slack to advise people of the situation and help them avoid the issue in future.
- [ ] 5) Create a Git PR Check that identifies duplicate entries in the future.
Notes for 5: Cannot simply search exclude files for duplicate lines, as the hash lines are all duplicates, and duplicate *test names* may still have different platforms and issue IDs in the same line. Parse by whitespace? Must tolerate tabs and spaces.

**Comment by adamfarley** [comment]
Actions 1, 2, and 3 are being worked here: https://github.com/adoptium/aqa-tests/pull/4651
Action 4 was executed here: https://adoptium.slack.com/archives/C5219G28G/p1687957144892759
Action 5 is pending.

**Comment by smlambert** [comment]
5) is partially addressed (part of https://github.com/adoptium/aqa-tests/issues/1853, there is a script written as part of a CanOSP project that parses all problemlists and does some checking for correct format and duplicate entries).  Noting, it is not enabled to run regularly, and it does more than check for correct formatting and duplicate entries. (related: https://github.com/adoptium/aqa-tests/tree/master/scripts/disabled_tests#dry-run-to-see-errors-and-warnings).

**Comment by adamfarley** [comment]
Looks like point 5 is handled by Shelley's issue, so I'll defer there to avoid duplication.

As for points 1-3, the PR is ready for review [here](https://github.com/adoptium/aqa-tests/pull/4651).

**Comment by adamfarley** [comment]
Fix in, issue resolved.
