### ISSUE TITLE
Lucene junit reports do not include failed tests 

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-tests#467]
https://ci.adoptopenjdk.net/view/work%20in%20progress/job/test_personal

Note: the the above build fails with following test failures: 

```
16:43:23    [junit4] Tests with failures [seed: E5783DE2DDD096EC]:
16:43:23    [junit4]   - org.apache.solr.cloud.autoscaling.IndexSizeTriggerTest.testSplitIntegration
16:43:23    [junit4]   - org.apache.solr.cloud.api.collections.ShardSplitTest.testSplitWithChaosMonkey
16:43:23    [junit4]   - org.apache.solr.cloud.autoscaling.sim.TestGenericDistributedQueue.testDistributedQueue
16:43:23    [junit4]   - org.apache.solr.cloud.autoscaling.sim.TestGenericDistributedQueue (suite)
```

However, the junit report shows all tests passed. For some reason the report is not listing failed tests. This needs to be investigated in a separate issue.

**Comment by smlambert** [comment]
Closing as stale, we are going through a health assessment of external tests via https://github.com/adoptium/aqa-tests/issues/3187 and will create fresh issues as they arise.
