### ISSUE TITLE
CryptoTests_0 fails for JDK 21 due to new algorithm

### ISSUE THREAD

**Issue by jiekang** [adoptium/aqa-tests#4731]
Fails consistently for JDK21.

Relevant output from:
https://ci.adoptium.net/job/Test_openjdk21_hs_extended.functional_x86-64_linux/123/consoleFull

```
11:56:34  running: cryptotest.tests.KeyFactoryTests
11:56:34  0)	SUN: 	HSS/LMS~HSS/LMS	 (KeyFactory)
11:56:34  cryptotest.utils.AlgorithmRunException: java.lang.UnsupportedOperationException: Tranlated key is null for HSS/LMS inSUN
11:56:34  failed to use: HSS/LMS from SUN version 21
11:56:34  Failed
11:56:34  1)	SUN: 	HSS/LMS~OID.1.2.840.113549.1.9.16.3.17	 (KeyFactory)
11:56:34  cryptotest.utils.AlgorithmRunException: java.lang.UnsupportedOperationException: Tranlated key is null for HSS/LMS inSUN
11:56:34  failed to use: HSS/LMS from SUN version 21
11:56:34  Failed
11:56:34  2)	SUN: 	HSS/LMS~1.2.840.113549.1.9.16.3.17	 (KeyFactory)
11:56:34  cryptotest.utils.AlgorithmRunException: java.lang.UnsupportedOperationException: Tranlated key is null for HSS/LMS inSUN
11:56:34  failed to use: HSS/LMS from SUN version 21
11:56:34  Failed
[...]
```

JDK21 has new signature algorithms:
https://bugs.openjdk.org/browse/JDK-8298127
https://jdk.java.net/21/release-notes

Does cryptotest.tests.KeyFactoryTests need to be updated?

**Test Info**
Test Name: CryptoTests_0
Test Duration: 6 min 23 sec
Machine: test-docker-centos8-x64-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=64e5189617052c6715cccca1

**Build Info**
Build Name: Test_openjdk21_hs_extended.functional_x86-64_linux
Jenkins Build start time: Aug 22 2023, 11:52 am
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk21_hs_extended.functional_x86-64_linux/123/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=64e5177417052c6715ccc71a

**Java Version**
openjdk version "21-beta" 2023-09-19
OpenJDK Runtime Environment Temurin-21+35-202308221542 (build 21-beta+35-ea)
OpenJDK 64-Bit Server VM Temurin-21+35-202308221542 (build 21-beta+35-ea, mixed mode, sharing)

**This test has been failed 45 times since May 17 2023, 10:51 pm**
**Java Version when the issue first seen**
openjdk version "21-beta" 2023-09-19
OpenJDK Runtime Environment Temurin-21+23-202305180244 (build 21-beta+23-202305180244)
OpenJDK 64-Bit Server VM Temurin-21+23-202305180244 (build 21-beta+23-202305180244, mixed mode, sharing)
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk21_hs_extended.functional_x86-64_linux/41/

The test failed on machine test-docker-centos8-x64-1 2 times 
The test failed on machine test-docker-ubuntu2004-x64-1 4 times 
The test failed on machine test-docker-fedora35-x64-1 4 times 
The test failed on machine test-ibmcloud-rhel7-x64-1 4 times 
The test failed on machine test-ibmcloud-ubuntu1604-x64-1 5 times 
The test failed on machine test-docker-ubi8-x64-1 3 times 
The test failed on machine test-equinix_esxi-ubuntu2204-x64-1 1 times 
The test failed on machine test-docker-fedora35-x64-2 5 times 
The test failed on machine test-equinix_esxi-ubuntu2204-x64-2 1 times 
The test failed on machine test-docker-ubi8-x64-2 4 times 
The test failed on machine test-docker-fedora37-x64-1 2 times 
The test failed on machine test-docker-debian11-x64-2 1 times 
The test failed on machine test-docker-ubuntu2204-x64-1 3 times 
The test failed on machine test-docker-ubuntu2004-x64-2 2 times 
The test failed on machine test-docker-fedora37-x64-2 1 times 
The test failed on machine test-docker-fedora37-x64-3 2 times 
The test failed on machine test-docker-ubuntu2204-x64-3 1 times

**Comment by jiekang** [comment]
@zzambers ^ thoughts?

**Comment by jiekang** [comment]
Probably needs another if statement case for the algorithms similar to:

https://github.com/rh-openjdk/CryptoTest/blob/master/cryptotest/tests/KeyFactoryTests.java#L175

**Comment by jiekang** [comment]
Ah, just saw this was a dupe of https://github.com/adoptium/aqa-tests/issues/4662

Sorry @smlambert : As this one has some analysis now, should 4662 be closed? My bad.

**Comment by zzambers** [comment]
I'll take a look.

**Comment by zzambers** [comment]
Created PRs to fix problems on JDK21:
https://github.com/rh-openjdk/CryptoTest/pull/52
https://github.com/rh-openjdk/CryptoTest/pull/51

**Comment by jiekang** [comment]
Closing. The tests now pass on all platforms [1]. The AIX failures are due to file system space issues like:

```
Caused by: java.io.IOException: There is not enough space in the file system.
```

[1] https://trss.adoptium.net/testPerPlatform?testId=64f69a1617052c67151443a9


Thanks @zzambers!
