### ISSUE TITLE
Update v0.9.8-release branch with new tag for aqa-systemtest

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4778]
Update the testenv.properties file to pick up v0.9.8.1 tag for aqa-systemtest

[Line 10](https://github.com/adoptium/aqa-tests/blob/v0.9.8-release/testenv/testenv.properties#L10) to be changed in the v0.9.8-release branch.

**Comment by sophia-guo** [comment]
Done by #4779
