### ISSUE TITLE
Clone the required repo only in test build

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4810]
The Openj9 repo is only needed for functional testing. For non-functional test builds (i.e., OpenJDK, system, etc), we do not need to clone the openj9 repo.

We can be more efficient by cloneing the required repo only. This will make test build run fast, save more machine time, and reduce unnecessary network activities.

**Comment by Adirala-Krishna** [comment]
@llxia Our **VENDOR_TEST_REPOS** are not getting cloned after this commit and we are facing issues while running svt tests in jenkins.

**Job link where tests ran before commit :** https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/8882/console
**rebuilding same job link without changing anything,** **`Error: cannot find the following tests` issue is seen here as repo is not getting cloned :** https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/8912/console

**Error :** 
No tests found for target: testList
No parallel test lists generated.
Error: cannot find the following tests: mix.3hrs_1, mix.3hrs_2, mix.3hrs_3, mix.3hrs_4 (note: group target such as sanity is not accepted inside testList)
makeGen.mk:45: recipe for target 'autogen' failed

Test seems running fine when this commit has been reverted : https://hyc-runtimes-jenkins.swg-devops.com/job/Grinder_CR/8933/console

Can you please check on this. Thank you.

**Comment by llxia** [comment]
@Adirala-Krishna PR https://github.com/adoptium/aqa-tests/pull/4818 should address the issue

**Comment by Adirala-Krishna** [comment]
Issue got resolved, Thank you very much @llxia
