### ISSUE TITLE
rerun failed openjdk tests with jdk_custom | hotspot_custon link should force set PARALLEL=None

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4830]
rerun failed openjdk tests with jdk_custom | hotspot_custon link fill most of parameters same as the current job. If the current job is a parents job of child job and it's parameter PARALLEL=Dynamic for rerun link the parameter should be set as None to avoid parallel mode. The reason is if there are too many testcases failure the rerun jdk_custom link won't work the suggestion is using the rerun failed target link. Rerun jdk_custom link works for quick rerun of a few test failures which doesn't need to run parallel.

**Comment by smlambert** [comment]
And also set RERUN_ITERATIONS=0

**Comment by sophia-guo** [comment]
RERUN_ITERATIONS=0 is set for rerun link https://github.com/adoptium/aqa-tests/pull/4441/files, 

Rerun _custom is also using the env.RERUN_LINK https://github.com/llxia/aqa-tests/blob/c33c62b3dd398456e622af948e961e1c8942b022/buildenv/jenkins/JenkinsfileBase#L1153

So any update about the url should be moved before  https://github.com/adoptium/aqa-tests/pull/4441/files#diff-21a56f751656da4e3e5abee13913f51a269d6eb43235bc16fc4be21ef70deaf2R1097

**Comment by sophia-guo** [comment]
For reset the parameter, current solution is loop all parameters { add the (key value) set,   if the key is specified parameter get the current set ( key, value) }  after the loop  replace the current set to preferred one. A bit of complicated. 

We can do as : 
loop all parameters
         if the key is specified parameter, reset the value (for example, key PARALLEL, RERUN_ITERATIONS)
         add the (key, value)
done

**Comment by jiekang** [comment]
I can take a look
