### ISSUE TITLE
temurin21 riscv64 start jtreg crash: v  ~StubRoutines::arrayof_jlong_disjoint_arraycopy

### ISSUE THREAD

**Issue by sendaoYan** [adoptium/aqa-tests#4833]
test command:

/home/yansendao/software/jdk/riscv64/jdk-21.0.1+12/bin/java -classpath /home/yansendao/software/jdk/jtreg-7/lib/jtreg.jar com.sun.javatest.regtest.agent.GetSystemProperty java.version

result:

![image](https://github.com/adoptium/aqa-tests/assets/24123821/c30b3a13-a3b8-46f8-ae2b-7372460221ac)

jdk version:

![image](https://github.com/adoptium/aqa-tests/assets/24123821/13411a3e-ca8c-4f61-98a5-deef282fe658)

env info:

![image](https://github.com/adoptium/aqa-tests/assets/24123821/cf253ba9-4a75-4566-a4ae-94e04b004199)

jtreg version: 7.3.1.1

[hs_err_pid4058728.log](https://github.com/adoptium/aqa-tests/files/13112828/hs_err_pid4058728.log)

**Comment by sxa** [comment]
Do you know what version of the vector instructions your machine is using? I get the same when running on a machine with 0.7 but it ought to be ok if yours has a 1.0 implementation (I see your machine is listed as `rv64imafdcv` but doesn't have the `cpu-vector` version listed in the error log.

**Comment by sxa** [comment]
If the vector theory is correct then it's likely due to the build not having https://github.com/openjdk/jdk21u/pull/203 in it, which didn't make it in to 21.0.1

**Comment by sendaoYan** [comment]
The build https://ci.adoptium.net/job/build-scripts/job/jobs/job/evaluation/job/jobs/job/jdk21[…]/OpenJDK21U-jdk_riscv64_linux_hotspot_2023-10-25-09-44.tar.gz works fine.

![image](https://github.com/adoptium/aqa-tests/assets/24123821/e2b309ac-096c-4767-8272-d155fcdab11b)
