### ISSUE TITLE
Release report summary showing in-accurate report from previous run ?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#4838]
Running a release report summary on http://20.90.182.165/releaseSummary?parentId=653a8b3a20748f006f9329f2&buildName=release-openjdk17-pipeline #46

Showed the following, however none of the sign_* and create_installer_windows had failed, they had failed in the previous run of this job, so it seems it's picking up the previous run or from some cache of the previous result? is this correct? :

#### Release Summary Report for release-openjdk17-pipeline 
**Report generated at:** Fri, 27 Oct 2023 08:54:36 GMT 
 
TRSS [Build](http://20.90.182.165/buildDetail?parentId=653a8b3a20748f006f9329f2&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](http://20.90.182.165/resultSummary?parentId=653a8b3a20748f006f9329f2) 
Jenkins Build URL https://ci.adoptium.net/job/build-scripts/job/release-openjdk17-pipeline/46/ 
Started by upstream project "build-scripts/utils/releaseTrigger_jdk17u" build number 3054 at 26/10/2023, 16:45:12 

 --- 

[**create_installer_windows**](undefined) ❌ undefined ❌

[**jdk17u-release-windows-x86-32-temurin**](https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk17u/job/jdk17u-release-windows-x86-32-temurin/18/) ⚠️ UNSTABLE ⚠️

[**sign_build**](undefined) ❌ undefined ❌

[**sign_installer**](undefined) ❌ undefined ❌

[**sign_temurin_gpg**](undefined) ❌ undefined ❌

 --- 

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows/138/) ⚠️ UNSTABLE ⚠️

[**Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0**](https://ci.adoptium.net/job/Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0/114/) ⚠️ UNSTABLE ⚠️
[jdk_tools_2](http://20.90.182.165/output/test?id=653b097c20748f006f93ab2c) => [deep history 7/20 passed](http://20.90.182.165/deepHistory?testId=653b097c20748f006f93ab2c) | [possible issues](http://20.90.182.165/possibleIssues?buildId=653b083f20748f006f93a3e6&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0&testId=653b097c20748f006f93ab2c&testName=jdk_tools_2)
[jvm_compiler_2](http://20.90.182.165/output/test?id=653b097c20748f006f93ab27) => [deep history 0/25 passed](http://20.90.182.165/deepHistory?testId=653b097c20748f006f93ab27) | [possible issues](http://20.90.182.165/possibleIssues?buildId=653b083f20748f006f93a3e6&buildName=Test_openjdk17_hs_extended.openjdk_x86-32_windows_testList_0&testId=653b097c20748f006f93ab27&testName=jvm_compiler_2)

**Comment by smlambert** [comment]
This is because the functional ID used to query Jenkins does not have access to those jobs.  Please see https://github.com/adoptium/ci-jenkins-pipelines/issues/236

I will close this issue as a dup of ci-jenkins-pipelines/issues/236
