### ISSUE TITLE
Move getJtreg ant target to a shared location

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4848]
As mentioned in https://github.com/adoptium/aqa-tests/pull/4835#issuecomment-1790587567 and also noting that jtreg is used for both openjdk and functional test groups, we should pull that target into a utilities file so it can be included into the different test groups where its used (and avoid duplicate ant script code).

https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L86-L117
https://github.com/adoptium/aqa-tests/blob/master/functional/security/Crypto/build.xml#L97-L132
and in the ssl-tests also.

**Comment by llxia** [comment]
Just for the record, the jtreg jar version logic: https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L44-L67

**Comment by llxia** [comment]
@annaibm Please take a look at this issue after https://github.com/adoptium/aqa-tests/pull/4853 is merged. Thanks

**Comment by llxia** [comment]
We may want to put the common code under https://github.com/adoptium/TKG/tree/master/scripts
