### ISSUE TITLE
Testing on jdk-17.0.10+1 requires jtreg version 7.3.1 b1 or higher

### ISSUE THREAD

**Issue by pshipton** [adoptium/aqa-tests#4851]
https://openj9-jenkins.osuosl.org/job/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OpenJDK17_testList_2/8/console
`Error: The testsuite at /home/jenkins/workspace/Test_openjdk17_j9_sanity.openjdk_aarch64_linux_OpenJDK17_testList_2/aqa-tests/openjdk/openjdk-jdk/test/jdk requires jtreg version 7.3.1 b1 or higher and this is jtreg version 6-dev+1.`

```
23:57:05  openjdk version "17.0.10-internal" 2024-01-16
23:57:05  OpenJDK Runtime Environment (build 17.0.10-internal+0-adhoc..BuildJDK17aarch64linuxOpenJDK17)
23:57:05  Eclipse OpenJ9 VM (build master-5c2e7031d83, JRE 17 Linux aarch64-64-Bit Compressed References 20231103_63 (JIT enabled, AOT enabled)
23:57:05  OpenJ9   - 5c2e7031d83
23:57:05  OMR      - 89febafbc23
23:57:05  JCL      - 1cd3f35fa7e based on jdk-17.0.10+1)
```

The jdk17 repo and branch/sha are OpenJ9 specific but the point is this is trying to test the recently tagged jdk-17.0.10+1 level.
```
23:58:28       [exec]   Fetch URL: https://github.com/ibmruntimes/openj9-openjdk-jdk17.git
23:58:28       [exec] sha:
23:58:28       [exec] 1cd3f35fa7e8a5aa460ef71888ccf377c4c4334f
```

**Comment by pshipton** [comment]
@llxia fyi

**Comment by llxia** [comment]
@annaibm could you update the logic? The code is at https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L50-L63
- Update the if block, so that JDK17 uses jtreg_7_3_1_1 (same as JDK21/22)
- Run Grinder using JDK17 to verify the change

**Comment by llxia** [comment]
This issue should be fixed by https://github.com/adoptium/aqa-tests/pull/4853
