### ISSUE TITLE
Remove JavaTestRunner

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4864]
[JavaTestRunner](https://github.com/adoptium/aqa-tests/blob/master/jck/jtrunner/JavaTestRunner.java) and [JavatestUtil](https://github.com/adoptium/aqa-tests/blob/master/jck/jtrunner/JavatestUtil.java) are similar file. 

And most of tests are using JavatestUtil except https://github.com/adoptium/aqa-tests/blob/4a1eca103c3a40e98f36328ca03f2eef02de05d9/jck/jck.mk#L129

https://github.com/search?q=repo%3Aadoptium%2Faqa-tests%20JCK_CMD_TEMPLATE&type=code

I think if we update these two tests to run via JavatestUtil, we can remove JavaTestRunner.

**Comment by smlambert** [comment]
Yes, that was the next step in the 'evolution' of this automation (stripping away unneeded layers).

**Comment by llxia** [comment]
@annaibm can you take a look at this one? Thanks
