### ISSUE TITLE
Add reproducible comparison tests in aqa-tests

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#4868]
Reproducible comparison tests have been enable as jenkins job in [Adoptium](https://ci.adoptium.net/view/ReproducibleBuild/). To broaden the functionalities we'd like to enhance it and incorporate to be part of aqa-tests, which can benefit from aqa-tests and trss' features. 

- https://github.com/adoptium/temurin-build/pull/3568
- https://github.com/adoptium/temurin-build/pull/3628
- https://github.com/adoptium/ci-jenkins-pipelines/pull/908

**Comment by smlambert** [comment]
Discussion about this is found in https://github.com/adoptium/temurin-build/issues/3587
