### ISSUE TITLE
Enable verbose GC log in openjdk tests

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4872]
We would like to collect more information for testing to help debug. To start, we can enable verbose gc log `-Xverbosegclog` in openjdk test. 

doc: https://www.ibm.com/docs/en/sdk-java-technology/8?topic=options-xverbosegclog

This option can be prepended in EXTRA_OPTIONS in https://github.com/adoptium/aqa-tests/blob/master/openjdk/openjdk.mk

FYI @dmitripivkine

**Comment by llxia** [comment]
@annaibm could you help with this issue? Thanks

**Comment by annaibm** [comment]
@llxia Should I need to prepend `-Xverbosegclog` option to EXTRA_OPTIONS for all operating systems?

**Comment by llxia** [comment]
> Should I need to prepend -Xverbosegclog option to EXTRA_OPTIONS for all operating systems?

Yes, but only for JDK_IMPL= openj9 or ibm
