### ISSUE TITLE
Add TestHeadlessComponent suite to AQAvit

### ISSUE THREAD

**Issue by andrlos** [adoptium/aqa-tests#4875]
This issue encapsulates the desire to add this set of test to aqa-tests:

https://github.com/rh-openjdk/TestHeadlessComponents

In short the testsuite basically monitors behavior of swing components with both jdk and jre in headless environment (basically a corner case test for application of java in server environment).

As of writing this issue there is a new addition to the testsuite in progress to make it multiplatform friendly (as originally intended only for linux).

**Comment by andrlos** [comment]
https://github.com/adoptium/aqa-tests/pull/5084

**Comment by smlambert** [comment]
Closed via https://github.com/adoptium/aqa-tests/pull/5084
