### ISSUE TITLE
Update testHost1Name to remove wiki.eclipse.org

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4877]
Related to temurin-compliance/issues/416 we need to update to testHost1Name since wiki.eclipse.org is going to be deprecated.  

Need to determine what URL is best suited and change this line: 
https://github.com/adoptium/aqa-tests/blob/master/jck/jtrunner/config/default/jcktest.properties#L10

**Comment by llxia** [comment]
cc @JasonFengJ9 for awareness

**Comment by smlambert** [comment]
@steelhead31 - would you have a suggestion for a replacement for this?

**Comment by steelhead31** [comment]
@smlambert  I've identified a potential replacment, Im going to run a test on a few platforms with my new values, to ensure it works.
