### ISSUE TITLE
Smoke tests failing on aarch64 mac platforms (related to Orka dynamic agents)

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4899]
Thank you for reporting a broken build! Please fill in the following details:

- **Jenkins link to the failing log:**
- https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk17u/job/jdk17u-mac-aarch64-temurin_SmokeTests/215/console
- **Which platforms (OS+arch) are affected?:** mac platforms
- **If you look at the historic logs, does the problem appear to be specific to one machine?**
- **Link to any upstream project bug report (e.g. [OpenJ9](https://github.com/eclipse/openj9/issues)/[JBS](https://bugs.openjdk.java.net/browse))**

All aarch64 mac nodes are now being spun up from Orka, which means no static machines are waiting for a test job being sent to them.  This was addressed for AQAvit tests via this [PR/844](https://github.com/adoptium/ci-jenkins-pipelines/pull/844), but for some reason the smoke tests do not call into this method ([waitForANodeToBecomeActive()](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L1759-L1796)).

x86 mac smoke tests are running and passing because there are still 2 static machines online in Jenkins, so jobs find available nodes

**Comment by smlambert** [comment]
A fix for this issue will involve updating [openjdk_tests PLATFORM_MAP](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L3) with 'DynamicAgents' : ['orka'] for the 2 mac platforms.

**Comment by sophia-guo** [comment]
Smoke tests and aqa-tests triggerred by pipeline has the parameter [context.string(name: 'ACTIVE_NODE_TIMEOUT', value: "${buildConfig.ACTIVE_NODE_TIMEOUT}"),](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/build/common/openjdk_build_pipeline.groovy#L330) . Currently the parameter is set as 0, which means if there is no label agent available it will exit.

```
[Pipeline] nodesByLabel
07:29:27  Could not find any nodes with 'ci.role.test&&hw.arch.aarch64&&(sw.os.osx||sw.os.mac)' label
[Pipeline] timeout
07:29:27  Timeout expired 0 ms ago
07:29:27  Cancelling nested steps due to timeout
```

By default the value is 15 mins in aqa-tests jenkins https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/openjdk_tests#L307-L314

**Comment by smlambert** [comment]
@sophia-guo - requesting your review on https://github.com/adoptium/aqa-tests/pull/4903 to address this issue.
