### ISSUE TITLE
TKG build failure on `temurin-build` Github actions checks

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#4914]
Temurin buil PR checks are currnetly failiung when building TKG material:

Copying this from my slack message:

Something in that area is causing a failure on the temurin-build automated PR checks and it wasn't immediately obvious from looking at recent PRs what it might be: https://github.com/adoptium/temurin-build/pull/3538#issuecomment-1846911986
Relevant run of the check: https://github.com/adoptium/temurin-build/actions/runs/7128536879/job/19455522686?pr=3538

**Comment by smlambert** [comment]
Noting: https://github.com/adoptium/temurin-build/blob/master/.github/workflows/build.yml#L95-L108 it is trying to run the smoke test as part of PR testing

**Comment by smlambert** [comment]
@llxia - FYI, this is related to recent improvements to how we handle dependencies we download.  

Looks like json.jar file is in an unexpected location now for run-aqa (github workflows).

**Comment by llxia** [comment]
https://github.com/adoptium/temurin-build/actions/runs/7128536879/job/19455522686?pr=3538#step:8:407

We need to set `LIB_DIR` in run aqa.

**Comment by sophia-guo** [comment]
LIB_DIR has the default value, which should not need to be explicitly export. The change https://github.com/adoptium/TKG/pull/476/files in settings.mk is invisible to  make compile process.

**Comment by sophia-guo** [comment]
I have rerun the github runner tests seems initial issue is fixed. https://github.com/adoptium/temurin-build/actions/runs/7172315110/job/19572418555#step:8:411. However similar issue happened when compile the tests, https://github.com/adoptium/temurin-build/actions/runs/7172315110/job/19572418555#step:8:552. In the locally run both compile process with build_tool.xml and build_test.xml are run correctly with -DLIB_DIR=/Users/.../test/aqa-tests/TKG/../TKG/lib. Reopen untill all issues be addressed.

**Comment by sophia-guo** [comment]
rerun jobs passed https://github.com/adoptium/temurin-build/actions/runs/7172315110/job/19613059609
