### ISSUE TITLE
ssl-tests fail for AIX, sparcv9_solaris, x86-64_solaris platforms

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4943]
We should disable these tests for those platforms, as they are not passing (and not skipping properly) on those platforms and by excluding them in the playlist, they will not get sent to these platforms to run.  

Noting that if we do exclude this test target, and it is currently the only target in dev.functional, then we should update the ci-jenkins-pipeline default settings for these platforms, or they will fail with "No Tests Found".

---

**Test Info**
Test Name: ssl-tests_0
Test Duration: 2 sec
Machine: test-osuosl-aix72-ppc64-1
TRSS link for the test output: https://trss.adoptium.net/output/test?id=659987e920748f006f19ea3d

**Build Info**
Build Name: Test_openjdk8_hs_dev.functional_ppc64_aix
Jenkins Build start time: Jan 06 2024, 07:40 am
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk8_hs_dev.functional_ppc64_aix/5/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=6599871a20748f006f19e825

**Java Version**
openjdk version "1.8.0_402-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_402-beta-202401061209-b05)
OpenJDK 64-Bit Server VM (Temurin)(build 25.402-b05, mixed mode)

**This test has been failed 5 times since Dec 09 2023, 07:46 am**
**Java Version when the issue first seen**
openjdk version "1.8.0_402-beta"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_402-beta-202312091209-b04)
OpenJDK 64-Bit Server VM (Temurin)(build 25.402-b04, mixed mode)
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk8_hs_dev.functional_ppc64_aix/1/

The test failed on machine test-osuosl-aix72-ppc64-1 2 times 
The test failed on machine test-osuosl-aix72-ppc64-2 1 times 
The test failed on machine test-osuosl-aix72-ppc64-3 2 times 

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=ssl-tests_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=1&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=ppc64_aix&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;RERUN_ITERATIONS=0&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=master&amp;LIGHT_WEIGHT_CHECKOUT=true&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=8&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk8u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Fjdk8u%2Fjdk8u-aix-ppc64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=dev&amp;LABEL_ADDITION=sw.os.aix.7_2&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=true&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=false&amp;BUILD_LIST=functional&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=425&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=10&amp;JVM_OPTIONS=&amp;PARALLEL=None)

**Comment by smlambert** [comment]
These tests are in dev level so do not affect the release activities, though we should still plan to create exclusions as they will fail during our weekly test runs where they have been added.

**Comment by zzambers** [comment]
Currently ssl-tests are windows, linux and mac only. See: https://github.com/rh-openjdk/ssl-tests/pull/21
I'll create PR with fix.
