### ISSUE TITLE
Remove check_version() in common_functions.sh for external tests

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#4949]
```
00:01:15.569       [exec] build_image.sh criu-ubi-portable-checkpoint 21 openj9 ubi jdk full linux_x86-64 ubi8-with-criu/linux_ppc-64_le-ubi8-criu 0 
00:01:15.569       [exec] ERROR: Invalid Version: 21
00:01:15.569       [exec] Usage: /home/jenkins/workspace/Test_openjdk21_j9_dev.external_ppc64le_linux_imageUpload/aqa-tests/TKG/../../jvmtest/external/external.sh [8 11 17]
```
[job link](https://hyc-runtimes-jenkins.swg-devops.com/job/Test_openjdk21_j9_dev.external_ppc64le_linux_imageUpload/9/)

I will add 21 at https://github.com/adoptium/aqa-tests/blob/master/external/common_functions.sh#L17 for now.
However, the root question is why we have `Supported versions` list at all.

**Comment by llxia** [comment]
@smlambert @sophia-guo do you have any idea why we have the `Supported versions` list?

**Comment by smlambert** [comment]
I do not recall that there is a good reason to limit, in fact, I vaguely recall it was an area that we were planning to simplify.  For external tests that can not run in later versions of Java, we can control that in the playlist for those targets.

**Comment by llxia** [comment]
Thanks @smlambert . I will update the issue title to reflect the required action.

**Comment by llxia** [comment]
@annaibm can you work on this when you have time? Thanks
