### ISSUE TITLE
UPSTREAM_JOB_NUMBER and UPSTREAM_TEST_JOB_NUMBER missing causing NumberFormatException

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#4972]
In certain cases, UPSTREAM_JOB_NUMBER and UPSTREAM_TEST_JOB_NUMBER do not get copied into rebuild parameters when rerun in Grinder.  This culminates in `Exception: java.lang.NumberFormatException: For input string: ""`.

Example: https://ci.adoptium.net/job/Grinder/8493/ which is a rerun in Grinder 

This does not happen in all cases/paths, need to determine when this occurs and when does not.

**Comment by smlambert** [comment]
Example:
https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.openjdk_x86-64_linux/155/ when trying to launch jdk_custom targets from that pipeline in https://ci.adoptium.net/job/Grinder/8538/, see same issue

**Comment by sophia-guo** [comment]
The failed testcase name includes #. All parameters after custom_target are cut. Need to use URLEncoder.
