### ISSUE TITLE
Execute OpenJCEPlus tests as part of a test target

### ISSUE THREAD

**Issue by jasonkatonica** [adoptium/aqa-tests#4979]
A new component is being bundled within the Semeru Java runtime called `OpenJCEPlus`. The `OpenJCEPlus` project contains a set of `Junit` test cases that we would like to create a specific test target that can be used to execute the tests. This test target we expect to be run as part of the Semeru release process for all FIPS 140-3 platforms and releases supported. 

The tests are located in this directory that we would like to execute:

https://github.com/IBM/OpenJCEPlus/tree/main/src/test/java/ibm/jceplus

**Comment by llxia** [comment]
Thanks @jasonkatonica

**Comment by llxia** [comment]
Tests are added as part of `extended.functional` in the test pipeline.
