### ISSUE TITLE
Exclude problematic testcases from AIX platform

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5010]
Follow-up for what is seen during Jan release, related (https://github.com/adoptium/aqa-tests/issues/4983#issuecomment-1896554846)

- exclude renaissance-philosophers for AIX 
  - check on  jck-skytap-aix72-ppc64-4 as per note below, in the event some machines have enough memory to support this test, and query whether all machines could have similar configuration
- jdk_tools ->JliLaunchTest.sh as non-blocking, to be excluded and Bad address issue to be investigated after the release period
- mark jdk_jdi -> com/sun/jdi/ThreadMemoryLeakTest.java as non-blocking, to be excluded and investigated post-release. 
  - @sxa  noted that he was able to get this to pass on a particular machine (SXA: Assuming my invocation was correct and valid, I've managed to get this to pass from the command line on jck-skytap-aix72-ppc64-4) - before exclusion, rerun in Grinder with multi ITERATIONS to determine if intermittent and/or different behaviour on different machines

**Comment by sophia-guo** [comment]
Recheck com/sun/jdi/ThreadMemoryLeakTest.java status. 
Grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/9196/
JliLaunchTest.sh. --> JliLaunchTest.java

**Comment by smlambert** [comment]
See JDK22 dry run triage here:
https://github.com/adoptium/aqa-tests/issues/5141#issuecomment-2005565917
where ThreadMemoryLeakTest and JliLaunchTest both fail.
