### ISSUE TITLE
sanity.external not being provisioned on Orka mac nodes due to sw.tool.docker

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5053]
https://ci.adoptium.net/job/Test_openjdk23_hs_sanity.external_aarch64_mac/7/console
```
02:53:41  Still waiting to schedule task
02:53:41  There are no nodes with the label ‘[ci.role.test&&hw.arch.aarch64&&(sw.os.osx||sw.os.mac)&&sw.tool.docker](https://ci.adoptium.net/label/ci.role.test&&hw.arch.aarch64&&(sw.os.osx%7C%7Csw.os.mac)&&sw.tool.docker/)’
02:58:26  Cancelling nested steps due to timeout
```

**Comment by sophia-guo** [comment]
external tests should be limited to linux*, which are docker installed.

**Comment by sophia-guo** [comment]
This should be fixed by https://github.com/adoptium/ci-jenkins-pipelines/pull/880/files

**Comment by smlambert** [comment]
The 'fix' for this is now merged via https://github.com/adoptium/ci-jenkins-pipelines/pull/929, so can close this issue.
