### ISSUE TITLE
JCK_GIT_REPO not being set for Temurin JCK jobs

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5062]
Not sure why but JCK_GIT_REPO is not being set, thus Temurin JCK jobs are failing with:
```
15:56:08  BUILD FAILED
15:56:08  /home/jenkins/workspace/Test_openjdk21_hs_sanity.jck_x86-64_linux/aqa-tests/TKG/scripts/build_test.xml:95: The following error occurred while executing this line:
15:56:08  /home/jenkins/workspace/Test_openjdk21_hs_sanity.jck_x86-64_linux/aqa-tests/jck/build.xml:294: env.JCK_GIT_REPO: ${env.JCK_GIT_REPO} was not correctly set for running JCK tests. If you do not want to compile JCK tests,       please use BUILD_LIST to include test folders you want to test.
```

Last successful run looks like 2 days ago ?

**Comment by sophia-guo** [comment]
Might relate with https://github.com/adoptium/aqa-tests/pull/5048

**Comment by sophia-guo** [comment]
Those jobs in Eclispe Temurin were generated with default value and triggered with default value. Now it seemed were triggered with empty string.

**Comment by sophia-guo** [comment]
No, it's not set in ` AQA Test Pipeline job`

**Comment by sophia-guo** [comment]
Yes, https://github.com/adoptium/aqa-tests/pull/5048 loop through all params in the job and hence trigger the child job setting JCK_GIT_REPO="".

**Comment by sophia-guo** [comment]
Can add [JCK_GIT_REPO same as those params](https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/aqaTestPipeline.groovy#L112-L114)?  @llxia

**Comment by llxia** [comment]
> the value of JCK_GIT_REPO is "" in  AQA Test Pipeline job

You are setting JCK_GIT_REPO to empty. This value got passed down to the child test build.
If you have the JCK_GIT_REPO default value in the child test job and would like to use it, then you just need to remove JCK_GIT_REPO parameter in AQA Test Pipeline.

**Comment by andrew-m-leonard** [comment]
> > the value of JCK_GIT_REPO is "" in  AQA Test Pipeline job
> 
> You are setting JCK_GIT_REPO to empty in AQA Test Pipeline job. This value got passed down to the child test build. If you have the JCK_GIT_REPO default value in the child test job and would like to use it, then you just need to remove JCK_GIT_REPO parameter in AQA Test Pipeline.

Ah thanks @llxia i've removed the blank JCK_GIT_REPO from our CI compliance Jenkins AQA_Test_Pipeline job configuration, and will see if that resolves the issue in the overnight builds. As you say the default value in the Test_openjdk21_hs_sanity.jck_x86-64_linux child jobs should then win through... thanks
@sophia-guo

**Comment by sophia-guo** [comment]
I'm not sure if there is any specific reason we added parameter JCK_GIT_REPO. Looking at history it was added July 18 2023. Seems preparing for  the 2023 July release.

**Comment by smlambert** [comment]
Think it was added when the remote trigger failed to work and we needed to launch AQA_Test_Pipeline manually on temurin-compliance server.

**Comment by sophia-guo** [comment]
Close this as the issue was fix https://github.com/adoptium/aqa-tests/issues/5062#issuecomment-1944159313 .  If we need to set JCK_GIT_REPO in special cases that we might need https://github.com/adoptium/aqa-tests/pull/5064.
