### ISSUE TITLE
jck_custom supports multiple testcases and different testsuite

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5068]
Enhance jck_custom to support multiple testcases if possible, which would make https://github.com/adoptium/aqa-tests/issues/4498 more useful feature.

**Comment by sophia-guo** [comment]
Current jck_custom can't show the testResult ( no testcase information to verify how many and which testcases have run). For example set custom_target as a directory api/java_applet/AppletStub, there is no information of which or how many tests have been run [temurin-compliance/job/Grinder/](temurin-compliance/job/Grinder/4027).

**Comment by smlambert** [comment]
Again, can't help but think there are some options that can be used when running the underlying javatest harness that would make the output more verbose (much like jtreg does).

From Example 5 on page 21 of https://docs.oracle.com/javacomponents/javatest-4-6/cli-user-guide/CLI.pdf for example:
```
java -jar lib/javatest.jar -config foo.jti -verbose \
-set test.val1 2007 -runtests
This is the same as Example 4 with the exception that it turns on verbose mode and
changes the answer of one of the questions in the configuration. 
```

What additional info is available in console with -verbose turned on?

**Comment by sophia-guo** [comment]
This is specific to jck_custom target. I think it is related with migration to JavaTestUtil, which doesn't update the running process of jck_custom. https://github.com/adoptium/aqa-tests/pull/4512

**Comment by sophia-guo** [comment]
jck_custom is broken issue opened https://github.com/adoptium/aqa-tests/issues/5071

**Comment by sophia-guo** [comment]
[Breaking jck_custom to jckruntime_custom, jckcompiler_custom and jckdevtools_custom](https://github.com/adoptium/aqa-tests/issues/5086)

**Comment by sophia-guo** [comment]
Current JavatestUtils.java [supports tests with multiple sub-folders ( or multiple testcases) separated by semicolon](https://github.com/adoptium/aqa-tests/blob/master/jck/jtrunner/JavatestUtil.java#L160-L170) ( arg tests=sub-folder1;subfolder2 or tests=testcase1;testcase2 or tests=subfolder;testcase ) by changing the tests to be listed with a single space ( the way JCK harness expects). Trying with multiple testcases in grinder only the first testcase can be running successfully. The other tests will be cut as sh command and will not run, which also set the job as successful .

temurin-compliance/job/Grinder/4059/ 

```
23:37:07  /bin/sh: 10: api/java_math/BigInteger: not found
```

**Comment by sophia-guo** [comment]
As we are running the target by make story text that follows a semicolon (;) will be executed as shell commands or build script. Instead of using ; to separate the testcases we can use a space, which is the exact same way JCK harness expects and is the same way as jdk_custom case.

**Comment by sophia-guo** [comment]
As [JavatestUtil only load testArgs with key,value pairs ](https://github.com/adoptium/aqa-tests/blob/master/jck/jtrunner/JavatestUtil.java#L157) we can use double quote for tests args.
