### ISSUE TITLE
Add a Mockito Testcase

### ISSUE THREAD

**Issue by babsingh** [adoptium/aqa-tests#5073]
There are two OpenJ9 user issues where a crash with Mockito is reported:
- https://github.com/eclipse-openj9/openj9/issues/18750
- https://github.com/eclipse-openj9/openj9/issues/18781

The Mockito test case will help us identify the above crashes in our builds.

Test case **variant 1:** https://github.com/eclipse-openj9/openj9/files/13920987/reproApp.tar.gz

Test case **variant 2**: https://github.com/eclipse-openj9/openj9/files/13989201/segmentationerror.zip

**Dependencies:**
- [Mockito](https://github.com/mockito/mockito/blob/main/LICENSE) jar: https://repo1.maven.org/maven2/org/mockito/mockito-core
- [Bytebuddy](https://github.com/raphw/byte-buddy/blob/master/LICENSE)
- Maven

Not all dependencies might be needed; and **test case variant 2** is simpler and relies on fewer dependencies.

**Guidance based on the discussions with the test team:**
- The test should be added in https://github.com/adoptium/aqa-tests/tree/master/functional since it can be run with both OpenJ9 and OpenJDK.
- We can create an folder `MockitoTests`.
- We do not need `testng` in this case.
- We need `build.xml`, `playlist.xml`, and the test case.
- Sample example: https://github.com/eclipse-openj9/openj9/tree/master/test/functional/TestExample.
- 3rd party jars should to be added in [adoptium/TKG/scripts/getDependencies.pl#L66-L176](https://github.com/adoptium/TKG/blob/4df82e13ba88075fdd8195a0575d964f0ea861af/scripts/getDependencies.pl#L66-L176).
- Licences of 3rd party jars should be verified before including them into TKG: 
    - Mockito: https://github.com/mockito/mockito/blob/main/LICENSE 
    - Byte-buddy: https://github.com/raphw/byte-buddy/blob/master/LICENSE

**Comment by babsingh** [comment]
fyi @llxia

**Comment by llxia** [comment]
@sophiaxu0424 Please take a look. Thanks

The test should be added under https://github.com/adoptium/aqa-tests/tree/master/functional
The example can be found at https://github.com/adoptium/aqa-tests/tree/master/functional/OpenJcePlusTests
You will need to modify both aqa-tests repo and TKG repo.

**Comment by llxia** [comment]
mockito test case is attached in the above issue description.

**Comment by llxia** [comment]
@sophiaxu0424 any progress on this issue?

**Comment by llxia** [comment]
https://github.com/eclipse-openj9/openj9/issues/18781 is a dup of https://github.com/eclipse-openj9/openj9/issues/18750. The two test case variant are almost the same. The only difference is that one is directly invoke `Mockito.mock(ArrayList.class);` in main; and the other using junit to call `Mockito.mock(Some.class);`.

@babsingh is it necessary to add both cases?

**Comment by babsingh** [comment]
No. Adding one should provide the required coverage.

**Comment by llxia** [comment]
Test case variant 1 is added. We can close this issue. Thanks @sophiaxu0424
