### ISSUE TITLE
Update v1.0.1-release branch with TKG v1.0.1.1 tag

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5145]
As per https://github.com/adoptium/aqa-tests/issues/5141#issuecomment-1995626408, want to be able to pick up the update to jcstress and the fixes for jck_custom for use in the v1.0.1-release branch.

These are the 3 PRs to ensure we include in the updated TKG tag [v1.0.1.1](https://github.com/adoptium/TKG/releases/tag/v1.0.1.1):
https://github.com/adoptium/TKG/pull/515
https://github.com/adoptium/TKG/pull/516/
https://github.com/adoptium/TKG/pull/520

Need to update:
https://github.com/adoptium/aqa-tests/blob/v1.0.1-release/testenv/testenv.properties#L2 
https://github.com/adoptium/aqa-tests/blob/v1.0.1-release/testenv/testenv_arm32.properties#L2
https://github.com/adoptium/aqa-tests/blob/v1.0.1-release/testenv/testenv_zos.properties#L2

**Comment by llxia** [comment]
I believe this issue can be closed. Not sure why the keyword in the PR did not auto-close the issue.
