### ISSUE TITLE
Propose to move system tests from OpenJ9 to AQAvit

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#5163]
When system tests were initially open-sourced (in 2017), the STF framework did not support running against different JVM implementations. As a result, system tests were split into 3 system test repos (below). Two repos are under Adoptium and one repo is under Openj9.

- https://github.com/adoptium/STF - system Test Framework
- https://github.com/adoptium/aqa-systemtest - system verification tests for hotspot
- https://github.com/eclipse-openj9/openj9-systemtest - system verification tests for OpenJ9

The AQA core team has been responsible for maintaining these three system test repositories, which involve updating tests and tagging each repository for every AQAvit release. With the capability to run tests against various implementations and versions using TKG, there's no longer a need to segregate the system test repositories. Consolidating all system tests into a single repository will simplify usage and maintenance. 

To start, I would like to propose moving the system test repo https://github.com/eclipse-openj9/openj9-systemtest from OpenJ9 to the AQAvit project.

If you agree with moving system tests from OpenJ9 to the AQAvit project, could you please 👍  in this issue? 
If further information is needed, please do not hesitate to ask. If I missed anyone, please feel free to tag them. Thanks

FYI @mstoodle @pshipton @tajila @0xdaryl @smlambert

**Comment by 0xdaryl** [comment]
Will anyone who currently has commit rights to "openj9-systemtest" and requires commit rights to that repo as part of their workflow no longer have the same rights when it moves to Adoptium?  If yes then you probably want to get their opinion on this proposed change.

What will the resulting license be?  Presumably Apache 2.0 since the "adoptium/aqa-systemtest" repo is only AP2.  I don't think this will be a problem for OpenJ9 (currently EPL2 and AP2), but just pointing it out in case someone thinks it is.

**Comment by pshipton** [comment]
All OpenJ9 committers have commit rights to openj9-systemtest, but few have used them. All the recent changes were merged by myself or Lan. Filip merged some in 2021. Lan and I are Adoptium committers.

**Comment by llxia** [comment]
Eclipse help desk issue opened: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4479

**Comment by pshipton** [comment]
Not sure that is the correct approach, but we'll see how your questions are answered.

**Comment by 0xdaryl** [comment]
Just a minor nit in that help desk issue request that the OpenJ9 license is EPL2 **or** AP2 (dual licensed).

**Comment by llxia** [comment]
Thanks @0xdaryl . The issue is updated.

**Comment by smlambert** [comment]
Thanks for this issue @llxia, I am very much in favour of consolidation, and the reduction in sprawl and maintenance that will be the result.

**Comment by llxia** [comment]
Eclipse Management Organization has kindly scheduled the restructuring review for moving [https://github.com/eclipse-openj9/openj9-systemtest](https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eclipse-2Dopenj9_openj9-2Dsystemtest&d=DwQGaQ&c=BSDicqBQBDjDI9RkVyTcHQ&r=bCAZ3kMkD7hSLT1r9t1IOpWhR_nP4RK3_vw93dMI9p8&m=-K7eMhmQtnyuLqYwo1JFGxKXWoiWXFVc2gmvjRX8CD8ttA6ZF_oqwfZDE1cdDc2n&s=M6AwF-ABhV-6JAL3PqUzUbdtRjPRQIMsfme83cZ_50Q&e=) repo from OpenJ9 to Adoptium AQAvit.

To summarize: 
PMI record: https://projects.eclipse.org/projects/adoptium.aqavit/reviews/2024.04-restructuring-review
GitLab issue: https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/737

I have sent out the email regarding this to [openj9-dev@eclipse.org](mailto:openj9-dev@eclipse.org). 
Could you please provide your +1 for this restructuring review via email? The end date of the review period is Wednesday, April 24, 2024.

If you have any questions, please let me know. Thanks

**Comment by keithc-ca** [comment]
Is the proposal to move openj9-systemtest (potentially with a new name) to the adoptium organization in github? Or is the plan to merge the tests in openj9-systemtest into aqa-systemtest? Or something else?

**Comment by llxia** [comment]
The plan is to merge the tests in openj9-systemtest into aqa-systemtest repo (assuming there is no merge conflict).

**Comment by r30shah** [comment]
openj9-systemtest has been used for adding tests for OpenJ9's DAA related tests [1][2]. Given that @llxia  and @pshipton  are committer at Adoptium, we should be fine. Just FYI, as work on improving / enhancing DAA api will continue in times to come, we would continue to add more tests as work progresses. 

[1]. https://github.com/eclipse-openj9/openj9-systemtest/tree/master/openj9.test.daa/src/test.daa/net/openj9/test
[2]. https://github.com/eclipse-openj9/openj9/tree/master/jcl/src/openj9.dataaccess/share/classes/com/ibm/dataaccess

**Comment by llxia** [comment]
Thanks @r30shah . For the record, @JasonFengJ9 and @LongyuZhang are also AQAvit committers, who can help to review openj9 related system test changes.

**Comment by llxia** [comment]
OpenJ9 system tests repo is moved into the Adoptium organization https://github.com/eclipse-aqavit/openj9-systemtest. This resulted in the creation of an AQAvit GitHub organization, which was unexpected. This will be passed back to EF Infra to be resolved. The plan is to move the content of the openj9-systemtest repo into [aqa-systemtest](https://github.com/adoptium/aqa-systemtest) repo.

Since openj9-systemtest repo is moved under Adoptium, I will close this issue. Thanks a lot for everyone's help.
