### ISSUE TITLE
Run of external tests - in docker - fails with podman, even with proper podman-docker binding/aliases 

### ISSUE THREAD

**Issue by judovana** [adoptium/aqa-tests#5196]
What are you trying to do?
I'm trying to run external tests on defualt fedora, install wehre is podman with docker aliases/bindings

Expected behaviour:
exteral tests will work (without removing podman, podman-docker, and withotu replacing it by 3rd party docker)

Observed behaviour:
Currently the podman-docker build faild. I had lost the traces but will elaborate.
It were cryptic messages, suspicions is going to privileged operations. But that is just guessing from air now.

Any other comments:
Possible help from @sefroberg needed

Related to https://github.com/adoptium/temurin-build/issues/3738

**Comment by sxa** [comment]
Noting that [test-marist-rhel8-s390x-2](https://ci.adoptium.net/computer/test%2Dmarist%2Drhel8%2Ds390x%2D2) probably has our only environment suitable for reproducing this if needed, although it has been commandeered for build work at the moment.

**Comment by judovana** [comment]
https://github.com/adoptium/aqa-tests/pull/5460  works moreover ok. There is issue with network, but may be considerd as god start

**Comment by judovana** [comment]
https://github.com/adoptium/aqa-tests/pull/5460/files podman support was added, detection now works.
