### ISSUE TITLE
April 2024 jdk21 dryrun triage

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5210]
#### Release Summary Report for release-openjdk21-pipeline 
**Warning:** The release summary report is not yet complete. Currently, it only contains partial results. 

**Report generated at:** Wed, 10 Apr 2024 17:56:35 GMT 
 
TRSS [Build](https://trss.adoptium.net/buildDetail?parentId=6615c279879917006ef89835&testSummaryResult=failed&buildNameRegex=%5ETest) and TRSS [Grid View](https://trss.adoptium.net/resultSummary?parentId=6615c279879917006ef89835) 
Jenkins Build URL https://ci.adoptium.net/job/build-scripts/job/release-openjdk21-pipeline/30/ 
Started by upstream project "build-scripts/utils/releaseTrigger_jdk21u" build number 2283 at 4/9/2024, 6:34:17 PM

 --- 

✔️ results in these Tables means the activity has successfully completed.
⏳ results means that we are actively working on closing off the runs needed for this version, platform, binaryType.
⛔ means there is no build planned for that version/platform combination.
⏸️ means activity not yet started.

| Platform | Status | Results |
| --- | --- | --- |
| **x86-64_mac** | ✔️   | [comment]() |
| **x86-64_linux** | ✔️  | [comment](https://github.com/adoptium/aqa-tests/issues/5210#issuecomment-2048290885) |
| **x86-64_windows** | ✔️ | [comment](https://github.com/adoptium/aqa-tests/issues/5210#issuecomment-2051798576) |
| **aarch64_linux** | ✔️ |[comment](https://github.com/adoptium/aqa-tests/issues/5210#issuecomment-2048323714) |
| **aarch64_mac** | ✔️ | [comment]() |
| x86-64_alpine-linux | ⏸️   | [comment]() |
| ppc64le_linux | ✔️  |  [comment](https://github.com/adoptium/aqa-tests/issues/5210#issuecomment-2048332085) |
| s390x_linux | ⏸️ |  [comment]() |
| ppc64_aix |  ⏸️  | [comment]() |
| aarch64_alpine-Linux |  ✔️ | [comment](https://github.com/adoptium/aqa-tests/issues/5210#issuecomment-2048332603) |

 ---

**Comment by sophia-guo** [comment]
x86-64_linux:

[Test_openjdk21_hs_extended.openjdk_x86-64_linux](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux/48/) ❌ FAILURE ❌

[Test_openjdk21_hs_extended.openjdk_x86-64_linux_rerun](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux_rerun/9/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_build_0,jdk_build_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=1&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk21u%2Fjdk21u-release-linux-x64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-21.0.3%2B6_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=4&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

java -version
[Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_0](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_0/5/) ⚠️ UNSTABLE ⚠️
[jdk_other_0](https://trss.adoptium.net/output/test?id=6616236b879917006efde66f) => [deep history 7/9 passed](https://trss.adoptium.net/deepHistory?testId=6616236b879917006efde66f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66162220879917006efdc22d&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_0&testId=6616236b879917006efde66f&testName=jdk_other_0)
[jdk_build_0](https://trss.adoptium.net/output/test?id=6616236b879917006efde677) => [deep history 13/14 passed](https://trss.adoptium.net/deepHistory?testId=6616236b879917006efde677) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66162220879917006efdc22d&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_0&testId=6616236b879917006efde677&testName=jdk_build_0)

[Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_1](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_1/5/) ❌ FAILURE ❌

[Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_2](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_2/5/) ⚠️ UNSTABLE ⚠️
[jdk_build_1](https://trss.adoptium.net/output/test?id=6616235c879917006efde64a) => [deep history 4/5 passed](https://trss.adoptium.net/deepHistory?testId=6616235c879917006efde64a) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66162220879917006efdc22b&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_linux_testList_2&testId=6616235c879917006efde64a&testName=jdk_build_1)

[Test_openjdk21_hs_sanity.functional_x86-64_linux](https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.functional_x86-64_linux/158/) ❌ FAILURE ❌ -- running on apline-linux. rerun https://ci.adoptium.net/job/Test_openjdk21_hs_sanity.functional_x86-64_linux/159/

**Comment by sophia-guo** [comment]
aarch64_mac

[Test_openjdk21_hs_extended.openjdk_aarch64_mac](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_aarch64_mac/45/) ⚠️ UNSTABLE ⚠️

[Test_openjdk21_hs_extended.openjdk_aarch64_mac_rerun](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_aarch64_mac_rerun/10/) ⚠️ UNSTABLE ⚠️
Rerun [failed](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&TARGET=testList+TESTLIST=jdk_jfr_1&BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=aarch64_mac&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&DOCKER_REGISTRY_DIR=&RERUN_ITERATIONS=1&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&SETUP_JCK_RUN=false&DOCKER_REGISTRY_URL_CREDENTIAL_ID=&LABEL=&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&JENKINS_KEY=&ADOPTOPENJDK_BRANCH=v1.0.1-release&LIGHT_WEIGHT_CHECKOUT=true&USE_JRE=false&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=21&DOCKER_REGISTRY_URL=&ITERATIONS=1&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21u&JCK_GIT_BRANCH=master&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk21u%2Fjdk21u-release-mac-aarch64-temurin&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&CLOUD_PROVIDER=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-21.0.3%2B6_adopt&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&TEST_TIME=&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&SLACK_CHANNEL=&DYNAMIC_COMPILE=false&RELATED_NODES=&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&NUM_MACHINES=&OPENJDK_SHA=&TRSS_URL=&USE_TESTENV_PROPERTIES=true&BUILD_LIST=openjdk&ADDITIONAL_ARTIFACTS_REQUIRED=&UPSTREAM_JOB_NUMBER=4&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

java -version
[Test_openjdk21_hs_extended.openjdk_aarch64_mac_testList_1](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_aarch64_mac_testList_1/4/) ⚠️ UNSTABLE ⚠️
[jdk_jfr_1](https://trss.adoptium.net/output/test?id=661607ac879917006efc137f) => [deep history 5/13 passed](https://trss.adoptium.net/deepHistory?testId=661607ac879917006efc137f) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=66160681879917006efbf65e&buildName=Test_openjdk21_hs_extended.openjdk_aarch64_mac_testList_1&testId=661607ac879917006efc137f&testName=jdk_jfr_1)

**Comment by sophia-guo** [comment]
aarch64_linux -  buidl https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk21u/job/jdk21u-release-linux-aarch64-temurin/4/ failed.

manually triage https://ci.adoptium.net/job/build-scripts/job/jobs/job/release/job/jobs/job/jdk21u/job/jdk21u-release-linux-aarch64-temurin/5/console

**Comment by sophia-guo** [comment]
x86-64_alpine-linux

**Comment by sophia-guo** [comment]
ppc64le_linux

**Comment by sophia-guo** [comment]
s390x_linux

**Comment by sophia-guo** [comment]
aarch64_alpine-Linux

**Comment by sophia-guo** [comment]
ppc64_aix

**Comment by Haroon-Khel** [comment]
s390x_linux

**Comment by sophia-guo** [comment]
x86-64_windows

[**Test_openjdk21_hs_extended.openjdk_x86-64_windows**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_windows/46/) ❌ ABORTED ❌

[**Test_openjdk21_hs_extended.openjdk_x86-64_windows_rerun**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_windows_rerun/10/) ❌ ABORTED ❌
Rerun [all](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=testList+TESTLIST%3Djdk_net_1%2Cjdk_net_0%2Cjdk_tools_0%2Cjdk_tools_1&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_windows&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=true&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=21&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk21u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk21u%2Fjdk21u-release-windows-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-21.0.3%2B6_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=openjdk&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=9&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None)
<details><summary>java -version</summary>

```
openjdk version "21.0.3" 2024-04-16 LTS
OpenJDK Runtime Environment Temurin-21.0.3+6 (build 21.0.3+6-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.3+6 (build 21.0.3+6-LTS, mixed mode, sharing)
```
</details>


[**Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_0**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_0/4/) ⚠️ UNSTABLE ⚠️
[jdk_net_0](https://trss.adoptium.net/output/test?id=6618a9ae879917006e3d4638) => [deep history 2/11 passed](https://trss.adoptium.net/deepHistory?testId=6618a9ae879917006e3d4638) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6618a88a879917006e3d44e7&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_0&testId=6618a9ae879917006e3d4638&testName=jdk_net_0)
[jdk_tools_0](https://trss.adoptium.net/output/test?id=6618a9ae879917006e3d463c) => [deep history 0/8 passed](https://trss.adoptium.net/deepHistory?testId=6618a9ae879917006e3d463c) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6618a88a879917006e3d44e7&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_0&testId=6618a9ae879917006e3d463c&testName=jdk_tools_0)
[jdk_tools_1](https://trss.adoptium.net/output/test?id=6618a9ae879917006e3d463d) => [deep history 0/9 passed](https://trss.adoptium.net/deepHistory?testId=6618a9ae879917006e3d463d) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6618a88a879917006e3d44e7&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_0&testId=6618a9ae879917006e3d463d&testName=jdk_tools_1)

[**Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_1**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_1/4/) ❌ ABORTED ❌
[jvm_compiler_0](https://trss.adoptium.net/output/test?id=6618a99d879917006e3d45ca) => [deep history 9/10 passed](https://trss.adoptium.net/deepHistory?testId=6618a99d879917006e3d45ca) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6618a88a879917006e3d44e5&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_1&testId=6618a99d879917006e3d45ca&testName=jvm_compiler_0)
[runtime_nestmate_0](https://trss.adoptium.net/output/test?id=6618a99d879917006e3d45cc) => [deep history 8/9 passed](https://trss.adoptium.net/deepHistory?testId=6618a99d879917006e3d45cc) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6618a88a879917006e3d44e5&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_1&testId=6618a99d879917006e3d45cc&testName=runtime_nestmate_0)

[**Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_2**](https://ci.adoptium.net/job/Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_2/4/) ⚠️ UNSTABLE ⚠️
[jdk_net_1](https://trss.adoptium.net/output/test?id=6618a9a5879917006e3d45ff) => [deep history 5/18 passed](https://trss.adoptium.net/deepHistory?testId=6618a9a5879917006e3d45ff) | [possible issues](https://trss.adoptium.net/possibleIssues?buildId=6618a88a879917006e3d44e6&buildName=Test_openjdk21_hs_extended.openjdk_x86-64_windows_testList_2&testId=6618a9a5879917006e3d45ff&testName=jdk_net_1)
