### ISSUE TITLE
The downlaoder seems to be apending slash to download url

### ISSUE THREAD

**Issue by judovana** [adoptium/aqa-tests#5254]
When dowloading cusotm url,  eg in  https://ci.adoptium.net/view/Test_grinder/job/Grinder/9743/console and set 

CUSTOMIZED_SDK_URL to eg https://jvanek.fedorapeople.org/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64.tar.gz  the downlader attempts to download  https://jvanek.fedorapeople.org/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64.tar.gz/ whcich do not exits

It can be workaroudne dby something like https://jvanek.fedorapeople.org/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64.tar.gz#noSlash  but generally it seems like bug.

**Comment by judovana** [comment]
It seems to be `latestBuildUrl="${CUSTOMIZED_SDK_URL}${max}/"` in get.sh

**Comment by sxa** [comment]
Where are you seeing this happening? https://ci.adoptium.net/job/Grinder/9794/console with your URL looks to have downloaded it without problems:
```
 _ENCODE_FILE_NEW=UNTAGGED curl -OLJSks --user ****:**** https://jvanek.fedorapeople.org/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64.tar.gz
 Uncompressing file: java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64.tar.gz ...
 Run /home/jenkins/workspace/Grinder/jdkbinary/j2sdk-image/bin/java -version
 =JAVA VERSION OUTPUT BEGIN=
 openjdk version "17.0.10" 2024-01-16 LTS
 OpenJDK Runtime Environment (Red_Hat-17.0.10.0.7-1.el7openjdkportable) (build 17.0.10+7-LTS)
 OpenJDK 64-Bit Server VM (Red_Hat-17.0.10.0.7-1.el7openjdkportable) (build 17.0.10+7-LTS, mixed mode, sharing)
 =JAVA VERSION OUTPUT END=
```

**Comment by judovana** [comment]
From the link in top: https://ci.adoptium.net/view/Test_grinder/job/Grinder/9743/console  
```
10:47:24  downloading files from https://jvanek.fedorapeople.org/java-17-openjdk-17.0.10.0.7-1.portable.jdk.el.x86_64.tar.gz/
10:47:24    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
10:47:24                                   Dload  Upload   Total   Spent    Left  Speed
10:47:24  
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   377  100   377    0     0   1081      0 --:--:-- --:--:-- --:--:--  1080
[Pipeline] }
[Pipeline] // dir
[Pipeline] }
10:47:24  $ ssh-agent -k
10:47:24  unset SSH_AUTH_SOCK;
10:47:24  unset SSH_AGENT_PID;
10:47:24  echo Agent pid 140032 killed;
10:47:25  [ssh-agent] Stopped.
```
nothing downloaded, game over.

It is likely that I had differently (wrongly) set up grinder.  I have suspicion that it appears onl with `nightly` on. At last by reading the code somehow,  The `latestBuildUrl="${CUSTOMIZED_SDK_URL}${max}/"`  is the only suspicious part I found.

**Comment by smlambert** [comment]
If you are trying to pull a binary from a CUSTOMIZED_SDK_URL, you should switch the SDK_RESOURCE to 'customized', not 'nightly'

**Comment by judovana** [comment]
Ok, my https://ci.adoptium.net/view/Test_grinder/job/Grinder/9795 failed, I'm failing to see cause, but download seems to be ok. And yours https://ci.adoptium.net/view/Test_grinder/job/Grinder/9796/ is ok. I need to comapre what you did. TY!

**Comment by smlambert** [comment]
you had set JDK_VERSION to 21, but were pulling a JDK17 binary, so we do a check once the binary is unpacked, and that check returned "mismatch" and failed
