### ISSUE TITLE
Validate Temurin on Docker's Ubuntu latest LTS base image

### ISSUE THREAD

**Issue by tellison** [adoptium/aqa-tests#5271]
Ubuntu Noble (24.04 LTS) was released on April 25th so just missed the release of Temurin's April CPU cycle.

Rather than wait until the next scheduled Temurin release, please run appropriate AQAvit tests to validate that Temurin can be supported there ([Ubuntu n24.04](https://hub.docker.com/_/ubuntu)).

ref: https://github.com/adoptium/containers/issues/532

**Comment by sxa** [comment]
Note that the currency item to add this version to the infrastructure is at https://github.com/adoptium/infrastructure/issues/3501

**Comment by smlambert** [comment]
Closing this one in favour of https://github.com/adoptium/infrastructure/issues/3501
