### ISSUE TITLE
HCRLateAttachWorkload_previewEnabled FAILED in Test_openjdk17_hs_extended.system_x86-64_linux

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5272]
HCRLateAttachWorkload_previewEnabled failed in original run on test-docker-ubuntu2204-x64-6, passed in auto rerun on test-ibmcloud-rhel6-x64-1, check if there is a pattern of passing on some infra and not on others

**Console output:**
```
[2024-04-17T07:56:52.456Z] AG  Heap
[2024-04-17T07:56:52.456Z] AG   garbage-first heap   total 100352K, used 10375K [0x00000000a0000000, 0x0000000100000000)
[2024-04-17T07:56:52.456Z] AG    region size 1024K, 10 young (10240K), 2 survivors (2048K)
[2024-04-17T07:56:52.456Z] AG   Metaspace       used 1023K, committed 1152K, reserved 1114112K
[2024-04-17T07:56:52.456Z] AG    class space    used 56K, committed 128K, reserved 1048576K
[2024-04-17T07:56:52.456Z] AG  
[2024-04-17T07:56:52.456Z] LT  07:54:50.067 - Thread completed. Suite=0 thread=1
[2024-04-17T07:56:52.456Z] LT  07:54:50.072 - Thread completed. Suite=0 thread=2
[2024-04-17T07:56:52.456Z] LT  07:54:50.079 - Thread completed. Suite=0 thread=0
[2024-04-17T07:56:52.456Z] LT  07:54:50.178 - Test stopped due to reaching runtime limit
[2024-04-17T07:56:52.456Z] LT  07:54:50.178 - Load test completed
[2024-04-17T07:56:52.456Z] LT  07:54:50.179 -   Ran     : 114188
[2024-04-17T07:56:52.456Z] LT  07:54:50.179 -   Passed  : 114188
[2024-04-17T07:56:52.456Z] LT  07:54:50.179 -   Failed  : 0
[2024-04-17T07:56:52.456Z] LT  07:54:50.179 -   Result  : PASSED
[2024-04-17T07:56:52.456Z] STF 07:56:47.301 - Monitoring Report Summary:
[2024-04-17T07:56:52.456Z] STF 07:56:47.301 -   o Process AG  has timed out
[2024-04-17T07:56:52.456Z] STF 07:56:47.303 -   o Process LT  ended sucessfully
[2024-04-17T07:56:52.456Z] STF 07:56:47.307 - Killing processes: AG  LT 
[2024-04-17T07:56:52.456Z] STF 07:56:47.308 -   o Process AG  pid 347738 is not running
[2024-04-17T07:56:52.456Z] STF 07:56:47.308 -   o Process LT  pid 347737 is not running
[2024-04-17T07:56:52.456Z] **FAILED** at step 3 (Wait for Agent to complete). Expected return value=0 Actual=1 at /home/jenkins/workspace/Test_openjdk17_hs_extended.system_x86-64_linux/aqa-tests/TKG/../TKG/output_17133352098015/HCRLateAttachWorkload_previewEnabled_0/20240417-074441-HCRLateAttachWorkload/execute.pl line 155.
[2024-04-17T07:56:52.456Z] STF 07:56:47.514 - **FAILED** execute script failed. Expected return value=0 Actual=1
```
**Test Info**
Test Name: HCRLateAttachWorkload_previewEnabled_0
Test Duration: 12 min 6 sec
Machine: test-docker-ubuntu2204-x64-6
TRSS link for the test output: https://trss.adoptium.net/output/test?id=66204832879917006ea4034d

**Build Info**
Build Name: Test_openjdk17_hs_extended.system_x86-64_linux
Jenkins Build start time: Apr 17 2024, 02:15 am
Jenkins Build URL: https://ci.adoptium.net/job/Test_openjdk17_hs_extended.system_x86-64_linux/420/
TRSS link for the build: https://trss.adoptium.net/allTestsInfo?buildId=66204726879917006ea3e31a

**Java Version**
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)

[Rerun in Grinder](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=upstream&amp;TARGET=HCRLateAttachWorkload_previewEnabled_0&amp;BASE_DOCKER_REGISTRY_CREDENTIAL_ID=&amp;TEST_FLAG=&amp;UPSTREAM_TEST_JOB_NAME=&amp;DOCKER_REQUIRED=false&amp;ACTIVE_NODE_TIMEOUT=5&amp;VENDOR_TEST_DIRS=&amp;EXTRA_DOCKER_ARGS=&amp;TKG_OWNER_BRANCH=adoptium%3Amaster&amp;OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&amp;PLATFORM=x86-64_linux&amp;GENERATE_JOBS=false&amp;KEEP_REPORTDIR=false&amp;PERSONAL_BUILD=false&amp;DOCKER_REGISTRY_DIR=&amp;RERUN_ITERATIONS=0&amp;ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&amp;SETUP_JCK_RUN=false&amp;DOCKER_REGISTRY_URL_CREDENTIAL_ID=&amp;LABEL=&amp;EXTRA_OPTIONS=&amp;CUSTOMIZED_SDK_URL=&amp;BUILD_IDENTIFIER=&amp;JENKINS_KEY=&amp;ADOPTOPENJDK_BRANCH=v1.0.1-release&amp;LIGHT_WEIGHT_CHECKOUT=false&amp;USE_JRE=false&amp;ARTIFACTORY_SERVER=&amp;KEEP_WORKSPACE=false&amp;USER_CREDENTIALS_ID=&amp;JDK_VERSION=17&amp;DOCKER_REGISTRY_URL=&amp;ITERATIONS=1&amp;VENDOR_TEST_REPOS=&amp;JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&amp;JCK_GIT_BRANCH=master&amp;OPENJ9_BRANCH=master&amp;OPENJ9_SHA=&amp;JCK_GIT_REPO=&amp;VENDOR_TEST_BRANCHES=&amp;UPSTREAM_JOB_NAME=build-scripts%2Fjobs%2Frelease%2Fjobs%2Fjdk17u%2Fjdk17u-release-linux-x64-temurin&amp;OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&amp;CLOUD_PROVIDER=&amp;CUSTOM_TARGET=&amp;VENDOR_TEST_SHAS=&amp;JDK_BRANCH=jdk-17.0.11%2B9_adopt&amp;LABEL_ADDITION=&amp;ARTIFACTORY_REPO=&amp;ARTIFACTORY_ROOT_DIR=&amp;UPSTREAM_TEST_JOB_NUMBER=&amp;DOCKERIMAGE_TAG=&amp;JDK_IMPL=hotspot&amp;TEST_TIME=&amp;SSH_AGENT_CREDENTIAL=&amp;AUTO_DETECT=true&amp;SLACK_CHANNEL=&amp;DYNAMIC_COMPILE=false&amp;RELATED_NODES=&amp;ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&amp;APPLICATION_OPTIONS=&amp;CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&amp;ARCHIVE_TEST_RESULTS=false&amp;NUM_MACHINES=&amp;OPENJDK_SHA=&amp;TRSS_URL=&amp;USE_TESTENV_PROPERTIES=true&amp;BUILD_LIST=system&amp;ADDITIONAL_ARTIFACTS_REQUIRED=&amp;UPSTREAM_JOB_NUMBER=21&amp;STF_OWNER_BRANCH=adoptium%3Amaster&amp;TIME_LIMIT=25&amp;JVM_OPTIONS=&amp;PARALLEL=None)

Originated from April triage: https://github.com/adoptium/aqa-tests/issues/5231#issuecomment-2062525377

**Comment by sxa** [comment]
@Haroon-Khel Are you aware of anything special about this machine, as the test seems to pass on other ubuntu2204 systems without problems.

[Grinder re-run link if required](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=releases&TARGET=testList+TESTLIST=HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1,HCRLateAttachWorkload_previewEnabled_0,HCRLateAttachWorkload_previewEnabled_1&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=Test_openjdk17_hs_extended.system_x86-64_linux&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=5&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=true&KEEP_REPORTDIR=false&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=1&LABEL=test-docker-ubuntu2204-x64-6&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=true&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=17&ITERATIONS=10&VENDOR_TEST_REPOS=&JDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Fjdk17u&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=&VENDOR_TEST_SHAS=&JDK_BRANCH=jdk-17.0.12%2B5_adopt&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=429&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=system&USE_TESTENV_PROPERTIES=false&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=25&JVM_OPTIONS=&PARALLEL=None)

**Comment by sophia-guo** [comment]
Did see failed on test-ibmcloud-rhel6-x64-1 once around  Jan 30 - Feb 8, 2024. No duration, might not run at all. 
![Screenshot 2024-06-28 at 4 08 59 PM](https://github.com/adoptium/aqa-tests/assets/18030625/c4ae2138-f40d-42c3-8fd8-81b8a606b165)

Rerun on test-docker-ubuntu2204-x64-6 to see if it's intermittent. https://ci.adoptium.net/job/Grinder/10500/console

**Comment by sophia-guo** [comment]
Feels something wrong with the agent?
[ttps://ci.adoptium.net/job/Grinder/10500/console](https://ci.adoptium.net/job/Grinder/10500/console)


```
Pausing (Preparing for shutdown)
Resuming build at Tue Jul 02 10:42:49 CEST 2024 after Jenkins restart
Ready to run at Tue Jul 02 10:42:49 CEST 2024
Pausing (Preparing for shutdown)
Resuming build at Tue Jul 02 10:54:11 CEST 2024 after Jenkins restart
Ready to run at Tue Jul 02 10:54:11 CEST 2024
Pausing (Preparing for shutdown)
Resuming build at Tue Jul 02 11:06:48 CEST 2024 after Jenkins restart
Ready to run at Tue Jul 02 11:06:48 CEST 2024
```

@Haroon-Khel

**Comment by Haroon-Khel** [comment]
The agent on [test-docker-ubuntu2204-x64-6](https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2204%2Dx64%2D6/) is unable to launch, taking a look

**Comment by Haroon-Khel** [comment]
test-docker-ubuntu2204-x64-6 is back online, the grinder is running

**Comment by sophia-guo** [comment]
Thanks @Haroon-Khel [https://ci.adoptium.net/job/Grinder/10500/console](https://ci.adoptium.net/job/Grinder/10500/console) - passed. Close this.
