### ISSUE TITLE
Create job to cleanup testDependency dir

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#5276]
As we upgrade 3rd party jars often, we could have old version of 3rd party jars (no longer needed) under testDependency.
https://github.com/adoptium/TKG/blob/master/scripts/getDependencies.pl

We need a job to cleanup pre-stage 3rd party jars under `testDependency` dir on each machine periodically (maybe every 6 months)

**Comment by llxia** [comment]
[internal example](https://hyc-runtimes-jenkins.swg-devops.com/job/Cleanup_JCK_Material/)

**Comment by annaibm** [comment]
Job created to cleanup testDependency ->
https://hyc-runtimes-jenkins.swg-devops.com/job/Cleanup_Test_Lib/

**Comment by LongyuZhang** [comment]
This cleanup testDependency job has been tested on all platforms, close this issue then. Thanks @annaibm

**Comment by llxia** [comment]
Thanks @annaibm . Please set Cleanup_Test_Lib to run every 6 months.

**Comment by annaibm** [comment]
@llxia Configured to run every six months. The next run will be on Sunday, December 15, 2024, at 10:11:46 PM Eastern Standard Time, according to the following schedule: `H H 15 6,12 *`.

https://hyc-runtimes-jenkins.swg-devops.com/job/Cleanup_Test_Lib/configure.
