### ISSUE TITLE
Validate Temurin on Amazon Linux 2023 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5285]
We would like to run Temurin builds through the AQAvit verification tests on Amazon Linux 2023 once a node is available.

Related: https://github.com/adoptium/infrastructure/issues/3041 

Triage:
https://ci.adoptium.net/job/AQA_Test_Pipeline/244/console
https://ci.adoptium.net/job/AQA_Test_Pipeline/245/console

**Comment by sophia-guo** [comment]
Dup of #5300
