### ISSUE TITLE
Error message `set: Illegal option -o pipefail`

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5295]
Running grinder with USE_TESTENV_PROPERTIES=true got error message

```
16:56:42  + MAKE=make
16:56:42  + cd ./aqa-tests
16:56:42  + . ./scripts/testenv/testenvSettings.sh
16:56:42  + set +x
16:56:42  /home/jenkins/workspace/Grinder@tmp/durable-b016861e/script.sh.copy: 3: set: Illegal option -o pipefail
[Pipeline] sh
```
https://ci.adoptium.net/view/Test_grinder/job/Grinder/9890/console

Might be something related with #5290 ? @llxia

**Comment by judovana** [comment]
This was fixed wrongly, and should be reopened. See; https://github.com/adoptium/aqa-tests/pull/5296#issuecomment-2102633008
