### ISSUE TITLE
checkTags.sh should be triggered when JDK_IMPL!=openj9 or ibm

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#5298]
When USE_TESTENV_PROPERTIES=true, checkTags.sh will run. It should be triggered when JDK_IMPL!=openj9 or ibm

https://github.com/adoptium/aqa-tests/blob/83bec274a10eb52ac812af2acc50bb3ec4bc4673/get.sh#L780

Add if statement. 

if JDK_IMPL!=`openj9` || JDK_IMPL != `ibm`, run checkTags.sh

**Comment by ftm-2005** [comment]
I'll work on it
