### ISSUE TITLE
create MiniMix_10m test

### ISSUE THREAD

**Issue by llxia** [adoptium/aqa-tests#5302]
copy `MiniMix_5m`,  rename it `MiniMix_10m` and change timeLimit=`10m`:
https://github.com/adoptium/aqa-tests/blob/83bec274a10eb52ac812af2acc50bb3ec4bc4673/system/otherLoadTest/playlist.xml#L34-L62

This is the first step of adding https://github.com/eclipse-openj9/openj9/issues/16428

**Comment by coolujain** [comment]
I'll do this

**Comment by Hajer-Dahmani** [comment]
I'll take this
