### ISSUE TITLE
Poor coverage of langtools by openjdk tests

### ISSUE THREAD

**Issue by zzambers** [adoptium/aqa-tests#5318]
There are almost no langtools tests ran. (not even `tier1` used in GHA by upstream)

**extended.openjdk:**
| target | jdk| tests |
| ---        | --- | --- |
| langtools_extpath_j9 | ibm/j9 | `tools/javap/ExtPath.java`  |

**special.openjdk:**
| target | jdk | tests | 
| ---  | --- | --- |
| langtools_custom | all | only runs default `tools/javac/4241573/T4241573.java` |

**Comment by sophia-guo** [comment]
@zzambers as mentioned in slack I have assigned the issue to you.  Please feel free to update the project status according to your work plan. Initially I've set as Q2 iteration 6 (June 11 - June 30).

**Comment by zzambers** [comment]
done by: https://github.com/adoptium/aqa-tests/pull/5353
