### ISSUE TITLE
Move the AQAvit Terminology wiki into /docs

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5326]
The contents of https://github.com/adoptium/aqa-tests/wiki/AQAvit-Terminology can be moved into https://github.com/adoptium/aqa-tests/tree/master/docs/pages and then a link to it added to the https://github.com/adoptium/aqa-tests/blob/master/docs/pages/aqa-reference.markdown file.

**Comment by Sangyoon21** [comment]
I could do this!
