### ISSUE TITLE
Move the 'How to map OpenJDK tests to AQAvit' wiki into /docs

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5327]
Move the contents of https://github.com/adoptium/aqa-tests/wiki/How-OpenJDK-tests-map-to-AQAvit-test-targets into https://github.com/adoptium/aqa-tests/tree/master/docs/pages and add a link to it from the https://github.com/adoptium/aqa-tests/blob/master/docs/pages/aqa-reference.markdown file.

**Comment by GioChkhaidze** [comment]
I'll do it
