### ISSUE TITLE
Create a 'How to Triage an Adoptium Release' document

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5328]
Create a simple markdown file in https://github.com/adoptium/aqa-tests/tree/master/docs/pages that contains links to this [recording](https://youtu.be/TWD_b8cwIVg) and this pdf file [AQAvitTriageLightningSlides.pdf](https://github.com/adoptium/aqa-tests/files/15349378/AQAvitTriageLightningSlides.pdf).

**Comment by diyorbekibragimov** [comment]
I can do it
