### ISSUE TITLE
Encountered an error with the `-checkTap` command after updating the TAP files in the specific directory

### ISSUE THREAD

**Issue by annaibm** [adoptium/aqa-tests#5347]
**Steps to Reproduce:**
1. Run the `-checkTap` command before placing rerun TAP files. There is no error.
2. Place the rerun TAP file (`Test_openjdk11_j9_extended.openjdk_aarch64_linux_rerun.tap`)  into the platform specific folder eg:  `ibm-semeru-certified-jdk_aarch64_linux_11.0.23.tap` folder.
3. Re-run the `-checkTap` command.
4. Observe the error.

```
jenkins/tapVerification/aqaTap.sh -ct
============================
check AQAvit TAP files in /Users/annabp/AQAvitTapFiles/ibm-semeru-certified-jdk_aarch64_linux_11.0.23.tap
============================
----------------------------
1. List *sanity.openjdk*.tap ...
./Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_0.tap
./Test_openjdk11_j9_sanity.openjdk_aarch64_linux_testList_1.tap
Total num of Files:    2
----------------------------
2. List *extended.openjdk*.tap ...
./Test_openjdk11_j9_extended.openjdk_aarch64_linux_rerun.tap
./Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_0.tap
./Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_1.tap
./Test_openjdk11_j9_extended.openjdk_aarch64_linux_testList_2.tap
Total num of Files:    4
[ERROR]: Missing *extended.openjdk*_testList_3* TAP file
```

**Expected Result:**
The command should execute and validate the TAP files without errors.

**Actual Result:**
Received an error indicating a missing *extended.openjdk*_testList_3* TAP file.

**Comment by llxia** [comment]
We should add ignore `rerun` files in `find`: https://github.com/adoptium/aqa-tests/blob/master/buildenv/jenkins/tapVerification/aqaTap.sh#L178
reference: https://www.cyberciti.biz/faq/find-command-exclude-ignore-files/
