### ISSUE TITLE
JDK8: Failing pkcs11 tests (libnss related?) on AL2023, UBI9+, F35+

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#5380]
Seen as part of the [Amazon Linux 2023 triage issue](https://github.com/adoptium/aqa-tests/issues/5300) but the failures are seen in some of the upstream distributions too such as UBI9, and Fedora 35+ (possibly earlier versions - I've only gone back to 35 so far). CentOS9-Stream would likely fail too, although UBI8/CentOS8 do not have the failures.

[Package](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	| [Duration](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	| [Fail](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	[(diff)](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	| [Skip](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	[(diff)](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	| [Pass](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	[(diff)](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	| [Total](https://ci.adoptium.net/job/Grinder/10266/testReport/#)	[(diff)](https://ci.adoptium.net/job/Grinder/10266/testReport/#)
---|---|---|---|---|---
[sun/security/pkcs11/Provider/Login](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_Provider_Login/)	|2 min 8 sec	|0		|0		|50		|50	
[sun/security/pkcs11/Secmod/AddPrivateKey](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_Secmod_AddPrivateKey/)	|5 min 59 sec	|0		|0		|50		|50	
[sun/security/pkcs11/Secmod/GetPrivateKey](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_Secmod_GetPrivateKey/)	|1 min 51 sec	|0		|0		|50		|50	
[sun/security/pkcs11/Secmod/JksSetPrivateKey](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_Secmod_JksSetPrivateKey/)	|1 min 51 sec	|0		|0		|50		|50	
[sun/security/pkcs11/Secmod/LoadKeystore](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_Secmod_LoadKeystore/)	| 1 min 12 sec	| 0	|	0	|	50	|	50	
[sun/security/pkcs11/Secmod/TrustAnchors](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_Secmod_TrustAnchors/)| 	59 sec	|0	|	0	|	50|		50	
[sun/security/pkcs11/ec/TestCurves](https://ci.adoptium.net/job/Grinder/10266/testReport/sun_security_pkcs11_ec_TestCurves/)	|2 min 52 sec	|0		|0		|50		|50	

I have tried running with `/usr/bin/update-crypto-policies --set LEGACY` set but that did not affect the failures.

Note that the results above are from x64. The tests are skipped on aarch64 due to [this map](https://github.com/openjdk/jdk8u/blob/012f59c7f63fc44c1949d905203ea3f449087cd4/jdk/test/sun/security/pkcs11/PKCS11Test.java#L579) not having an entry for Linux-aarch64-64 so it trips over [this line](https://github.com/openjdk/jdk8u/blob/012f59c7f63fc44c1949d905203ea3f449087cd4/jdk/test/sun/security/pkcs11/PKCS11Test.java#L256) which skips it.

A suitable Grinder for re-running these (plus a few other s that fail on the platform) is at [this link](https://ci.adoptium.net/job/Grinder/parambuild/?SDK_RESOURCE=nightly&TARGET=jdk_custom&TEST_FLAG=&UPSTREAM_TEST_JOB_NAME=&DOCKER_REQUIRED=false&ACTIVE_NODE_TIMEOUT=&VENDOR_TEST_DIRS=&EXTRA_DOCKER_ARGS=&TKG_OWNER_BRANCH=adoptium%3Amaster&OPENJ9_SYSTEMTEST_OWNER_BRANCH=eclipse%3Amaster&PLATFORM=x86-64_linux&GENERATE_JOBS=false&KEEP_REPORTDIR=true&PERSONAL_BUILD=false&ADOPTOPENJDK_REPO=https%3A%2F%2Fgithub.com%2Fadoptium%2Faqa-tests.git&RERUN_ITERATIONS=0&LABEL=test-docker-amazon2023-x64-1&EXTRA_OPTIONS=&CUSTOMIZED_SDK_URL=&BUILD_IDENTIFIER=&ADOPTOPENJDK_BRANCH=master&LIGHT_WEIGHT_CHECKOUT=false&NON_AQA_TEST_REPOS=&ARTIFACTORY_SERVER=&KEEP_WORKSPACE=false&USER_CREDENTIALS_ID=&JDK_VERSION=8&ITERATIONS=50&VENDOR_TEST_REPOS=&JDK_REPO=&OPENJ9_BRANCH=master&OPENJ9_SHA=&JCK_GIT_REPO=&VENDOR_TEST_BRANCHES=&OPENJ9_REPO=https%3A%2F%2Fgithub.com%2Feclipse-openj9%2Fopenj9.git&UPSTREAM_JOB_NAME=&CLOUD_PROVIDER=&PLATFORM_AND_MACHINE=&CUSTOM_TARGET=sun%2Fnio%2Fcs%2FTestCharsetMapping.java+sun%2Fnio%2Fcs%2FTestIBMBugs.java+sun%2Fnio%2Fcs%2FTestCharsetMapping.java+sun%2Fnio%2Fcs%2FTestIBMBugs.java+sun%2Fsecurity%2Fpkcs11%2Fec%2FTestCurves.java+sun%2Fsecurity%2Fpkcs11%2FProvider%2FLogin.sh+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FAddPrivateKey.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FGetPrivateKey.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FJksSetPrivateKey.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FLoadKeystore.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FTrustAnchors.java+sun%2Fsecurity%2Ftools%2Fkeytool%2Fautotest.sh+sun%2Fsecurity%2Fpkcs11%2Fec%2FTestCurves.java+sun%2Fsecurity%2Fpkcs11%2FProvider%2FLogin.sh+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FAddPrivateKey.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FGetPrivateKey.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FJksSetPrivateKey.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FLoadKeystore.java+sun%2Fsecurity%2Fpkcs11%2FSecmod%2FTrustAnchors.java+sun%2Fsecurity%2Ftools%2Fkeytool%2Fautotest.sh&VENDOR_TEST_SHAS=&JDK_BRANCH=&TEST_IMAGES_REQUIRED=true&LABEL_ADDITION=&ARTIFACTORY_REPO=&ARTIFACTORY_ROOT_DIR=&UPSTREAM_TEST_JOB_NUMBER=&DOCKERIMAGE_TAG=&JDK_IMPL=hotspot&SSH_AGENT_CREDENTIAL=&AUTO_DETECT=true&DYNAMIC_COMPILE=false&ADOPTOPENJDK_SYSTEMTEST_OWNER_BRANCH=adoptium%3Amaster&APPLICATION_OPTIONS=&CUSTOMIZED_SDK_URL_CREDENTIAL_ID=eclipse_temurin_bot_email_and_token&ARCHIVE_TEST_RESULTS=false&OPENJDK_SHA=&NUM_MACHINES=&BUILD_LIST=openjdk&USE_TESTENV_PROPERTIES=true&UPSTREAM_JOB_NUMBER=&STF_OWNER_BRANCH=adoptium%3Amaster&TIME_LIMIT=50&JVM_OPTIONS=&PARALLEL=None)

**Comment by sxa** [comment]
See more complete table in https://github.com/adoptium/aqa-tests/issues/5420#issuecomment-2217625378

**Comment by sxa** [comment]
We can possibly close this as a dupliate of #5420 sine most of these are seen there too (The exception being `pkcs11/ec/TestCurves` but maybe that's been fixed in the last few months)

**Comment by smlambert** [comment]
Agree, closing as dup of #5420
