### ISSUE TITLE
Unrecognized VM option 'EnableExtendedHCR' from IllegalAccessProtectedMethodTest_0 suite

### ISSUE THREAD

**Issue by sxa** [adoptium/aqa-tests#5393]
Seen in https://github.com/adoptium/infrastructure/issues/3598#issuecomment-2168484847
Looks to have been added in https://github.com/adoptium/aqa-tests/pull/5385

@JasonFengJ9 Is this a J9-specific option?

**Comment by JasonFengJ9** [comment]
> Is this a J9-specific option?

@sxa Yes, it was added to `serviceability_jvmti_j9` via 
* https://github.com/adoptium/aqa-tests/pull/5385
https://github.com/adoptium/aqa-tests/blob/1eae88fe1065e6f55b329487a75310a6cb35d375/openjdk/playlist.xml#L435-L438

**Comment by sxa** [comment]
Seems reasonable ... looking further the line that's in my log is:
```
 "/home/jenkins/workspace/Test_openjdk21_hs_extended.functional_riscv64_linux/jdkbinary/j2sdk-image/bin/java"   \
 -XX:+EnableExtendedHCR \
```
which is not the same as your code which has that new parameter directly after `-Xmx512` so I'm wondering if it has sneaked in somewhere else for the test suite on hotspot variants.

@smlambert recommended re-running with the `DYNAMIC_COMPILE` option which I did at https://ci.adoptium.net/job/Grinder/10401 but that has not changed the result - same error message.

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/blob/master/test/functional/IllegalAccessError_for_protected_method/playlist.xml#L27
https://github.com/eclipse-openj9/openj9/pull/19554

The OpenJ9 test needs to be split to have a hotspot variant. @LongyuZhang

**Comment by JasonFengJ9** [comment]
> The OpenJ9 test needs to be split to have a hotspot variant. 

The OpenJ9 `playlist` needs the following `<impls>` otherwise it can't be consumed by Adoptium hotspot tests.
```
		<impls>
			<impl>openj9</impl>
			<impl>ibm</impl>
		</impls>
```

**Comment by LongyuZhang** [comment]
I will split the the test `IllegalAccessProtectedMethodTest` to have openj9 and hotspot variant then.

**Comment by pshipton** [comment]
https://github.com/eclipse-openj9/openj9/pull/19554 added the option to quite a few tests, I'm not sure how many of them run on hotspot. I'm also wondering if all these tests need to have the option added. There is a bug being fixed via https://github.com/eclipse-openj9/openj9/pull/19710

**Comment by LongyuZhang** [comment]
Checked all other tests in `playlist.xml` modified by https://github.com/eclipse-openj9/openj9/pull/19554, they are all `openj9` and `ibm` only.
