### ISSUE TITLE
TRSS is not picking up new builds...?

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5410]
https://trss.adoptium.net/ is currently not picking up new builds since about 25th June ?

**Comment by sophia-guo** [comment]
I see 28th June of  [AQA_Test_Pipeline](https://trss.adoptium.net/builds?buildName=AQA_Test_Pipeline&url=https%3A%2F%2Fci.adoptopenjdk.net&type=Test) https://trss.adoptium.net/

**Comment by jiekang** [comment]
E.g.

https://trss.adoptium.net/builds?buildName=openjdk21-pipeline&url=https%3A%2F%2Fci.adoptium.net%2Fjob%2Fbuild-scripts&type=Test

At time of writing shows build 293 as latest, but

https://ci.adoptium.net/job/build-scripts/job/openjdk21-pipeline/

Has builds well past that.

**Comment by andrew-m-leonard** [comment]
@sophia-guo @ShelleyLambert Could the issue be the Mongo DB maybe?

It's also interesting that the AQA_Test_pipeline list is fine, noticably that one uses the old Jenkins DNS: **https://ci.adoptopenjdk.net**
Also, the others qualify the Jenkins with "job/build-scripts", whereas AQA_Test_pipeline does not, has the URl been updated?
**https://ci.adoptium.net/job/build-scripts**

**Comment by smlambert** [comment]
I found the actual problem.  All monitoring of pipelines except the AQA_Test_Pipeline appears to have been removed (not sure by who).  Fixing now.

**Comment by smlambert** [comment]
Close as resolved.
