### ISSUE TITLE
Avoid archiving tap files when `enableTests` is false

### ISSUE THREAD

**Issue by LongyuZhang** [adoptium/aqa-tests#5412]
In build pipeline, when `enableTests` is unchecked, then archiving tap files is not needed.
E.g. hyc_jenkins/job/build-scripts/job/openjdk17-pipeline-IBM/775/parameters/ the `enableTests` is unchecked, but the tap files were still collected.
`16:24:20  + find . -type f -name *.tap -exec tar -czf AQAvitTapFiles.tar.gz {} +`

**Comment by sophia-guo** [comment]
Dup of https://github.com/adoptium/ci-jenkins-pipelines/issues/1039, fixed by a couple of PR, the main one is https://github.com/adoptium/ci-jenkins-pipelines/pull/1041/files

@LongyuZhang IBM pipeline code needs to sync manually to get the latest code.
