### ISSUE TITLE
JDK22 & JDK21: CommandLinePositiveTest.java (httpserver and jwebserver versions) both fail with address in use

### ISSUE THREAD

**Issue by adamfarley** [adoptium/aqa-tests#5474]
[Original comment](https://github.com/adoptium/temurin/issues/50#issuecomment-2253696539) by Shelley Lambert in the July 2024 General Retrospective:

x64 Windows: com/sun/net/httpserver/simpleserver/CommandLinePositiveTest.java and simpleserver/jwebserver/CommandLinePositiveTest.java are problematic for JDK22 and JDK21, address in use failures

**Comment by steelhead31** [comment]
please assign to me.

**Comment by adamfarley** [comment]
I can't. I've posted a request in the Slack channel.

**Comment by smlambert** [comment]
Some recent Grinders in this triage comment https://github.com/adoptium/aqa-tests/issues/5445#issuecomment-2233607633

**Comment by sophia-guo** [comment]
So it's intermittent. Feels like the tests are affected if ports are used by other processes. Should be excluded or not?

**Comment by steelhead31** [comment]
Test runs :-   
:hourglass\_flowing\_sand: test-azure-win2019-x64-1 : [https://ci.adoptium.net/job/Grinder/10806](https://ci.adoptium.net/job/Grinder/10806)   
:heavy\_check\_mark: test-azure-win2022-x64-1 : [https://ci.adoptium.net/job/Grinder/10804](https://ci.adoptium.net/job/Grinder/10804)   
:hourglass\_flowing\_sand: test-azure-win2022-x64-2 : [https://ci.adoptium.net/job/Grinder/10805](https://ci.adoptium.net/job/Grinder/10805)   
:heavy\_check\_mark: test-azure-win2022-x64-3 : [https://ci.adoptium.net/job/Grinder/10803/](https://ci.adoptium.net/job/Grinder/10803/)
