### ISSUE TITLE
compiler/loopopts/TestUnrollLimitPreciseType.java#test1 fails on 32-bit platforms with Unknown VM option 'MaxVectorSize=64'

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5475]
Seen in July triage, compiler/loopopts/TestUnrollLimitPreciseType.java#test1 fails for x86-32_windows and arm_linux.

https://github.com/adoptium/aqa-tests/issues/5441#issuecomment-2237248649

Do not find any upstream issue but presume since this option is not recognized by either platform that the test should be excluded on the 2 platforms.

**Comment by smlambert** [comment]
Ideally this testcase exclusion would be reported upstream (in which case our problem lists can be changed to refer to the upstream issue and this one be closed) and/or added to upstream problem lists, in which case we can remove the exclusion from our problemlists, since we use both ours and upstream problem lists when executing test material.

**Comment by jiekang** [comment]
I will write a JBS report for this.

**Comment by jiekang** [comment]
Though first I will see what happened in 11+ compared to 8...

**Comment by jiekang** [comment]
This test is in `hotspot_jre` which only runs for jdk 8 and 9:

```
		<versions>
			<version>8</version>
			<version>9</version>
		</versions>
```

https://github.com/adoptium/aqa-tests/blob/6c93937ee35a08a95226c2b15dbe91867f95af25/openjdk/playlist.xml#L499

**Comment by jiekang** [comment]
Also noting for history, this test was introduced via backports of https://bugs.openjdk.org/browse/JDK-8303466

**Comment by sophia-guo** [comment]
> Though first I will see what happened in 11+ compared to 8...

July release the test was disabled for jdk11+.

Grinder with hotspot_custom shows the test will be skipped with jdk11+ on win32 , passed on other platform
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10727/ - jdk11 win32
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10728/ - jdk17 win32
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10729/ -jdkk11 win64

The test will not be skipped and failed with `Unrecognized VM option 'MaxVectorSize=64'` with jdk8 win32. Passed with jdk8 linux-x64
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10735/console
https://ci.adoptium.net/view/Test_grinder/job/Grinder/10736/

If 32 bits cannot work with `MaxVectorSize=64` it should be skipped on 32bits. Looks like for jdk11+ [@requires vm.compiler2.enabled](https://github.com/adoptium/jdk11u/blob/master/test/hotspot/jtreg/compiler/loopopts/TestUnrollLimitPreciseType.java#L29) skips win32 platform while jdk8 doesn't support property `[vm.compiler2.enabled](https://github.com/adoptium/jdk8u/blob/master/test/jtreg-ext/requires/VMProps.java)`

There will be two solution for JBS reports. One is update jdk8 VMProps.java or add `@requires vm.bits != "32"` to test https://github.com/adoptium/jdk11u/blob/master/test/hotspot/jtreg/compiler/loopopts/TestUnrollLimitPreciseType.java#L29

**Comment by jiekang** [comment]
Excellent, thank you for the analysis @sophia-guo I will take this info and open a JBS to try to have an appropriate upstream fix.

**Comment by sophia-guo** [comment]
Closed in favour of https://bugs.openjdk.org/browse/JDK-8338125
