### ISSUE TITLE
hotspot_custom is broken with jdk8

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5491]
hotspot_custom is broken with jdk8 due to change of   JVM_NATIVE_OPTIONS in the playlist to `-nativepath:"$(TESTIMAGE_PATH)/hotspot/jtreg/native"` in https://github.com/adoptium/aqa-tests/pull/5370.  This change meant to use TARGET=disabled.hotspot_custom to run **openj9 custom serviceability jvmti test**  https://github.com/adoptium/aqa-tests/issues/5357 , which works by disabled.* target instead of hotspot_custom directly. I would prefer to separate a custom target to standardize the use of custom target.  https://github.com/adoptium/aqa-tests/issues/5357#issuecomment-2197503446  https://github.com/adoptium/aqa-tests/issues/5357#issuecomment-2197510570 

https://ci.adoptium.net/view/Test_grinder/job/Grinder/10733/

```
11:08:52  TESTING:
11:08:52  Error: The -nativepath path does not exist: /hotspot/jtreg/native
11:08:52  Usage:
```

@LongyuZhang @llxia

**Comment by LongyuZhang** [comment]
Will separate the custom test for hotspot and j9 then.
