### ISSUE TITLE
jck_run jdk tar ball download does not download for re-builds if folder already exists

### ISSUE THREAD

**Issue by andrew-m-leonard** [adoptium/aqa-tests#5625]
If a release re-build is performed, eg. for jdk-23+37 for risxcv64, when the jck jobs run and download and populate the jck_run/jdk folder with the jdk, if that folder already exists, ie.from the previous build, then it does not re-download:
https://github.com/adoptium/aqa-tests/blob/0c3f98b0fdd77deabebf896d2dfcfb665395f09d/buildenv/jenkins/JenkinsfileBase#L578

We should at least be wary of this? Always downloading would be an overhead...?

**Comment by sophia-guo** [comment]
This purpose of setup_jck_interactives() is to setup the  testing jdk automatically for interactive test to use. Once the agent has been assigned once to run jenkins test job the jdk will be available for interactive test, which run once is good and should not be deleted and run again.

**Comment by smlambert** [comment]
This works 'as designed', with the option as Sophia mentioned to remove the folder via a separate job (or manually) in the not so common event that a new build is created under the same tag.

**Comment by andrew-m-leonard** [comment]
Yep, I think we have this covered
