### ISSUE TITLE
jdk23+: Update openjdk test repo and branch setting logic

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5642]
Upstream openjdk/jdk now branch rather than forking since jdk23, same as adoptium.  Openjdk test repo and branch setting logic needs to update since there will be no repo like https://github.com/adoptium/jdkDDu or https://github.com/adoptium/jdkDD repo for jdk23+

**Comment by sophia-guo** [comment]
Jobs triggered nightly or release by pipeline wont be affected as JDK_REPO and JDK_BRANCH are set by upstream job.

**Comment by sophia-guo** [comment]
Check if [repo jdkDDu exists ](https://github.com/adoptium/aqa-tests/blob/master/openjdk/build.xml#L183-L201) can be removed. JDKDDu repo will aways be available for versions before jdk23. For jdk23+ repo will be always same as adopitium/jdk, tags are used to refer different versions.

**Comment by sophia-guo** [comment]
For jdk23+ what will be the test senario when using grinder? Should jdk_branch is a must? Otherwise how should the tag be set? For earlier version we set the default branch as dev. For jdk23+ the dev would actually be head master as latest version.  @smlambert

**Comment by smlambert** [comment]
We should keep previous functionality where we default to use the jdkXXu repo and its dev branch, so now our default could be
https://github.com/adoptium/jdk and dev_jdk{$JDK_VERSION} , so [dev_jdk23](https://github.com/adoptium/jdk/tree/dev_jdk23) when no JDK_REPO or JDK_BRANCH is supplied.

**Comment by smlambert** [comment]
for reference: https://api.adoptium.net/q/swagger-ui/#/Release%20Info/getAvailableReleases

**Comment by andrew-m-leonard** [comment]
Ref openjdk maillist on stabilization release branching: https://mail.openjdk.org/pipermail/jdk-dev/2024-March/008834.html

**Comment by sophia-guo** [comment]
@andrew-m-leonard for Adotpium, when or will jdk23u be available? openjdk has https://github.com/openjdk/jdk23u but right now no jdk23u in adoptium. By default openjdk test in aqa-tests will use adoptium repo.

**Comment by andrew-m-leonard** [comment]
> @andrew-m-leonard for Adotpium, when or will jdk23u be available? openjdk has https://github.com/openjdk/jdk23u but right now no jdk23u in adoptium. By default openjdk test in aqa-tests will use adoptium repo.

I shall try and create it in the next few days

**Comment by sophia-guo** [comment]
To simplify ( refer https://api.adoptium.net/q/swagger-ui/#/Release%20Info/getAvailableReleases and https://github.com/adoptium/jdk/branches )

```
 If it's adoptium/jdkDDu available 
        use adoptium/jdkDDu repo and dev branch 
else it's tip version
       use adopitum/jdk and dev branch
else
       use adoptium/jdk and dev_jdkversion branch
```

@andrew-m-leonard is that correct?

**Comment by andrew-m-leonard** [comment]
> To simplify ( refer https://api.adoptium.net/q/swagger-ui/#/Release%20Info/getAvailableReleases and https://github.com/adoptium/jdk/branches )
> 
> ```
>  If it's adoptium/jdkDDu available 
>         use adoptium/jdkDDu repo and dev branch 
> else if it's tip version
>        use adopitum/jdk and dev branch
> else
>        use adoptium/jdk and dev_jdkversion branch
> ```
> 
> @andrew-m-leonard is that correct?

Looks good thanks @sophia-guo
