### ISSUE TITLE
TestVectorizationMismatchedAccess fails on Big Endian platforms (s390x Linux, aix / JDK23)

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#5706]
Seen in https://github.com/adoptium/aqa-tests/issues/5693#issuecomment-2420765323

TestVectorizationMismatchedAccess fails and needs exclusion under https://bugs.openjdk.org/browse/JDK-8342489

```
TestVectorizationMismatchedAccess fails with:
java.lang.RuntimeException: fix test that was written for a little endian platform
	at compiler.c2.irTests.TestVectorizationMismatchedAccess.main(TestVectorizationMismatchedAccess.java:54)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.sun.javatest.regtest.agent.MainWrapper$MainTask.run(MainWrapper.java:138)
	at java.base/java.lang.Thread.run(Thread.java:1575)

JavaTest Message: Test threw exception: java.lang.RuntimeException: fix test that was written for a little endian platform
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: fix test that was written for a little endian platform
```

**Comment by sophia-guo** [comment]
A pr is created https://github.com/openjdk/jdk/pull/21736 so we might not need to do the exclusion. Just to confirm that the PR will be backported to jdk23

**Comment by sophia-guo** [comment]
@jiekang could you please update https://bugs.openjdk.org/browse/JDK-8342489 Affects Version/s with 23 too?

**Comment by jiekang** [comment]
> @jiekang could you please update https://bugs.openjdk.org/browse/JDK-8342489 Affects Version/s with 23 too?

Done

**Comment by offamitkumar** [comment]
>Just to confirm that the PR will be backported to jdk23 

I'll backport it to jdk23 once I get approval for PR on head stream. Also for s390x-specific issues, feel free to tag/mail me :-)

**Comment by sophia-guo** [comment]
Commit in https://github.com/openjdk/jdk23u/commit/37c05c05c1977bcf22cdeb9d0b6c44a4fa51d7cc

grinder s390x https://ci.adoptium.net/job/Grinder/11348/
ppc64aix https://ci.adoptium.net/job/Grinder/11349/
