### ISSUE TITLE
jck17a version

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5748]
There should be a jck17a for the January CPU, aqa need to update to support that version.

Change should be related with https://github.com/adoptium/aqa-tests/tree/master/jck/jtrunner/config . Similar PR is https://github.com/adoptium/aqa-tests/pull/4601

**Comment by adamfarley** [comment]
Please assign this task to me.

**Comment by adamfarley** [comment]
Thanks :)

**Comment by adamfarley** [comment]
PR ready for review. https://github.com/adoptium/aqa-tests/pull/5780

The JCK repo will also need updating. Will cover that work here: https://github.com/temurin-compliance/temurin-compliance/issues/601
