### ISSUE TITLE
 /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5754]
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found on https://ci.adoptium.net/computer/test%2Ddocker%2Dubuntu2004%2Dx64%2D4/

https://ci.adoptium.net/view/Test_grinder/job/Grinder_Simple/391/
Same job no issues on https://ci.adoptium.net/computer/test-docker-ubuntu2204-x64-6/
https://ci.adoptium.net/view/Test_grinder/job/Grinder_Simple/392/

**Comment by sxa** [comment]
> Re-opening this one to ensure we apply an appropriate test label (following an agreed upon labelling schema so it interoperates across all Jenkins servers) and modify the test pipeline code (rather than the build pipeline code), to avoid continuously hitting this when running Grinders.
> 
> https://ci.adoptium.net/view/Test_grinder/job/Grinder/11386/console

Can we go back a step and clarify the goal here as I wasn't aware we were "continually" hitting this and the `rhel6` label should cover all the Temurin use-cases?

Are we trying to allow arbitrary binaries from elsewhere which may have arbitrary requirements to execute on our machines? Without knowing that, the amount of labels required to support that and the complexity of expressions could get a bit unwieldy.

**Comment by smlambert** [comment]
> Are we trying to allow arbitrary binaries from elsewhere which may have arbitrary requirements to execute on our machines? Without knowing that, the amount of labels required to support that and the complexity of expressions could get a bit unwieldy.

No.

We are trying to write test pipeline code that can run on any vendors own Jenkins server without forking it or modification.  As such, we have agreed upon a label schema, so that when we need new labels for things, its predictable and remains the same across all disparate servers.

**Comment by sxa** [comment]
> > Are we trying to allow arbitrary binaries from elsewhere which may have arbitrary requirements to execute on our machines? Without knowing that, the amount of labels required to support that and the complexity of expressions could get a bit unwieldy.
> 
> No.
> 
> We are trying to write test pipeline code that can run on any vendors own Jenkins server without forking it or modification. As such, we have agreed upon a label schema, so that when we need new labels for things, its predictable and remains the same across all disparate servers.

Gotcha - I think it would be good to have a working session on a call to thrash this one out since there are likely a lot of subtleties with this to come up with something practical and not overly onerous to avoid "tag sprawl" complexities - it sounds like we are looking for a generic form of our `rhel6` label on the basis that other people might have a similar situation for their testing where they're running a jenkins server where not all agents are capable of running the JVM that they have. I guess things like building targetting a specific distribution would be a good example.

**Comment by smlambert** [comment]
> I think it would be good to have a working session on a call to thrash this one

That public discussion happened a long time ago, in 2018 I believe, from which sprung forth the current labeling schema https://github.com/adoptium/aqa-tests/blob/master/doc/pages/LabelSchema.md#jenkins-machine-labelling-schema we use for test pipelines, exactly to avoid duplication and sprawl.

The reason we chose to use 'long name labels' is to help categorize the types of labels and give guidance to anyone who wanted to extend the schema.

**Comment by sxa** [comment]
> One of the reasons we chose to use 'long name labels' is to help categorize the types of labels and give guidance to anyone who wanted to extend the schema.

Yeah absolutely - I have no issues with that, but I think we need to carefully thinkg about how many different ones we want to have for this particular use case. Maybe a topic for Tuesday's call :-)

**Comment by smlambert** [comment]
> Have I captured this correctly as per your understanding?

Pretty much, as per the original discussion and per how some of the real-world labels look like, dotted version numbers look like:
- sw.os.zos.1_13 (where dotted version numbers represented by _ )
- the name of the parameter is LABEL_ADDITION (which behaves to append `&&` its value to the LABEL parameter, so our approach has been to use !someValue when it makes more sense to, as in this case)

**Comment by sxa** [comment]
>   sw.os.zos.1_13 (where dotted version numbers represented by _ )

OK so I'll look at implementing `sw.tool.glibc.2_12` for us initially as a direct replacement for the current [rhel6](https://ci.adoptium.net/label/rhel6/) and [centos6](https://ci.adoptium.net/label/centos6/) labels :-)

>  the name of the parameter is LABEL_ADDITION (which behaves to append `&&` its value to the LABEL parameter, so our approach has been to use !someValue when it makes more sense to, as in this case)

Yep - `ADDITIONAL_TEST_LABEL` is the equivalent parameter in the json of the [platform-specific pipelines](https://ci.adoptium.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-temurin/501/parameters/) which should get passed down to `LABEL_ADDITION` in the test jobs. e.g. at https://github.com/adoptium/ci-jenkins-pipelines/blob/782ebb0ffc5fbf9947dfb6c9065648e47bab2c7f/pipelines/jobs/configurations/jdk21u_pipeline_config.groovy#L30

**Comment by sophia-guo** [comment]
> modify the test pipeline code (rather than the build pipeline code)

Currently the test information mainly locates in two places in build pipelines:

- [jdk**_pipeline_config.groovy](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/jobs/configurations/jdk21u_pipeline_config.groovy): maps test and additionalTestLabels.

- [testDetails](https://github.com/adoptium/ci-jenkins-pipelines/blob/master/pipelines/defaults.json#L39-L78)

Those configuration can be moved https://github.com/adoptium/aqa-tests/tree/master/buildenv/jenkins/config/temurin and https://github.com/adoptium/aqa-tests/tree/master/buildenv/jenkins/config/openj9
