### ISSUE TITLE
Turn off the verbose(debug) option for disable tests linter workflow

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#5795]
Disable tests linter workflow enables the verbose(debug) output, which is used for debug and would be better to turn off for the workflow. So it's easy to notice the error message.

**Comment by jiekang** [comment]
Feel free to assign me

**Comment by llxia** [comment]
I noticed that @annaibm is working on the fix: https://github.com/annaibm/aqa-tests/commit/df233002f4c9b603344da9ead2c5fa2468f1043b
