### ISSUE TITLE
type:external Reported Upstream issues 

### ISSUE THREAD

**Issue by Mesbah-Alam** [adoptium/aqa-tests#587]
- [x] Open-Liberty bug opened upstream : https://github.com/OpenLiberty/open-liberty/issues/5125

- [x] Payara-mp-tck issue https://github.com/AdoptOpenJDK/openjdk-tests/issues/1160  : https://github.com/payara/MicroProfile-TCK-Runners/issues/42 

- [x] jenkins error https://github.com/AdoptOpenJDK/openjdk-tests/issues/1409 : https://github.com/eclipse/openj9/issues/7669

**Comment by smlambert** [comment]
The upstream bug has been fixed.  If something is excluded or not running, we should check its working and reinclude.

**Comment by smlambert** [comment]
https://github.com/payara/MicroProfile-TCK-Runners/issues/42 has been closed with a note that it is fixed.  Need to try to reinclude payara-mp-tck tests and see if they can run clean.

**Comment by smlambert** [comment]
All related upstream issues are closed, closing this asstale, we are going through a health assessment of external tests via https://github.com/adoptium/aqa-tests/issues/3187 and will create fresh issues as they arise.
