### ISSUE TITLE
Investigate and fix openj9 sanity functional test failures when run in docker containers

### ISSUE THREAD

**Issue by chandrams** [adoptium/aqa-tests#791]
From #714

Gave a run of openj9 sanity functional tests in docker container and below tests fail in docker container:

FAILED test targets:

cmdLineTester_callsitedbgddrext_openj9_0
cmdLineTester_SCCommandLineOptionTests_1

**Comment by chandrams** [comment]
cmdLineTester_callsitedbgddrext_openj9_0

OUT] Could not load dump file and/or could not load XML file: Image file '/openj9/test/TestConfig/test_output_15433322797739/cmdLineTester_callsitedbgddrext_openj9_0/j9core.dmp' not found.
[OUT] For a list of commands, type "help"; for how to use "help", type "help help"
[OUT] > DDR is not enabled for this core file, '!' commands are disabled

To resolve this failure, we will need to modify the content of /proc/sys/kernel/core_pattern on the host machine to just j9core which would require root access.  And core_pattern content should be changed before this test and restored back after the test. 

 cmdLineTester_SCCommandLineOptionTests_1

[OUT] nameOption2: TEST FAILED
[OUT] nameOption2: Expected to find the cache name
[OUT] TEST PASSED

Investigated the above test failure and found that it uses env variable LOGNAME to validate if the cache is created with the name of the user logged in, this doesn't work in a docker container as LOGNAME is blank. We can pass try passing LOGNAME as an env to docker run.

**Comment by smlambert** [comment]
Defining environment variables in the autogenerated Dockerfile can be done via [common_functions.sh](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/common_functions.sh#L222-L237) file in a similar fashion to how its done in [camel tests](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/external/common_functions.sh#L183).

**Comment by smlambert** [comment]
We now run as type=normal (versus native) gets rid of issues with native test images not being available.
