### ISSUE TITLE
Add solaris jdk8 testing (openjdk + system)

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#799]
Now that there are [solaris builds for jdk8](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-solaris-sparcv9-hotspot), we should enable testing

jdk8 openjdk: 

- [ ] [openjdk8_hs_openjdktest_sparcv9_solaris](https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_sparcv9_solaris/)

jdk8 system:

- [ ] openjdk8_hs_systemtest_sparc_solaris

Do not yet see a live jdk11 build for solaris, so will wait for it before enabling testing in that version.

**Comment by smlambert** [comment]
smlambert:solarisTest has the updates required, now just need a solaris machine with the test prereqs installed on it:

Test job fails due to "Can't locate XML/Parser.pm" which is one of the test prereqs:
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_sparcv9_solaris/7/console

**Comment by smlambert** [comment]
Now we have a dedicated solaris machine for test, will revisit this item.  https://ci.adoptopenjdk.net/computer/test-inspira-solaris10u11-sparcv9-1/

**Comment by smlambert** [comment]
related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/846

**Comment by smlambert** [comment]
Once https://github.com/eclipse/openj9/pull/6737 is merged, and we create the test jobs for versions required, this can be closed.

**Comment by smlambert** [comment]
Grinder: 
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder_Advanced/706

**Comment by smlambert** [comment]
Closing this as test portion of this is completed, we still require a solaris machine with all of the prereqs installed for use by testing, but there is no further test work to do.  

Related: https://github.com/AdoptOpenJDK/openjdk-infrastructure/issues/631

**Comment by sxa** [comment]
Let's reopen this and try to complete it :-) We've put in a couple of PRs recently and at the time of writing the jobs still aren't quite able to complete:
- https://github.com/AdoptOpenJDK/TKG/pull/110
- https://github.com/AdoptOpenJDK/TKG/pull/157
- Looks like this might also require a `printenv` -> `env` fix that had previously only been made for SPARC: https://github.com/sophia-guo/openjdk-tests/commit/abc1db1d825986a8810efc0ffb4aeb55e2c5e587

**Comment by sxa** [comment]
*Summary of fixes:*
- On `test-inspura-solaris10u11-sparcv9-1` there were three versions of ant on the system. `/usr/sfw` (1.7.1) `/opt/csw` (1.8.4) and the useful one in `/usr/local` (1.10.5). Since `/opt/csw/bin` was in the path first I've replaced `/opt/csw/bin/ant` with a symlink to the `/usr/local` one to allow testing to proceed for now
- On `build-packet_esxi-solaris10u11-x64-1` I've added `/usr/local/bin` to the `PATH` in the jenkins machine definition to allow it to proceed.
*Summary of PRs required* (Grinder_TKG have been run with both of these patches applied)
- 
*Summary of execution:*
- [X64](https://ci.adoptopenjdk.net/job/Grinder_TKG/191/console): `jdk_lang` failures due to machine being broken with `/bin` not being sane.
- [SPARC](https://ci.adoptopenjdk.net/job/Grinder_TKG/190/): A couple of timeouts in `jdk_math` and `jdk_util` but otherwise good

**Comment by smlambert** [comment]
Need to add solaris platforms to ottawa.csv and likely buildPlatformMap.properties in https://github.com/adoptium/TKG/tree/master/resources (that is how variations in playlists are determined, if they are using shorthand 'mode' nomenclature instead of fully expanded command line option entries)

**Comment by lumpfish** [comment]
Might be similar to https://github.com/AdoptOpenJDK/openjdk-tests/issues/2096 where the root cause was the system test build failing to complete successfully (in that case the native test cases).

**Comment by smlambert** [comment]
Yes, system tests need extra changes when adding support for new platforms.  I will be reviewing and merging some improvements/PRs (related: https://github.com/adoptium/aqa-systemtest/issues/413) from @Mesbah-Alam this week before endeavouring to update systemtest support for these solaris platforms.

**Comment by sxa** [comment]
>  before endeavouring to update systemtest support for these solaris platforms.

SGTM - I'll hold off on those until you've done that work.

**Comment by sxa** [comment]
https://ci.adoptopenjdk.net/job/Grinder_TKG/202/console still seems to have the problem with being unable to find `stf.pl`

**Comment by sxa** [comment]
@Mesbah-Alam Is there a reason that the Solaris systemtests are currently unable to find `stf.pl`?
```
14:23:48  Can't open perl script "/export/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../../jvmtest/system/otherLoadTest/..//stf/stf.core/scripts/stf.pl": No such file or directory
```

**Comment by Mesbah-Alam** [comment]
Looking at the output of [this](https://ci.adoptopenjdk.net/job/Grinder_TKG/194/consoleFull) build, the first failure is here: 

```
08:48:05  /export/home/jenkins/workspace/Grinder_TKG/openjdk-tests/system/stf/stf.build/include/top.xml:610: java os.name property value SunOS not recognised.  Update the get-platform-prefix macrodef in stf.build/include/top.xml
```
systemtest fails at a [check](https://github.com/adoptium/STF/blob/master/stf.build/include/top.xml#L566) in top.xml that fails to recognize output of `java.os.name` property on this Solaris box - `SunOS`. 

I'll create a PR to add `SunOS` to the list of known platforms in top.xml as a short term fix. 

In long term, we need to investigate if `get-platform-prefix` macro is needed any longer, now that systemtest makefiles [do not need PLATFORM variable anymore](https://github.com/adoptium/aqa-systemtest/issues/413).

**Comment by Mesbah-Alam** [comment]
After getting past the top.xml issue, a bunch of new issues are [surfacing](https://ci.adoptopenjdk.net/job/Grinder_TKG/210/console) from STF Perl layer, e.g.: 

```
11:59:46  Uncaught exception from user code:
11:59:46  	Unable to determine amount of free space for test results, terminating
11:59:46   at /export/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../../jvmtest/system/otherLoadTest/..//stf/stf.core/scripts/stf.pl line 774
11:59:46  	main::check_free_space('/export/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/...') called at /export/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../../jvmtest/system/otherLoadTest/..//stf/stf.core/scripts/stf.pl line 380
11:59:46  Unable to parse df -k /export/home/jenkins/workspace/Grinder_TKG/openjdk-tests/TKG/../TKG/output_1616083182335/ClassLoadingTest_5m_0 output:
11:59:46  Filesystem            kbytes    used   avail capacity  Mounted on
11:59:46  rpool/export/home    245661696 4056006 228459383     2%    /export/home
```

Looking at them now..

**Comment by Mesbah-Alam** [comment]
@sxa , After [adding](https://github.com/adoptium/STF/pull/108) the required support for Solaris in STF, system tests have now stated to run and pass on Solaris: https://ci.adoptopenjdk.net/job/Grinder_TKG/216/console 

Will submit my PR for review once the build finishes.

**Comment by smlambert** [comment]
Can this now be closed?

**Comment by sxa** [comment]
Depends if the goal of this was "add support" or "test it regularly" ;-) But in principle I'm ok with closing it and dealing with subsequent issues in follow-on issues. We haven't fully tested on sparc yet (it's mentioned in the checkbox in the description as being required for this issue) but I expect that the test scripts will be in a decent state now for that too.

**Comment by smlambert** [comment]
I think the 'build it and test it regularly' part needs to be an issue raised in https://github.com/AdoptOpenJDK/ci-jenkins-pipelines repo.

I'll create an issue then close this.

**Comment by smlambert** [comment]
https://github.com/adoptium/ci-jenkins-pipelines/issues/115 was created to add regularity to testing on these 2 platforms (sparcv9_solaris and x86-64_solaris).  All changes required to run tests are in, so this issue can be closed (noting that we are even able to run JCKs on these two platforms along with the AQA test groups).
