### ISSUE TITLE
regression tests error  with openj9 java8

### ISSUE THREAD

**Issue by sophia-guo** [adoptium/aqa-tests#830]
**On Mac:**
Following tests got timeout error with error message " RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL". No JBS reports.

java/io/Serializable/serialver/classpath/run.sh.run
java/io/Serializable/serialver/nested/run.sh.run 
java/util/logging/TestLoggingWithMainAppContext.java.TestLoggingWithMainAppContext
java/util/logging/TestMainAppContext.java.TestMainAppContext

```
Stacktrace

Program `/Users/jenkins/workspace/openjdk8_j9_openjdktest_x86-64_macos/openjdkbinary/j2sdk-image/jre/bin/../../bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960045ms).    

Standard Output

Creating loggers.
bar1.getParent() is the same as foo1
Now running with security manager
Timeout refired 960 times
    

Standard Error

_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
    
```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_macos/lastCompletedBuild/testReport/

java/rmi/activation/Activatable/checkAnnotations/CheckAnnotations.java
java/rmi/activation/Activatable/nestedActivate/NestedActivate.java same failure with ' nested exception is: java.lang.NullPointerException', no JBS report

Both triggered by code:
`                        ActivationGroupID groupID =
                            ActivationGroup.getSystem().
                            registerGroup(groupDesc);
`

```
Test failed with: null
java.lang.NullPointerException
	at CheckAnnotations.main(CheckAnnotations.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)
rmid shut down
ACTIVATION_LIBRARY: Activation System available after 0 milliseconds
RMID: getting a reference to the activation system
RMID: obtained a reference to the activation system
RMID: testlibrary finished shutting down rmid
RMID: rmid exited on shutdown request
ACTIVATION_LIBRARY: finished destroying rmid
RMID: removing rmid's old log file...
TestFailedException: TEST FAILED: ; nested exception is: 
	java.lang.NullPointerException
java.lang.NullPointerException
	at CheckAnnotations.main(CheckAnnotations.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)

```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_macos/83/testReport/junit/java_rmi_activation_Activatable_checkAnnotations_CheckAnnotations/java/CheckAnnotations/

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_macos/86/testReport/junit/java_rmi_activation_Activatable_nestedActivate_NestedActivate/java/NestedActivate/

**Comment by sophia-guo** [comment]
**On Win32**
sun/util/logging/PlatformLoggerTest.java failed with 'Logger test.logger.bar does not exist  '
JBS report https://bugs.openjdk.java.net/browse/JDK-8142464

```
java.lang.RuntimeException: Logger test.logger.bar does not exist
	at PlatformLoggerTest.checkLogger(PlatformLoggerTest.java:121)
	at PlatformLoggerTest.main(PlatformLoggerTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)

```
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-32_windows/118/testReport/junit/sun_util_logging_PlatformLoggerTest/java/PlatformLoggerTest/

**Comment by sophia-guo** [comment]
**LargeHeap:**
java/util/Arrays/TimSortStackSize2.java 'java.lang.OutOfMemoryError: Java heap space '

```
java.lang.OutOfMemoryError: Java heap space
	at TimSortStackSize2.createArray(TimSortStackSize2.java:164)
	at TimSortStackSize2.doTest(TimSortStackSize2.java:59)
	at TimSortStackSize2.main(TimSortStackSize2.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)

```

https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_linux_linuxXL/92/testReport/junit/java_util_Arrays_TimSortStackSize2/java/TimSortStackSize2/

**JBS: https://bugs.openjdk.java.net/browse/JDK-8199265**

**Comment by sophia-guo** [comment]
Note:
java/net/Inet6Address/B6206527.java.B6206527
java/net/MulticastSocket/SetGetNetworkInterfaceTest.java.SetGetNetworkInterfaceTest
java/net/MulticastSocket/SetOutgoingIf.java.SetOutgoingIf
java/net/ipv6tests/B6521014.java.B6521014
java/net/ipv6tests/UdpTest.java.UdpTest

also intermittent failed with hotspot java8 on linux-x86
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_x86-64_linux/313/#showFailuresLink

**Comment by lumpfish** [comment]
jdk/test/java/util/Arrays/TimSortStackSize2.java is referenced above as failing on linuxXL and the test is currently excluded for linux.  Test also fails with MacXL openjdk8-openj9 (tests being run for the first time).
```
15:34:03 ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.OutOfMemoryError: Java heap space
15:34:03 REASON: User specified action: run main/othervm -Xms385m TimSortStackSize2 67108864 
15:34:03 TIME:   15.218 seconds

15:34:03 java.lang.OutOfMemoryError: Java heap space
15:34:03 	at TimSortStackSize2.createArray(TimSortStackSize2.java:164)
15:34:03 	at TimSortStackSize2.doTest(TimSortStackSize2.java:59)
15:34:03 	at TimSortStackSize2.main(TimSortStackSize2.java:43)
15:34:03 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:34:03 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:34:03 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:34:03 	at java.lang.reflect.Method.invoke(Method.java:498)
15:34:03 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:34:03 	at java.lang.Thread.run(Thread.java:813)
```

**Comment by lumpfish** [comment]
Also on MacXL, PlatformLoggerTest.java is failing as described avoce for Windows and linuxXL.  Test is currently excluded for Windows and Linux, but not Mac.

```
15:57:50 java.lang.RuntimeException: Logger test.logger.bar does not exist
15:57:50 	at PlatformLoggerTest.checkLogger(PlatformLoggerTest.java:121)
15:57:50 	at PlatformLoggerTest.main(PlatformLoggerTest.java:73)
15:57:50 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:57:50 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:57:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:57:50 	at java.lang.reflect.Method.invoke(Method.java:498)
15:57:50 	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
15:57:50 	at java.lang.Thread.run(Thread.java:813)
15:57:50 
15:57:50 JavaTest Message: Test threw exception: java.lang.RuntimeException: Logger test.logger.bar does not exist
```

**Comment by sophia-guo** [comment]
Thanks @lumpfish will exclude those tests on Mac XL. 

Unfortunately currently there is no way to exclude the LargeHeap specifically as openjdk use uname to get out machine or OS information.

**Comment by sophia-guo** [comment]
sun/net/www/http/ChunkedOutputStream/checkError.java.checkError Issue opened in JBS as resolved: https://bugs.openjdk.java.net/browse/JDK-8041924
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_j9_openjdktest_x86-64_windows/199/testReport/junit/sun_net_www_http_ChunkedOutputStream_checkError/java/checkError/

```
Standard Error

java.lang.RuntimeException: Test Failed: haven't received the expected IOException
	at checkError.testExit(checkError.java:121)
	at checkError.main(checkError.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:813)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Test Failed: haven't received the expected IOException
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Test Failed: haven't received the expected IOException
    
```

**Comment by sophia-guo** [comment]
com/sun/net/httpserver/Test1.java get timeout error `Program `/home/jenkins/workspace/openjdk8_hs_openjdktest_ppc64le_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java' timed out (timeout set to 960000ms, elapsed time including timeout handling was 960563ms)' could be a net work issue?
https://ci.adoptopenjdk.net/view/Test_openjdk/job/openjdk8_hs_openjdktest_ppc64le_linux/265/console

**Comment by sophia-guo** [comment]
Remove sun/rmi/runtime/Log/6409194/NoConsoleOutput.java as same issue happened to HS and reported to JBS as closed https://bugs.openjdk.java.net/browse/JDK-8156798. Need to reopen it. 	
https://github.com/AdoptOpenJDK/openjdk-tests/issues/913

**Comment by smlambert** [comment]
This issue is pretty stale. Are there more current or specific issues that cover the failures? What actions need to be taken to address and close this one?

**Comment by sophia-guo** [comment]
This is openj9 specific. Tests are either excluded by openj9 problemlist or no longer failed. Close here.
