### ISSUE TITLE
gc/g1/TestShrinkAuxiliaryData25 hotspot test fails with AdoptOpenJDK test harness

### ISSUE THREAD

**Issue by jerboaa** [adoptium/aqa-tests#842]
I'm running `_extended.openjdk` tests on an upstream JDK 8u build like this:

    $ cat run_adopt_openjdk_jtreg_tests.sh
    #!/bin/bash
    OPENJDK_SOURCES=$1
    OPENJDK_BUILD=$2
    TEST_TARGET=$3
    if [ -z $TEST_TARGET ]; then
      TEST_TARGET="_sanity.openjdk"
    fi
    git clone https://github.com/AdoptOpenJDK/openjdk-tests
    cd openjdk-tests
    TOP_DIR=$(pwd)
    TEST_DIR="$TOP_DIR"
    pushd openjdk_regression
    ln -s $OPENJDK_SOURCES openjdk-jdk
    popd
    export JAVA_BIN=$OPENJDK_BUILD/jre/bin
    export SPEC=linux_x86-64
    export JDK_IMPL=hotspot
    export BUILD_LIST=openjdk_regression 
    export BUILD_ROOT=$TOP_DIR/test-results
    export JRE_IMAGE=$OPENJDK_BUILD/../j2re-image
    ./get.sh -t $TEST_DIR
    ./maketest.sh $TEST_DIR
    OPENJDK_DIR=$OPENJDK_SOURCES ./maketest.sh $TEST_DIR $TEST_TARGET
    $ rm -rf test-me-extended; mkdir test-me-extended; pushd test-me-extended; bash ../run_adopt_openjdk_jtreg_tests.sh /disk/openjdk/upstream-sources/openjdk8u-dev /disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image _extended.openjdk; popd

This runs `gc/g1/TestShrinkAuxiliaryData25` test which then fails with:

    Test will use 104 857 600 bytes of memory of 7 350 517 760 available
    Available memory is 7 245 660 160 with 8 bytes pointer size - can save 48 307 893 pointers
    Max cache size: 2^25 = 33 554 432 elements
    Command line: [/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/bin/../../bin/java -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=11 -XX:+UseG1GC -XX:G1HeapRegionSize=1048576 -XX:-ExplicitGCInvokesConcurrent -XX:+PrintGCDetails -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -Xbootclasspath/a:. -XX:G1ConcRSLogCacheSize=25 -ea -esa -Xmx512m -XX:ObjectAlignmentInBytes=8 TestShrinkAuxiliaryData$ShrinkAuxiliaryDataTest ]
    Heap
     garbage-first heap   total 505856K, used 1024K [0x00000000e0000000, 0x00000000e0100f70, 0x0000000100000000)
      region size 1024K, 2 young (2048K), 0 survivors (0K)
     Metaspace       used 2502K, capacity 4480K, committed 4480K, reserved 1056768K
      class space    used 273K, capacity 384K, committed 384K, reserved 1048576K

    Error: Could not find or load main class TestShrinkAuxiliaryData$ShrinkAuxiliaryDataTest

     stdout: [Heap
     garbage-first heap   total 505856K, used 1024K [0x00000000e0000000, 0x00000000e0100f70, 0x0000000100000000)
      region size 1024K, 2 young (2048K), 0 survivors (0K)
     Metaspace       used 2502K, capacity 4480K, committed 4480K, reserved 1056768K
      class space    used 273K, capacity 384K, committed 384K, reserved 1048576K
    ];
     stderr: [Error: Could not find or load main class TestShrinkAuxiliaryData$ShrinkAuxiliaryDataTest
    ]
     exitValue = 1

    Exception in thread "main" java.lang.RuntimeException: Expected to get exit value of [0]

            at com.oracle.java.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:362)
            at TestShrinkAuxiliaryData.performTest(TestShrinkAuxiliaryData.java:108)
            at TestShrinkAuxiliaryData.test(TestShrinkAuxiliaryData.java:95)
            at TestShrinkAuxiliaryData25.main(TestShrinkAuxiliaryData25.java:40)

When I run this via jtreg directly it passes:

    $ rm -rf JTwork JTreport && JT_JAVA=/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/jtreg/bin/jtreg -verbose hotspot/test/gc/g1/TestShrinkAuxiliaryData25.java 
    Directory "JTwork" not found: creating
    Directory "JTreport" not found: creating
    runner starting test: gc/g1/TestShrinkAuxiliaryData25.java
    runner finished test: gc/g1/TestShrinkAuxiliaryData25.java
    Passed. Execution successful
    Test results: passed: 1
    Report written to /disk/openjdk/upstream-sources/openjdk8u-dev/JTreport/html/report.html
    Results written to /disk/openjdk/upstream-sources/openjdk8u-dev/JTwork

**Comment by jerboaa** [comment]
When I look at the re-run commands I see this:

Adopt:

      $ cd /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/scratch/5 && DISPLAY=:0 GNOME_DESKTOP_SESSION_ID=this-is-deprecated HOME=/home/sgehwolf LANG=en_US.UTF-8 PATH=/bin:/usr/bin XMODIFIERS=@im=none     /disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/bin/../../bin/java         -Dtest.class.path.prefix=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/testlibrary:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/testlibrary/whitebox         -Dtest.src=/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1         -Dtest.src.path=/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary/whitebox         -Dtest.classes=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/gc/g1         -Dtest.class.path=/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/gc/g1:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/testlibrary:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/testlibrary/whitebox         -Dtest.vm.opts='-ea -esa -Xmx512m'         -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m'         -Dtest.compiler.opts=         -Dtest.java.opts=         -Dtest.jdk=/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/bin/../..         -Dcompile.jdk=/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/bin/../..         -Dtest.timeout.factor=8.0         -Dtest.root=/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test         -classpath /home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/testlibrary:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/work/classes/5/testlibrary/whitebox:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary/whitebox:/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/jre/bin/../../lib/tools.jar:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/jtreg/lib/javatest.jar:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/jtreg/lib/jtreg.jar         TestShrinkAuxiliaryData25

JTREG directly:

        $ cd /disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/scratch && \
    DISPLAY=:0 \
    GNOME_DESKTOP_SESSION_ID=this-is-deprecated \
    HOME=/home/sgehwolf \
    LANG=en_US.UTF-8 \
    PATH=/bin:/usr/bin \
    XMODIFIERS=@im=none \
    CLASSPATH=/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/testlibrary:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary:/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/testlibrary/whitebox:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary/whitebox:/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/lib/tools.jar:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/jtreg/lib/javatest.jar:/home/sgehwolf/Documents/openjdk/adopt-openjdk-prototype/test-me-extended/openjdk-tests/test-results/openjdk_regression/jtreg/lib/jtreg.jar \
        /disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java \
            -Dtest.src=/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1 \
            -Dtest.src.path=/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary:/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test/testlibrary/whitebox \
            -Dtest.classes=/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/gc/g1 \
            -Dtest.class.path=/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/gc/g1:/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/testlibrary:/disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/classes/testlibrary/whitebox \
            -Dtest.vm.opts= \
            -Dtest.tool.vm.opts= \
            -Dtest.compiler.opts= \
            -Dtest.java.opts= \
            -Dtest.jdk=/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image \
            -Dcompile.jdk=/disk/openjdk/upstream-sources/openjdk8u-dev/build/linux-x86_64-normal-server-release/images/j2sdk-image \
            -Dtest.timeout.factor=1.0 \
            -Dtest.root=/disk/openjdk/upstream-sources/openjdk8u-dev/hotspot/test \
            com.sun.javatest.regtest.agent.MainWrapper /disk/openjdk/upstream-sources/openjdk8u-dev/JTwork/gc/g1/TestShrinkAuxiliaryData25.d/driver.2.jta

**Comment by jerboaa** [comment]
So the commands look very different. Plain JTREG uses `MainWrapper`, Adopt's test harness not.

**Comment by smlambert** [comment]
This test passes when run in Jenkins using the Adopt setup/commands:
https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_extended_x86-64_linux/

Background:
We use the pre-defined groups for the openjdk test targets, example of a command looks like:
`$(JAVA_COMMAND) -Xmx512m -jar $(Q)$(TEST_RESROOT)$(D)jtreg$(D)lib$(D)jtreg.jar$(Q) \
	$(JTREG_BASIC_OPTIONS)  -vmoptions:$(Q)-Xmx512m $(JVM_OPTIONS)$(Q) \
	-w $(Q)$(TEST_RESROOT)$(D)work$(Q) \
	-r $(Q)$(TEST_RESROOT)$(D)report$(Q) \
	-jdk:$(Q)$(JDK_HOME)$(Q) \
	-exclude:$(Q)$(JTREG_TEST_DIR)$(D)ProblemList.txt$(Q) \
	-exclude:$(Q)$(TEST_RESROOT)$(D)ProblemList_$(JVM_VERSION).txt$(Q) \
	$(Q)$(JTREG_TEST_DIR):jdk_awt$(Q);`

See https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk_regression/playlist.xml#L127-L134 as an example.  Each target in a playlist has an associated command.  For openjdk, the targets align with pre-defined test groups from openjdk.

Console output, invoking a test run on a pre-defined group results ultimately in calling MainWrapper.  I am not sure which group that TestShrinkAuxiliaryData25 belongs to, but will try to reproduce this problem to see (or at least determine what is different between your 2 runs).

**Comment by jerboaa** [comment]
> This test passes when run in Jenkins using the Adopt setup/commands:
> https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_extended_x86-64_linux/

Yes, but I've also noticed that `TestShrinkAuxiliaryData30` passes for me locally via the Adopt framework. Though, with:

     Skiping test for 30 cache size due max cache size 25

Would there be a way to see test output/logs of the jenkins runs? Perhaps they are passing because of a similar reason to my `TestShrinkAuxiliaryData30` passing?

**Comment by smlambert** [comment]
jtr files are archived for each job run, for the Jenkins job mentioned above, see the [jtr_test_output.tar.gz](https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_extended_x86-64_linux/1/artifact/jtr_test_output.tar.gz) file off of the Build artifacts page: https://ci.adoptopenjdk.net/view/Test_weekly/job/openjdk8_hs_openjdktest_extended_x86-64_linux/1/artifact/

**Comment by smlambert** [comment]
So yes, possibility they are skipped and show as passing, if test config settings or machine config is not suitable.

**Comment by jerboaa** [comment]
Yes, that's it.

From `./jvmtest/openjdk_regression/work/gc/g1/TestShrinkAuxiliaryData25.jtr`:

    ----------rerun:(19/3694)*----------
    cd /home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/scratch/2 && \\
    HOME=/home/jenkins \\
    LANG=en_US.UTF-8 \\
    PATH=/bin:/usr/bin \\
        /home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../bin/java \\
            -Dtest.class.path.prefix=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/gc/g1:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/gc/g1:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/testlibrary:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/testlibrary/whitebox \\
            -Dtest.src=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/gc/g1 \\
            -Dtest.src.path=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/gc/g1:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/testlibrary/whitebox \\
            -Dtest.classes=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/gc/g1 \\
            -Dtest.class.path=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/gc/g1:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/testlibrary:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/testlibrary/whitebox \\
            -Dtest.vm.opts='-ea -esa -Xmx512m' \\
            -Dtest.tool.vm.opts='-J-ea -J-esa -J-Xmx512m' \\
            -Dtest.compiler.opts= \\
            -Dtest.java.opts= \\
            -Dtest.jdk=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \\
            -Dcompile.jdk=/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../.. \\
            -Dtest.timeout.factor=8.0 \\
            -classpath /home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/gc/g1:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/gc/g1:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/testlibrary:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/testlibrary:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/work/classes/2/testlibrary/whitebox:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdk-tests/openjdk_regression/openjdk-jdk/hotspot/test/testlibrary/whitebox:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/openjdkbinary/j2sdk-image/jre/bin/../../lib/tools.jar:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/jtreg/lib/javatest.jar:/home/jenkins/workspace/openjdk8_hs_openjdktest_extended_x86-64_linux/jvmtest/openjdk_regression/jtreg/lib/jtreg.jar \\
            TestShrinkAuxiliaryData25
    ----------System.out:(1/52)----------
    Skiping test for 25 cache size due max cache size 21
    ----------System.err:(3/35)----------

**Comment by jerboaa** [comment]
Only these two are run in jenkins (others are problem listed):

    ./jvmtest/openjdk_regression/work/gc/g1/TestShrinkAuxiliaryData30.jtr
    ./jvmtest/openjdk_regression/work/gc/g1/TestShrinkAuxiliaryData25.jtr

Both pass trivially because of the cache size issue.

**Comment by jerboaa** [comment]
Whether a test runs or not seems to depends on available memory size of the test machine:
http://hg.openjdk.java.net/jdk8u/jdk8u-dev/hotspot/file/4b8584c24ff4/test/gc/g1/TestShrinkAuxiliaryData.java#l135

**Comment by jerboaa** [comment]
> btw, do you know if anyone has ever raised an issue on openjdk to ask that they report skipped tests differently than passed tests?

I don't, sorry. Question for  [quality-discuss@openjdk.java.net](https://mail.openjdk.java.net/mailman/listinfo/quality-discuss)?

**Comment by sophia-guo** [comment]
The issue is stale. Test is not excluded and passes. For example in recent run https://ci.adoptium.net/job/Test_openjdk8_hs_extended.openjdk_ppc64le_linux_rerun/12/testReport/. Close it.
