### ISSUE TITLE
openjdktest_extended on windows do not complete within timeout

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#970]
Both hotspot and openj9 are hitting the 10hr timeout before completing:

https://ci.adoptopenjdk.net/view/Test_all/job/openjdk8_hs_openjdktest_extended_x86-64_windows/
https://ci.adoptopenjdk.net/view/Test_all/job/openjdk8_j9_openjdktest_extended_x86-64_windows/

We will have to consider running these extended tests in parallel (when we have more machine capacity).  

As an interim workaround, we could consider increasing timeout, and/or reducing number of targets in this set.

**Comment by smlambert** [comment]
Those jobs have been disabled until we have a "run in parallel" story.

**Comment by smlambert** [comment]
https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_x86-64_windows/28/

Jobs now split into 3 child jobs - we still need valid test execution times to query from TRSS to ensure the targets are split more equally (first 2 child jobs run in ~1hr, last one still runs for 9+hrs and times out).

**Comment by sophia-guo** [comment]
Also we probably need to take a deep look at jdk_management and jdk_jmx. Jdk_management is time out and jdk_jmx unexpectedly exit after 20 sec. As a result there is no information about the finish time either in test output or in console. Not sure in this case how TRSS calculate the tests running time.

**Comment by llxia** [comment]
This is another case where the query to TRSS is incorrect. 
 https://trss.adoptopenjdk.net/api/getTestAvgDuration?limit=10&jdkVersion=11&impl=hs&platform=x86-64_windows_xl&group=openjdk&level=extended
 
There is no `x86-64_windows_xl`. The correct query should use `x86-64_windows`. That is
https://trss.adoptopenjdk.net/api/getTestAvgDuration?limit=10&jdkVersion=11&impl=hs&platform=x86-64_windows&group=openjdk&level=extended

FYI @renfeiw

**Comment by llxia** [comment]
The prefered solution is to remove xl and mixed. We should use one platform that matches with job name and simplify ottawa.csv. However, this needs updates of the internal builds. We need to investigate if the change is possible internally.

Alternatively, we can remove xl and mixed suffix in TKG when querying TRSS. Adding lots of these changes in TKG will cause code complication in the long run.

**Comment by sophia-guo** [comment]
A good run with jdk_jmx: https://ci.adoptopenjdk.net/view/work-in-progress/job/grinder_sandbox_new/54/console.

Though I did get some strange issue with running on test-ibmcloud-win2012r2-x64-1, same as https://ci.adoptopenjdk.net/view/Test_openjdk/job/Test_openjdk11_hs_extended.openjdk_x86-64_windows_testList_2/1/. Probably need to see if it's machine related.

**Comment by sophia-guo** [comment]
jobs timeout due to the test case jdk_managements, which takes more than 9 hours on windows only for all jdk versions. It takes only a few seconds on other platforms. Investigation needed to figure out the underlying issue about it.  Will exclude it for now.

**Comment by sophia-guo** [comment]
jdk_management issue opened https://github.com/adoptium/aqa-tests/issues/2637

**Comment by lumpfish** [comment]
See also https://github.com/adoptium/aqa-tests/issues/2294
Problem test cases are identified in https://github.com/adoptium/aqa-tests/pull/2639

**Comment by smlambert** [comment]
#2294 and this issue are duplicates - closing this one as the excludes reference 2294.
