### ISSUE TITLE
Copy Junit results from external tests 

### ISSUE THREAD

**Issue by smlambert** [adoptium/aqa-tests#976]
A single issue to track which external tests have their junit results copied out for easier viewing via Jenkins GUI, will close the individual issues in favour of this issue.

External tests that have been updated to copy junit results out to mount:
- [ ] kafka
- [ ] tomcat
- [ ] wildfly
- [ ] lucene-solr - https://github.com/AdoptOpenJDK/openjdk-tests/pull/466 is using mount, which has been removed. Need to update
- [ ] derby
- [x] elasticsearch - https://github.com/AdoptOpenJDK/openjdk-tests/pull/1057
https://github.com/AdoptOpenJDK/openjdk-tests/pull/611
- [x] jenkins - https://github.com/AdoptOpenJDK/openjdk-tests/pull/537
- [ ] scala

- [x] thorntail-mp-tck - https://github.com/AdoptOpenJDK/openjdk-tests/pull/533
- [x] payara-mp-tck - https://github.com/AdoptOpenJDK/openjdk-tests/pull/1068
 https://github.com/AdoptOpenJDK/openjdk-tests/pull/528 - though 528 is merged, results are not displayed, we need to check why
- [x] openliberty-mp-tck - https://github.com/AdoptOpenJDK/openjdk-tests/pull/1066 https://github.com/AdoptOpenJDK/openjdk-tests/pull/552/

**Comment by sophia-guo** [comment]
As mentioned in #1042 the current junit test report strategy is running the tests locally to find out where the junit reports are generated, and then use that path in the docker cp command to copy to host machine. This is kind of hardcoded, which only works for certain version. If anything updates the reports are not accurate.

**Comment by smlambert** [comment]
Your last sentence is not quite right... If reports get generated they are still accurate, we just happen not to be able to find them because something may have changed about where they get generated, so the reports are not available via Jenkins UI.

For the underlying test frameworks, there is usually a way to tell the framework where you would like to put the report.  If so, that is what we should do, so that all reports go to a common/standard location.

**Comment by smlambert** [comment]
@yinggzz - some of the tests in the description were removed, but this is the issue to get test results to a mount so that the Jenkins job could display them (to make it easier to debug)

**Comment by smlambert** [comment]
Actually going to close this as stale and created https://github.com/adoptium/aqa-tests/issues/3464 as a fresh take on this work.
