### ISSUE TITLE
AIX test failure on JDK8 - java/lang/ClassLoader/Assert.java.Assert

### ISSUE THREAD

**Issue by archanaNogriya** [adoptium/aqa-tests#982]
Failed
java/lang/ClassLoader/Assert.java.Assert (from java_lang_ClassLoader_Assert.java)
Execution failed: exit code 1    

This was running on Adopt as well as hyc-runtimes-jenkins.swg-devops.com, and still same failures.
SDK Url ; https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u-2019-03-11-11-19/OpenJDK8U-jdk_ppc64_aix_openj9_2019-03-11-11-19.tar.gz

https://hyc-runtimes-jenkins.swg-devops.com/view/Test_grinder/job/Grinder/1770/parameters/

**Comment by archanaNogriya** [comment]
I will request to exclude this test to make the AIX build green.

**Comment by smlambert** [comment]
Thanks for looking at these @archanaNogriya  

Some triage suggestions:

1) it will be more useful to paste the console output, as Jenkins jobs are transient (and especially in the case of internal job links):

10:29:16 TEST: java/lang/ClassLoader/Assert.java
10:29:16 TEST JDK: /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../..
10:29:16 
10:29:16 ACTION: shell -- Failed. Execution failed: exit code 1
10:29:16 REASON: User specified action: run shell/timeout=300 Assert.sh 
10:29:16 TIME:   0.041 seconds
10:29:16 messages:
10:29:16 command: shell Assert.sh
10:29:16 reason: User specified action: run shell/timeout=300 Assert.sh 
10:29:16 elapsed time (seconds): 0.041
10:29:16 STDOUT:
10:29:16 **Unrecognized system!**
10:29:16 STDERR:
10:29:16 rerun:
10:29:16 cd /home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/work/scratch && \
10:29:16 HOME=/home/jenkins \
10:29:16 LANG=en_US \
10:29:16 PATH=/bin:/usr/bin \
10:29:16 TZ=America/Toronto \
10:29:16 TESTSRC=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression/openjdk-jdk/jdk/test/java/lang/ClassLoader \
10:29:16 TESTSRCPATH=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression/openjdk-jdk/jdk/test/java/lang/ClassLoader \
10:29:16 TESTCLASSES=/home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/work/classes/java/lang/ClassLoader \
10:29:16 TESTCLASSPATH=/home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/work/classes/java/lang/ClassLoader \
10:29:16 COMPILEJAVA=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../.. \
10:29:16 TESTJAVA=/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/jre/bin/../.. \
10:29:16 TESTVMOPTS='-ea -esa -Xmx512m -Xcompressedrefs' \
10:29:16 TESTTOOLVMOPTS='-J-ea -J-esa -J-Xmx512m -J-Xcompressedrefs' \
10:29:16 TESTJAVACOPTS= \
10:29:16 TESTJAVAOPTS= \
10:29:16 TESTTIMEOUTFACTOR=8.0 \
10:29:16 TESTROOT=/home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression/openjdk-jdk/jdk/test \
10:29:16 FS=/ \
10:29:16 PS=: \
10:29:16 NULL=/dev/null \
10:29:16     sh \
10:29:16         /home/jenkins/workspace/Grinder/openjdk-tests/openjdk_regression/openjdk-jdk/jdk/test/java/lang/ClassLoader/Assert.sh
10:29:16 
10:29:16 TEST RESULT: Failed. Execution failed: exit code 1
10:29:16 --------------------------------------------------
10:38:54 Test results: passed: 428; failed: 1
10:39:01 Report written to /home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/report/html/report.html
10:39:01 Results written to /home/jenkins/workspace/Grinder/jvmtest/openjdk_regression/work
10:39:01 Error: Some tests failed or other problems occurred.
10:39:01 
10:39:01 jdk_lang_0_FAILED

It will be good if you can take a look at the code for Assert.sh, to see what would cause the test to hit the "Unrecognized system!" output.

2) As this is an openjdk test case, follow the guidance in https://github.com/AdoptOpenJDK/openjdk-tests/wiki/Guidance-for-Creating-OpenJDK-Test-Defects to check if this is an known defect.  If so, the exclude you will create, should link to the jbs defect.  

Already reported:  
java/lang/ClassLoader/Assert.sh https://bugs.openjdk.java.net/browse/JDK-8037013

3) JDK-8037013 is marked as resolved, should see why we do not have the fix, if that is the case, does it need to be ported elsewhere?

If it was not found in JBS as already reported, you could check if this fails for both vm implementations (openj9 & hotspot), if only openj9, then you would open an openj9 defect and use the openj9 issue link in your exclude.

**Comment by smlambert** [comment]
Should verify if this is resolved or not: https://github.com/adoptium/aqa-tests/blob/master/openjdk/excludes/ProblemList_openjdk8-openj9.txt#L27

**Comment by sophia-guo** [comment]
Error message `Unrecognized system!` JBS https://bugs.openjdk.org/browse/JDK-8037013, fixed in jdk9 and up. Not backport to jdk8. Apply the change and run in grinder https://ci.adoptium.net/view/Test_grinder/job/Grinder/11384/  - passed.

Solutions

- Help backport from upstream or 
- Label as won't fix and keep the test excluded. 

@smlambert which would you prefer?

**Comment by smlambert** [comment]
Let's take the general approach to always prefer fixing issues over excluding test cases (when possible / when a backport would be accepted).  If backport not possible or accepted, I am fine with moving it to a permanent exclusion for this testcase.

**Comment by sophia-guo** [comment]
Backport PR https://github.com/openjdk/jdk8u-dev/pull/604
